### ISSUE TITLE
Webpack / Laravel-Mix outputs a file for each component

### ISSUE THREAD

**Issue by Coding-Kiwi** [inertiajs/inertia#1004]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue3` version: 0.5.2

### Describe the problem:

With the new `createInertiaApp` function, webpack / laravel-mix outputs the 3 js files app, manifest and vendor, but also a file for each component:

![image](https://user-images.githubusercontent.com/5007641/145725253-ce77817f-4546-4463-9970-6d4c919a4ed2.png)

when I return to the "old" way, using `createApp` and `resolveComponent`, its only the 3 normal js files as it should be
![image](https://user-images.githubusercontent.com/5007641/145725314-7ade60b2-9b7a-45b7-a4d7-2a2ceed16c0e.png)

### Steps to reproduce:

Have a laravel project with laravel-mix, switch to `createInertiaApp` and watch your public folder get spammed with files.

**Comment by rhysemmerson** [comment]
resolveComponent uses code splitting with [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) which will create a file per page component. It's documented [here](https://inertiajs.com/client-side-setup#code-splitting)

> Code splitting breaks apart the various pages of your application into smaller bundles, which are then loaded on demand when visiting new pages. This can significantly reduce the size of the initial JavaScript bundle, improving the time to first render.

**Comment by Coding-Kiwi** [comment]
That is indeed correct. My bad, I must have copied it from the release notes without fully reading the text, my bad
