### ISSUE TITLE
Security issue, can navigate to previous pages even after logged out of session

### ISSUE THREAD

**Issue by jcs224** [inertiajs/inertia#102]
I think this has to do with the way Inertia saves props in the history.pushState, but I'm able to navigate back and forth on pages even after I'm logged out, and see all the data in their full glory. Is there some way to force a refresh after logged out after a session?

![securty-inertiajs](https://user-images.githubusercontent.com/6226188/69284107-063a0400-0bab-11ea-87d2-eb5de4b025de.gif)

**Comment by adamwathan** [comment]
This is actually true of all server rendered applications, and just the way the browser works by default.

Try it here on GitHub even for example 👍🏻

**Comment by jcs224** [comment]
Oh man you're right.. just tried it with a different Laravel app with normal pages, and it happens there too. I guess I'll have to find some other way to get around this. The reason I'm concerned about this is because this app will likely be used in a computer lab with lots of different users with their own sensitive data.

FYI, GitHub doesn't seem to have this issue. Logged out and navigated back, forced a page refresh.

**Comment by adamwathan** [comment]
Weird, happens for me on GitHub! But yeah pretty normal browser behavior unfortunately for your case :/

**Comment by jcs224** [comment]
@adamwathan Well, FWIW, I did solve this particular issue for me as best as I could figure out. It was a little more difficult than normal, because my logout made an Inertia request instead of a full page reload. So, I did two things. 

1. A regular, non-Inertia Axios call and then used JavaScript to load the login page:
2. Added middleware in Laravel to not cache HTML responses at all, but leave any other request alone (including Inertia)

```javascript
// Inertia code
axios.post('/logout').then(() => { window.location.href = '/login' })
```

```php
// Laravel middleware
public function handle($request, Closure $next)
    {
        $response = $next($request);

        if (strpos($response->headers->get('Content-Type'), 'text/html') !== false) {
            return $response->header('Cache-Control','no-cache, no-store, max-age=0, must-revalidate')
            ->header('Pragma','no-cache')
            ->header('Expires','Sun, 02 Jan 1990 00:00:00 GMT');
        } else {
            return $response;
        }
    }
```
This means that upon logout, it will remember that the HTML the app is loaded in is not cached, and the back button will try to reload the page rather than just take the cached page. The middleware alone would work for a normal Laravel app, but this didn't apply with Inertia because the logout didn't do a full page reload.

**Comment by gregupton** [comment]
Just out of curiosity are you using the auth/guest middleware to protect your routes?

**Comment by jcs224** [comment]
@gregupton yep, using `guest` middleware for the login page and request, and `auth` middleware for the rest of the pages.

It turns out that @adamwathan is right about this being standard behavior, even for non-Inertia apps, which freaked me out. The standard solution to this issue is to just apply the above middleware, which works when all the pages are regular, server-rendered Blade pages or whatever. But with Inertia I had to force the page to fully reload upon logout so that a different user couldn't just sit down and hit the back button, seeing the previous page.

**Comment by drfraker** [comment]
After looking into this myself I've made a few discoveries. 
1. Github does not have the behavior that @adamwathan mentions when you test the behavior on private repos.
You can test this by going to github signing in and navigating to a private repo that you own. Then log out. Click the back button and you will see a 404 page. 
2. You can definitely prevent back button issues on web apps where you need higher security by using Cache-Control headers. 
3. You can test this by adding a header to your response 'Cache-Control': 'no-cache, no-store, private', visit a page then click the back button and you will see a full page refresh. 

The full page refresh happens because the headers tell the browser it must not cache pages and get the page from the server every time. This is how you can make web apps more secure when necessary. 

However, it doesn't seem that Inertia is taking this into account when it makes its ajax calls. I think it should. I wonder if this issue should be reopened so we can explore a solution.?

**Comment by Humpz** [comment]
Hello everyone, does anyone have a work around on this? I also noticed this behaviour and I was not able to find any solutions.

**Comment by Humpz** [comment]
Hello, I was able to solve this using the suggestion of @reinink here https://github.com/inertiajs/inertia/issues/247. You might wanna read on it and try to apply on your project.

**Comment by RCady** [comment]
Not sure if this is still an issue for anyone, but I was able to resolve this by using `replace: true` in my logout request. This is built with Laravel on the backend.

```
Inertia.post('/logout', {}, { replace: true }
```
