### ISSUE TITLE
this.$inertia is undefined in version 0.8.0

### ISSUE THREAD

**Issue by limsocheat** [inertiajs/inertia#1039]
### Versions:

- `@inertiajs/inertia` version: ^0.11.0
- `@inertiajs/inertia-vue` version: 0.8.0

### Describe the problem:

When install version 0.8.0 the property $inertia is undefined

**Comment by RobertBoes** [comment]
You now have to register the Inertia plugin yourself in Vue 2, see https://github.com/inertiajs/inertiajs.com/pull/208 for more information

**Comment by claudiodekker** [comment]
Thanks @RobertBoes
