### ISSUE TITLE
Inertia v0.11.0 no longer seems to support custom headers passed by Axios interceptor

### ISSUE THREAD

**Issue by onlime** [inertiajs/inertia#1046]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0
- `axios` version 0.24.0

### Describe the problem:

In previous inertia v0.10.0, I was able to set an Axios intercepter to define a custom header which was passed to the backend by every XHR request by Inertia.

I was using this for a frontend language switcher with vue-i18n, which stored the current locale additionally in `localStorage` and the Axios intercepter would then pass it to the backend with every request.

Example:

```js
import axios from 'axios'

function detectBrowserLocale() {
    const availLocales = ['de', 'en']
    const detected = localStorage.getItem('locale') || navigator.language.substring(0, 2).toLowerCase()
    return availLocales.includes(detected) ? detected : availLocales[0]
}

axios.interceptors.request.use(function (config) {
    config.headers.common['X-Inertia-Language'] = detectBrowserLocale()
    return config
})
```

I was then importing this in `app.js` and it worked perfectly. The `X-Inertia-Language` header was always passed. But since upgrading to Inertia 0.11.0 that interceptor callback is never called. It looks like Inertia gave up on using Axios altogether and uses its own implementation or some other HTTP client library.

I remember @reinink 's comment back in Aug 2020: https://github.com/inertiajs/inertia/issues/147#issuecomment-682002098

> Let's maybe leave it open, because I'm considering removing Axios entirely from Inertia.js, and if we do that, we'd want to provide another way to do this.

But in [inertia@0.11.0 Release Notes](https://inertiajs.com/releases/inertia-0.11.0-2022-01-07) I don't find any hint about this being done.

Is there another newer recommended way of doing this in Inertia 0.11.0 which is a bit more future proof? I am not talking about custom headers on a per-request basis (as in #202) but rather a way to pass a header with every request by some global configuration/callback.

**Comment by ajnsn** [comment]
Hey @onlime 
This might be the same issue [as described here](https://github.com/inertiajs/inertia/issues/195). TL;DR: You could try to use the same Axios version [as Inertia does](https://github.com/inertiajs/inertia/blob/master/packages/inertia/package.json#L3). Otherwise there are multiple Axios versions around and your v0.24 interceptor will not affect Inertia's requests.

**Comment by onlime** [comment]
> Hey @onlime This might be the same issue [as described here](https://github.com/inertiajs/inertia/issues/195). TL;DR: You could try to use the same Axios version [as Inertia does](https://github.com/inertiajs/inertia/blob/master/packages/inertia/package.json#L3). Otherwise there are multiple Axios versions around and your v0.24 interceptor will not affect Inertia's requests.

Great @ajnsn thanks a lot! That did the trick. Right before, @RobertBoes gave me the same answer on Inertia.js Discord channel. Really appreciate your help!

So, for those who struggle with the same issue: Just make sure you don't have `axios` as another `devDependency` in your `package.json`, or if you really need, make sure the version matches Inertia's axios dependency. In my `package-lock.js` I found:

```json
        "@inertiajs/inertia": {
            "version": "0.11.0",
            "resolved": "https://registry.npmjs.org/@inertiajs/inertia/-/inertia-0.11.0.tgz",
            "integrity": "sha512-QF4hctgFC+B/t/WClCwfOla+WoDE9iTltQJ0u+DCfjl0KdGoCvIxYiNtuH8h8oM+RQMb8orjbpW3pHapjYI5Vw==",
            "dev": true,
            "requires": {
                "axios": "^0.21.1",
                "deepmerge": "^4.0.0",
                "qs": "^6.9.0"
            },
            "dependencies": {
                "axios": {
                    "version": "0.21.4",
                    "resolved": "https://registry.npmjs.org/axios/-/axios-0.21.4.tgz",
                    "integrity": "sha512-ut5vewkiu8jjGBdqpM44XxjuCjq9LAKeHVmoVfHVzy8eHgxxq8SbAVQNovDA8mVi05kP0Ea/n/UzcSHcTJQfNg==",
                    "dev": true,
                    "requires": {
                        "follow-redirects": "^1.14.0"
                    }
                }
            }
        },
```

I had the wrong `"axios": "^0.24"` version in my `package.json` - downgrading it to `^0.21` did the trick. Or even better, remove it completely from your direct dependencies as you're probably not going to use plain Axios in an Inertia.js project. I only had this because I have selected Axios on initial Laravel project bootstrapping (`composer create-project laravel/laravel myproject`).

**Comment by ryanzeng1990** [comment]
Hi is this working on react? I try to use this code in the `app.js` but it's not work. I have checked the axios version is 0.21 and inertia": "^0.11.0",,inertia-react": "^0.8.0",
```
import axios from "axios";
axios.interceptors.request.use(function (config) {
    config.headers.common['X-Tab-Id'] = 'This is my tab id';
    return config
})
```
