### ISSUE TITLE
Modal Route - Is it possible?

### ISSUE THREAD

**Issue by joshhornby** [inertiajs/inertia#106]
Hi 👋 

Is it possible to create a modal route? See the URL below for an example:

https://codedaily.io/tutorials/47/Create-a-Modal-Route-with-Link-and-Nav-State-in-React-Router

Clicking a link would open the modal on top of the current page and change the URL, closing the modal changes to URL back to the previous page.

**Comment by tinyfly** [comment]
@joshhornby Yes, it's possible. Take a look at [this comment](https://github.com/inertiajs/inertia/pull/44#issuecomment-535806028) for an example of how you might do it.

**Comment by reinink** [comment]
Closing this in favour of #249. 👍
