### ISSUE TITLE
Vue 3 watch property not working with Inertia useForm fields

### ISSUE THREAD

**Issue by Athanax** [inertiajs/inertia#1068]
### Versions:

- `@inertiajs/inertia` version: ^0.10.0
- `@inertiajs/inertia-vue3` version: ^0.5.1

I am using the watch Vue js property with the Inertia useForm() function. 

```
  data() {
    return {
      form: useForm({
        username: "dsamfna",
      }),
    };
  },

  watch: {
    form.username: function (val) {
      console.log(val);
    },
  },
```

I have also specified the v-model prop as the useForm property as per the documentation. 

```
<input
          type="text"
          v-model="form.username"
          id="username"
          :class="[
            'block w-full pr-10  sm:text-sm rounded-md',
            form.errors.username
              ? 'border-red-300 text-red-900 focus:outline-none focus:ring-red-500 focus:border-red-500'
              : 'border-gray-300 text-indigo-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500',
          ]"
          placeholder="Username"
          aria-invalid="true"
          aria-describedby="username-error"
 />
```

I have a problem with not being able to watch the changes in the input field in inertia.

**Comment by RobertBoes** [comment]
The supplied watch statement doesn't work (I think that would even throw compile / runtime errors), watching form fields should be possible using the following syntax:
```js
watch: {
  'form.username': function (val, oldVal) {
    // do something
  }
}
```
Taken from the Vue 3 docs: https://v3.vuejs.org/api/options-data.html#watch

**Comment by Athanax** [comment]
It worked.
I wanted to crear validation errors from the form.
```
watch: {
    "form.username": function (val, oldVal) {
      //
      if (this.form.errors) {
        this.form.clearErrors();
      }
    },
  },
```
Problem solved.
