### ISSUE TITLE
Callback for requests

### ISSUE THREAD

**Issue by franzdumfart** [inertiajs/inertia#107]
First and foremost I'm not sure if this is already possible, but I didn't find it in the documentation.

I have a submit button in a form. When the form gets submitted I want to add a loading state to the button and then show some animation. When the request is done I want to set the loading state to false. 

To submit the form I use `this.$inertia.post` for the request. When the post request return a validation error for example, the errors will be shown but I have no way to reset the loading state.

I thought a callback to the post method would help and couldn't find it. Am I thinking the wrong way? Thanks in advance!

**Comment by georgehanson** [comment]
IIRC, as long as the error isn't one that is handled by Inertia (such as an exception being thrown which loads within the modal), you should be able to add any failed logic to a `catch` callback as it returns a Promise.

For example:

```javascript
this.$inertia.post('/my/url', data).catch((error) => {
    // Handle the error here
});
```

**Comment by franzdumfart** [comment]
Thanks a lot @georgehanson. `catch` doesn't do the trick but `then` does. It's perfect for me.

So my submit method looks something like this:

```
this.loading = true;

this.$inertia.post('some-route', this.formData).then(() => {
    this.loading = false;
});
```

**Comment by kurucu** [comment]
Are there any conditions for this? This never fires for me, telling me that (I think) the return from post() is not defined.

**Comment by foroughi1380** [comment]
> Are there any conditions for this? This never fires for me, telling me that (I think) the return from post() is not defined.

visit : https://inertiajs.com/manual-visits

**Comment by waizinkyaw7** [comment]
> Thanks a lot @georgehanson. `catch` doesn't do the trick but `then` does. It's perfect for me.
> 
> So my submit method looks something like this:
> 
> ```js
> this.loading = true;
> 
> this.$inertia.post('some-route', data).then(() => {
>     this.loading = false;
> });
> ```

it's not workin in my vue3 code why?

**Comment by rojtjo** [comment]
@austin691 This was changed a while ago. 

```js
this.loading = true;

this.$inertia.post('some-route', data, {
    onFinish: () => {
        this.loading = false;
    },
});
```

Check the event callbacks in the docs for more info: https://inertiajs.com/manual-visits#event-callbacks

**Comment by austin691** [comment]
> @austin691 This was changed a while ago.
> 
> ```js
> this.loading = true;
> 
> this.$inertia.post('some-route', data, {
>     onFinish: () => {
>         this.loading = false;
>     },
> });
> ```
> 
> Check the event callbacks in the docs for more info: https://inertiajs.com/manual-visits#event-callbacks

Where can i import {router} and use like createInertiaApp and createApp in app.js cause i'm beginner
