### ISSUE TITLE
Share data not working

### ISSUE THREAD

**Issue by ejobity** [inertiajs/inertia#1075]
Hi good day. I am using laravel and inertiajs with vue.

I am having trouble with shared data. It seems not to be working or sending the data to Vue. What ever I put into shared data i am not seeing it in Vue developer tools. I am not even seeing the errors: Object in props in Vue developer tools.  I have a simple code that seems not to be working. I try to access it using {{ $page.props.auth.user.username }}. However the systems says it is undefined. I go to Vue developer tools to prop and im not seeing auth: Object.

```
class HandleInertiaRequests extends Middleware
{
public function share(Request $request)
    {
        return array_merge(parent::share($request), [
         
            'auth' => [
                'user' => [
                    'username' => 'JohnDoe'
                ]
            ]

        ]);
    }
}
```

**Comment by ajnsn** [comment]
Hey @ejobity 
Did you [register](https://inertiajs.com/server-side-setup#middleware) the `HandleInertiaRequests`within your `App\Http\Kernel`?

```php
'web' => [
    // ...
    \App\Http\Middleware\HandleInertiaRequests::class,
],
```

**Comment by ejobity** [comment]
> ```
> \App\Http\Middleware\HandleInertiaRequests::class,
> ```

works now. Thank you.
