### ISSUE TITLE
Navigation scroll position reset not working on Firefox

### ISSUE THREAD

**Issue by craigrileyuk** [inertiajs/inertia#1079]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

I'm having an issue with the scrolling on navigation. On Firefox, clicking an InertiaLink results in the scroll-to-top behaviour not working at all (next page loads with the user still positioned at the bottom of the page), or only climbing halfway up the page.

### Steps to reproduce:

- Create page with some decent amount of vertical height.
- Use a persistent layout
- Use Firefox
- Click an Inertia link

**Comment by marcbelletre** [comment]
I can confirm the same behaviour in MS Edge.
