### ISSUE TITLE
Inertiajs For Lavavel render displays nothing

### ISSUE THREAD

**Issue by eteka75** [inertiajs/inertia#108]
I am working on a project in which I have integrated the library **but nothing is displayed except the html tag**

**Comment by Sinnbeck** [comment]
Can I suggest going on something like laracasts.com and creating a support ticket? Also remember to post some code (and check the console)

**Comment by Larsklopstra** [comment]
Did you write `return` before `inertia`?

**Comment by reinink** [comment]
@eteka75 If you want to post some code, as well as your console (as @Sinnbeck is suggesting), I'd be happy to help figure this out. Without that, this is going to be impossible to diagnose.

I'm going to close this issue for now, but feel free to add that, and I'll still respond.

**Comment by eteka75** [comment]
https://github.com/inertiajs/inertia/issues/108#issuecomment-581145311
Yes
