### ISSUE TITLE
Capture exception that pushState or replaceState throws

### ISSUE THREAD

**Issue by SabatinoMasala** [inertiajs/inertia#109]
Firefox has a rather cryptic error message when we add a large state to the browser history. The Mozilla docs mention the [hard limit of 640k characters](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState#Parameters). When you encounter this issue you get an `NS_ERROR_ILLEGAL_VALUE` error in your console, nothing more.

Intertia could handle this exception in the [setState](https://github.com/inertiajs/inertia/blob/master/src/inertia.js#L138) method, and provide the developer with some insights on what could have been the issue.

Related issue: https://github.com/inertiajs/inertia-vue/issues/106

Would like some extra input before creating a PR.

**Comment by reinink** [comment]
Thanks so much for looking into this @SabatinoMasala and sharing your findings. I'd certainly be open to a PR that adds an exception handler for this.

**Comment by affektde** [comment]
That's a stupid question:

If you do transfer large data, couldn't you use an option in an `Inertia request` as a new feature that excludes certain data for `pushState`? Large amounts of data for data tables would not necessarily have to be included in the history. Or do I see it wrong?

Something like:

```javascript
Inertia.visit(url, {
  method: 'get',
  data: {},
  replace: false,
  preserveState: false,
  preserveScroll: false,
  only: [],
  excludeFromPushState: ['myLargeDataKey'],
})
```

```javascript
window.history.pushState({
        cache: {},
        ...page,
      }, '', page.url)
```

**Comment by reinink** [comment]
Considering this resolved, as per my comment here:

https://github.com/inertiajs/inertia/pull/110#issuecomment-705543954

Thanks so much for reporting!
