### ISSUE TITLE
<Head> error : Cannot read properties of undefined (reading 'createProvider')

### ISSUE THREAD

**Issue by vipinkundal** [inertiajs/inertia#1090]
### Versions:

- `@inertiajs/inertia` version: ^0.11.0
- `@inertiajs/inertia-vue3` version: ^0.6.0

### Problem:
If I include `<Head title="Sign Up" />` in the vue component then it throws an error in the console logs.

Signup component
![Screenshot 2022-02-08 at 11 58 22 AM](https://user-images.githubusercontent.com/6591564/152931941-4478d638-356f-4d9f-ba9d-9945d9d6a838.png)

My `app.js` file 
![Screenshot 2022-02-08 at 11 58 43 AM](https://user-images.githubusercontent.com/6591564/152931880-863b7874-9e47-4826-a750-c2950bb2398c.png)

My app.blade.php
![Screenshot 2022-02-08 at 12 01 53 PM](https://user-images.githubusercontent.com/6591564/152932028-fc77d548-b670-4cd3-b254-84a22d13c834.png)

Error
![Screenshot 2022-02-08 at 11 59 25 AM](https://user-images.githubusercontent.com/6591564/152932159-b4db42d9-1733-4b26-a99c-9576148811db.png)
![Screenshot 2022-02-08 at 11 59 48 AM](https://user-images.githubusercontent.com/6591564/152932188-75a1306b-5fe0-430e-b7a4-61578a0373a9.png)

### Steps to reproduce:
Created a new Laravel, Vue 3 and InertiaJs project.

Shared all related code in the screenshot above.

I'm missing something?

**Comment by ajnsn** [comment]
Hey @vipinkundal 
Your `setup` seems to be missing Inertia's plugin via`.use(plugin)` as [described here](https://inertiajs.com/client-side-setup).

Background: [The plugin defines](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue3/src/app.js#L100) the `$headManager` which is need for the Head-component to work.

**Comment by vipinkundal** [comment]
Thanks @ajnsn it worked.
