### ISSUE TITLE
Link new tab not working in vue

### ISSUE THREAD

**Issue by ayophanz** [inertiajs/inertia#1096]
I'm trying to add a link using the inertiajs build it link components

`<Link href="/blog/uncategorized/test-slug" target="_blank">Preview</Link>`

instead of redirect to new tab the line will remain in the current tab.

Please help
thanks

**Comment by ajnsn** [comment]
Hey @ayophanz 
For this use case, you could just use a normal anchor-tag instead.

**Comment by reinink** [comment]
Yup, exactly @ajnsn, thanks for helping out here 👍

**Comment by amirmasoud** [comment]
If you have to do it inside of JS for whatever reason, one solution can be something like this:

```vue
<script setup>
const newTab = $ref(true);
const openInNewTab = (href) => {
  Object.assign(document.createElement("a"), {
    target: "_blank",
    rel: "noopener noreferrer",
    href: href,
  }).click();
};
</script>
<template>
  <button
    @click="newTab ? openInNewTab('/open-in-new-tab') : $inertia.visit('/inertia-link')"
  >
    click
  </button>
</template>
```
Reference\
[https://stackoverflow.com/a/28374344/2747661](https://stackoverflow.com/a/28374344/2747661)

**Comment by vitalijalbu** [comment]
Neither in react works

**Comment by andreapozza** [comment]
A cleaner solution: `const openInNewTab = href => window.open(href, '_blank')`
https://github.com/inertiajs/inertia/issues/1096#issuecomment-1419872292

**Comment by amirmasoud** [comment]
`window.open` might be blocked by browsers as popup if it's not happening on the actual click event.

**Comment by andreapozza** [comment]
Hi @amirmasoud, thank you for the explanation. I didn't think about that.

**Comment by vedmant** [comment]
That's unfortunate, I have a component that optionallity opens in a new tab, in this case I have to conditionally use `<Component :is=""` to switch between just `a` and `Link` which is making the code more cumbersome. Btw, `NuxtLink` implementation supports `target` attribute
