### ISSUE TITLE
Link component keeps rendering `href` attribute even when it is not passed or `:href="undefined"`

### ISSUE THREAD

**Issue by rtabulov** [inertiajs/inertia#1100]
### Versions:

- `@inertiajs/inertia` version: 0.11.0

### Describe the problem:

Link component keeps rendering `href` attribute even when it is not passed or `:href="undefined"`

apparently all Link components rely on `mergeDataIntoQueryString`

this affects at least vue3  & react, but probably others too

### Why this is a problem? 

- cannot properly disable a link, which requires removing `href` attribute completely
- browsers treat `<a href>` as `<a href=".">` (eg link to the current page)

### Reproduction:

https://stackblitz.com/edit/vitejs-vite-irxlcc - vue3

https://stackblitz.com/edit/vitejs-vite-cn2nkk - react

#### option 1

update `mergeDataIntoQueryString` to return href as `undefined` instead of `''` empty string

#### option 2 

update Link component in every lib-specific packages (inertia-vue3, inertia-react, etc)

i am willng to open a pr 🙂

**Comment by reinink** [comment]
Hey thanks for reporting this, but I'm pretty certain this was resolved already in #843. You'll just need to make sure you're on the latest version of the Vue adapters 👍

**Comment by rtabulov** [comment]
hey @reinink 

the PR you mentioned just fixes the error when using `<Link :href="null"></Link>`. it basically just gets rid of the thrown error 
but Link still renders as `<a href><a>` (empty href as you can see) which makes this link go to the current page

this is an issue because sometimes we just want to render `a` without `href` so that it's disabled
after my PR `<Link :href="null"></Link>` or `<Link :href="undefined"></Link>`  renders as `<a></a>`

**Comment by jakedowns** [comment]
what i do in my "smart-link" component is define an bindAttributes object, and use v-bind="bindAttributes" 
then, i _only_ add the "href" key to the object if there's a valid href. this prevents the empty href being printed in the dom.

see here: https://github.com/jakedowns/inertia-smart-link/blob/9e7eecac8e8ca3dd8978f8e2a9b3b777d139cc43/SmartLink.vue#L76-L85

**Comment by rtabulov** [comment]
@jakedowns yes, this works without a doubt. but it is a workaround, not a solution

**Comment by anne-gropler** [comment]
This is still a current problem.
