### ISSUE TITLE
Use of gRPC instead of JSON

### ISSUE THREAD

**Issue by omar391** [inertiajs/inertia#1109]
### Discussed in https://github.com/inertiajs/inertia/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **omar391** February 23, 2022</sup>
Hi everyone,

Is there a way to replace API output from JSON to gRPC(protobuf) or such fn is already available?

Best.</div>

**Comment by ninjaparade** [comment]
@omar391 can you please close this issue? I think the discussion point is enough, creating an issue as well seems like the incorrect use of issues.

Thanks!

**Comment by omar391** [comment]
Sorry for the inconvenience.
