### ISSUE TITLE
Blank page on IE11

### ISSUE THREAD

**Issue by chinleung** [inertiajs/inertia#111]
## Description

I'm trying to make Inertia run on IE11 and it is not working. I've tried what has been suggested [here](https://github.com/inertiajs/pingcrm/issues/28) and it is still not working.

I've started a fresh install of Laravel with `laravel new ie`. After that, I've followed the instructions for the both server-side and client-side without code splitting. Every thing is working properly on Chrome, Firefox, Edge, but on Internet Explorer I first get an error about Promise.

Therefore, I've installed the polyfill for Promise:

```bash
npm install --save-dev es6-promise
```

And added `require('es6-promise').polyfill();` to the top of my `resources/js/app.` which then fixes the Promise error. However, when I attempt to load it on Internet Explorer afterward, simply get a blank page with no error and the following `body` in the DOM:

```html
<body>
    <!---->
</body>
```

I've made a repository to reproduce the issue: https://github.com/chinleung/inertia-ie.

### app.blade.php

```php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
        <script src="{{ mix('/js/app.js') }}" defer></script>
    </head>
    <body>
        @inertia
    </body>
</html>
```

### routes/web.php

```php
Route::get('/', function () {
    return Inertia\Inertia::render('Home');
});
```

### resources/js/app.js

```js
require('es6-promise').polyfill();

import { InertiaApp } from '@inertiajs/inertia-vue'
import Vue from 'vue'

Vue.use(InertiaApp)

const app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => require(`./Pages/${name}`).default,
    },
  }),
}).$mount(app)
```

### resources/js/Pages/Home.vue

```vue
<template>
    <div>
        Hello World
    </div>
</template>
```

## Update

I'm able to make the page load if I don't use the `render` from the docs, so I can confirm that Vue itself is working. 

```js
new Vue({
    template: '<div>Hello World</div>',
}).$mount(app)
```

**Comment by chinleung** [comment]
I've debugged the issue and found out that it's stuck here in the `setState` method in `@inertiajs/inertia/src/inertia.js`:

```js
window.history.replaceState({
    cache: preserveState,
    ...{ cache: preserveState && window.history.state ? window.history.state.cache : {} },
    ...page,
}, '', page.url)
```

**Comment by chinleung** [comment]
The issue with the spread is the code has been to:

```js
Object.assign(...);
```

However, `Object.assign` is not defined in IE11, so I've fixed this by adding the following to my `app.js`:

```js
import 'core-js/es6/object';
```

**Comment by lucaros97** [comment]
Just tried this and still not working on IE11

**Comment by chinleung** [comment]
> Just tried this and still not working on IE11

Have you also included a polyfill for Promise?

**Comment by lucaros97** [comment]
> > Just tried this and still not working on IE11
> 
> Have you also included a polyfill for Promise?

Yes, added `require('es6-promise').polyfill();` to the top of my `app.js` file

**Comment by chinleung** [comment]
> Yes, added `require('es6-promise').polyfill();` to the top of my `app.js` file

Any errors? Could you show your `app.js` and `webpack.mix.js`?

**Comment by lucaros97** [comment]
Sure!

`webpack.mix.js`:
```
const cssImport = require('postcss-import')
const mix = require('laravel-mix')
const path = require('path')
const tailwindcss = require('tailwindcss')
/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/sass/app.css', 'public/css', [
        cssImport(),
        tailwindcss(),
    ])
    .webpackConfig({
        output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
        resolve: {
            alias: {
                vue$: 'vue/dist/vue.runtime.esm.js',
                '@': path.resolve('resources/js'),
            },
        },
    })
    .babelConfig({
        plugins: ['@babel/plugin-syntax-dynamic-import'],
      });

if (mix.inProduction()) {
    mix.version();
}


mix.copyDirectory('resources/assets', 'public/assets');
```

`app.js`:
```
require('es6-promise').polyfill();
import 'core-js/es6/object';

import { InertiaApp } from '@inertiajs/inertia-vue'
import PortalVue from 'portal-vue'
import Vue from 'vue'
import pdfvuer from 'pdfvuer'
const moment = require('moment')
require('moment/locale/it')

Vue.component("pdfvuer", pdfvuer);

Vue.use(require('vue-moment'), {
  moment
})

import wysiwyg from "vue-wysiwyg";
Vue.use(wysiwyg, {});

import axios from 'axios'
import VueAxios from 'vue-axios'
Vue.use(VueAxios, axios);

Vue.config.productionTip = false
Vue.mixin({ methods: { route: window.route } })

Vue.use(InertiaApp);
Vue.use(PortalVue);

let app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)
```

**Comment by chinleung** [comment]
@lucaros97 I've installed the packages that you have, and the issue seems to come from `pdfvuer`, not from Inertia itself.

If you put the code related to that package in comment, the page loads fine on IE11.

**Comment by lucaros97** [comment]
Ok works also for me now! The problem is that i've to use pdfvuer and it must work also on IE11 😁

**Comment by AhmadJafari2019** [comment]
@lucaros97  Hi Can  you tell me please how did you solve that? i am corrently working on a react gatsby project which i have the same issue as i ran the page locally it render just a blank page. Can you help please.

**Comment by lucaros97** [comment]
At the moment I've not resolved without removing pdfvuer. There's no way to keep it work with pdfvuer on IE11
