### ISSUE TITLE
Inertia Code Splitting with use of CDN

### ISSUE THREAD

**Issue by jny986** [inertiajs/inertia#114]
I am wanting to setup use of a CDN for delivery of my assets

I am using inertia-laravel and have setup for mix to use a full URL however I can't find any way that allows for the addition of the full asset URL in inertia.

Would appreciate being pointed in the right direction.

**Comment by reinink** [comment]
Hmm, I've never used Inertia via CDN yet, nor while using code splitting at the same time. That said, you should be able to use UNPKG for this. For example:

https://unpkg.com/@inertiajs/inertia@0.1.7/dist/index.umd.js

Hope that helps! 🤟
