### ISSUE TITLE
set a conf for show error format on modal.

### ISSUE THREAD

**Issue by zodman** [inertiajs/inertia#115]
Sometimes the frameworks when you send a xhr call. It detect from json/text format so the error its showed  on text format and not on html.

I think from the js(inertia-vue) component you can configure the modal to show the error.

![](https://i.imgur.com/FafzASS.png)

**Comment by reinink** [comment]
So we now check to see if non-Inertia responses contain JSON, and if they do, we show a warning with the JSON:

https://github.com/inertiajs/inertia/blob/536440c74da0bbdad956ca913a9a9af505c05344/packages/inertia/src/modal.js#L6-L8

Otherwise we just show the HTML. 👍

**Comment by enextiarg** [comment]
Maybe your are using this.$inertia, it wait for Inertia resopnse; 

```
this.$inertia.get(route('example'))
  .then(res => {
     console.log(res)
  })
```

Please use axios. instead 

```
axios.get(route('example'))
  .then(res => {
     console.log(res)
  })
```

**Comment by Benoit1980** [comment]
> Maybe your are using this.$inertia, it wait for Inertia resopnse;
> 
> ```
> this.$inertia.get(route('example'))
>   .then(res => {
>      console.log(res)
>   })
> ```
> 
> Please use axios. instead
> 
> ```
> axios.get(route('example'))
>   .then(res => {
>      console.log(res)
>   })
> ```

It does not work, using axios returns:
`{"cookies":{},"transferStats":{}}`
