### ISSUE TITLE
layout doesn't work until refresh the page after logged in.

### ISSUE THREAD

**Issue by namsir** [inertiajs/inertia#1158]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: ^0.6.0

### Describe the problem:

I was mimicking ping crm example but added vite, instead of webpack. The issue is when i first login, persistence layout doesn't show until i manually refresh the page. Anyone else having this issue?

**Comment by aliwesome** [comment]
@namsir 
How did you fix this problem? I'm facing the same issue using it with the Laravel Vite plugin.
