### ISSUE TITLE
How to mix Inertia with plain pages

### ISSUE THREAD

**Issue by Mochaka** [inertiajs/inertia#117]
I'm working on an older project that is a mix of Vue and plain Laravel blade files.

I'd like to know, what the best way would be to slowly integrate inertia into my project?

The main pain point would be having links in our menu that would go to a non-inertia page. Currently inertia opens those pages up in a modal, but i need a way to tell Inertia to load those links normal.

**Comment by reinink** [comment]
This is actually really easy to do. Simply create plain anchor links (`<a href="">`) for non-Inertia pages, and Inertia links (`<inertia-link href="">`) for Inertia pages. As you convert more of your site to Inertia, you can replace these plain links with Inertia links.

There is no way for Inertia to handle this automatically, as you've noticed, Inertia will open non-Inertia responses in a modal.

The only thing to be careful with here is server-side redirects. It's fine if a regular request redirects to an Inertia endpoint, but it won't work the other way around.

Hope that helps! 🤟

**Comment by killgt** [comment]
There is a way to add a header or any kind of indication that the next page wont be a inertia one? The most common scenario is using a inertia link to do a post to /logout, then the login page wont be a inertia one. Maybe adding a header to the response...

The alternative is not using a inertial link, and that require a full form with csrf...

**Comment by Juhlinus** [comment]
> There is a way to add a header or any kind of indication that the next page wont be a inertia one? The most common scenario is using a inertia link to do a post to /logout, then the login page wont be a inertia one. Maybe adding a header to the response...
> 
> The alternative is not using a inertia link, and that require a full form with csrf...

Axios sniffs out the csrf token and passes it to the request. So, using Axios would fit your use-case

**Comment by medfree** [comment]
@killgt thanks for the solution

**Comment by jakedowns** [comment]
in our app, as we phase in inertia, it was becoming too cumbersome to manually distinguish by using `<a>` and `<inertia-link>` in all of our templates, so we created this `<smart-link>` component, it might be overkill for most, but in case anyone is interested, here it is: https://github.com/jakedowns/inertia-smart-link/blob/main/SmartLink.vue

**Comment by joowdx** [comment]
> This is actually really easy to do. Simply create plain anchor links (`<a href="">`) for non-Inertia pages, and Inertia links (`<inertia-link href="">`) for Inertia pages. As you convert more of your site to Inertia, you can replace these plain links with Inertia links.
> 
> There is no way for Inertia to handle this automatically, as you've noticed, Inertia will open non-Inertia responses in a modal.
> 
> The only thing to be careful with here is server-side redirects. It's fine if a regular request redirects to an Inertia endpoint, but it won't work the other way around.
> 
> Hope that helps! 🤟

This only works with hyperlinks. Are there any ways to handle non-inertia pages when submitting forms? I want my default login to do a full page reload on submit, depending on the user's privileges.
