### ISSUE TITLE
$page is not defined after updating inertia-vue

### ISSUE THREAD

**Issue by Mazeland** [inertiajs/inertia#1175]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue` version: 0.8.0

### Describe the problem:

After updating inertia-vue from 0.7.2 to 0.8.0, inertia can't find $page and has problems reading the shared data (props) from HandleInertiaRequests.php.

These are the console error messages:
- Property or method "$page" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

- Error in data(): "TypeError: Cannot read properties of undefined (reading 'props')"

Is someone familiar with this problem and able to help?

**Comment by ElMassimo** [comment]
This is related to an update in the way Inertia injects these into the Vue app.

Make sure to `use` the plugin provided by Inertia in `setup`.

### Vue 2

```js
createInertiaApp({
  setup({ el, App, props, plugin }) {
    Vue.use(plugin) // use the plugin
    new Vue({
      render: h => h(App, props),
    }).$mount(el)
  }
...
```

### Vue 3

```
createInertiaApp({
  setup({ el, App, props, plugin }) {
    createApp({ render: () => h(App, props) })
      .use(plugin) // use the plugin
      .mount(el)
  },
...
```

**Comment by Mazeland** [comment]
Thank you so much for your answer! I'm working on another project at the moment. 
I will test this as soon as possible and let you know if it succeeded.

**Comment by Mazeland** [comment]
Thnx a lot @ElMassimo, the problem is fixed now :)

**Comment by JSabelli-FDX** [comment]
The problem is happening again in v1.0 of Inertia and Vue 3. I am also using Laravel Mix. I can't use Vite because we strictly need Laravel Mix for our stuff.
