### ISSUE TITLE
Help with file uploads and large object

### ISSUE THREAD

**Issue by roarkmccolgan** [inertiajs/inertia#118]
Hi Guys,

This is more of help wanted than an issue.

I would like to upload images along with a large deeply-nested object.
The docs suggest using the formData API to do this, however with a large data object doing this:
```
data.append('first_name', first_name || '')
... //for each property and nested property 
```
This feels very wrong and unmaintainable.

What I am doing now is json.stringify'ing the complex data object on the frontend and adding it to the formData object as a property of it and then json_decode'ing it on the backend back to an object.

Do you think this is OK, is there a better way to handle this?

Thank you so much for the awesome package

**Comment by georgehanson** [comment]
This looks like a useful javascript package you could try. You pass it an object and it returns back a FormData instance. You could then append the file to the FormData instance - https://github.com/therealparmesh/object-to-formdata

N.B: I haven't used the above package before, I just came across it a few days ago and thought it might help you.

**Comment by roarkmccolgan** [comment]
Hey @georgehanson thanks for the reply and suggestion.
I have actually already tried that exact package, and it was able to convert the request into a formdata instance I started getting a "too many request variables" PHP error.
Because I needed indexed arrays, the converted data looks  like this:
```
sections[0]['option'][0]['name']='option1'
sections[0]['option'][0]['price']='price1'
```
a variable for every property happens thus the error

Great suggestion though!

**Comment by reinink** [comment]
I agree that the `FormData` API is kind of ugly, and that it's much nicer to just submit JSON, but this isn't really a limitation of Inertia, but rather just the way these JavaScript APIs work. I haven't personally JSON encoded and decoded like that, although that's a clever idea!

You can see an example of how I do this in the Ping CRM source code [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Create.vue#L62-L68).

Hope that helps!

**Comment by begueradj** [comment]
Is there a way to upload large files with Inertia.js ?
I currently can upload files of less than 2 MB size in Laravel + Vue + Inertia.js

**Comment by jefhar** [comment]
@begueradj you probably need to adjust your PHP [post_max_size](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) setting. Add a route: `Route::get('secret', static function () { phpinfo(); });` and use it to check your php-fpm settings. Likely not an inertia issue.

**Comment by begueradj** [comment]
@jefhar Thank you for the feedback. And sorry, I forgot to mention that my **php.ini** settings are big enough to handle an image of 5 MB size. This is really weird. I wonder if there ise something wrong with  inertia's` useForm()`

**Comment by Ayush-Mishra-7** [comment]
Any update on this?? There seems to be some issue from Inertia.js form handling as when I do Inertia.post() it seems to not work for large files. I have made sure that all the server and php.ini settings are correct but nothing seems to work. Thanks
