### ISSUE TITLE
useForm messes up props inside v-for loop after form.delete()

### ISSUE THREAD

**Issue by Arturexe** [inertiajs/inertia#1180]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

I built a CMS with simple CRUD functionality and resource controllers. This is my vue component hirarchy (parent/child):

gallery page (sends `data array` to table as prop)
----table with rows (renders row components with `v-for loop` and passes `data row object` as prop)
--------row component
--------row component
--------row component

The row components have a `delete` button that upon press activates a `destroy()` function, which sends `form.delete()` to the backend:

```
const destroy = () => {
    if (confirm('Delete entry?')) {
        form.delete('/admin/gallery/' + props.data['id'])
    }
}
```
        
additionally the `form` sends the `image_path` that has to be deleted from public storage:

```
const form = useForm({
    image_path: props.data['image_path']
})
```

Backend:

```
public function destroy(Request $request, $id)
{

    Storage::disk('public')->delete($request->image_path);
    Gallery::destroy($id);

    return redirect('/admin/gallery');
}
```

And this is where the props get messed up. Inertia seems to redirect to `/admin/gallery` without updating the `props` on the `gallery page`, that are passed down to the components. The result is that wrong `image_path`s are assigned to rows, which prevents the removal of images from the `public storage`.

I was able to workaround this by using the `$id` parameter inside the controller to recall the `image_path` from the database entry, but this is unnecessary overhead compared to using the `$request` parameter to get the `image_path` directly. But it gets messed up through `useForm` in the frontend.

```
public function destroy($id)
{

    $image_path = Gallery::where('id', $id)->get('image_path')[0]['image_path'];
    
    Storage::disk('public')->delete($image_path);
    Gallery::destroy($id);

    return redirect('/admin/gallery');
}

```
Is this a bug or intended behaviour? Should props and `useForm` not be updated after a record is destroyed?

**Comment by ciamarro** [comment]
Shot in the dark here but do your <row components/> have unique ":ids"

**Comment by Arturexe** [comment]
@ciamarro The database table has unique ids which is passed to the components via props. As I said, using the id via `props` works, using `useForm` with data messes up the `v-for rendering`.

**Comment by ciamarro** [comment]
Sorry, I meant to ask if each component had its own unique `:key`, not `:id`

**Comment by Arturexe** [comment]
I don't think I've put any logic in that. Would it help the problem? Maybe using each `id` as key?

**Comment by ciamarro** [comment]
Yes, something like this
```
<row-component class="w-full" v-for="record in records" :key="record.id">
<!-- etc -->
</row-component>
```

**Comment by Arturexe** [comment]
@ciamarro That solved the problem. Thank you
