### ISSUE TITLE
Can we use inertia components with portals?

### ISSUE THREAD

**Issue by hailwood** [inertiajs/inertia#119]
We're using inertia and it's great, but now we're looking at using modals.
Specifically we want to use react-modal which uses Reacts `portal` api to render the modal at the bottom of the page outside of the main app element.

In a component it just looks like

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import Modal from 'react-modal';
import OurCustomComponent from 'components/our-custom-component';

function App(){
  const [modalIsOpen,setIsOpen] = React.useState(false);

    return (
      <div>
        <button onClick={() => setIsOpen(true)}>Open Modal</button>
        <Modal
          isOpen={modalIsOpen}
          onRequestClose={() => setIsOpen(false)}
          contentLabel="Example Modal"
        >
            <OurCustomComponent />
        </Modal>
      </div>
    );
}
```

However we run into issues if `OurCustomComponent` uses inertia's `usePage` -
> Uncaught Error: usePage must be used within the Inertia component

Is there any way to make this work without having to use `usePage` in the parent component and pass through what we care about to the modal?

**Comment by snaptopixel** [comment]
I'm no react expert but `usePage` is [simply wrapping](https://github.com/inertiajs/inertia-react/blob/master/src/usePage.js) `useContext` which is where the incompatibility is coming from. Can you `usePage` inside the `App` component and pass it through to `<OurCustomComponent page={page}/>`?

**Comment by hailwood** [comment]
Yeah, that's what I thought I might need to do, but I was really hoping I could avoid it.

I have a hook I use to connect inertia with formik - 

```js
import {usePage} from '@inertiajs/inertia-react';
import React from 'react';
import mapValues from 'lodash.mapvalues';

function useInertiaForm(values) {
  const {errors: serverErrors} = usePage();
  const errors = mapValues(serverErrors, fieldErrors => fieldErrors[0]);
  const touched = mapValues(serverErrors, () => true);
  const formikProps = {initialValues: values, initialErrors: errors, initialTouched: touched, enableReinitialize: true};

  return [values, errors, touched, formikProps];
}

export default useInertiaForm;
```

And I use it in my forms as follows

```jsx
import React from 'react';
import PrimaryButton from 'Components/PrimaryButton';
import {Inertia} from '@inertiajs/inertia';
import route from 'laravel-routes';
import {ErrorMessage, Field, Form, Formik} from 'formik';
import * as Yup from 'yup';
import useInertiaForm from 'Support/Hooks/useInertiaForm';

const CreateOrganisationForm = (props) => {

  const [, , , formikProps] = useInertiaForm({
    name: '',
  });


  const validationSchema = Yup.object().shape({
    name: Yup.string()
      .required('Please provide an organisation name'),
  });

  return (
    <Formik {...formikProps} onSubmit={values => Inertia.post(route('account.organisations.store'), values)} validationSchema={validationSchema}>
      <Form {...props}>

        <label className="block mt-5">
          <span className="text-gray-700">What's the name of the organisation?</span>
          <Field className="form-input mt-1 block w-full" type="text" name="name" placeholder="Acme Corp"/>
          <ErrorMessage name="name" component="div" className="text-red-500 text-xs italic"/>
        </label>

        <div className="mt-5">
          <PrimaryButton type="submit">Create</PrimaryButton>
        </div>
      </Form>
    </Formik>
  );
};

export default CreateOrganisationForm;
```

So the forms are isolated components, which in this case I want to render in the modal, if I have to pull the usePage out of the hook modal, it pulls it out of my form as well

**Comment by snaptopixel** [comment]
Can you skip all the React gymnastics and just use the Axios obj returned from `Inertia.post`?

**Comment by hailwood** [comment]
In the end it just came down to me using the `<ModalProvider />` outside of the `<Inertia />` component.

Changed the order in which they're wrapped and we're golden.
