### ISSUE TITLE
Reloading in Safari

### ISSUE THREAD

**Issue by scottzirkel** [inertiajs/inertia#12]
Tested in Safari 12.03 & 12.1

The initial page loads fine, but when you refresh, it throws the following error:

```
"TypeError: undefined is not an object (evaluating 'window.performance.getEntriesByType("navigation")[0].type')"
```

I added a length check on the array in inertia.js line 28 and it seems to work. Happy to open a PR.

**Comment by reinink** [comment]
Thanks for reporting this Scott! I know exactly what this is:

https://github.com/inertiajs/inertia/blob/c4ca9c04bee73825e605e35560905545c3f0ab6a/src/inertia.js#L26-L30

**Comment by scottzirkel** [comment]
Yup. I changed it to this and it worked:

```
  navigationType() {
    if (window.performance) {
      if (window.performance.getEntriesByType('navigation').length) {
        return window.performance.getEntriesByType('navigation')[0].type
      }
    }
  },
```

**Comment by reinink** [comment]
And yes, a PR would be great! Sorry, didn't see your last line there.

**Comment by reinink** [comment]
If you're putting together a PR, you can do this:

```js
if (window.performance && window.performance.getEntriesByType('navigation').length) {
```

**Comment by scottzirkel** [comment]
Yeah, just cleaning it up to do that. :)
