### ISSUE TITLE
<inertia-link method="post">

### ISSUE THREAD

**Issue by abdessamadelhamdany** [inertiajs/inertia#121]
When using inertia link using the post method, an iframe popup, anyway we can redirect or handle the server response using VueJs like we would do using axios.

reproduce in new laravel installation with setup of inertiaJs

`<inertia-link href="/logout" method="post">Logout</inertia-link>`

**Comment by Juhlinus** [comment]
Hello @abdessamadelhamdany !

Inertia expects an inertia response, if it doesn't get one then it will generate a popup.

Have a look at the documentation regarding [Responses](https://inertiajs.com/responses).

**Comment by abdessamadelhamdany** [comment]
Hello @Juhlinus 
Now I have a better idea, so instead of handling it in the frontend part, we'll redirect to a Inertia response. In this case redirect to the '/' route.

Thank you 👍

**Comment by Juhlinus** [comment]
@abdessamadelhamdany Great! If you feel this issue has been resolved, then please close the issue. 😄
