### ISSUE TITLE
How to trigger toast programmatically in vue3/inertia, composition api

### ISSUE THREAD

**Issue by lingtalfi** [inertiajs/inertia#1218]
Hi, I'm trying to make a toast appear using a flash message (from laravel), and I read this documentation: https://inertiajs.com/shared-data#flash-messages, which works fine.

But in the doc example, the toast is manually coded.
Although that's nice, I would prefer to call a dedicated toast package, such as this one for instance: https://github.com/ankurk91/vue-toast-notification.

Now for this particular toast package, the triggering of the toast is done programmatically, like so:

```
  const $toast = useToast();
  let instance = $toast.success("Hello message");
```

Also, I would like to use the composition api (if possible), and so I'm trying to detect whenever a flash message is available, but I don't know how. 

Here is my code so far:

```
<script setup>
import {Head} from '@inertiajs/inertia-vue3';
import {watch} from 'vue';
import {useToast} from 'vue-toast-notification';
import {usePage} from '@inertiajs/inertia-vue3';

let message = usePage().props.value.flash.message;
watch(message, function() {
  if (message) {
    const $toast = useToast();
    let instance = $toast.success('Hello message');
  }
});


</script>
```

And it doesn't work (i.e., I can not trigger the toast because it doesn't detect the change on the flash message).

So my question is basically:

how do you translate a condition like this...
```
  <div v-if="$page.props.flash.message"
       class="text-white text-4xl bg-emerald-800 relative z-20 p-4">
    {{ $page.props.flash.message }}
    <div class="absolute top-2 right-2">X</div>
  </div>
```

...in the composition api?

Note: my laravel controller looks something like this:

```
    public function aboutMeUpdate(AboutMeRequest $request)
    {
        AboutMe::firstWhere('user_id', Config::$ownerId)->update($request->validated());
        return redirect()->route('aboutMeEdit')->with('message', 'About Me info updated');
    }
```

**Comment by lingtalfi** [comment]
Ok, I found a way to trigger a self made toast programmatically, so I'm using that for the moment, but I leave the issue open in case there is a more elegant solution.

My work around so far looks like this:
In the vue component, script part:
```
<script setup>
import {Head} from '@inertiajs/inertia-vue3';
import AdminNavbar from '@/components/Navbars/AdminNavbar.vue';
import Sidebar from '@/components/Sidebar/Sidebar.vue';
import HeaderStats from '@/components/Headers/HeaderStats.vue';
import FooterAdmin from '@/components/Footers/FooterAdmin.vue';
import {usePage} from '@inertiajs/inertia-vue3';
import {computed, ref, watch} from 'vue';

const isToastActive = ref(false);

const triggerToast = computed(() => {
  let ret = usePage().props.value.toast;
  if (undefined !== ret) {

    isToastActive.value = true;
    setTimeout(function() {
      isToastActive.value = false;
    }, 3000);
  }
});


</script>
```

In the vue component, template part:
```
  <div v-if="isToastActive"
       class="text-white text-2xl bg-emerald-800 z-20 p-4 max-w-sm fixed right-2 top-2 mynotif active">
    {{ $page.props.toast }}
  </div>
  <div v-if="triggerToast"></div>
```

Notice that the line ```<div v-if="triggerToast"></div>``` does nothing visually, but it's necessary to make vue trigger the computed callback. Without this line, I suppose vue optimizes its processing and does not trigger the computed callback.


So, with this workaround, after 3 seconds, I'm able to submit the edit form again and see the notification everytime I save.

**Comment by ngiraud** [comment]
Hi,
I'm using (https://github.com/Maronato/vue-toastification)) to display my notifications, but it seems to be the same.
Here is how I display the notifications : 

```
const toast = useToast()

watch(() => usePage().props.value.flash, flash => {
    let toastId = null;

    if (flash.message) {
        toastId = toast({component: Notification, props: {type: TYPE.DEFAULT, title: flash.message}})
    }
    if (flash.success) {
        toastId = toast({component: Notification, props: {type: TYPE.SUCCESS, title: flash.success}})
    }
    if (flash.error) {
        toastId = toast({component: Notification, props: {type: TYPE.ERROR, title: flash.error}})
    }

    if (toastId !== null) {
        setTimeout(() => toast.dismiss(toastId), 5000)
    }
}, {deep: true})
```

Notice the `() => usePage().props.value.flash` when watching the changes, I think this should do the trick because I think it needs to watch a getter.

**Comment by lingtalfi** [comment]
@ngiraud: Thanks :) It did the trick.
