### ISSUE TITLE
Missing Types when using with Typescript

### ISSUE THREAD

**Issue by tcampbPPU** [inertiajs/inertia#1219]
### Versions:

- `@inertiajs/inertia` version: ^0.11.0"
- `@inertiajs/inertia-vue3` version: ^0.6.0

### Describe the problem:

I am using Typescript with my Inertia and Vue 3 app.  I am wondering how to fix possibly in my IDE several missing types. The primary one I am wondering about is the `route` method. This works fine inside the `<template></template>` as you can confirm with Laravel Jetstream, but when using with the script I get this: `Cannot find name 'route'.`

Is there any way to include this types in something like a `vue-shim.d.ts` or somthing of that nature that makes my IDE think this is valid?

### Steps to reproduce:

Here is a small example where if you where to copy in IDE like VS Code you would see the same error.
> You can test this with a new Laravel Jetstream app using Vue 3 to the file like `resources/js/Pages/Welcome.vue`

```vue
<script lang="ts" setup>
import { reactive, PropType } from 'vue'
import { Inertia } from '@inertiajs/inertia'
import JetButton from '@/Jetstream/Button.vue'

const props = defineProps({
    filters: {
        type: Object as PropType<{
            limit: number
            page: number
            search: string
        }>,
        required: true,
        default: () => {},
    },
})

const form = reactive({
    limit: props.filters.limit,
    page: props.filters.page,
    search: props.filters.search,
})

const reload = () => {
    Inertia.get(route('dashboard', { ...form, remember: 'forget' }))
}
</script>
<template>
    <div>
        <JetButton @click="reload">
            Reload
        </JetButton>
    </div>
</template>
```
![image](https://user-images.githubusercontent.com/25044744/177872562-3d6af4e4-40bc-4fb1-bd7c-c58302ac890c.png)

Here is my `tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "preserve",
        "sourceMap": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowJs": true,
        "lib": [
            "esnext",
            "dom"
        ],
    },
    "typeRoots": [
        "./node_modules/@types",
        "resources/js/Types"
    ],
    "include": [
        "resources/js/**/*.ts",
        "resources/js/**/*.d.ts",
        "resources/js/**/*.vue"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by SuperDJ** [comment]
I guess `route()` is from Ziggy and not Inertia.

**Comment by alexandersix** [comment]
I was just bumping into this issue and resolved it with the following steps:

1. Install the `@types/ziggy` NPM package
2. Add `@types/ziggy` to your `types` array in `tsconfig.json`
```json
{
  "types": [
    "@types/ziggy"
  ]
}
```
3. Import the routes function in your TS Vue component with `import route from "ziggy-js";`

Hopefully that will resolve the issue for you! Seems to be working on my end, but I'm _very_ new to using Typescript with Inertia, so your mileage may vary.

**Comment by tcampbPPU** [comment]
@alexandersix Thanks so much for this! Seems to me working as expected for me now

**Comment by tcampbPPU** [comment]
Hey @alexandersix wondering if you were able to figure how to add/extend the typing of the `$page` property or the `usePage()` hook.
![image](https://user-images.githubusercontent.com/25044744/179069007-a9e9e8f9-0585-480d-a8f3-8f4f214fb2bb.png)
