### ISSUE TITLE
Implementing a data table with a details modal/drawer with Inertia

### ISSUE THREAD

**Issue by veeral-patel** [inertiajs/inertia#122]
Thanks for inertia!

Say I want to create a UI like this:

https://miro.medium.com/max/1600/1*NSGIPqQ5nnFhunR8Osiunw.gif

I have a datatable, and when I click on a row, it should open a modal or drawer with additional details about that row.

With a SPA, this is easy to do. When you click on a row, make an API request to fetch additional data about that row, show a loading indicator in the meantime, and then render the modal when you get a response.

How would you implement something like this with inertia, where you have no API?

**Comment by georgehanson** [comment]
No different from how you would do if you had a full SPA.

You would still have API endpoints and you would call them from your front end (such as with Vue.js).

**Comment by veeral-patel** [comment]
@georgehanson got it. I was interested in inertia because it promised that you didn't need to create an API. But it seems like you still need to create an API!

Am I not understanding something?

**Comment by reinink** [comment]
Yeah you don't need an API. I think what @georgehanson is getting at is that you can simply make an XHR request to load some data from a local endpoint and then show a modal in these cases. Inertia.js works excellent for pages, but for non-pages (such as a modal), as classic XHR request is a totally valid approach. 👍

**Comment by veeral-patel** [comment]
@reinink would it be accurate to say you don't need GET API endpoints, but you do need all other API endpoints?

I can see how you can make an ORM call and pass data as props from your server side to client side app.

But how do you allow the client side app to create/update/data without an API?

**Comment by georgehanson** [comment]
@veeral-patel You can still use normal form POST requests that refresh the page, but if you want to make resource creation, updating and deletion without a page refresh then you can just use XHR requests. You don't *need* to have API endpoints if you don't want to.

**Comment by reinink** [comment]
Closing this in favour of #249. 👍
