### ISSUE TITLE
What can't inertia do vs SPAs?

### ISSUE THREAD

**Issue by veeral-patel** [inertiajs/inertia#123]
Thanks for inertia!

I'm thinking about the tradeoffs between inertia and a SPA that consumes a API.

With inertia, I get faster development time, as I don't need to build an API and I can just consume data from my ORM.

However - what can't I do with inertia that I can do with a SPA? What is difficult to do with inertia that I can do with a SPA?

I know offline support is one thing, what are others?

**Comment by lucasdcrk** [comment]
You can't use loading placeholders (https://zalog.ro/placeholder-loading/) like you would typically do with a Vue SPA.

**Comment by reinink** [comment]
@lucasdcrk That's true right now, but I've actually already got a prototype of this feature working in Inertia.js. See [here](https://twitter.com/reinink/status/1179498715129765888).

@veeral-patel At the end of the day, Inertia apps are really just Vue.js, React and Svelte apps. Inertia really just handles the routing and data providing (which are huge of course), but for the rest, they are classic SPAs. Meaning, there shouldn't be much that you can't do with an Inertia app that you can't do with a regular SPA. You can always drop down to making plain XHR requests for some parts of your app if Inertia requests don't make sense.

That said, two things come to mind that are not possible with Inertia today, that are possible with some JavaScript SPA frameworks. Those are 1. offline support, and 2. server-side rendering. Who knows what we're able to do in the future though. 💪

**Comment by lucasdcrk** [comment]
@reinink Awesome!! Does it works right now?

**Comment by reinink** [comment]
@lucasdcrk Sorry, not yet! That feature still requires a bunch of work. Probably in a 3-5 months. 👍

**Comment by deantheiceman** [comment]
@reinink hows the progress on this? any luck? really keen to see something like this

**Comment by reinink** [comment]
@deantheiceman Sorry no progress yet.

**Comment by espressonist** [comment]
@reinink Just found out about this library and I wanna study about it this week. I'm curious about the placeholder-loading too. How's the progress? Thank you :bow:

**Comment by egyptik** [comment]
@reinink Great to see you got server-side rendering to work! Do you have any ideas regarding offline support? Would that be possible at all? Happy to help work on that!

**Comment by harunalrd** [comment]
> @lucasdcrk That's true right now, but I've actually already got a prototype of this feature working in Inertia.js. See [here](https://twitter.com/reinink/status/1179498715129765888).
> 
> @veeral-patel At the end of the day, Inertia apps are really just Vue.js, React and Svelte apps. Inertia really just handles the routing and data providing (which are huge of course), but for the rest, they are classic SPAs. Meaning, there shouldn't be much that you can't do with an Inertia app that you can't do with a regular SPA. You can always drop down to making plain XHR requests for some parts of your app if Inertia requests don't make sense.
> 
> That said, two things come to mind that are not possible with Inertia today, that are possible with some JavaScript SPA frameworks. Those are 1. offline support, and 2. server-side rendering. Who knows what we're able to do in the future though. 💪

How's the progress? Its support for reactjs?

**Comment by kratos-digital** [comment]
No offline support yet or not possible at all?

**Comment by towel** [comment]
Bump. I guess instead of everyone trying to hack something for this on their own, we would all benefit from an official implementation.

A possibly quick implementation could allow for something like a `router.mount(path, ComponentName) ` function that would just load and mount the component, leaving the data fetching to the component itself.
