### ISSUE TITLE
Is Inertia's render prop method for react documented anywhere?

### ISSUE THREAD

**Issue by hailwood** [inertiajs/inertia#128]
So I was looking for a way to have my base app include all the relevant providers I required as I didn't want to have to include them all in my layouts.

In the docs I couldn't find anything, but reading through the code I found you can do something like

```jsx
<InertiaApp
    initialPage={JSON.parse(app.dataset.page)}
    resolveComponent={async name => (await import `./Pages/${name}`)).default}>
    {({key, props, Component}) => {
        const child = <Component key={key} {...props} />;
        return (
            <ModalProvider>
                {Component.layout ? Component.layout(child) : child}
            </ModalProvider>
        );
    }}
</InertiaApp>
```

With the part of interest being

```jsx
{({key, props, Component}) => {
    const child = <Component key={key} {...props} />;
    return {Component.layout ? Component.layout(child) : child};
}}
```

**Comment by reinink** [comment]
This is an old issue. 😂 

So, no, we don't document the render functions right now. These are baked into the adapters, which can now be found in this repo. This is typically found in the adapter file labelled "app". 👍
