### ISSUE TITLE
Is it possible to globally inject custom header value in axios with inertiajs react

### ISSUE THREAD

**Issue by ryanzeng1990** [inertiajs/inertia#1284]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-react` version:0 .8.0
- `axios`: 0.21.4

### Describe the problem:

I think I have the similar issue like this one : https://github.com/inertiajs/inertia/issues/1046

### Steps to reproduce:
I added the following code in app.js file, but it's not work,I have ensured my axios version is the same as inertiajs one
```
import axios from "axios";
axios.interceptors.request.use(function (config) {
    config.headers.common['X-Custom-Id'] = 'This is my custom id';
    return config
})
```

**Comment by reinink** [comment]
Hey! You can do this like this:

```js
import { Inertia } from '@inertiajs/inertia'

Inertia.on('before', (event) => {
  event.detail.visit.headers['my-custom-header'] = 'sweet'
})
```

Note, this only works because you're modifying an existing object. For example, this won't work, as it creates a whole new object:

```js
import { Inertia } from '@inertiajs/inertia'

Inertia.on('before', (event) => {
  event.detail.visit.headers = { 'my-custom-header': 'sweet' }
})
```

Hope that helps 👍
