### ISSUE TITLE
The `<title>` tag of the `<Head>` component doesn't appear in the page source. 

### ISSUE THREAD

**Issue by osmianski** [inertiajs/inertia#1288]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

The `<title>` tag of the `<Head>` component changes the title of the browser tab just fine. However, if you check the page source, there is no `<title>` element.

In some use cases, it's important for SEO.

### Steps to reproduce:

1. In the `view-source:http://demo.inertiajs.com/login`, there is no `<title> element.

**Comment by craigrileyuk** [comment]
The page source is what's downloaded from the server. It won't have anything that's processed client side in it.

Sounds like you need to read the Server-Side Rendering section of the documentation.

**Comment by osmianski** [comment]
I did read it, and I agree - it's SSR. 

However, with Inertia, all Vue components are SSRed, and you can see the final HTML in the page source.

Meta description, added using Head component is also SSRed.

But for some reason, `<title>`, added using the same Head component is not SSRed, and imo, it should.

**Comment by osmianski** [comment]
You know what? You were right, and I was wrong. The page in question is not SSRed, so this is not really an issue.
