### ISSUE TITLE
Persistent layouts and named slots

### ISSUE THREAD

**Issue by memdev** [inertiajs/inertia#129]
Is it possible to have named slots with persistent layouts?

Example:

Layout.vue:
```vue
<template>
    <div>
        <div class="bg-gray-800 pb-32">
            <header class="py-10">
                <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

                    <slot name="title" />

                </div>
            </header>
        </div>
        <main class="-mt-32">
            <div class="max-w-7xl mx-auto pb-12 px-4 sm:px-6 lg:px-8">

                <slot/>

            </div>
        </main>
    </div>
</template>
```

Dasboard/Index.vue:
```vue
<template>
    <div title="Dashboard">
        <template v-slot:title>
            <div>
                Content for "title" slot...
            </div>
        </template>

        <div>
            Content for default slot...
        </div>
    </div>
</template>

<script>
    import Layout from '@/Shared/Layout'

    export default {
        layout: Layout
    }
</script>
```

If I try this approach, even the default slot stays empty. If I remove `<template v-slot:title>` from Index.vue, the default slot gets rendered.

**Comment by slovenianGooner** [comment]
Couldn't you just do...

```
<template>
    <layout title="Dashboard">
        <template v-slot:title>
            <div>
                Content for "title" slot...
            </div>
        </template>

        <div>
            Content for default slot...
        </div>
    </layout>
</template>

<script>
    import Layout from '@/Shared/Layout'

    export default {
         components: { Layout }
    }
</script>
```

**Comment by memdev** [comment]
Yeah, I could, but then it's not anymore a persistent layout (see https://inertiajs.com/pages#persistent-layouts) and will get re-rendered on every navigation.

**Comment by jasonlfunk** [comment]
I would also love to see this. :+1:

**Comment by memdev** [comment]
Seems like this isn't so easy to implement. But there is a workaround I can live with. 
See https://github.com/inertiajs/inertia-vue/issues/129#issuecomment-640848129

**Comment by xKairu** [comment]
Any work on this? I would use the workaround in https://github.com/inertiajs/inertia-vue/issues/129#issuecomment-640848129 but I swap my layout depending on if the page is a frontend page or admin panel page, so hardcoding a layout isn't gonna work.

**Comment by claudiodekker** [comment]
Related: #171
