### ISSUE TITLE
useForm should use undefined instead of null

### ISSUE THREAD

**Issue by Im-Fran** [inertiajs/inertia#1308]
### Versions:

- `@inertiajs/inertia` version: 0.11.1
- `@inertiajs/inertia-react` version: 0.8.1

### Describe the problem:
Let's say I have the following form (with the form helper):
```jsx
const {data}= useForm({
	name: user.name,
	email: user.email,
	notifications_email: user.notifications_email,
})
```
So, the column `notifications_email` can be nullable and it'll be replaced with the default email if null. Currently if I use an input like so:
```jsx
<input value={data.notifications_email}/>
```
and `notifications_email` is null I get the following error: 
![image](https://user-images.githubusercontent.com/30329003/194715932-6e5b003d-2d02-4dc8-85e1-1150442589d7.png)
and as the error suggests I added `notifications_email: user.notifications_email || undefined` to the useForm declaration, now the error is gone.

My idea would be that inertia-react provides a way to detect null values and replace them with undefined instead of null, so this wouldn't happen, and the developer (in this case me xD), won't have to do for every nullable value `nullable_value: data.nullable_value || undefined`, this would save some time in the development process.

**Comment by bVNyDUKE** [comment]
I don't believe this should be inertia form helpers job and the solution is already very simple. Don't see the need for this issue personally.

**Comment by Im-Fran** [comment]
Ok, I’ll just write an implementation on my end to automate this, thanks anyway :p
