### ISSUE TITLE
Exposing the undelying HTTP client

### ISSUE THREAD

**Issue by VicGUTT** [inertiajs/inertia#132]
Is there any plans on letting a user configure/set the underlying HTTP client to be used ? What if that client follows a specific interface ?

In my particular use case, I'd actually use a "customized" Axios, which Inertia would have absolutly no notion of as the API is exactly the same.
My "customized" Axios just handles caching requests that have previously been made, and therefore allows for :
- Not re-fetching the page the user is currently on
- Faster page change when re-visiting a cached route

Some food for thoughts 🤷‍♂️

**Comment by reinink** [comment]
We are slowly working towards removing axios from Inertia, so I don't think this will likely ever happen.

We are exposing more options to Inertia.visit(), to allow more customization. For example, we recently added the ability to set custom headers on an Inertia request.

Who knows, maybe in the future we add first-class support for things like caching.

Hope that makes sense!

**Comment by jhourlad** [comment]
Manual visit looks good but not allowing JSON responses seems like something out of the early 2000's.
