### ISSUE TITLE
Inertia meta tags contain unwanted "inertia" attribute

### ISSUE THREAD

**Issue by riabiy-denis** [inertiajs/inertia#1368]
### Version:

- `@inertiajs/vue3` version: any :) 

### Description AND steps

This behaviour is in inertia <Head> component. `inertia` attribute is always present, even, if it's empty. 
I mean [this one](https://github.com/inertiajs/inertia/pull/704/commits/4321157e754c2f0188bcbaa9ba2e13db8f1b1504) :) 

Just go to Ping CRM and you will see that

`<Head title="Login" />` turns into  `<title inertia="">Login - Ping CRM</title>`

I'd prefer to hide `inertia` :)

**Comment by reinink** [comment]
Hey, Inertia uses this attribute to keep track of head elements, so this is necessary is you're using the Inertia `Head` component.
