### ISSUE TITLE
`form.put` is not a function

### ISSUE THREAD

**Issue by wonder95** [inertiajs/inertia#1369]
### Version:

- `@inertiajs/vue3` version: 0.6.0

### Describe the problem:

I am attempting to use the [form helper](https://inertiajs.com/forms) to submit an edit form. However, when I submit the form, I get an error saying `TypeError: form.put is not a function`.

### Steps to reproduce:
```
<script setup>
    import { Head, Link, useForm } from '@inertiajs/inertia-vue3'
    import { Inertia } from '@inertiajs/inertia'
    import TextInput from '@/Components/ping/TextInput.vue'
    import PrimaryButton from '@/Components/PrimaryButton.vue'
    import SelectInput from '@/Components/ping/SelectInput.vue'

    const props = defineProps({
        user: Object
    })

    const form = useForm({
        first_name: props.user.first_name,
        middle_name: props.user.middle_name,
        last_name: props.user.last_name,
        preferred_first_name: props.user.preferred_first_name,
        member_number: props.user.member_number,
        card_number: props.user.card_number,
        email: props.user.email,
        member_type: props.user.member_type,
        status: props.user.status,
        profile: props.user.profile
    })

    function update(form) {
        form.put(`/users/${props.user.id}`)
    }
</script>

<template>
    <div>
            <form @submit.prevent="update">
             ...
            </form>
    </div>
</template>
```
And here is my Laravel route defintion:
```
Route::put('users/{user}', [UserController::class, 'update'])
    ->name('users.update')
    ->middleware('auth');
```
When viewing the component in the Vue dev tools, the `form` object shows as having all of the form verbs (.i.e. post, put, delete, etc) as valid form properties.

The docs are not up to date with the current `<script setup>` syntax, so I'm struggling with getting a form submission like this to work.

**Comment by Ifriqiya** [comment]
Try this: 
''''
    const form = useForm({
         _method: 'PUT',
        first_name: props.user.first_name,
        middle_name: props.user.middle_name,
        last_name: props.user.last_name,
        preferred_first_name: props.user.preferred_first_name,
        member_number: props.user.member_number,
        card_number: props.user.card_number,
        email: props.user.email,
        member_type: props.user.member_type,
        status: props.user.status,
        profile: props.user.profile
    })
''''
and `    function update(form) {
        form.post(`/users/${props.user.id}`)
    }`

**Comment by wonder95** [comment]
I assume the methods need to match, so it should be 
```
function update(form) { form.put(/users/${props.user.id}) } 
```
correct?

Also, what is the point of having the helper methods (e.g. `form.put`, `form.post`, etc) if you still have to specify `_method` in `useForm()`?

**Comment by craigrileyuk** [comment]
Your problem is here:

```
function update(form) {
    form.put(`/users/${props.user.id}`)
}
```

You're defining `form` as a parameter of `update` when it already has access to `form` object that `useForm` returns. What's happening is that when `@submit.prevent="update"` is called, it's passing the submit event as an argument to your `update` function and then you're trying to call `put()` on that submit event, not your `useForm` object.

A simple change to:

```
function update() {
    form.put(`/users/${props.user.id}`)
}
```

should sort your problem.

In general, if something this simple fails to work as expected in a project that has been around for a while and is quite popular, chance are it's going to be user error rather than an issue with the package itself.

**Comment by wonder95** [comment]
Yes, I was accordingly chastised elsewhere yesterday, too. I removed the parameter, and and works now. My apologies

Thank you for the detailed explanation.
