### ISSUE TITLE
Redirect as a Inertia request

### ISSUE THREAD

**Issue by slovenianGooner** [inertiajs/inertia#137]
OK,

so I have this modal window - that upon submit would send an Inertia request to the server:

```js
this.$inertia..post(url, {
          _method: 'PUT',
          ids: this.ids,
          orderNo: this.form.orderNo,
          fields: this.fields,
          skip_base_order_update: skip_base_order_update
        })
```

What I would like to achieve, considering it's a modal is to redirect back to the underlying route but with loading only certain variables, like I would with the `only` property. But when I do `Redirect::back()->withErrors()` in Laravel controller, all variables get reloaded.

Is it possible to redirect back with only loading certain variables? Would this be possible using some headers or something? I inspected the Inertia request when using `only` but couldn't seem to figure it out.

Thanks for your help.

**Comment by reinink** [comment]
The feature you want to use is [partial reloads](https://inertiajs.com/requests#partial-reloads), which allows you to only request a subset of the data on subsequent requests to the same endpoint. To do this, pass the keys of the data you want back as an array.

```js
this.$inertia..post(url, {
  _method: 'PUT',
  ids: this.ids,
  orderNo: this.form.orderNo,
  fields: this.fields,
  skip_base_order_update: skip_base_order_update,
  only: ['the', 'data', 'you', 'want']
})
```
