### ISSUE TITLE
$page type not defined

### ISSUE THREAD

**Issue by nurdism** [inertiajs/inertia#1382]
### Version:

- `@inertiajs/vue3` version: 1.0.0

### Describe the problem:

`$page` type for `ComponentCustomProperties` is not defined in the typings for `@inertiajs/vue3`

**Comment by martinbean** [comment]
I’m getting the same too with code like this:

```html
<Link
  v-bind:class="{ 'active': $page.component === 'Dashboard' }"
  v-bind:href="dashboardUrl"
>Dashboard</Link>
```

The error I get in Visual Studio Code is:

> `Property '$page' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => ...'.ts(2339)`

**Comment by nurdism** [comment]
I think the issue might be that [`types.ts`](https://github.com/inertiajs/inertia/blob/master/packages/vue3/src/types.ts#L15) never gets exported in `index.ts` where typescript is trying to pickup its types.

**Comment by nurdism** [comment]
As a temp fix you can declare your own types like this:
```ts
import type { Page } from '@inertiajs/core'
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $page: Page
  }
}
```

**Comment by rev4324** [comment]
You can also just import types.ts into your own .d.ts file as another temporary fix:
```js
import Types from "@inertiajs/vue3/types/types"
```

**Comment by iraklisg** [comment]
The last release (1.0.0) does not include that fix. Is it going to be included in a future patch?

**Comment by martinbean** [comment]
@reinink Hey, any news on what version this fix will be included in and a ETA on release?
