### ISSUE TITLE
createInertiaApp doesn't handle missing div to mount to. 

### ISSUE THREAD

**Issue by daamsie** [inertiajs/inertia#1391]
### Version:

- `@inertiajs/react` version: ^0.11.0

### Describe the problem:

I'm using inertia combined with AdonisJS. On pages where the mounting div doesn't exist (ie, pages that should not mount Adonis) an error is thrown in console. 

### Steps to reproduce:
Navigate to a page in an AdonisJS / InertiaJS project that doesn't have a div with the ID of "app"

-- I have done some debugging of this and track it down to the following code in createInertiaApp.js

```
export default async function createInertiaApp({ id = 'app', resolve, setup, title, page, render }) {
  const isServer = typeof window === 'undefined'
  const el = isServer ? null : document.getElementById(id)
  const initialPage = page || JSON.parse(el.dataset.page)
```

These two lines in particular

```
const el = isServer ? null : document.getElementById(id)
const initialPage = page || JSON.parse(el.dataset.page)
```

if the `document.getElementById(id)` returns null, you end up in a situation where it's trying to read the dataset of null and failing. 

Can be solved by adding a check between the two lines. 

`if (!el) return`

**Comment by reinink** [comment]
Hey, so the expectation here is that you only load Inertia.js via `createInertiaApp()` on pages that are actually Inertia endpoints.

If it's not an Inertia endpoint, I'd recommend omitting this from the scripts entirely. If that's not possible, then just wrap your `createInertiaApp()` call in a guard checks to see if an `#app` element exists on the page. Something like this:

```js
if (document.getElementById('app')) {
  createInertiaApp({
    // ...
  })
}
```

Hope that helps!

**Comment by daamsie** [comment]
Awesome, makes sense! Reworked my app a bit to avoid trying to load Inertia on those pages.  

I still do feel it would be good to catch the possibility of that div not existing, possibly returning an error / warning that makes it clear to the dev what went wrong. But that's your call. My immediate issue is fixed :)
