### ISSUE TITLE
manifest not found: Default persistent layout with SSR

### ISSUE THREAD

**Issue by stuartcusackie** [inertiajs/inertia#1404]
### Version:

- `@inertiajs/vue3` version: 0.6.0

### Describe the problem:

I have successfully set up a default persistent layout as described [here](https://inertiajs.com/pages#default-layouts), however, when running `npm run build` on the production server I am seeing this error:
```
Unable to locate file in Vite manifest: resources/js/Pages/Home.vue.
```

I have tried copying the exact code from app.js to ssr.js:
```
resolve: name => {
  const pages = import.meta.glob('./Pages/**/*.vue', { eager: true })
  let page = pages[`./Pages/${name}.vue`]
  page.default.layout = page.default.layout || DefaultLayout
  return page
},
````
but this doesn't work, and I can see in the build process that the mjs files are no longer generated, e.g.:
```
bootstrap/ssr/assets/Home-8813509e.mjs  
```

Apologies if this is not a bug and I am doing something wrong, but perhaps the docs could be updated to add additional steps for default persistent layouts with SSR.

### Steps to reproduce:

1. Set up SSR and 'Client side hydration' exactly as described in the [docs](https://inertiajs.com/server-side-rendering#add-server-entry-point)
2. Set up default persistent layout as described in the [docs](https://inertiajs.com/pages#default-layouts)
3. Run production built processes.
4. Visit home page.

### Additional info:

If I set up app.js like so:
```
resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
```
Then the manifest.json contains entries like:
```
  "resources/js/Pages/Home.vue": {
    "file": "assets/Home-72c519ce.js",
    "src": "resources/js/Pages/Home.vue",
    "isDynamicEntry": true,
    "imports": [
      "resources/js/app.js",
      "_Heading-f864e1b0.js"
    ]
  },
```

If I set up up app.js like so:
```
resolve: (name) => {
        const pages = import.meta.glob('./Pages/**/*.vue', { eager: true })
        let page = pages[`./Pages/${name}.vue`]
        page.default.layout = page.default.layout || DefaultLayout
        return page
    },
```
Then the page entries are missing from manifest.json

**Comment by stuartcusackie** [comment]
Figured it out. The below method works for me. Add to BOTH app.js and ssr.js:

```
resolve: (name) => {
  const page = resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'));

  page.then((module) => {
    module.default.layout = module.default.layout || DefaultLayout;
  });

  return page
},
```

**Comment by Ifriqiya** [comment]
Hi, how did you come about '(module)'? I currently have to import my layout in each component and I would prefer to do this globally.

How can I do so? This is my app.js:

````js
import './bootstrap'
import '../css/app.css'

import { createApp, h } from 'vue'
import { createInertiaApp, Link, Head  } from '@inertiajs/vue3'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers'

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'Laravel'

createInertiaApp({
    progress: {
        color: '#3869d4',  
        showSpinner: true
    },
    title: (title) => `${appName} - ${title}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),

    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .mixin({ methods: { route } })
            .component('Link', Link)
            .component('Head', Head)
            .mount(el)
    },
})

````

**Comment by stuartcusackie** [comment]
You should be able to simply replace:
```
resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
```

With:
```
import DefaultLayout from '@/Layouts/Default.vue'
...
resolve: (name) => {
  const page = resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'));

  page.then((module) => {
    module.default.layout = module.default.layout || DefaultLayout;
  });

  return page
},
...
```

And if using SSR then do it in both app.js and ssr.js

**Comment by Ifriqiya** [comment]
I already did that and it works. I was just trying to understand how...

**Comment by stuartcusackie** [comment]
oh! Well I don't think I can explain very well, but I think it's just a callback function. They work the same in any programming language.

```
// It could be this
page.then((module) => {
    module.default.layout = module.default.layout || DefaultLayout;
});

// Or it could be this
page.then((sillyname) => {
    sillyname.default.layout = sillyname.default.layout || DefaultLayout;
});
```

You can name callback parameters whatever you want. They are provided to the function anyway. It is up to you to name them. It could be 'module' or it could be 'whatever'

**Comment by Ifriqiya** [comment]
Thanks for your explanation. Got this explanation on chatGPT: 'When you use module.default.layout, you are accessing the default export of the imported module and then the layout property on it.'
