### ISSUE TITLE
global router.on('finish') event no longer has session data

### ISSUE THREAD

**Issue by mattyybee** [inertiajs/inertia#1407]
### Version:

- `@inertiajs/vue3` version: 1.0.0

### Describe the problem:
I have been using a router.post and requesting only certain data.  Previously, before updating to v1.0.0, I was able to get the page data on the global 'finish' event to flash any flashed data to the page, namely for toast. 

The global even now results in a null value but the onSuccess callback has access to the data; as per the data in the network tab. 

### Steps to reproduce:

- data post to a controller
- flash some data to the session. 
- listen to the global finish/success router event

**Comment by mattyybee** [comment]
In addition, from the controller I

`return redirect()->back()`

**Comment by aurelkoci** [comment]
**I have the same problem.**

From my controller I return

` return redirect()->back()->with('success' , 'success.');`

**Comment by aurelkoci** [comment]
**For me the problem was solved**

I redirected to another page, everything works.

` return redirect('/')->with('success', 'success'); `
