### ISSUE TITLE
SSR Fails to create chunks for component then i get the `Unable to locate file in Vite manifest`

### ISSUE THREAD

**Issue by sibalonat** [inertiajs/inertia#1411]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:
I upgraded to Inertia V1. It's much faster and for most things, it works splendidly. But there is an issue with the SSR, or probably I'm too unaware of what may cause this.
After changing all the necessary names in the convention and upgrading, I run npm run dev. Works very well, I may say is even faster than before. But the issue is when I run the npm run build "build": "vite build && vite build --ssr".
Here it fails to create the chunks for the components. 
it stops at ssr.mjs. 
The vite.config has 
    build: {
        chunkSizeWarningLimit: 1600,
        transpile: ['@heroicons/vue'],
    },
    ssr: {
        noExternal: ["@inertiajs/server"],
    },
and 
        laravel({
            input: 'resources/js/app.js',
            ssr: 'resources/js/ssr.js',
            refresh: true,
        }),

So it apparently its missing something to generate the necessary chunks

**Comment by sibalonat** [comment]
I have to add that for some reason when you remove the { eager: true } in the app.js or ssr.js for resolving the pages, it works. I'm not sure what this eager refers to. I may have to through the source code to understand it better. As of now, it doesn't work. I tried it with a fresh laravel app, still the same

**Comment by jessarcher** [comment]
Which file is it unable to locate in the Vite manifest?

Are there any errors when you run `vite build --ssr` or just when you view it in your browser?

If you're using `{ eager: true }`, then Vite won't do any code-splitting. If your `@vite` directive is trying to load a specific page (like the below example) you will need to modify it to just load the main entrypoint:

```diff
- @vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
+ @vite(['resources/js/app.js'])
```

**Comment by sibalonat** [comment]
Thank you @jessarcher it makes sense now.
