### ISSUE TITLE
Redirect with flashed session data not working

### ISSUE THREAD

**Issue by graeme1995** [inertiajs/inertia#142]
Hi, in my Laravel project I am currently doing 

`return redirect()->route('home')->with(['message' => "Test"]);` 

and this is what I have in my AppServiceProvider
````
        Inertia::share('flash', function () {
            return [
                'message' => Session::get('message'),
            ];
        });

        Inertia::share([
            'success' => function () {
                return Session::get('success')
                    ? Session::get('success')
                    : (object) [];
            },
        ]);

        Inertia::share([
            'errors' => function () {
                return Session::get('errors')
                    ? Session::get('errors')->getBag('default')->getMessages()
                    : (object) [];
            },
        ]);
````

This however is not returning the message from the session into my props when using Vue.js. 

That is just one example, this is also the case with `withSuccess` and `withError` as well.

I am also using Debugbar which also doesn't show the expected session data. 

Below are some of my files to help:

Web.php

````
Auth::routes();


Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('polls', 'PollController');
    Route::post('polls/vote', 'PollController@vote')->name('polls.vote');
});

Route::resource('api/polls', 'API\PollController');
````

Part of `RouteServiceProvider.php`
````
    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }
````

Web Middleware group in kernel.php 

````
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Inertia\Middleware::class,

        ],

        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
````

What is in the session from my HomeController@index after being redirected.

````
  "_token" => "pbZJgfC6XNG2eTqlcGADm68NqhjOHI16rWe4U1bt"
  "_previous" => array:1 [▼
    "url" => "http://127.0.0.1:8000"
  ]
  "_flash" => array:2 [▼
    "old" => []
    "new" => []
  ]
  "url" => []
  "login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d" => 1
]
````

Am i potentially missing anything?

**Comment by rick20** [comment]
@graeme1995 maybe you can check from the network tab in chrome's devtools if the initial request got redirected twice and causing the flash data discarded on your last response?
Also, you dont need to add the inertia middleware manually since it will be pushed automatically.

**Comment by reinink** [comment]
Hmm, I'm not sure this an issue with Inertia.js, as it appears that even Laravel is not flashing the data, based on the empty `_flash` array. If that is empty, then Inertia.js will definitely not have it either. I suspect maybe there is a double redirect happening, that could be preventing this flash data from persisting.

Sorry I cannot be more helpful than that. I'm going to close this issue, but feel free to leave further comments if you still need help. 👍

**Comment by potofcoffee** [comment]
I just had the same problem. Actually, it appears that the ````AppServiceProvider```` is not a good place to call ````Inertia::share()````, because the flash messages are not properly filled at that point. You should move your ````Inertia::share```` configuration to the ````HandleInertiaRequests```` middleware, as per [the official docs here](https://inertiajs.com/shared-data#flash-messages). At least that's what worked for me. Thought I'd document this here for other people looking for a solution.
