### ISSUE TITLE
Disable Props from Being Displayed in "data-page" attribute

### ISSUE THREAD

**Issue by MohammadAbdorrahmani** [inertiajs/inertia#1435]
### Discussed in https://github.com/inertiajs/inertia/discussions/1430

<div type='discussions-op-text'>

<sup>Originally posted by **MohammadAbdorrahmani** February  4, 2023</sup>
Hello, I use React. Is there a way to not show this `data-page` attribute? Thanks

![Spring - Google Chrome 2_4_2023 02_27_13](https://user-images.githubusercontent.com/53135000/216727002-90004ad3-b0b0-41f4-84b1-4bb96a4117ff.png)
</div>

**Comment by SergkeiM** [comment]
Hi @MohammadAbdorrahmani 

You can remove `data-page` inside `setup`

```js
import { createInertiaApp } from '@inertiajs/react'
import { createRoot } from 'react-dom/client'

createInertiaApp({
  resolve: name => {
    const pages = import.meta.glob('./Pages/**/*.jsx', { eager: true })
    return pages[`./Pages/${name}.jsx`]
  },
  setup({ el, App, props }) {
    el.removeAttribute("data-page"); // remove attribute
    createRoot(el).render(<App {...props} />)
  },
})
```

**Comment by MohammadAbdorrahmani** [comment]
that's work thanks

**Comment by iambherulal** [comment]
> Hi @MohammadAbdorrahmani
> 
> You can remove `data-page` inside `setup`
> 
> ```js
> import { createInertiaApp } from '@inertiajs/react'
> import { createRoot } from 'react-dom/client'
> 
> createInertiaApp({
>   resolve: name => {
>     const pages = import.meta.glob('./Pages/**/*.jsx', { eager: true })
>     return pages[`./Pages/${name}.jsx`]
>   },
>   setup({ el, App, props }) {
>     el.removeAttribute("data-page"); // remove attribute
>     createRoot(el).render(<App {...props} />)
>   },
> })
> ```

This is only removed from the front end(Inspect-element) not from the page-source.

**Comment by iambherulal** [comment]
There is another solution. return an empty error 

app/Http/Middleware/HandleInertiaRequests.php

```
    public function share(Request $request): array
    {
        return array_merge(parent::share($request), [
            'auth' => [
                'user' => $request->user(),
            ],
            'ziggy' => function () use ($request) {
                return [ ];
            },
        ]);
    }
```
