### ISSUE TITLE
State object size limitation in Firefox

### ISSUE THREAD

**Issue by Juhlinus** [inertiajs/inertia#144]
See https://github.com/inertiajs/inertia-vue/issues/106#issuecomment-579830089

> The state object can be anything that can be serialized. Because Firefox saves state objects to the user's disk so they can be restored after the user restarts the browser, we impose a size limit of 640k characters on the serialized representation of a state object. If you pass a state object whose serialized representation is larger than this to pushState(), the method will throw an exception. **If you need more space than this, you're encouraged to use sessionStorage and/or localStorage**.

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

It seems that Firefox imposes a character limit of the serialization of the state object. 640K characters is quite a lot, but it seems a couple developers have hit this ceiling.

I'm not really a fan of adding some warning to the docs or the like explaining the above situation, since it doesn't really fix the problem. People will still make issues, and post on forums when this happens to them. It will create clutter in the community.

Is there any downside to using `localStorage` and/or `sessionStorage` instead? A couple of quick google searches hasn't yielded any result that argues against using them.

Another possible "fix" to this would be this PR: https://github.com/inertiajs/inertia/pull/110#issue-369034891 by @sabatinomasala. It would more sidestep than actually solve the problem though.

**Comment by reinink** [comment]
So, I think the solution here is to simply ensure that server responses don't exceed 640k, which is honestly a HUGE amount of data. If you're sending this much data, you might want to reconsider how you're architecting your app.

That said, I've added a [warning about this](https://inertiajs.com/responses#maximum-response-size) in the documentation:

> To enable client-side history navigation, all Inertia server responses are stored in the browser's history state. It's good to be aware that some browsers impose a size limit on how much data can be saved there. For example, Firefox has a size limit of 640k characters. This is generally much more than you'll ever need, but it's good to be aware of this when building an Inertia application.
