### ISSUE TITLE
RefImpl is not a constructor after upgrading to inertia 1.0

### ISSUE THREAD

**Issue by kayintveen** [inertiajs/inertia#1455]
### Version:

- `@inertiajs/vue3` version: 1.0.1

### Describe the problem:

During development i receive a lot of issues with the following error message:

```
Uncaught TypeError: RefImpl is not a constructor
    at createRef (reactivity.esm-bundler.js:1025:12)
    at ref (reactivity.esm-bundler.js:1016:12)
    at app.ts:17:19
```

This seems to be related or triggered on 
`/node_modules/@inertiajs/vue3/src/app.ts`
on this line:
```
const component = ref(null)
```

On builds, it does not seem to be an issue.

**Comment by kayintveen** [comment]
Seems that in main.ts or app.ts i have to Import 
```
import { createApp, defineProps, h } from 'vue';
```

before all the rest. now it seems to work fine.

**Comment by jeffreyvanhees** [comment]
> Seems that in main.ts or app.ts i have to Import
> 
> ```
> import { createApp, defineProps, h } from 'vue';
> ```
> 
> before all the rest. now it seems to work fine.

Fixed it for me too! Thank! Took me hours :/
