### ISSUE TITLE
laravel put or patch request are not accepting file

### ISSUE THREAD

**Issue by Arafat1243** [inertiajs/inertia#146]
I can't send a file using inertia put or patch requests.
FormData is not working in a patch or put requests. Laravel can not accept the file.

**Comment by Juhlinus** [comment]
Hi @Arafat1243 !

This is a bug in PHP, you need to use POST instead of PUT or PATCH.

**Comment by Arafat1243** [comment]
Hello @Juhlinus !
The update method that is in the Laravel Resource Controller does not accept post.

**Comment by Arafat1243** [comment]
Thank you for your support.
