### ISSUE TITLE
How to add custom headers?

### ISSUE THREAD

**Issue by kirrg001** [inertiajs/inertia#147]
Hi!

I've already searched through issues and code base, but I cannot find a way **to pass custom headers globally** or per `Inertia.visit` call. I am using Inertia in React.

Thanks!
Kate

**Comment by rojoca** [comment]
Since inertia uses axios under the hood you can set global default headers for your requests:

https://github.com/axios/axios#config-defaults

For finer-grained control you could use interceptors to add headers to requests before they are sent:

https://github.com/axios/axios#interceptors

**Comment by kirrg001** [comment]
Okay thanks :) Are you sure this is working? Do you have an example? Because I have to install axios separately. I am then operating on a different instance.

**Comment by rodrigopedra** [comment]
I use both default headers and interceptors and it works. JavaScript modules work as singletons, importing them return the same export always. 

So unless you manually instantiate with axios.create(), any global headers or interceptors will apply to the same axios instance inertia uses.

Here is an excerpt from a project I am working on:

~~~js
import axios from 'axios';
import {publish} from '@/js/libs/bus.js';

axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

axios.interceptors.request.use(
    function (config) {
        publish('request:started', config);

        return config;
    },

    function (error) {
        publish('request:ended');

        return Promise.reject(error);
    },
);

// response interceptor omitted for brevity
~~~

`bus` is a global event bus I use in this project.

**Comment by NWBY** [comment]
@rodrigopedra Could this issue be closed now?

**Comment by reinink** [comment]
Let's maybe leave it open, because I'm considering removing Axios entirely from Inertia.js, and if we do that, we'd want to provide another way to do this. 👍

**Comment by reinink** [comment]
This is now possible, thanks to the work of @claudiodekker (#202).

**Comment by ctrlaltdylan** [comment]
@reinink I know this is a stale issue but I really hope if there is a migration from `axios` to `fetch` that you'll consider a including this global configuration.

This interceptors functionality really helped me out, because my app has to play nice in an iframed environment with custom auth. Thanks to request interceptors, I was able to easily add custom authentication headers to the `router` actions.

Amazing!

**Comment by awebartisan** [comment]
@ctrlaltdylan I am assuming you made it work with Shopify Apps, can you please share a snippet on how you did it? 
I am battling with where do I put the code to pass the Session Token in Authorization header on all the Inertia requests.
