### ISSUE TITLE
useRemember logs warning in console - Invalid watch source

### ISSUE THREAD

**Issue by gbaggaley** [inertiajs/inertia#1483]
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

Using `useRemember` logs a warning in the console `Invalid watch source:  {search: null}`

This happens on all of the pages I try it on

### Steps to reproduce:

Just adding this to any page will recreate the warning:
```js
const form = useRemember({
    search: null,
});
```

**Comment by devinfd** [comment]
Same issue

**Comment by inkomomutane** [comment]
Same issue here
