### ISSUE TITLE
Return data rather than redirect on certain requests

### ISSUE THREAD

**Issue by ghost** [inertiajs/inertia#149]
We've found ourselves in a weird scenario but one that I imagine others finding themselves in too. Essentially, we've got a page that list our users. With that, we've a 'slideover' feature that allows us to stay on the page while adding new users. 

When using inertia to post the form of the new user, the component doesn't refresh, the main page does with the new data. The problem is, because the ```preserveState``` the Slideover is still open. 

Temporarily to get around this, we've added data to the parent prop and put a watch on when that prop changes. It's not ideal but it works.

Any ideas on how to get around this for the future?

**Comment by claudiodekker** [comment]
Hi,

Yeah, you'd probably want to use a persistent layout for this, as I imagine you're probably already doing.
As for closing the slideover when the page switched, would the [event system](https://inertiajs.com/events#event-callbacks) help you with this?

**Comment by claudiodekker** [comment]
Hi, thank you for your feature request!

Right now, there indeed isn't a super-great solution to this, but we do have an idea on the roadmap now (https://github.com/inertiajs/inertia/issues/249) that will solve this issue altogether.

Thanks again!
