### ISSUE TITLE
multipart/form-data request with useForm() excludes empty arrays 

### ISSUE THREAD

**Issue by Julian-Katz** [inertiajs/inertia#1498]
### Version:

- `@inertiajs/vue3` version: 1.0.2
- and Laravel version: 9.19

### Describe the problem:

If I use the Inertia form helper with `forceFormData: true` or send a file all empty arrays are excluded from the requests payload. 

I think the empty array should be included. 

### Steps to reproduce:

That's the Code to send the request: 
```
<script>
import { useForm } from '@inertiajs/vue3';

export default {
  data() {
    return {
      form: useForm({
        first_name: [],
        last_name: 'Mustermann',
        email: null,
      }),
    };
  },
  methods: {
    submit() {
      this.form.post('/users', { forceFormData: true });
    },
  },
};
</script>
```

That's the payload of the request in Chrome `first_name` is missing:
![image](https://user-images.githubusercontent.com/68509862/227748320-eab81fef-717f-4577-bb3a-5b95ef7122b7.png)

**Comment by reinink** [comment]
Hey! So this isn't really an issue with Inertia.js, but rather just how `formData` works — there is no way to submit an empty array.

Here's a related discussion that might be helpful:

https://github.com/axios/axios/discussions/5577
