### ISSUE TITLE
History back issue

### ISSUE THREAD

**Issue by mauricecalhoun** [inertiajs/inertia#150]
Hello All, Here is my issue. My navigation uses Inertia links and following happens

1. Click on link (this.$inertia.vist)
2. Visit next page (component) and click on link (this.$inertia.post )
3. Visit next another page (same component) and click on link (this.$inertia.post )
4. Visit next another page (same component) and click on link (this.$inertia.post )

When I go back
Visit page same as item 3 above
Go Back
Visit page same as item 2 above but it show the data of item 3

It appears that when I do a post to a different url but the same component, it never remembers the first component information

Please Help
![HistoryIssue](https://user-images.githubusercontent.com/245577/87105295-8b505700-c228-11ea-90ce-e257215331d7.gif)

**Comment by ycs77** [comment]
Preserve state: https://inertiajs.com/links#preserve-state

**Comment by mauricecalhoun** [comment]
I have that on the visit 
`this.$inertia.visit(href, {
          preserveState: true,
      });`

**Comment by ycs77** [comment]
Sorry

**Comment by ycs77** [comment]
You can try to change the tabs to `<inertia-link>`

**Comment by mauricecalhoun** [comment]
> You can try to change the tabs to `<inertia-link>`

The tabs are not navigation items it stays on the same page.

**Comment by mauricecalhoun** [comment]
Can I live demo this with anyone in the community...

**Comment by ycs77** [comment]
Or try using like vuex to store the tabs state. I can't think of other options...

**Comment by ycs77** [comment]
I found it: https://inertiajs.com/local-state-caching

**Comment by mauricecalhoun** [comment]
> I found it: https://inertiajs.com/local-state-caching

The data for those page are props from the server.

**Comment by ycs77** [comment]
Can cache the tabs state

**Comment by ycs77** [comment]
> Can I live demo this with anyone in the community...

You can create a repository that reproduces this issue

**Comment by ycs77** [comment]
I have no other solution......

**Comment by mauricecalhoun** [comment]
I will attempt to produce something similar
