### ISSUE TITLE
Website not open on Egypt

### ISSUE THREAD

**Issue by aemaddin** [inertiajs/inertia#1508]
Dears, sorry, but i don't know where I am supposed to put this issue, so I decided to put it here until you guided me to the right place.

I have been trying to access the website https://inertiajs.com from Egypt with no luck and this since three months ago, and now it's still not working, loading forever until it reaches timeout, also ping returns "Request timeout for icmp_seq 0"

Would you happen to have any idea how I can solve the problem?

**Comment by RobertBoes** [comment]
Not sure what the issue would be, or if it would even be easily solvable, but the website is open source so you can run it locally, see: [inertiajs/inertiajs.com](https://github.com/inertiajs/inertiajs.com)

**Comment by aemaddin** [comment]
Yep, it's a great idea. I cloned the project to the localhost.

Thanks

**Comment by reinink** [comment]
Yeah sorry, the site uses Cloudflare, so maybe it's being blocked somehow by them? Unfortunately not much I can do about this, so I'm going to close this for now, but if we get more reports of this issue I'll take another look.

**Comment by Graphicfort** [comment]
[reinink](https://github.com/reinink)
Yes, it's blocked in Egypt and you need to use VPN to access the website or use [RobertBoes](https://github.com/RobertBoes) suggestion

**Comment by youssefeldakar** [comment]
It is not accessible from Egypt.

**Comment by themustafaomar** [comment]
Hey @reinink the Laravel framework is incredibly wide and rich in Egypt, that said, unfortunately there're a lot of people who want to give Inertia a try but literally they can't access the website, I can assure you that Inertia website isn't accessible for the developers in Egypt for months.

**Comment by jefhar** [comment]
@themustafaomar does it work if someone uses a VPN that avoids the Egyptian government’s website blockade?

I didn’t know the legalities in Egypt around using a VPN, so I’m not suggesting you break the law.

**Comment by themustafaomar** [comment]
@jefhar yes it's working using VPNs and online proxies (that's in case if the VPN or proxy website is not blocked as well :D)

> I didn’t know the legalities in Egypt around using a VPN, so I’m not suggesting you break the law, but that would help to diagnose the issue.

Oh, no please feel free, it's not a government they're bunch of idiots, cdn.jsdeliver.net was blocked for 2 months.

However it's working via: https://plainproxies.com/resources/free-web-proxy we can rely on it for now.

Thanks!

**Comment by m-elewa** [comment]
the website has been down in Egypt for a very long time now
