### ISSUE TITLE
Using inertiajs between Laravel backend and Vue.js frontend on different domain

### ISSUE THREAD

**Issue by gilles6** [inertiajs/inertia#151]
Can I use Inertiajs with Laravel backend and Vue.js frontend that are on different domains ?
If yes, how to connect them together ?
Where can I see an example of such use ?

**Comment by reinink** [comment]
So, this isn't really how Inertia.js was designed to work. Rather, Inertia.js is designed to work more like a typical monolithic application, where all the front-end and back-end code exist on the same domain. It sounds like you might be better off looking at the more typical API app and client-side app combo. 👍
