### ISSUE TITLE
v-for inside <Head> component fails on production build

### ISSUE THREAD

**Issue by craigrileyuk** [inertiajs/inertia#1510]
### Version:

- `@inertiajs/vue3` version: 1.0.2

### Describe the problem:

When passing elements through the default slot of the <Head> component, if using a `v-for`, the looped elements will fail to render in production builds due to the way Inertia detects Fragment nodes.

### Steps to reproduce:

In a new Vue 3 project, add something like the following to either a layout or a page:

```js
<template>
    <Head>
        <meta
            v-for="(tag, index) in metaTags"
            :key="index"
            :head-key="tag.name ?? tag.property"
            v-bind="tag"
        />
        <meta name="static" content="content" />
    </Head>
    <main>
        <slot></slot>
    </main>
</template>

<script setup>
import { Head } from "@inertiajs/vue3";
import { computed } from "vue";

const metaTags = computed(() => [
    {
        name: "description",
        content: "The description meta tag",
    },
    { property: "og:type", content: "website" },
    { property: "og:url", content: "http://inertia-ssr.test/" },
    {
        property: "og:title",
        content: "The og title",
    },
    {
        property: "og:description",
        content: "The og description",
    },
    { name: "twitter:card", content: "The twitter card" },
    { name: "twitter:site", content: "website" },
    {
        name: "twitter:title",
        content: "Twitter title",
    },
    {
        name: "twitter:description",
        content: "Twitter description",
    },
]);
</script>
```

In a development build, everything will render correctly; In a production build, only `<meta name="static" />` will render.

Fixed in PR #1509

**Comment by craigrileyuk** [comment]
Any news on this one?

Been nearly a month and it's a pretty major issue with a pretty easy fix (that I've already submitted a pull request for).

Having to use a fork in the meantime for any sites with SSR and dynamic head components.

**Comment by reinink** [comment]
@craigrileyuk hey yup, we'll try to get to this one soon 👍

**Comment by reinink** [comment]
@craigrileyuk Thanks again for reporting this one! Merged and released: https://github.com/inertiajs/inertia/releases/tag/v1.0.7
