### ISSUE TITLE
Default layout multiple named slots not working

### ISSUE THREAD

**Issue by fidderr** [inertiajs/inertia#1520]
### Version:

"laravel/framework": "v10.7.1",
"laravel/breeze": "v1.20.1",
"vite": "4.2.1",
"laravel-vite-plugin": "0.7.4",
"@vitejs/plugin-vue": "4.1.0",
"vue": "3.2.47"
"@inertiajs/vue3": "1.0.3",

### Describe the problem:

trying to access named slots that are inside of a default layout will cause an error:
`[plugin:vite:vue] Codegen node is missing for element/if/for node. Apply appropriate transforms first.`

when you get rid of the slot refrence the error disapears, but then it is not placed inside of the slot.

### Steps to reproduce:

app.js inside of createInertiaApp: (as the documentation suggests: https://inertiajs.com/pages#default-layouts)
```
    resolve: async (name) => {
      let page = await resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'));
      page.default.layout = page.default.layout || layout
      return page;
    },
```

example layout:
```
<template>
<div><slot name="header"/></div>
<div><slot/></div>
</template>
```

page:
```
<template>
        <template #header>
        header slot
        </template>

        <div>
            default slot
        </div>
</template>

```

**Comment by fidderr** [comment]
i was able to create a crude work-around that works for me but it is not really a valid fix:

app.js inside of createInertiaApp:
```
    resolve: async (name) => {
      let page = await resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'));
      page.default.layout = name.startsWith('Public/') ? undefined : layout;
      return page;
    },
```

example layout:
```
<template>
<div><span data-slot="header" /></div>
<div><slot/></div>
</template>
```


page:
```
<script setup>
import LayoutSlot from '@/Components/LayoutSlot.vue';
</script>

<template>
    <LayoutSlot slot="header">
            header slot
    </LayoutSlot>
    <div>
          main slot
    </div>
</template>
```


component:
```
<script setup>
import { onMounted, ref, toRefs, computed } from 'vue';

const props = defineProps({
    slot: {
        type: String,
        required: true
    }
});

const { slot } = toRefs(props)

const mounted = ref(false);

onMounted(() => mounted.value = true);

const to = computed(() => {
    return `[data-slot="${slot.value}"]`;
});

</script>

<template>
    <Teleport :to='to' v-if="mounted">
        <slot/>
    </Teleport>
</template>
```

**Comment by craigrileyuk** [comment]
Inertia doesn't support named slots in layouts. So this is a feature request, not a bug report.

**Comment by reinink** [comment]
> Inertia doesn't support named slots in layouts. So this is a feature request, not a bug report.

Yup, exactly. This might be something we revisit in the future, but as of right now this isn't supported, sorry!

**Comment by projct1** [comment]
Same actual problem :(
I want something like this as main default layout:
```
<script setup>

</script>

<template>
    <aside>
        <slot name="aside"/>
    </aside>

    <header>
        <slot name="header"/>
    </header>

    <main>
        <slot/>
    </main>

    <footer>
        <slot name="footer"/>
    </footer>
</template>
```

And child layout:
```
<script setup>

</script>

<template>
    <template #header>
        HEADER
    </template>

    MAIN CONTENT
    
    <template #footer>
        FOOTER
    </template>
</template>
```

Inertiajs supports only default slot :/?

**Comment by craigrileyuk** [comment]
Yes. Inertia only supports using the default slot in layouts. 

You can use something like [Portal Vue](https://portal-vue.linusb.org/) if you want to emulate similar functionality.
