### ISSUE TITLE
if using usePage before initialization, page.value lost reactivity

### ISSUE THREAD

**Issue by DJafari** [inertiajs/inertia#1532]
after this PR : https://github.com/inertiajs/inertia/pull/1469 we have a bug in 3rd libraries that used `usePage` hook

@Tofandel explain problem in this comment: https://github.com/inertiajs/inertia/pull/1469#issuecomment-1517475989

i hope solve this bug, as soon as possible, i think set `const page = ref<Page<any>>({})` instead of `const page = ref<Page<any>>(null)` solved this bug

thanks @reinink

**Comment by reinink** [comment]
*(sharing my same response from [#1469](https://github.com/inertiajs/inertia/pull/1469#issuecomment-1526319267))*

Hey I'm still not totally convinced that our current implementation is wrong. The `usePage()` hook now *always* returns a reactive object. Yes, the values within it are nullable, but the returned `page` is always a reactive object and is never `null`.

The `page` object that's referenced in the `usePage` hook is a `ref` — meaning it can have an initial value of `null` and still be reactive — that's how refs work in Vue 3 (as far as I'm aware).

I've tested this new implementation in the Vue 3 adapter with the Momentum Modal library, and it works exactly as expected, so I'm wondering if there is something else going on here with your particular implementation @DJafari. Are you able to please provide a minimal reproduction of this problem as a Git repo for me to test with?

**Comment by DJafari** [comment]
Sorry, it was a bug on my part
thanks

**Comment by reinink** [comment]
@DJafari Glad you got it figured out! 💪
