### ISSUE TITLE
Preserve scroll not working for page visits with Vue 3 composition API

### ISSUE THREAD

**Issue by matthewknill** [inertiajs/inertia#1538]
### Version:

- `@inertiajs/vue3` version: 1.0.6

Whenever I use the `Link` component or the `router.visit` function with the `preserveScroll` attribute set, it doesn't seem to work.

I tried the following in my `Link` component:
```vue
<Link v-else :key="`link-${key}`" class="mb-1 mr-1 px-4 py-3 focus:text-indigo-500 text-sm leading-4 hover:bg-white border rounded" :class="{ 'bg-white': link.active }" :href="link.url" preserve-scroll v-html="link.label" />
```

I have also tried the following, using the router manually (instead of using the link component):
```js
import { router } from '@inertiajs/vue3'
// ...

function changePage(url) {
    router.visit(url, {
        preserveScroll: true
    })
}
```

Oddly, I find that it's only `get` requests that seems to not preserve the scroll, other request types seem to work fine...

**Comment by xtreme2020** [comment]
Hi, for some reason using inertia router from latest version cause a lot problems,
try to do this
//import
import {Inertia} from "@inertiajs/inertia";

**Comment by matthewknill** [comment]
> Hi, for some reason using inertia router from latest version cause a lot problems, i used legacy site version to get everything working because examples for the latest version doesn`t work as expected try to do this //import import {Inertia} from "@inertiajs/inertia"; function changePage(url) { Inertia.visit(url, { preserveScroll: true }); }

Not only do I have to install the old package to do this, it doesn't seem to even fix the issue for me. Each time I do an `Inertia.visit`, it hard loads the page like it would for a non-SPA app. Would really like this issue to be solved...

**Comment by matthewknill** [comment]
This seems to be working as per `v1.0.7`
