### ISSUE TITLE
Unable to get response from controller to view

### ISSUE THREAD

**Issue by KhanAmaan55** [inertiajs/inertia#1540]
### Version:

- `@inertiajs/react : "^1.0.2"`,
- `@inertiajs/inertia-react : "^0.8.1"`,

### Describe the problem:

Developing a Adonis-Inertia-React application
Here I am trying to get data from Adonis controller to react view but not able to get response instead got `undefined`
I am using `Inertia.get` method

### Here is the Code
Adonis Controller
```
export default class PostsController {

    public async view({ response }) {
        return response.json({message: true})
    }
}
```
React Code
```
let data = await Inertia.get("/createUser")
console.log(data);
```
Got the same problem with post method as well where I am able to send data but unable to get the response
Is there any other method to get data from controller to view using Inertia?

**Comment by RobertBoes** [comment]
First of all, you have 2 conflicting packages installed. The pre-1.0 version and the current version. You should remove `@inertiajs/inertia-react` (see the [docs](https://inertiajs.com/client-side-setup) and [upgrade guide](https://inertiajs.com/upgrade-guide)). You'd then make a request like this:
```ts
import { router } from '@inertiajs/react'

router.get('/createUser')
```

Then secondly, Inertia's client-side adapter is not a API client like Axios, but rather a router. Making an Inertia visit would visit the page and swap components etc. It doesn't return the response. It's not a library to make a request to a JSON endpoint. So using `router.get('/url')` would make a call to that endpoint and "navigate" to it. If you just need to call some JSON endpoint you'd have to make your call yourself, like with Axios or fetch.
