### ISSUE TITLE
Triggering router.reload inside useEffect() would not work as expected

### ISSUE THREAD

**Issue by stefano-ciotola** [inertiajs/inertia#1547]
### Version:

- `@inertiajs/react` version: 1.0.6

### Describe the problem:

When calling `router.reload` inside the `useEffect` hook with specific props, it returns a 409 error and doesn't reload the specified props. However, when wrapping `router.reload` in a `setTimeout` of 0ms (as suggested in: https://laracasts.com/discuss/channels/inertia/using-routerreload-with-laravel-inertia-and-react), it works as expected.

### Steps to reproduce:

1. Use the following code inside the `useEffect` hook:
`useEffect(() => {
router.reload({
only: ['lazyContent'],
})
}, [])`

2. Observe that the page keeps refreshing and returns a 409 error each time.

### Additional Information:

- Link to a discussion I found about this issue: https://laracasts.com/discuss/channels/inertia/inertia-lazy-first-render-with-react

**Comment by wgerro** [comment]
I have same problem :<

**Comment by reinink** [comment]
Hey looks like you got this figured out in the link you shared to Laracasts 👍

**Comment by aganov** [comment]
Using `useTimeout` in `useEffect` seems to fix the issue of the missing `X-Inertia-Partial-Component` as well (https://github.com/inertiajs/inertia/issues/1363), but it does not seem right to me either.
