### ISSUE TITLE
Relationship between Inertia and SPA

### ISSUE THREAD

**Issue by todaycodemaster** [inertiajs/inertia#1557]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Steps to reproduce:

I create simple Laravel and Vue 3 project and inertia router was used.

Vue and React's principle is SPA.

But when I used Inertia, the whole page have been reloaded every time

Isn't it possible SPA (only single page changing) with inertia.

Please give me answer.

Thanks

**Comment by aadrian** [comment]
@todaycodemaster 

> But when I used Inertia, the whole page have been reloaded every time
> Isn't it possible SPA

That's the main point of Inertia in first place: to allow exactly that :).


If coded right, it doesn't reload the entire page every time. Take a look a at the demo http://demo.inertiajs.com/
or at the sources https://github.com/inertiajs/pingcrm  (exactly a Laravel + Vue3 project with Inertia).

**Comment by todaycodemaster** [comment]
I checked the project you provided me and compared with mine

https://github.com/todaycodemaster/simpleLV

As I think there is no differences but I'm feeling a whole page reloading now.

If you have time, please check my code and let me know what is problem.

**Comment by RobertBoes** [comment]
@todaycodemaster You're mixing 2 Inertia versions of the Vue adapter, this would cause mismatches. Make sure to only use a single version. This would be `@inertiajs/vue3`, and remove `@inertiajs/inertia-vue3` from your packages

**Comment by todaycodemaster** [comment]
I removed @inertiajs/inertia-vue3 but the Link is not working.

And I checked sample code and it is using the inertia-vue3 too.

Is there something wrong in my code?

I attached my code part. please check and let me know.

I'm very interested in this inertia and attractive it.
![Annotation 2023-05-18 151122](https://github.com/inertiajs/inertia/assets/80197242/01d44ff6-440f-4ed1-ab08-36452932ed59)

**Comment by RobertBoes** [comment]
So, that's just Vue 3, if you use `<script>` that's the Options API and you'd need to add the component to the `components` export, see https://vuejs.org/guide/components/registration.html#local-registration

```js
export default {
  components: {
    Link,
  },
}
```

**Comment by todaycodemaster** [comment]
not working yet.

**Comment by todaycodemaster** [comment]
Thanks for your advice. I solved the problem.

The problem was Link component was under layout. So it was not working.

thanks agian

**Comment by todaycodemaster** [comment]
I have one more question.
a tag router reload a whole page? only SPA will be integrated only via Link component ?
