### ISSUE TITLE
Vue 3.3.0+

### ISSUE THREAD

**Issue by pouzarm** [inertiajs/inertia#1558]
### Version:

- `@inertiajs/vue3` version: 1.0.6
- `vue` 3.3.0 and newer

We also use Typescript, but only update of Vue creates this problem, so i asume, that it is problem of Vue/Inertia combination.

### Describe the problem:

Throws error that stop whole application in inertia Head component.

![image](https://github.com/inertiajs/inertia/assets/68845670/18da241e-d2c9-4750-ba5c-4320b13ec2ca)

![image](https://github.com/inertiajs/inertia/assets/68845670/0955bf29-b64a-4ff9-bf41-1fe5f09139ad)

### Steps to reproduce:

Just update Vue to that version.

**Comment by tchartron** [comment]
I think this is the same as : https://github.com/inertiajs/inertia/issues/1552
