### ISSUE TITLE
[inertia-vue] How to pass custom headers

### ISSUE THREAD

**Issue by kapsonic** [inertiajs/inertia#157]
Hi,

I see that $inertia uses axios internally and I have set global config for axios to pass in my auth header in every request.
Requests that are being made by axios respect that but those made by $inertia dont.
Can you please tell me if there a way around this?

I want to pass in my custom header in every request.

**Comment by reinink** [comment]
This is now possible, thanks to the work of @claudiodekker (#202).

**Comment by StefanNeuser** [comment]
Hi @reinink , we are using inertia-js in our shopify apps. We need to send X-Shop-* header to our backend to make it possible that a single user (Browser) can work on different shops within the iframe where the same app ist loaded.

**Comment by craigrileyuk** [comment]
For anyone searching for this in inertia v1+

```js
router.on("before", (ev) => {
	ev.detail.visit.headers["X-Socket-ID"] = echo.socketId();
});
```

Put that in a main layout and the custom header will be attached to every request that Inertia makes. Obviously swap out the socket variables for whatever header/value you need to set.
