### ISSUE TITLE
router.visit spamming requests

### ISSUE THREAD

**Issue by midiidev** [inertiajs/inertia#1580]
### Version:

- `@inertiajs/vue3` version: 1.0.7

### Describe the problem:

I have a search bar in my Layout, and a watcher that calls the `search()` function whenever its updated, however, the router will spam requests, even when it hasn't been updated, which i confirmed by temporarily adding a `console.log` to my watcher.

here's my script
```vue
<script setup>
import { ref, useAttrs, watch } from 'vue'
import { Link, router, usePage } from '@inertiajs/vue3'
import { config } from '../config.js'

const attrs = useAttrs()

const showSearch = ref(false)

const page = usePage()

const query = ref('')

const reload = () => {
    const url = new URL(window.location.href)
    url.searchParams.delete('page')
    router.visit(`${url.pathname}${url.search}`, {
        preserveScroll: true,
        preserveState: false
    })
}

const search = () => {
    if (page.url.startsWith('/s/')) {
        router.visit(`/s/${attrs.subforum}?search=${query.value}`)
    } else {
        router.visit(`/?search=${query.value}`)
    }
}

watch(page.url, () => {
    if (page.url.endsWith('search=') && page.url.startsWith('/?') || page.url.startsWith('/s/')) {
        if (page.url.startsWith('/s/')) {
            router.visit(`/s/${attrs.subforum}`)
        } else {
            router.visit(`/`)
        }
    }
})

watch(query, () => {
    search()
})
</script>
```

as well as a piece from my template
```vue
<template>
    <input type="text" placeholder="Search" v-model="query" />
    <slot />
</template>
```

When I call the refresh function (I have a button to do that in my template), it doesn't spam the request, but my search does.

### Steps to reproduce:

1. Use inertia.js with vue3
2. copy my script and template
3. check the network tab of devtools and see that it's sending the same request repeatedly

Here's a screenshot of my problem
![2023-06-03_22-48](https://github.com/inertiajs/inertia/assets/101067949/f44378d5-8135-48eb-a702-8f1a1bbf71e8)

**Comment by sdon2** [comment]
You have `page.url` watcher that repeatedly triggers xhr requests.

**Comment by reinink** [comment]
Hey! I'm sure you've come up with a solution by now, but in general I don't think watching the `page.url` sounds risky.

Personally I've done similar things in the past, but I use a watcher on the search value. There is an example of this in PingCRM, which you can see here:

https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Index.vue#L94-L101

Hope that helps 👍
