### ISSUE TITLE
[inertia-vue] Listening to & intercepting visit (navigation) events

### ISSUE THREAD

**Issue by baaskoen** [inertiajs/inertia#159]
If you were to implement a feature like warning a user before exiting a page, how would you go about and implement this in Inertia?

If the user navigates back or clicks on a `<inertia-link />`, the "onbeforeunload" event is not actually called. When a user navigates back in history, the "popstate" event seems to be called indefinitely.

Are there any events that I can subscribe my listeners to?

**Comment by reinink** [comment]
The new event system (#208) has been merged in, which allows you to listen for visit events and cancel them. I hope to tag a release tomorrow, and I also plan to add documentation to the website explaining how to use it. 🙌
