### ISSUE TITLE
Inertia <Head> issue: TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by y1ann1s85** [inertiajs/inertia#1592]
### Version:

- `@inertiajs/vue3` version: 1.0.8

### Description of problem:

Hello, we are currently working in a vue2 to vue3 migration. Since we upgraded to vue.js ^3.3.4 we face a certain problem regarding the Head component. We receive the following error:

![Screenshot from 2023-06-15 13-20-04](https://github.com/inertiajs/inertia/assets/45979358/a10ec965-cad3-4b8b-a60d-241ab761ae47)

It seems that the problem appears when we try to render a script tag in the Head Component.
For example:

`<component :is="'script'" type="application/ld+json">
      {{ microData }}
  </component>`

**Comment by ilaoniu** [comment]
#1590 may fix the problem.

**Comment by reinink** [comment]
Just tested this out, and #1590 fixes this 👍

**Comment by reinink** [comment]
Fix released: https://github.com/inertiajs/inertia/releases/tag/v1.0.9
