### ISSUE TITLE
[inertia-vue] Incorrect typings

### ISSUE THREAD

**Issue by innocenzi** [inertiajs/inertia#160]
I'm using `@inertiajs/inertia 0.1.4` and `@inertiajs/inertia-vue 0.1.2`. 
I'm refactoring my app using TypeScript, but I got this error as soon as I enabled TypeScript linting in my main file: 

![](https://i.imgur.com/vCPIN1p.png)

<details>
  <summary>Error message</summary>

```
No overload matches this call.
  Overload 1 of 2, '(plugin: PluginObject<unknown> | PluginFunction<unknown>, options?: unknown): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, never, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<unknown> | PluginFunction<unknown>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<unknown> | PluginFunction<unknown>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<unknown>'.
  Overload 2 of 2, '(plugin: PluginObject<any> | PluginFunction<any>, ...options: any[]): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, never, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<any> | PluginFunction<any>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<any>'.
```
</details>

I believe the typings may be incorrect?

**Comment by reinink** [comment]
If someone wants to PR this update to `/packages/inertia-vue/index.d.ts`, great, otherwise this will get fixed when the library is updated to TypeScript (on the roadmap).

I don't personally use TypeScript, so I don't feel this pain. Instead of keeping issues open for all these TypeScript definition issues, I'd recommend just creating a PR to fix it. 👍

**Comment by innocenzi** [comment]
I'll wait 'till the TypeScript rewrite personally. 👍
