### ISSUE TITLE
Rename global inertia variable to router

### ISSUE THREAD

**Issue by swarakaka** [inertiajs/inertia#1606]
https://github.com/inertiajs/inertia/blob/2adfa2cdb08432283f68ce0b4f5009bf29d47376/packages/vue3/src/app.ts#L121
Since version one, inertia has changed to router. I think this variable should be changed as well.

**Comment by reinink** [comment]
Hey! So we're actually quietly deprecating the global `$inertia` property in favor of importing it:

```js
import { router } from '@inertiajs/vue3'
```

While the global `$inertia` property isn't going anywhere (largely for backwards compatibility), moving forward we recommend using the import instead. This is why we haven't added a global `$router` property.

Hope that helps 🤙
