### ISSUE TITLE
defineOptions macro not available

### ISSUE THREAD

**Issue by DominusKelvin** [inertiajs/inertia#1613]
### 1.0.9:

- `@inertiajs/vue3` version:1.0.9

### Describe the problem:

It seems the Vue 3 adapter is not using the latest version of Vue which means macros like `defineOptions()` is not available.

**Comment by craigrileyuk** [comment]
It uses a peerDependency of:
```
  "peerDependencies": {
    "vue": "^3.0.0"
  },
  ```
  so it's no business of Inertia's what version of Vue is being used as long as there a version above 3 present in your project.
  
  If you're having issues with getting a specific version, try installing it manually as a direct dependency with `npm i vue@latest`.

**Comment by DominusKelvin** [comment]
That's quite interesting 🤔 

But doesn't installing Vue as a dependency in userland to get latest features in Vue sort of defeat the purpose of a Inertia letting you instal @inertiajs/vue3 to have access to Vue?

I'm trying to understand this by the way.

**Comment by DominusKelvin** [comment]
I had Vue as a `devDependency` which pegged an older patch of Vue 3 🤦🏾‍♂️. Closing this now as resolved.
