### ISSUE TITLE
[inertia-vue] NS_ERROR_ILLEGAL_VALUE in Firefox

### ISSUE THREAD

**Issue by paulotra** [inertiajs/inertia#162]
works fine on chrome, but in firefox it fires `NS_ERROR_ILLEGAL_VALUE` maybe some errors in window.history.replaceState and window.history.pushState

**Comment by reinink** [comment]
So, I think the solution here is to simply ensure that server responses don't exceed 640k, which is honestly a HUGE amount of data. If you're sending this much data, you might want to reconsider how you're architecting your app.

That said, I've added a [warning about this](https://inertiajs.com/responses#maximum-response-size) in the documentation:

> To enable client-side history navigation, all Inertia server responses are stored in the browser's history state. It's good to be aware that some browsers impose a size limit on how much data can be saved there. For example, Firefox has a size limit of 640k characters. This is generally much more than you'll ever need, but it's good to be aware of this when building an Inertia application.
