### ISSUE TITLE
Disabled prop of Link component doesn't work

### ISSUE THREAD

**Issue by Ferks-FK** [inertiajs/inertia#1620]
### Version:

- `@inertiajs/react` version: `^1.0.9`

### Describe the problem:
When trying to provide the `disabled` attribute for the Link component of inertia, it is completely ignored.
I believe the link should not work if `disabled` is `true`.

### Steps to reproduce:
Just import the `Link` from `'@inertiajs/react'`, and try setting a `disabled` prop.
See the link still working normally when it should be blocked.

**Comment by reinink** [comment]
Hey! So under the hood Inertia just uses regular `<a>` tags for links, which don't support `disabled`. You can make the Inertia `<Link>` a button using the `as` prop, in which case you can use `disabled`, since that's supported by the native `<button>` element:

```jsx
<Link as="button" href="/somewhere">My Link</Link>
```

Hope that helps!

**Comment by gareginra** [comment]
Idk about React, but this works in Vue, it's called "renderless component":
`        <component :is="editMode ? 'div' : Link" :href="sectionLink">`

**Comment by Zai185** [comment]
@gareginra Cool Trick bro, Thanks for help.
