### ISSUE TITLE
`interface` typed variable not working with `router.post()` or other method

### ISSUE THREAD

**Issue by xsjcTony** [inertiajs/inertia#1623]
### Version:

- `@inertiajs/react` version: `v1.0.9`

### Describe the problem:

variable typed by `interface` raises error when send with `router` method:

This is a little bit annoying because my rule is use `interface` as much as possible, but the API is stopping me from doing so. I don't see there's any difference between `interface` and `type` in this case.

Just to mention, `interface` is not working for generic type of `useForm()` either, a bit annoying too. https://github.com/inertiajs/inertia/issues/1624

### Steps to reproduce:

https://stackblitz.com/edit/vitejs-vite-uwysop?file=src%2FApp.tsx

**Comment by derrickreimer** [comment]
As a workaround, you can have your interface extend `Record<string, FormDataConvertible>`:

```typescript
import { router } from '@inertiajs/react';
import { FormDataConvertible } from '@inertiajs/core';

function App() {
  type TestType = { name: string };
  interface TestInterface extends Record<string, FormDataConvertible> {
    name: string;
  }

  const typeData: TestType = { name: 'test' };
  const interfaceData: TestInterface = { name: 'test' };

  router.post('/test', typeData);
  router.post('/test', interfaceData);

  return null;
}

export default App;
```
