### ISSUE TITLE
Set link preserveState default based on method

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#164]
By default the post/put/patch methods preserve state by default ([see here](https://github.com/inertiajs/inertia/blob/master/src/inertia.js#L156-L174)). However, an Inertia link that uses post/put/patch will not do this by default, since the attribute default is false ([see here](https://github.com/inertiajs/inertia-vue/blob/master/src/link.js#L28)).

It makes me think that we should maybe check the link method, and if it's a post/put/patch request, automatically set it preserve state, like Inertia core does.

**Comment by claudiodekker** [comment]
@reinink I think this is partially fixed as per https://github.com/inertiajs/inertia/releases/tag/v0.4.1, but I'll still tag it as `todo` for now
