### ISSUE TITLE
SSR - Head title repeating twice.

### ISSUE THREAD

**Issue by rinoj** [inertiajs/inertia#1641]
### Version:

- `@inertiajs/vue3` version: 1.0.9

### Describe the problem:

When I am using the Head component for meta, without SSR everything is working fine. When using the SSR, the title is being rendered twice.

```
<Head>
    <title>Testttt</title>
</Head>
```

In the browser tab, the title is being rendered twice: `Testttt - Testttt`

Any clue about this?
### Steps to reproduce:

```createServer((page) =>
    createInertiaApp({
        page,
        render: renderToString,
        title: (title) => { 
          console.log('title:', title);
          return `${title}` },
        resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
        setup({ App, props, plugin }) {
            const VueApp = createSSRApp({ render: () => h(App, props) })
            VueApp.config.globalProperties.emitter = mitt();
            VueApp.use(plugin)
            VueApp.use(ZiggyVue, {
                ...page.props.ziggy,
                location: new URL(page.props.ziggy.location),
            })
            VueApp.use(i18n);
            return VueApp;
        },
    })
);
```

**Comment by reinink** [comment]
Hey! Can you provide a minimal reproduction of this issue as a Git repo that I can use to reproduce this issue myself? Using the snippet you provided I am unable to reproduce this issue.

I suspect that you probably have a different `title` callback in your `ssr.js` file. This callback must be the same (or absent) in both `app.js` and `ssr.js`.

**Comment by rinoj** [comment]
> 

Hey, thanks for the suggestion, it seems like my `app.js` title callback was different from the one in `ssr.js`. That fixed the issue. Thank you !
