### ISSUE TITLE
[inertia-vue] [Suggestion] Inertiajs pwa and hybrid mobile

### ISSUE THREAD

**Issue by ShirazCoders** [inertiajs/inertia#165]
Hello,
I found interiajs is powerfull and can help developer to build spa as easy as hot cake.
There is some features that we need to become best.
1. PWA: By supporting pwa developer can fouce on one  code base.
2. Out put for cordova or hybrid: if we build dist folder or public folder that contain html file for cordova app we can build it and make mobile app which is very exciting.

In this way one code base can be used for all platform.

**Comment by reinink** [comment]
Neat thoughts, and things we'll keep in mind for the long-term roadmap. Thanks for sharing! 👍

**Comment by Atiladanvi** [comment]
So good ! Well, I think I'll risk write a adapter for the quasar-ui before major releases.

**Comment by thewisejun** [comment]
Is there still a chance there's any updates?
