### ISSUE TITLE
Head title doesn’t get server side rendered

### ISSUE THREAD

**Issue by Meraik** [inertiajs/inertia#1660]
I have a fresh laravel installation with Inertiajs ssr option selected. The page gets server side rendered but not the Head title. It first loads the default title that is set in the ssr.tsx file and once the page loads it changes to the title set in Welcome.tsx

When disabling javascript on the browser, the page loads fine as expected but the head title that is set in Welcome.tsx  does not.

Github repo: https://github.com/Meraik/inertia-head-ssr

**Comment by reinink** [comment]
So when you're running Inertia in SSR, you shouldn't provide a default `<title>`, as that will lead to two titles being included in the SSR generated HTML.

The fix here is to update your `app.blade.php` file to not have this line:

```diff
  <!DOCTYPE html>
  <html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
      <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
  
-         <title inertia>{{ config('app.name', 'Laravel') }}</title>
  
          <!-- Fonts -->
```

Removing that will fix this issue 👍

We should probably update the Laravel Breeze installer to omit this `<title>` when selecting the SSR option.

Hope that helps!
