### ISSUE TITLE
same laravel collections get labeled differently on vue props.

### ISSUE THREAD

**Issue by Toylycker** [inertiajs/inertia#1666]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

If in laravel controller we differentiate same models like this and send it to vue page as props

$categories = Category::where('category_id', null)->with('children')->get();
$product_categories = $categories->where('type', 'product');
$ad_categories = $categories->where('type', 'ad');

then vue says that 
1) 'categories' is array and objects inside it are reactive
2)But 'product_categories' and 'ad_categories' are reactive and objects inside it are just an Object and not reactive.

due to that, naive ui's select component fires event when i give them 'product_categories' or 'ad_categories':
<n-select :options="(chosen_type == 'product' ? product_categories : ad_categories)" />
error
type check failed for prop "options". Expected Array, got Object.

But if i pass categories there, then it works fine.

### Steps to reproduce:
 laravel, Inertia, Vue.

**Comment by jefhar** [comment]
`$product_categories` and `$ad_categories` are a Builder class while `$categories` is a Collection of models.  You probably want to send the results of the query to your view file, not the Builder class.  Append the `->get()` method to your Builders. 

```PHP
$product_categories = $categories->where('type', 'product')->get();
$ad_categories = $categories->where('type', 'ad')->get();
```

**Comment by RobertBoes** [comment]
You're filtering collections, which keeps the current index. When transforming that to JSON it would become an object (because the indices are like 1,4,6,7,10 etc, not zero indexed). You can solve this by using `->values()` on the collection, this will reindex the collection and that would result in an array when transformed to JSON. Not really a thing Inertia should do anything about imho, it's just how PHP arrays work (they're kind of objects)

**Comment by Toylycker** [comment]
It really worked out, i have never had any idea about that way of array behavior. Respect!!!

**Comment by Toylycker** [comment]
> `$product_categories` and `$ad_categories` are a Builder class while `$categories` is a Collection of models. You probably want to send the results of the query to your view file, not the Builder class. Append the `->get()` method to your Builders.
> 
> ```
> $product_categories = $categories->where('type', 'product')->get();
> $ad_categories = $categories->where('type', 'ad')->get();
> ```

they are already collections, calling get on them would fire error or wrap it with another array)
