### ISSUE TITLE
How do I make a custom component act as an inertia link?

### ISSUE THREAD

**Issue by jdion84** [inertiajs/inertia#1668]
Using React Bootstrap and it allows you to specify hrefs in the components e.g.:

```jsx
<Navbar.Brand href="/">
    {app.name}
</Navbar.Brand>
```

How would I make this `Navbar.Brand` component act like an inertia `Link`?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
