### ISSUE TITLE
Is there a way to pass route state when navigating?

### ISSUE THREAD

**Issue by xsjcTony** [inertiajs/inertia#1674]
### Version:

- `@inertiajs/react` version: latest

### Describe the problem:

Is that possible to push route state along with the navigation, either in `<Link />` or `router.get()`?

It should work just like in `React Router`:
`state` prop in https://reactrouter.com/en/main/components/link#link
`state` option in https://reactrouter.com/en/main/hooks/use-navigate#usenavigate
And get via `useLocation().state` https://reactrouter.com/en/main/hooks/use-location#uselocation

Is there such functionality in Inertia or how can I mimic it?

**Comment by craigrileyuk** [comment]
That's not how Inertia works. It's not a traditional SPA and so state is controlled by the Laravel controllers.

You can set query params or path params to your route as part of the navigation, or you can implement a Pinia store and store local state like that.
