### ISSUE TITLE
form obj reactivity lost

### ISSUE THREAD

**Issue by dublue** [inertiajs/inertia#1680]
### Version:

- `@inertiajs/vue3` version: 1.0.11

### Describe the problem:

I create a form object:
const form = useForm({
  name: '',
  address: ''
});

then I found I cannot see 'form' in chrome vue devtools

then I check with isRef(form) it returns false

**Comment by jessarcher** [comment]
Hi @dublue,

I've tried this in the Vue 3 playground in this repo, and I can see the `form` object in dev tools.

`isRef` is expected to return false - you'd need to use `isReactive` on the form object.

Are you able to replicate the issue in the Vue 3 playground this repo, or alternatively provide a minimal reproduction repo?

**Comment by dublue** [comment]
fixed
