### ISSUE TITLE
Snyk scan issues

### ISSUE THREAD

**Issue by Raman117** [inertiajs/inertia#1684]
### Version:

"@inertiajs/inertia": "0.11.1",

  this version is using qs 6.9.0
  [ dependencies:
    axios "^0.21.1"
    deepmerge "^4.0.0"
    qs "^6.9.0"
  ]
    which has high security problems reported by Snyk scan
    
![image](https://github.com/inertiajs/inertia/assets/105584135/917e0ea6-f13e-4c85-bcc5-365aaff6290e)

**Comment by craigrileyuk** [comment]
The current version of the @inertiajs/inertia package is 1.0.11, not 0.11.1.

It uses qs 6.11.2.

**Comment by Raman117** [comment]
> The current version of the @inertiajs/inertia package is 1.0.11, not 0.11.1.
> 
> It uses qs 6.11.2.

![image](https://github.com/inertiajs/inertia/assets/105584135/7850a248-c626-4440-ad64-7f42502ee377)

and

![image](https://github.com/inertiajs/inertia/assets/105584135/1a7be451-007d-44f3-b1ed-f9aac2ea43f6)

this max option in yarn is 0.11.1

**Comment by Raman117** [comment]
@RobertBoes @craigrileyuk 
updated to latest  version
but still qs is 6.9.0
this has high security issue

![image](https://github.com/inertiajs/inertia/assets/105584135/67791c31-c7a9-4538-b94a-68d116e371c0)

**Comment by RobertBoes** [comment]
Then you probably have a different dependency that's preventing an upgrade, don't think Inertia is the culprit here. As you can see the requirement is `^6.9.0`, which allows the installation of any 6.x version, looking on NPM the latest version is `6.11.2`. Running `npm info qs` shows me `qs@6.11.2`, also in the lock file it's listed as version `6.11.2`.

**Comment by reinink** [comment]
Hey! From what it sounds like you're seeing this warning for an older version of Inertia.js which is no longer supported. As @RobertBoes suggested you need to update your dependencies 👍
