### ISSUE TITLE
[inertia-vue] How to configure Google Analytics in Laravel Vue Inertia SPA?

### ISSUE THREAD

**Issue by nextifier** [inertiajs/inertia#169]
This is my first time building a Laravel-Vue SPA with Inertia JS.
Because this is a SPA, Google Analytics can't detect any page visits when user navigating the pages.

In Vue Router, the configuration is something like this:

```
import Vue            from 'vue';
import router           from './routes.js'

new Vue({
    router,
}).$mount('#app')


ga('set', 'page', router.currentRoute.path);
ga('send', 'pageview');

router.afterEach(( to, from ) => {
  ga('set', 'page', to.path);
  ga('send', 'pageview');
});
```

How do you do this in Inertia JS?

Note: I'm using Ziggy library to use Laravel routes in my Vue app, so I can use route() helper, but I have no idea how to use it to send the pageview to Google Analytics.

**Comment by reinink** [comment]
The new event system (#208) has been merged in, which makes this a piece of cake using the `navigate` event!

```js
Inertia.on('start', event => {
  // Track visit via Google Analytics
})
```

I hope to tag a release tomorrow, and I also plan to add documentation to the website explaining how to use it. 🙌
