### ISSUE TITLE
Form fails to submit with Link component as Button

### ISSUE THREAD

**Issue by JaredCostall** [inertiajs/inertia#1690]
### Version:

- `@inertiajs/vue3` version: 1.0.0

### Describe the problem:

When using the `Link` component as a button, with the type `submit`, the form fails to submit.

### Steps to reproduce:

```
const form = useForm({
    title: null,
});
```
```
<form @submit.prevent="form.post(route('resource.store'))">
    <input type="text" v-model="title" />
    <Link as="button" type="submit">Save</Link>
</form>
```

**Comment by jessarcher** [comment]
The `Link` component and `useForm` helper are two separate approaches for making Inertia requests. The `Link` component makes Inertia requests using the required `href` prop and optional `data` prop. It has its own `onClick` behaviour to achieve this and shouldn't be used when you just want the standard HTML button behaviour - just use a `<button>` element.
