### ISSUE TITLE
Bundle growing strangely

### ISSUE THREAD

**Issue by WillRy** [inertiajs/inertia#1738]
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:
With each new page created, the app.js bundle increases even using code splitting. With 33 pages created, it is enough to increase 30kb in app.js. I believe that in large applications this will generate scalability problems, in a short time it will exceed 500kb in app.js

Is this a bug? Or is this normal behavior due to the fact that app.js has mapping for importing pages and their other dependencies?

In my application there was a 30kb difference between having 1 page or 33 pages.

Thanks for everything, sorry for any English mistakes, it's not my native language

### Steps to reproduce:

Configure code splitting and create new pages with multiple components inside

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
