### ISSUE TITLE
Error in File Upload documentation : https://inertiajs.com/file-uploads

### ISSUE THREAD

**Issue by KristenGarnier** [inertiajs/inertia#1744]
### Version:

- `@inertiajs/react` version: 1.0.0

### Describe the problem:

Encountered during file upload implementation, in the documentation the react implementation and other libraries are like this : 
```javascript
import { useForm } from '@inertiajs/react'

const { data, setData, post, progress } = useForm({
  name: null,
  avatar: null,
})

function submit(e) {
  e.preventDefault()
  post('/users')
}

return (
  <form onSubmit={submit}>
    <input type="text" value={data.name} onChange={e => setData('name', e.target.value)} />
    <input type="file" value={data.avatar} onChange={e => setData('avatar', e.target.files[0])} />
    {progress && (
      <progress value={progress.percentage} max="100">
        {progress.percentage}%
      </progress>
    )}
    <button type="submit">Submit</button>
  </form>
)
``` 

The main problem here is this line : 
```javascript
<input type="file" value={data.avatar} onChange={e => setData('avatar', e.target.files[0])} />
``` 
the data.avatar in value return an error because form input cannot display a File object

This has troubled some of my student that thought it was not working correctly when uploading an image.

We have fixed the issue displaying the file name directly (but i am sure there is an more elegant solution)  : 
```javascript
<input type="file" value={data.avatar ? data.avatar.fileName : ""} onChange={e => setData('avatar', e.target.files[0])} />
``` 
### Steps to reproduce:

Try to implement the exemple from the upload documentation

PS : Thanks for creating such a great Library, my student really liked Laravel + Inertia combo !

**Comment by driesvints** [comment]
Thanks @abdorrahmani

**Comment by haiffy420** [comment]
hi, my bad for bringing this up again, sorry but why is the docs not updated? also would be great if you give us proper **working** example instead of just code snippets. i love react and laravel, and i thank inertia for this wonderful tool. but the docs is really lacking
