### ISSUE TITLE
[inertia-vue] Inertia empty existing components

### ISSUE THREAD

**Issue by lucabecchetti** [inertiajs/inertia#175]
Hi guys, I have these inside my app.blade.php:

```html
<div id="app" data-page="{{ json_encode($page) }}">
    @include('layouts.sidebar')
    <c-wrapper>
        @include('layouts.header')
        <div class="c-body">
            <main class="c-main">
                    @yield('content')           
            </main>
        </div>
    </c-wrapper>
</div>
```

the problem is that when I mount inertia component all app child did removed, how con I mount intertia component at the place of @yield content
????

**Comment by reinink** [comment]
Exactly, thanks for answering this @ExpDev07. You can see a good example of this on the [server-side setup](https://inertiajs.com/server-side-setup) documentation. 👍
