### ISSUE TITLE
The PATCH method sends [ ] when changing files

### ISSUE THREAD

**Issue by Hernanarica** [inertiajs/inertia#1758]
### Version:

- `@inertiajs/react` version: #.#.#

### Describe the problem:

  When having a form with an input type file, when changing the image and sending the form using the PATCH method, it sends an empty array [ ], however when sending it via POST, it sends all data to the controller.

## web.php
```
  Route::patch('/test', function (Request $request) {
    dd($request->all());
  })
```

## React Component Edit
```
  const {  post, setData, patch } = useForm({
    title: '',
    description: '',
    description_image_name: null
  });

  const handleSubmit = (e) => {
    e.preventDefault();

    patch(`/test`);
  }

      <form
        action="#"
        method="patch"
        encType="multipart/form-data"
        onSubmit={ handleSubmit }
      >

        <input
          type="text"
          name="title"
          placeholder="Title"
          onChange={ (e) => setData('title', e.target.value) }
        />

        <input
          type="text"
          name="description"
          placeholder="Description"
          onChange={ (e) => setData('description', e.target.value) }
        />

        <input
          type="file"
          name="description_image_name"
          placeholder="Poster"
          onChange={ (e) => setData('description_image_name', e.target.files[0]) }
        />

        <button type="submit">enviar</button>
      </form>
```

https://github.com/inertiajs/inertia/assets/44417976/919bbdf9-55a4-43ab-9304-889aa9ce08d3

**Comment by RobertBoes** [comment]
This behaviour is explained in the docs: https://inertiajs.com/file-uploads#multipart-limitations

Inertia actually sends the file, but your backend (by the looks of it Laravel) uses PHP, which doesn't process file uploads on PATCH requests.

**Comment by Hernanarica** [comment]
Hello! Thank you very much for your prompt help, yes indeed, I had just solved it by reading the documentation, I was about to close the issue and I saw your message, thank you very much!

**Comment by Hernanarica** [comment]
I find that when I want to use the useForm, the _method gives me an error, worse when using router() it works. Is there a way to use useForm with _method?

returns correct
```
    router.post(`/promotions/${ promotion.id }`, {
      _method: 'patch',
      ...data
    }, {
      onSuccess: () => {
        notificationSuccess('Promoción Editada');
      }
    })
```

returns error
```
  post(`/promotions/${ promotion.id }`, {
      data: {
        _method: 'patch',
        ...data
      },
      onSuccess: () => {
        notificationSuccess('Promoción Editada');
      },
    });
```

![Captura de pantalla 2023-12-23 a las 12 02 05](https://github.com/inertiajs/inertia/assets/44417976/424cd846-651f-4c35-8337-f667b421a6f1)

**Comment by Hernanarica** [comment]
Solved! You have to add the _method in the userForm({
_method: 'patch'
})
