### ISSUE TITLE
Send Select without a form with GET method not working... React

### ISSUE THREAD

**Issue by vitalijalbu** [inertiajs/inertia#1777]
### Version:

- `@inertiajs/react` version: **latest**

### Describe the problem:

Please see here description: 
[https://github.com/inertiajs/inertia/discussions/1774](https://github.com/inertiajs/inertia/discussions/1774)

**Comment by derrickreimer** [comment]
Hey @vitalijalbu! I think you can get by without using the `useForm` hook here. I'd recommend just navigating the page in the `onChange` hook for your select, rather than setting form state and subsequently triggering navigation. Simplified example:

```jsx
<select value={props.filters.order_by} onChange={(e) => router.get("/page", { order_by: e.target.value })}>
```
