### ISSUE TITLE
Page transitions: Fade

### ISSUE THREAD

**Issue by diemah77** [inertiajs/inertia#179]
I'm trying to figure out how to apply a fade animation on component switching. Any idea how to get this done?

**Comment by claudiodekker** [comment]
Hey, great to hear you've solved your problem. I've closed this issue, but if you feel like this is still an Inertia-related bug, please do not hesitate to re-open it. Thanks! 👍

**Comment by gitwithravish** [comment]
Thanks !

**Comment by mohkoma** [comment]
Here is a simple solution that can help.
In the Layout component, Use the `$page.url` of the current url as a key 🎉.
```
<transition name="fade" mode="out-in" appear>
     <div :key="$page.url">
          <slot  />
     </div>
</transition>
```
