### ISSUE TITLE
Non optimised production build?

### ISSUE THREAD

**Issue by jamesh-purr** [inertiajs/inertia#1804]
### Version:

- `@inertiajs/vue3` version: ^1.0.0

### Describe the problem:

Using very bare bones app.js file still triggers googles reduce unused javascript. I have tried a lot of things with vite and I still can't get this issue resolved. 

### Steps to reproduce:

import { createInertiaApp } from '@inertiajs/vue3';
createInertiaApp({
    setup({ el, App, props }) {

    },
});

first is size of app.js and second is savings it could make with removed js code.
…assets/app-06b5762a.js(example-app.test) | 56.8 KiB | 44.1 KiB

Any ideas or any possible way to get this to stop triggering google's page speed warnings?

**Comment by jameshulse** [comment]
Someone else has raised some PRs to address some of this: https://github.com/inertiajs/inertia/pull/1791 and https://github.com/inertiajs/inertia/pull/1792.

**Comment by jamesh-purr** [comment]
Oh I see @jameshulse thanks for pointing out already open tasks for this issue.

**Comment by jamesh-purr** [comment]
Hey @reinink 

https://github.com/inertiajs/inertia/pull/1792
https://github.com/inertiajs/inertia/pull/1791

As the two pull requests above have been refused and closed this is still an issue and by google standards inertia isn't optimised.

**Comment by wilsenhc** [comment]
It would be a great addition to fix this issue, reducing bundle size is always good

**Comment by driesvints** [comment]
Looks like we won't change anything here sorry.

**Comment by RomainLanz** [comment]
> Looks like we won't change anything here sorry.

Can we know the reason at least?
It seems to be a simple and needed change (as shared in both linked PR)

**Comment by RomainLanz** [comment]
Do you have any news on this work? May I create a fork of the `@inertia/core` package to lower the build size?

Currently, most of the Inertia size is from axios (unnecessary) and `qs` (not needed either).

![](https://github.com/inertiajs/inertia/assets/2793951/ea8553aa-c621-4d64-a197-c3dd16dbb08d)

**Comment by RomainLanz** [comment]
Since Inertia 2 is approaching, can we move on and start changing those dependencies? It can be a great time to do so since it will be a major release with expected breaking changes.

**Comment by reinink** [comment]
@RomainLanz Hey you mention that axios isn't required - what are you suggesting as an alternative?

**Comment by RomainLanz** [comment]
Absolutely! 🙌🏻

I recommend checking out [`ky`](https://github.com/sindresorhus/ky), a lightweight wrapper around the Fetch API.

While you could build your own wrapper on top of `fetch` for your needs, `ky` is so minimal and efficient that it might save you the effort.

Thanks for considering this!

**Comment by reinink** [comment]
@RomainLanz So ky looks great, but it doesn't support upload progress, which is a significant limitation of fetch, and would be a major breaking change for Inertia apps that rely on upload progress. So while I love the idea of using fetch, I just don't think we can until we have upload progress support.

**Comment by RobertBoes** [comment]
That wouldn't work in Firefox: https://developer.mozilla.org/en-US/docs/Web/API/Request/body

**Comment by reinink** [comment]
@pedroborges Looks like [they just simulate progress](https://github.com/suhaotian/xior?tab=readme-ov-file#upload-and-download-progress-plugin) — that feels like a pretty big step backwards still:

> Enable upload and download progress like axios, but the progress is simulated, This means it doesn't represent the actual progress but offers a user experience similar to libraries like axios.

**Comment by pedroborges** [comment]
@reinink bummer, I hadn't noticed that 🥲

**Comment by osbre** [comment]
Unlike xior, [Ky](https://github.com/sindresorhus/ky) uses the actual progress and doesn't simulate it.
