### ISSUE TITLE
[inertia-react] Preserving state on input search/Inertia.visit

### ISSUE THREAD

**Issue by andregoldstein** [inertiajs/inertia#181]
Hi there, I'm having an issue trying to get a live search on a table view working. When I update the query, I'm calling (via way of a `useEffect` hook)

`Inertia.visit(url, data: { query }, { preserveState: true })`

However although the query works and the data is reloaded, it's still causing the component to reload and hence the query input is continually losing focus. I'm pretty sure I have achieved this fine with Inertia previously but I can't seem to figure out why the component is continually remounting on input. Perhaps I have misunderstood what preserveState does? Or it could be somewhere else in my code that is causing a re-render?

Thank you

**Comment by reinink** [comment]
Going to close this issue for now, but feel free to leave a comment if you have any further issues. 👍
