### ISSUE TITLE
Drop remember mixin support

### ISSUE THREAD

**Issue by Coding-Kiwi** [inertiajs/inertia#1837]
### Version:

- `@inertiajs/vue3` version: 1.0.15

### Describe the problem:

I want to disable the options api for treeshaking by specifying it in the webpack config

```
__VUE_OPTIONS_API__: false
```

Sadly this causes the warning `[Vue warn]: Mixins are only available in builds supporting Options API`

All issues created regarding this (https://github.com/inertiajs/inertia/issues/458, https://github.com/inertiajs/inertia/issues/882) have been closed because "there's a decent chance that they have since been resolved or are simply not relevant any longer"

the [vue docs](https://vuejs.org/api/application.html#app-mixin) clearly state:

> Mixins are supported in Vue 3 mainly for backwards compatibility, due to their widespread use in ecosystem libraries. Use of mixins, especially global mixins, should be avoided in application code.

**----> Use of mixins, especially global mixins, should be avoided in application code. <----**

Both https://legacy.inertiajs.com/remembering-state and https://inertiajs.com/remembering-state say to use
`import { useRemember } from '@inertiajs/vue3'` instead of the mixing

So my question: why even include the mixin in the vue3 package, mixins are a vue2 feature?

**Comment by driesvints** [comment]
Thanks for your issue report. We'd very much appreciate a PR that helps remove this if it's deprecated. However, please keep in mind not to break backwards compatibility.

**Comment by Coding-Kiwi** [comment]
It's really amazing how you do everything to keep the issue count low. Just close all old issues and pull-requests in one fell swoop in the hope that nobody will complain about them, just close new issues with a "haha sounds nice, do a PR or get lost" comment.

The "closed as completed" message in my email inbox is pure mockery. Just like the "However, please keep in mind not to break backwards compatibility.", just make it my issue, eh?

I created the issue to give you (or someone else) the chance to make the project better and to give others who receive the warning in the console a chance to know that they are not alone with the problem.

The result is that the issue is simply closed and can now only be found if you explicitly remove the "is open" filter and if you do find it, you realize that the project owners don't seem to care about the problem.

I am really grateful for the free provision of the project and the work that is invested to keep it alive, please don't misunderstand. But some days the way things are done in the open-source community seems really strange to me
