### ISSUE TITLE
Data props change from boolean (0/1) to string ("0"/"1") in production

### ISSUE THREAD

**Issue by edikurniawan-dev** [inertiajs/inertia#1841]
### Version:

- `@inertiajs/react` version: 1.0.15

### Describe the problem:

I have data in database with type is boolean 0 or 1, in local development i get data with type boolean like this
![image](https://github.com/inertiajs/inertia/assets/50087198/944f2a55-9803-4533-8df8-a90a63fd0ef8)
but in production why data change to be string like this?
![image](https://github.com/inertiajs/inertia/assets/50087198/709a9bcb-6b3d-47fc-9f28-3a747a0ee69b)

how to solve it? thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
