### ISSUE TITLE
Link component cannot be rendered as a custom component due to toLowerCase()

### ISSUE THREAD

**Issue by ammagv** [inertiajs/inertia#1844]
### Version:

- `@inertiajs/react` version: 1.0.14

### Describe the problem:

https://github.com/inertiajs/inertia/blob/2ebd86224d2c12fdad4e4b23276129832754cf6d/packages/react/src/Link.ts#L114

Because of the above line, it is not possible to use a custom component in the "as" of a Link component. Otherwise, it would be possible to use it as shown below:
```
import { Link } from '@inertiajs/react';
import { Button } from './components';

...
<Link as={Button}>Foo</Link>
...
```

Would it be possible to remove the above line to enable this use case?

_Originally brought up by @bobbypiper in https://github.com/inertiajs/inertia/discussions/998_

**Comment by driesvints** [comment]
Heya thank you for this issue. This is more a feature request so I suggest to just attempt a PR to see if it gets accepted.
