### ISSUE TITLE
Incompatible with laravel vapor

### ISSUE THREAD

**Issue by EionRobb** [inertiajs/inertia#1847]
### Versions:

- `@inertiajs/core` version: v1.0.15

### Describe the problem:

Currently the use of unencoded square brackets in the URL is causing 400 errors when running on laravel vapor.  I need to use arrays in the get requests to work with spatie query builder in laravel for filtering.

Looking at the source, this is due to `encodeValuesOnly: true,` in https://github.com/inertiajs/inertia/blob/master/packages/core/src/url.ts#L25 which is preventing `[` and `]` being encoded as `%5B` and `%5D` - removing this line lets everything work.  Is this line here just to make the URLs look nicer?

There's a bit more info about the cause of the 400 error on the vapor docs:
https://docs.vapor.build/projects/troubleshooting.html#sandbox-url-returns-400-message-null

Maybe also relevant: https://www.rfc-editor.org/rfc/rfc1738#page-3 which says that `[` and `]` are unsafe and must always be encoded in a url

### Steps to reproduce:

1. Deploy a laravel app which uses inertia, onto AWS Lambda via vapor
2. Use `Inertia.useForm()` with an array to get a request

**Comment by driesvints** [comment]
I think we should fix this yes. Could you please send in a PR? thanks!

**Comment by driesvints** [comment]
@EionRobb ideally this would be configurable with the default being `true`.
