### ISSUE TITLE
Page doesn't get rendered 

### ISSUE THREAD

**Issue by nafea107** [inertiajs/inertia#1851]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

When opening the page for the first time it get rendered but after closing the browser then trying to open the browser again the cached page of inertia app returns json instead of html

### Steps to reproduce:

  I don't know the reason. I just installed ssr app and disabled the ssr from inertia config
![Screenshot_20240411-234902](https://github.com/inertiajs/inertia/assets/47711093/5dc43104-976d-4754-b6ce-0d31448be834)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
