### ISSUE TITLE
 "undefined" is not valid JSON at JSON.parse in createInertiaApp()

### ISSUE THREAD

**Issue by whatnotery** [inertiajs/inertia#1853]
### Version:

- `@inertiajs/svelte` version: 1.0.15

### Describe the problem:

I am trying to setup a rails application with inertia and svelte

I've got  the following files set-up as  per the documentation however it will not render the svelte component it errors in the console with this message:

```
Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at createInertiaApp (@inertiajs_svelte.js?v=5b546d2f:5036:37)
    at application.js:3:1
```

I saw this error referenced in #1358 as well although I'm not sure they're directly related if anyone has insight on how to resolve this I'd appreciate it

*app/frontend/entrypoints/application.js*
```js
import { createInertiaApp } from '@inertiajs/svelte'

createInertiaApp({
  resolve: name => {
    const pages = import.meta.glob('./Pages/**/*.svelte', { eager: true })
    return pages[`./Pages/${name}.svelte`]
  },
  setup({ el, app, props }) {
    new app({ target: el, props })
  },
})
```
*config/routes.rb*
```ruby
Rails.application.routes.draw do  
  root "static#home"
end
```

*app/controllers/static_controller.rb*
```ruby
class StaticController < ApplicationController
    def home
      render inertia: 'app'
    end
  end
```
*app/views/layouts/application.html.erb*
```erb
<!DOCTYPE html>
<head>
    <%= vite_client_tag %>
    <%= vite_javascript_tag "application", defer: true %>
</head>
<body>
    <div id="app">
    </div>
</body>
```

*app/frontend/pages/app.svelte*
```html
<h1>Hello World!</h1>
<p>This is the App component</p>
```

### Steps to reproduce:

setup a rails/inertia/svelte app
with the preceding set up

**Comment by whatnotery** [comment]
This was error on my part and I have resolved this

**Comment by alexmillman23** [comment]
> This was error on my part and I have resolved this

thanks for the detailed response

**Comment by whatnotery** [comment]
I'm sorry I've upset so many people, I just kept trying to things till it worked out and don't fully understand what I did to resolve things I can link to the repo where I resolved the issue so people can dig into it themselves

**Comment by whatnotery** [comment]
https://github.com/whatnotery/MovieFinder.club/blob/main/app/frontend/entrypoints/application.js

**Comment by alexmillman23** [comment]
All good :) . these types of front-end issues just make me want to stay on the backend. thank you for the additional info
