### ISSUE TITLE
Router methods type issues with wrong use of Exclude

### ISSUE THREAD

**Issue by aktasumut34** [inertiajs/inertia#1856]
In `router`, `get`, `reload`, `replace`, `post`, `put`, `patch`, `delete` typed wrong. It uses

```ts
Exclude<VisitOptions, FieldsToHide>
```
instead of
```ts
Omit<VisitOptions, FieldsToHide>
```

This causes behaviours like 'preserveState', 'preserveScroll' is included in `reload` functions `options` parameter type.

**Comment by driesvints** [comment]
Thanks @aktasumut34. Seems you sent in a PR so let's see how it goes.
