### ISSUE TITLE
Form defaults() then reset() doesn't work as expected

### ISSUE THREAD

**Issue by fufaldinav** [inertiajs/inertia#1862]
### Version:

- `@inertiajs/vue3` version: 1.0.6

### Describe the problem:

The form does not reset **isDirty** state after calling **defaults()** and then calling **reset()**
This behavior is observed if there are only primitive values in the form
I assume that watcher doesn't see changes and does not change the IsDirty state
```js
watch(
  form,
  (newValue) => {
    form.isDirty = !isEqual(form.data(), defaults)
    if (rememberKey) {
      router.remember(cloneDeep(newValue.__remember()), rememberKey)
    }
  },
  { immediate: true, deep: true },
)
```
### Steps to reproduce:

Create a form as in the playground:

```js
const form = useForm('NewUser', {
  name: '',
  company: '',
  role: '',
})
```

Try to change some value

![image](https://github.com/inertiajs/inertia/assets/1456499/3132800c-3698-4039-9b32-3bff289f76b5)

Next, call defaults() and reset(), isDirty will not change its state

https://github.com/inertiajs/inertia/assets/1456499/81c37c7e-c0d9-4c7d-8c5b-9e8e27574674

**Comment by gravitymedianet** [comment]
Any update on this? This is a pretty serious bug
