### ISSUE TITLE
Version MUST be a string, otherwise page refreshes

### ISSUE THREAD

**Issue by laurentvd** [inertiajs/inertia#187]
Hi, I used a timestamp of the moment the front-end is built as a version number. The code basically came down to `Inertia::version(1597347897973)` which made a lot of sense to me. 

However, I kept seeing refreshes and after some research I noticed the 409 Conflict responses indicating a version mismatch. The docs say the version can be a number, but when the number really is a number (not a numeric string), Inertia thinks it is not the same version. 

To fix this you could change it to `Inertia::version('1597347897973')`. Do you see the same issue I'm seeing? If so, would it make sense to mention this in the docs or (probably preferable) should we 'fix' this in the Inertia version comparison code? I could make a PR for either solution.

**Comment by ycs77** [comment]
Using type casting. Example for PHP:

```php
Inertia::version((string) 1597347897973);
```

**Comment by laurentvd** [comment]
Yes, that's basically what I'm doing. I think the docs are confusing as it says numbers are allowed.

**Comment by reinink** [comment]
I agree, this is confusing. I’ll get this fixed. 💪

**Comment by laurentvd** [comment]
Great @reinink, let me know if I can help!

**Comment by claudiodekker** [comment]
Submitted a fix that solves this for the Laravel adapter.

I don't know any Ruby, but[ if I'm reading this correctly](https://github.com/inertiajs/inertia-rails/blob/8b24e62b8aa6070c9226dff3a225d590c4b6ece3/lib/inertia_rails/middleware.rb#L35) I believe the issue still persists over there, though.

**Comment by reinink** [comment]
Done! We've updated the Laravel adapter to automatically cast versions to a string. I've also updated the docs to reflect this better (https://github.com/inertiajs/inertiajs.com/commit/679d57a19c7bd1d4bf497fd69775ce8a275018c7). 👍

**Comment by slovenianGooner** [comment]
Quick update on this - I had no version inside the boot method and I got a 409 error constantly. Perhaps we need to check if a version actually exists?
