### ISSUE TITLE
[1.1.0] Partial reloads - Object props updated incorrectly

### ISSUE THREAD

**Issue by Megarsh** [inertiajs/inertia#1885]
### Version:

- `@inertiajs/vue3` version: 1.1.0

### Describe the problem:

On partial reloads Object props are updated incorrectly.

Example 
----

if we have a data prop with value 
```
{
  "b": 2,
  "a": 1,
  "c": 3,
  "d": 4
}
```
And on the partial reload we get a new value of
```
{
  "b": 40
}
```
The missing keys are being kept and the new value is returned as
```
{
  "b": 40,
  "a": 1,
  "c": 3,
  "d": 4
}
```

### Steps to reproduce:

Minimal reproduction - https://github.com/Megarsh/inertia-issue

**Comment by reinink** [comment]
Hey thanks for reporting, this should be fixed now in v1.2.0 👍
