### ISSUE TITLE
Unable to view Head attribute and <meta description> tag - When viewing source

### ISSUE THREAD

**Issue by Dlas1212** [inertiajs/inertia#1886]
### Version:

- `@inertiajs/vue3` version: 1.1.0

### Describe the problem:

Adding the `Head` component does not work, including adding `meta description` adds it when you inspect element, but if you view the source of the website, then the `meta description tag` is missing.

I am using this with Laravel's set up too but the package is specifically `"@inertiajs/vue3": "^1.1.0",`. I noticed that the "Head" items don't even get included. I even have `@inertiaHead` in `app.blade.php`

### Steps to reproduce:

```
    <Head title="Home">
        <meta name="description" content="This is my description">
    </Head>
```

Inspecting the element:
<img width="543" alt="Screenshot 2024-06-01 at 10 29 14 PM" src="https://github.com/inertiajs/inertia/assets/25422899/807384ff-9b60-4c2c-9b24-c13f7c786ea0">

Viewing Source: Nothing for "title" Home exists, even CMD+F & nothing for meta description. 
<img width="592" alt="Screenshot 2024-06-01 at 10 32 56 PM" src="https://github.com/inertiajs/inertia/assets/25422899/e04ec303-1e6b-43df-ba63-5b469599534f">

**Comment by RobertBoes** [comment]
You need SSR in order for that to work: https://inertiajs.com/server-side-rendering
