### ISSUE TITLE
Please update docs

### ISSUE THREAD

**Issue by ignacio-dev** [inertiajs/inertia#1893]
I spent days trying to fix an issue related to infinite scroll, only to eventually find out that you can pass ```{ preserveUrl: true }``` when using Inertia's router.

There is no mention of this option on your website.

Could you please add it to your docs? It would saved me a few days of googling around!!

**Comment by RobertBoes** [comment]
Inertia doesn't have a `preserveUrl` option

**Comment by ignacio-dev** [comment]
It does now, and I'm using it on my project without issues.

See #1009

**Comment by RobertBoes** [comment]
It doesn't, if you look at the files being changed in that PR; it's empty. That PR was closed, but since there are no changes I guess GitHub shows it as merged.

**Comment by reinink** [comment]
Yup exactly — it's something that's been asked about a number of times, mostly because of challenges when doing infinite scrolling, but not something we've actually solved yet in Inertia.js. Maybe in the future though! 💪

Given that I'm going to close this issue.

**Comment by ignacio-dev** [comment]
My bad then

**Comment by reinink** [comment]
> My bad then

ALL GOOD! 🤙

**Comment by harryqt** [comment]
v2 have `preserveUrl`, I guess we should update the docs now.
