### ISSUE TITLE
Query Param array gets repeated after second call to any router method

### ISSUE THREAD

**Issue by eddi00** [inertiajs/inertia#1897]
Hi there, I'm trying to send the server multiple query array parameters and after clicking a method button after the first time the arrays values get merged together when the expected behavior is them to be replaced.

Example: `
router.reload({
			data: {
				ports,
				cities,
			},
		});
`

Both variables `ports` and `cities` are arrays.

After many times clicking the search button the result is:
`http://localhost:4000/page?cities[]=1&cities[]=1&cities[]=1&ports[]=5&ports[]=5&ports[]=5`

I'm using  `"@inertiajs/react": "^1.0.15"`

I think the issue is in this line

https://github.com/inertiajs/inertia/blob/eb19b39c6fc526cb2b52c3e4302f43767920eb0a/packages/core/src/url.ts#L24

Thanks in advance!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
