### ISSUE TITLE
[Contribution Guide / PingCRM] Yarn Link & Yarn Install not working

### ISSUE THREAD

**Issue by claudiodekker** [inertiajs/inertia#190]
Hey @reinink,

Just tried to set up a local copy of the repo, as well as PingCRM using the [Contributing Guidelines](https://github.com/inertiajs/inertia/blob/master/.github/CONTRIBUTING.md), but I'm getting the following error:

![Screenshot 2020-08-19 at 19 56 01](https://user-images.githubusercontent.com/1752195/90672182-09574300-e256-11ea-96d5-c66dac83fae7.png)

Any thoughts?

**Comment by reinink** [comment]
So @pedroborges just ran into this. Here was why:

> Turns out it was because I had `.config` as a symlink to `.dotfiles/config`.

You can read more about this issue [here](https://github.com/yarnpkg/yarn/issues/1297#issuecomment-546995350).

Let me know if that helps. 👍

**Comment by claudiodekker** [comment]
Unfortunately, I don't have that folder symlinked: 

![Screenshot 2020-08-19 at 20 03 55](https://user-images.githubusercontent.com/1752195/90672907-2c362700-e257-11ea-9559-21af8eb9787f.png)

**Comment by reinink** [comment]
Do you see `@inertiajs` listed in your `~/.config/yarn/link` folder?

**Comment by claudiodekker** [comment]
Yep, as a folder:

![Screenshot 2020-08-19 at 20 08 53](https://user-images.githubusercontent.com/1752195/90673285-ceeea580-e257-11ea-83f7-fc604434972c.png)

**Comment by reinink** [comment]
You are using Yarn, and not NPM, correct?

If you go to your PingCRM `node_modules` folder, what do you see in the `@inertiajs` folder? You should see two folders, symlinked:

![image](https://user-images.githubusercontent.com/882133/90673527-e44adc00-e225-11ea-9d94-9ac97a6cb3e6.png)

**Comment by claudiodekker** [comment]
Yep, using Yarn, and I'm seeing those links like you're seeing them:

![Screenshot 2020-08-19 at 20 12 43](https://user-images.githubusercontent.com/1752195/90673933-b3d06580-e258-11ea-8a56-9d733bf8e3bb.png)

![Screenshot 2020-08-19 at 20 13 32](https://user-images.githubusercontent.com/1752195/90673913-ac10c100-e258-11ea-9289-39a08764bb1c.png)

**Comment by reinink** [comment]
What version of Yarn are you using?

**Comment by claudiodekker** [comment]
1.22.4, I just installed it from brew (didn't have it on this machine)

**Comment by reinink** [comment]
Hmm, have you tried totally removing the `node_modules` folder from PingCRM, and trying again?

```sh
rm -rf node_modules
yarn install
yarn link @inertiajs/inertia
yarn link @inertiajs/inertia-vue
yarn dev
```

**Comment by pedroborges** [comment]
Have you run `yarn watch` or `yarn build` on the `@inertiajs/inertia` and `@inertiajs/inertia-vue` packages? Make sure both packages you linked have the `dist` folder.

**Comment by claudiodekker** [comment]
@reinink Yeah, I did that. I also tried the same on my other machine, but there it works.
I'm re-installing Node now, but it's definitely something weird on my side, so I'll close this one.

Thanks guys!
