### ISSUE TITLE
ability to setData using array/objects on useForm 

### ISSUE THREAD

**Issue by ph-hitachi** [inertiajs/inertia#1911]
Hi 

### Describe the problem:
i want to use `useForm` but i can handle setData when passing js arrays as formData

```js
import { useForm } from '@inertiajs/react';

const { data, setData, post, processing, errors, reset } = useForm({
        email: '',
        password: '',
    });

    // useEffect(() => {
    //     return () => {
    //         reset('password');
    //     };
    // }, []);

    const login = (formData: {email: string, password: string}) => {
        console.log(formData) // {email: 'example@mail.com', password: 'password'}
        post(route('login'), { 
            data: formData,
        });
    };
 ```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
