### ISSUE TITLE
Scroll restoration issue

### ISSUE THREAD

**Issue by mrleblanc101** [inertiajs/inertia#1922]
### Version:

- `@inertiajs/vue3` version: 1.2.0

### Describe the problem:

If you click on a link at the bottom of a page, then use any mean to go to the previous page (back button, trackpad gesture, history.back()), the scroll position is not always properly restored.

As you can see in this exemple, the first back does not restore the correct position, but the second back does.
![2024-07-13 22 20 50](https://github.com/user-attachments/assets/670d1f75-cac4-420b-aa94-05457525eb3c)

### Steps to reproduce:

Here is the website where you can reproduce the issue: https://tee-time.ca/search?city_id=65&date=2024-07-14
If the is no results, try changing the date in the top-left corner.

**Comment by mrleblanc101** [comment]
Probably relates to #1915

**Comment by benjivm** [comment]
Same as #1698 does not appear to affect Chrome, at least in my testing and repro repo.

**Comment by pedroborges** [comment]
Fixed by #1980 ✅
