### ISSUE TITLE
enable the text compression 

### ISSUE THREAD

**Issue by johnqiuwan** [inertiajs/inertia#1947]
### Version:

- `@inertiajs/vue3` version: ^1.0.0

### Describe the problem:

The ssr is running smooth but the chrome lighthouse keeps giving suggestion to enable the text compression. I inspected the chrome dev tools and find some response header of vue file is not using any text compression. 

I have turned on the text compression on the php server side (apache), but it still not solve this issue.  

Does this should be done on the node server side ? I have searched online and someone is asking the same question, but no one seems know how to answer it.

I am not quite sure if it Is a bug.

**Comment by RobertBoes** [comment]
The Inertia SSR server only renders the HTML of your page (whatever would be in the `@inertia` directive), it does not serve JS files, that's served by your webserver.

**Comment by johnqiuwan** [comment]
Thank you for you quick reply! 

I noticed that the server still serve vue files after vite build & vite build --ssr. What I think is that the vue files should already compiled to the js file. 

After run the command 
`php artisan inertia:start-ssr`
It should serve the production bundle.  

The image below is from chrome dev tools network tab, and the server is still serving the vue files. These files are not text compressed.

<img width="761" alt="Screenshot 2024-08-19 at 3 14 08 PM" src="https://github.com/user-attachments/assets/8ba4d6a4-c488-4ab9-8236-4025077d8428">

**Comment by johnqiuwan** [comment]
Thank you for your reply, I have solved the issue, and some people online facing the same issue.  
If someone has same issue, the solution is that you need to delete the public/hot file.

Why?
The public/hot force the app using dev mode, and therefore it will not use the production bundle. It usually will not cause the issue on production deploy since the public/hot file is included in the .gitignore file, but it will happen when in local dev.

**Comment by RobertBoes** [comment]
> The public/hot force the app using dev mode, and therefore it will not use the production bundle. It usually will not cause the issue on production deploy since the public/hot file is included in the .gitignore file, but it will happen when in local dev.

That wouldn't happen locally either, when you stop the Vite dev server that file won't exist and Laravel will attempt to use the production build.
