### ISSUE TITLE
How would you test props returned by the usePage() hook?

### ISSUE THREAD

**Issue by nooxx** [inertiajs/inertia#199]
Hi all,

I think everything is in the title. I am trying to write tests that check against values returned from my controllers to my pages.

Using Laravel and React.

@sebastiandedeyne 

Thanks

**Comment by reinink** [comment]
Ping @sebastiandedeyne.

**Comment by sebastiandedeyne** [comment]
Hey @nooxx! What kind of tests are you talking about? Full-stack integration tests, or client side unit tests?

Could you share a snippet of what you're trying to assert?

**Comment by reinink** [comment]
Closing this for now because of no response.

@nooxx Feel free to respond still, and we'll happily help if we can. 👍
