### ISSUE TITLE
Scrolling causes many asset requests to favicon

### ISSUE THREAD

**Issue by alexbowers** [inertiajs/inertia#2]
When scrolling on a page, there are hundreds of requests made to get a favicon.

**Comment by reinink** [comment]
Interesting side affect to how I'm tracking scroll position.

https://github.com/inertiajs/inertia/blob/cea11a3a265508a96560fd315f0f91b50c256040/src/inertia.js#L130-L132

Will have to think of a new way to do this.

Thanks for reporting @alexbowers!

**Comment by cmizzi** [comment]
I don't think it's a real problem. Chrome acts like that because a favicon is not set or empty. Firefox doesn't handle the same behavior : it only asks once the favicon. When a favicon is set and not empty, Chrome stops sending request between each page load.

@alexbowers try to set up a favicon ;)

**Comment by reinink** [comment]
This problem should be fixed now, since Inertia no longer does scroll restoration.
