### ISSUE TITLE
Bug 404 in docs inertia 2.0

### ISSUE THREAD

**Issue by HichemTab-tech** [inertiajs/inertia#2010]
### Versions:

- inertia 2.0 docs

### Describe the problem:

When searching in the search bar `infinite scroll`, and i click on the link [[intersection-observer](https://v2.inertiajs.com/intersection-observer#always-trigger)](https://v2.inertiajs.com/intersection-observer#always-trigger), I get 404 error.

### Steps to reproduce:

just search in the search bar `infinite scroll`, and click on the second result : 
![image](https://github.com/user-attachments/assets/a7a5cafa-ff79-47df-b80e-65fa0985f0fa)

**Comment by PedroAugustoRamalhoDuarte** [comment]
@HichemTab-tech can you please create an issue in inertia documentation GitHub https://github.com/inertiajs/inertiajs.com? Thanks!!

**Comment by HichemTab-tech** [comment]
@PedroAugustoRamalhoDuarte done ! 👌
