### ISSUE TITLE
$page.url breaking change

### ISSUE THREAD

**Issue by Cacamoto** [inertiajs/inertia#2020]
### Version:

- `@inertiajs/vue3` version: lagest

### Describe the problem:

$page.url returns http://localhost:8000/ instead of /

### Steps to reproduce:

Update to v2 and {{ $page.url }}

**Comment by pedroborges** [comment]
@Cacamoto what backend adapter are you using? With the Laravel adapter I'm still getting the full path as usual, see below. This URL value comes from the backend.

<img width="832" alt="Screen Shot 2024-10-11 at 12 43 58" src="https://github.com/user-attachments/assets/a1a3e6c8-f355-4062-95f1-02144cea6190">

**Comment by chhaihongsrun** [comment]
> ### Version:
> * `@inertiajs/vue3` version: lagest
> 
> ### Describe the problem:
> $page.url returns http://localhost:8000/ instead of /
> 
> ### Steps to reproduce:
> Update to v2 and {{ $page.url }}

yes, you are right.
when I want to activate the link, I to use url.startsWith('profile') it's no longer work.
i switch to use component === 'Profile/Edit' ? 'active' : 'nope'

ref: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js/episodes/8

**Comment by Cacamoto** [comment]
@pedroborges 
`"inertiajs/inertia-laravel": "2.x-dev"`
$page.component === 'Home' ? 'outline' : 'ghost' works as expected

**Comment by the-goodies** [comment]
> @Cacamoto what backend adapter are you using? With the Laravel adapter I'm still getting the full path as usual, see below. The URL value comes from the backend.
> 
> <img alt="Screen Shot 2024-10-11 at 12 43 58" width="832" src="https://private-user-images.githubusercontent.com/688309/375813903-a1a3e6c8-f355-4062-95f1-02144cea6190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NTAwOTMsIm5iZiI6MTcyODc0OTc5MywicGF0aCI6Ii82ODgzMDkvMzc1ODEzOTAzLWExYTNlNmM4LWYzNTUtNDA2Mi05NWYxLTAyMTQ0Y2VhNjE5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxNjE2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDU1ZjBkMDNmZWE3NDNlZDA2NDZhZjcyYWI0YTI4N2RmM2FlYTU4OTBkZTNiMDRhNDI1MDY2Mjk5M2E2MWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FI2CIa5BuWUTXDOhaR8dKDZyKXDoYTPQQWoWLGNHTo0">

React has this issue also. While the returned **url** prop from the backend is correct, the returned  **url** from React's usePage() has **domain** included:
```javascript
  const { url } = usePage()
  console.log(url)
```

**Comment by mathcrln** [comment]
I second this. Also experiencing it with the React+Laravel adapters. It now returns the fully qualified url with the protocol and the domain.
