### ISSUE TITLE
[v2] Uncaught TypeError: component2 is undefined

### ISSUE THREAD

**Issue by harryqt** [inertiajs/inertia#2022]
### Version:

- `@inertiajs/svelte` version: 2.0.0-beta.1

Tested using Bun, NodeJs - same issue.

### Describe the problem:

<img width="498" alt="Screenshot 2024-10-11 at 10 12 56 PM" src="https://github.com/user-attachments/assets/a84e28d1-5d2c-4cdb-acb8-1156c2692728">

### Steps to reproduce:

https://github.com/harryqt/laravel-inertia-v2

**Comment by pedroborges** [comment]
Hey @harryqt, I tested you repo with Node and Bun, dev and build, and couldn't reproduce this error.

<img width="780" alt="Screen Shot 2024-10-11 at 14 32 21" src="https://github.com/user-attachments/assets/ac340570-aa63-44b8-94be-080093cbe0c3">

If you can provide more details I'd be happy to look into it.

**Comment by harryqt** [comment]
Eh.? 🤔 Using macOS btw, but I don't see how that's relevant here.

**Comment by pedroborges** [comment]
I'm on macOS too, and:

```
> node -v
v18.20.4
> bun -v
1.1.30
```

**Comment by harryqt** [comment]
Clearing `bootstrap/cache/*` `bootstrap/ssr/*` removes the warning. I guess something was cached.
