### ISSUE TITLE
Problem clicking the link twice

### ISSUE THREAD

**Issue by warlisson** [inertiajs/inertia#2027]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

When clicking on the link (using Link), the loading is displayed and then the data. When clicking on the link again, it only loads and does not display the data.

### Steps to reproduce:

When loading the page, the loading text is displayed. When clicking on the links, the loading is also displayed, but when clicking twice on the same link, the loading text is displayed and the object with the data is not returned.

 Here is the code used for testing:

`

    <Link href="/">All Users</Link> -
    <Link href="/?status=active">Users active</Link>

    <Deferred data="users">
      <template #fallback>
        <div>Loading...</div>
      </template>
      <div v-for="user in props.users">
        <p class="p-2 bg-slate-100 mb-1">My name is {{ user.name }}</p>
      </div>
    </Deferred>

`

**Comment by MarcEspiard** [comment]
I think it's the same as #2013

**Comment by reinink** [comment]
This should be fixed in #2024, and we hope to get a new beta release out shortly 👍
