### ISSUE TITLE
[2.x] Should `nprogress` remain a dependency?

### ISSUE THREAD

**Issue by NickSdot** [inertiajs/inertia#2031]
I wanted to open this to ensure awareness and have it tracked.

The core package requires `nprogress` which seems more or less abandoned. The last 0.2.0 release on npm was 9 years ago. 

4 years ago there was an attempt to release 1.0.0, which was tagged on GitHub but never made it as "latest" to npm. 

Issues and merge requests are ignored; new packages spammed.

Not sure how I feel about such a dependency in general. Additionally, not everyone needs progress bars. And support for the navigation api (native spinners, yay!) in all major browsers seems only months away.🤏

I was wondering if Inertia v2 would be a good moment to drop mentioned dependency and make it (and it's Inertia wrapper) optional?

**Comment by NickSdot** [comment]
Forgot: 
removing `nprogress` would also be another step towards the goal of moving away from Axios, as mentioned here https://github.com/inertiajs/inertia/issues/132#issuecomment-705640758

**Comment by SuperDJ** [comment]
Also many UI packages already include their own progress bar.

**Comment by NickSdot** [comment]
> Also many UI packages already include their own progress bar. 

Good point! And who still really wants it from Inertia can use core-independent [inertiajs/progress](https://github.com/inertiajs/progress) with no hustle (but still stuck on the abandoned `nprogress`).
