### ISSUE TITLE
Partial reloads do not play well with Laravel validation

### ISSUE THREAD

**Issue by Erik-Jonker** [inertiajs/inertia#205]
The errors are not thrown in the error bag when validation fails in the controller

**Laravel**
```php
public function update(Request $request){
  $request->validate([
    'name' => 'required' //<-- if this fails
  ]);
  return redirect()->back();
}
```

**Vue**
```javascript
this.$inertia.post(this.$route('routename'), {}, { //Sending empty data to trigger validation fail
  preserveState: true,
  preserveScroll: true,
  //only:['myVar']
}).then(()=>{
  console.log(this.$page.$errors); //<-- Empty if I specify "only", otherwise it works perfectly
});
```

**Comment by claudiodekker** [comment]
Hi,

Are you sure you're reading the correct errors property?:
```diff
- this.$page.$errors
+ this.$page.errors
```
(As of `inertiajs/inertia-laravel` `0.2.9`, the errors property is automatically mapped to `this.$page.errors`)

---

Another problem _might_ be related to the promise: 

The way that Inertia works, is that once [any `$inertia.visit` helper (`$inertia.visit`, `$inertia.get`,`$inertia.post`, etc.) ](https://inertiajs.com/requests)gets used and a response to the request comes back, Inertia (under the hood) updates the current "page" component. 

As a result, it _might_ be (I'm not 100% sure on the next part), that the `this` reference inside your chained `.then()` could still be referring to the 'old' page component state.


In either case, what I recommend to do & what should work, is to write your page in such a way that it contains both states. Something along these lines:
```js
<input type="text" v-model="name" name="name" />
<span v-if="$page.errors.name" class="error">{{ $page.errors.name }}</span>

// ...

this.$inertia.post(this.$route('routename'), {}, {
  preserveState: true,
  preserveScroll: true,
});
```

Hope this helps!

**Comment by Erik-Jonker** [comment]
Thanks for the tips!

I've added a small screenshot of my `console.log(this.$page)` which shows the response with $errors 

![image](https://user-images.githubusercontent.com/20435798/92594978-f0b1da00-f2a3-11ea-9d76-e495cbd64334.png)

I did check though, we are still using 0.1.9 so perhaps that could be the problem...

I don't think it is related to the promise because I have some other code inside of the promise that definitely refers to the new component state.

**Comment by claudiodekker** [comment]
Alright, interesting. I'll do some more digging into this hopefully later today to see if I can replicate this.

Thank you for reporting this!

---

Extra info regarding the built-in `errors` feature: 
> Inertia.js now automatically shares validation errors (#135) via the errors prop. Previously you had to manually share these in your app service provider ... (read more: https://github.com/inertiajs/inertia-laravel/releases/tag/v0.2.9)

**Comment by reinink** [comment]
So you're saying that when using partial reloads, you don't get your validation errors, yes?

Unless I am missing something, that seems like the correct behaviour to me. The `errors` prop is just like any other piece of data. If you submit a request saying you only want `myVar` back, the `errors` prop will be omitted.

If you need the validation errors as well when doing a partial reload, you'll need to specify that:

```js
only:['myVar', 'errors']
```

Am I understanding your problem correctly?

**Comment by Erik-Jonker** [comment]
Yes sir, you are understanding my problem correctly.

I see what you are saying, but hear me out. Should errors really be handled like a normal piece of data though? If I throw a validation Exception on the server I'd expect the error(s) to come through without having to "ask" for the errors.

This means that **all** the Inertia requests will always need an `['errors']` which could become quite redundant. Also, should one forget to add 'errors' to the partial reloads that means the request won't get errors sent back and my front-end will just "accept" that the validation passed and will indicate accordingly to the user (meanwhile there were validation errors and the data was not actually created / edited).

Not sure if I'm giving a strong argument or not, would love to hear your feedback! 
:)

**Comment by claudiodekker** [comment]
Hey, thanks for the feedback! 

I've closed this issue, because the original issue being discussed here is solved, as well as that there's now a specific issue regarding the feedback you've given (see #164). Feel free to weigh in over there if you want to! 👍
