### ISSUE TITLE
params in WhenVisible are not working at all

### ISSUE THREAD

**Issue by HichemTab-tech** [inertiajs/inertia#2064]
### Version:

- `@inertiajs/react` version: 2.0.0-beta.1

### Describe the problem:

the `params` attribute is not having any effect on the component WhenVisible.

### Steps to reproduce:

I tried to use the params to pass the cusrsor of pagination in infinite scrolling page, but the params are not working at all

```jsx
<WhenVisible
        always
        fallback={(
            <SpinnerWithRetry/>
        )}
        data='rooms'
        params={{
            data: {
                lastRoomId: rooms.data[rooms.data.length - 1].id
            },
            onBefore: async (data) => {
                console.log("onBefore", data);
            }
        }}
        children={null}/>
```

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @HichemTab-tech good catch, maybe is duplicated from https://github.com/inertiajs/inertia/issues/2025, i have made a PR to fix this one too

**Comment by HichemTab-tech** [comment]
Oh yes @PedroAugustoRamalhoDuarte Thanks for the PR, we really need that.
