### ISSUE TITLE
history.pushState() > history.back() > Cannot find module './undefined'

### ISSUE THREAD

**Issue by JayCasee** [inertiajs/inertia#209]
First of all, thank you for your great works regarding `inertia.js`.

I have some reasons that I need to have a custom 'history state' on my service.
 - A user may do some actions (e.g. click, drag and etc.) on a web page.
 - The each action changes the URL in the address bar.
 - The user can freely navigate backward & forward for checking the one's action histories.

For this, I'm using `history.pushState()` & `window.onpopstate = () => {}`, and this combination has no problem.

BTW, when the user clicks backward & forward, `./node_modules/@inertiajs/inertia/dist/index.js` generate this error on the console.

![image](https://user-images.githubusercontent.com/10718444/92842286-8ddc5200-f40d-11ea-8a06-069657af13cc.png)

I guess this is because of the route structure of `inertia.js`.

**Is there any way that I ignore (not to appear on the console) or fundamentally solve the problem...?**

**Comment by reinink** [comment]
Yeah, this makes sense, because Inertia.js is listening for `popstate` events, and is trying to handle them as if they were Inertia.js history navigation events. I'm not really sure you would go about mixing your own `pushState/popstate` events alongside an Inertia.js app. I think we would have to somehow check in the `popstate` event listener to see if it's an Inertia.js restore event. That might be all it takes. I'll do some testing with this to confirm. 👍

**Comment by reinink** [comment]
So, I think a better approach here is to actually do this check in your app, for your own `pushState`/`replaceState` calls. For example:

```js
window.history.pushState({
  nonInertiaVisit: true,
  // your other visit data
}, '', url)
```

Then, in your `popstate` handler, you can check for the presence of `nonInertiaVisit`, and prevent the default the default Inertia `popstate` handler:

```js
window.addEventListener('popstate', event => {
  if (event.state.nonInertiaVisit) {
    event.stopImmediatePropagation()
    // the rest of your handler
  }
})
```

I hope that helps! 👍

**Comment by deslittle** [comment]
I've just run into this same issue. Unfortunately it looks like `event.stopImmediatePropagation()` does not cancel the inertia event listener. As far as I can tell the error in the console does not have an impact on the behaviour of Intertia.

Perhaps Inertia could also check for `event.state.nonInertiaVisit` and cancel itself if true?

**Comment by Livijn** [comment]
I am experiencing an issue with this as well. I am using vue-router in my Inertia app (i know, it is anti-pattern). The same error gets thrown `Error: Cannot find module './undefined'` when pressing back/forward in the browser. I tried this with no luck:

```js
window.addEventListener('popstate', event => {
    event.stopImmediatePropagation()
})
```

Is there a way to disable Inertias tampering with history?

**Comment by Livijn** [comment]
So I added an event listener in my **app.blade.php** which fires before Inertia's event listener. Then I subscribe to the `beforePopstate` in my code to stop propagation or similar.

```js
window.addEventListener('popstate', function () {
  window.dispatchEvent(new Event('beforePopstate'))
})
```
