### ISSUE TITLE
[inertia-vue] Support for Vue 3 / Vue2 + Composition API

### ISSUE THREAD

**Issue by KingDoxik** [inertiajs/inertia#210]
I've started working with Inertia for the first time yesterday. I work a lot with vue and I have gotten used to using the new composition api. I've been trying to get it up and running with Inertia but I couldn't find any information about it. Is it currently supported? If so, would it be possible to update the docs with some sort of setup guidlines. If it is not supported, are there any plans to for the future?

**Comment by reinink** [comment]
Sorry, no, Vue 3 and the composition API are not supported yet, but there is absolutely plans to support it in the future. Stay tuned! 👍
