### ISSUE TITLE
Lazy sharing

### ISSUE THREAD

**Issue by IP-Developer** [inertiajs/inertia#213]
I can't get to understand what is the point of having lazy data sharing with closures, if those are always evaluated and sent to the client. What am I missing?

There is no difference in behaviour when using this:
```
Inertia::share(
[
	'auth' => function ()
	{
		return
		[
			'user' => Auth::user() ?
			[
				'id' => Auth::user()->id,
				'name' => Auth::user()->name,
			] : null
		];
	}
]);
```

or this:
```
Inertia::share(
[
	'auth' => 
	[
		'user' => Auth::user() ?
		[
			'id' => Auth::user()->id,
			'name' => Auth::user()->name,
		] : null
	]
]);
```

**Comment by IP-Developer** [comment]
Ok, I found out what I was missing. Actually there is a **big** difference in behaviors when using lazy sharing. First of all, `Auth::user()` is not yet instantiated in the service provider (don't ask me how I missed that 🤦 ). Next, the closure is evaluated **on response**, this means it is evaluated when calling `Inertia::render` in controller method.

**Comment by reinink** [comment]
Yup, your understanding is correct...using a closure is both useful for partial reloads, and it's useful when the data you need isn't ready yet, ensuing it's evaluated as the last possible moment (in the response). 👍
