### ISSUE TITLE
Laravel / Inertia responds a 419 response, but still processes my submission

### ISSUE THREAD

**Issue by Drillan767** [inertiajs/inertia#219]
Ok so I have seen quite a lot of similar issues, yet I don't know if I missed something, so don't hesitate to close this if I missed something obvious.

As said in the title, I have a form that I submit by doing the following:

```
// this.newCategory is my Inertia form
submitCategory() {
    this.newCategory.color = this.color.hex;
    this.newCategory.icon = this.$refs.icon.files[0]
    this.newCategory.post('/admin/category/add', {
        preserveScroll: true
    },
    ).then(() => {
        if (! this.newCategory.hasErrors()) {
            this.createCategory = false;
      }
    })
},
```
Meanwhile, this happens in my controller:

```
public function store(CategoryRequest $request)
{
    $category = new Category();
    foreach (['title', 'description', 'color'] as $field) {
        $category->$field = $request->get($field);
    }
    $category->save();

    return Redirect::route('category.all', ['categories' => Category::all()]);
}
```
Oh and this is my boostrap.js file (the relevant part):

```
window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

What's really odd is that when I submit my form, it's getting processed. However, I'm getting an XHR error related to the 419 that displays in my console... once I receive my controller's response. And my element is added to the database.

Here is the 419 error's how it's getting displayed)

![fetch](https://user-images.githubusercontent.com/16261166/93392017-60116600-f870-11ea-9a80-72123a4116ea.png)

And here is the error's detail:

![heasders](https://user-images.githubusercontent.com/16261166/93392088-7a4b4400-f870-11ea-97ce-8febc6570512.png)

So... either I'm doing something wrong, or I just missed something. But I didn't touch the bootstrap.js settings because it was written nowhere that I needed to do so, [this page](https://inertiajs.com/forms) tells me that I'm doing the right stuff.. So, what's happening?

Feel free to ask me for some more files if needed

**Comment by Drillan767** [comment]
In the mean time, I moved my form in a template to win space and avoid code duplication, and now it seems to work correctly. Welp.

**Comment by reinink** [comment]
Have you seen the CSRF protection section of [this page](https://inertiajs.com/security)? Almost all CSRF token issues in Inertia.js are the result of including the CSRF meta tag in your template. It cannot be there, otherwise you'll get errors. Simply remove it. Laravel and Axios automatically handle this for you. 👍

**Comment by Drillan767** [comment]
How come I didn't ever see this page before! Thanks for the head's up, I removed it!
