### ISSUE TITLE
What would be a way to redirect to a page with a success message?

### ISSUE THREAD

**Issue by Drillan767** [inertiajs/inertia#226]
Hello,

I have this CRUD that I setup, but I can't manage to display correctly any message transmitted to the front.

For example, I have this function:

```php
/**
 * @param UpdateCategoryRequest $request
 * @return RedirectResponse
 */
public function update(UpdateCategoryRequest $request)
{
    $category = Category::find($request->get('id'));
    $this->handleCategories($request, $category);

    return Redirect::route('category.all',
        ['categories' => Category::all()]
    )->with('success', 'La catégorie a bien été mise à jour.');
}
```

And, in my layout, I have this component:

```jsx
<alert-bag v-if="$page.success" :type="'success'" :title="'Opération réussie'" :message="$page.success" />
```

That will then display a nice alert sign containing whatever message I want to display.

##### However :

* When using Laravel's function of redirection, I get no message.
* Using `Inertia::render('My/Template')->with('some', 'incredible message');` will however work
* Using it after submitting a form will display a modal, the same one that get displayed when getting a 500 response, but completely white.

I could use a 3rd party library to display these messages, but I'm not in found of the idea. How should I proceed?

Thank you all in advance

**Comment by pedroborges** [comment]
Since you flashing a `success` message, you can access it with `$page.flash.success`. See the [docs](https://inertiajs.com/shared-data#flash-messages) for flash messages in Inertia.

**Comment by Drillan767** [comment]
Hello, thank you for your quick reply, however I found the documentation to be quite incomplete about this particular subject. I managed to make my messages getting displayed, but I had to rely on the "PingCRM" repository to make it work. Still, thanks a lot for making me look at the right place!

**Comment by yashiroiori** [comment]
Hi.
I try to show a Toast message instace of html alert, if use html alert it's work perfect, the toast alert only work when use redirect back in Laravel but not work if use redirect to route into Laravel

Component
![image](https://user-images.githubusercontent.com/17031855/99848653-c56b2700-2b3f-11eb-98d2-8349fdcf3752.png)

Redirect back work toast and html alert
![image](https://user-images.githubusercontent.com/17031855/99848873-2e529f00-2b40-11eb-9ee5-579fdec4b4a5.png)

But into redirecto to route not work only show html alert
![image](https://user-images.githubusercontent.com/17031855/99848915-3dd1e800-2b40-11eb-9366-7bfc31b5b7df.png)
