### ISSUE TITLE
How to mutate/transform page props to add interface relevant data?

### ISSUE THREAD

**Issue by aske-cph** [inertiajs/inertia#238]
Say you have a blog and you want each blog post received from the backend routes to have some extra properties relevant to how the user interface works, but irrelevant to everything else for example an editor-instance, "is_active" and an "is_expanded" property.

As far as i can se all props can be blanket modified : https://inertiajs.com/transforming-props

But how would one go about doing different kinds of array transformations on different pages, and how do you modify the props array in the first place?

In a regular old API you can append the extra frontend relevant properties to each item like "is_active", "is_open" when transforming the request in Vuex with mutators - stuff that should be removed again before going back to the server.

Maybe one should not do this at all, and instead create a prop array copy in the component of equal length with the relevant data - but this also seems convoluted?

Am thinking about this in the wrong way?

**Comment by reinink** [comment]
So generally speaking, with Inertia.js, you want to avoid transforming the props client-side as much as possible. The transforming props feature really exists for situations like converting the default `errors` object into some type of JavaScript class.

Instead, I think it's better to prepare your data server-side. From there, you can always do page-specific transformations within your components, or via helpers.

I've been building Inertia apps for almost two years now, and I really don't run into situations where this approach doesn't work. That said, if you have a situation, please do share, and I'll do my best to help explain how I'd handle that. 👍 

Closing this, as it's not really an "issue" with the library. That said, feel free to comment further. 👍
