### ISSUE TITLE
Handle Custom Exceptions

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia#250]
Hi,
It's there any way to handle custom expections throwed by a specific function that doesn't have a status like 503, 500 etc. (so I can handle like [here](https://inertiajs.com/error-handling))?

Example:
![image](https://user-images.githubusercontent.com/8333004/95603374-7917cc00-0a56-11eb-9ba0-f2f304d51fa5.png)
I've this custom exception in my register function that checks if an organization exists. But when i return it, it show my the exception with Ignition in a modal.
Is there any way to get it back to my Vue component?

**Comment by lucaros97** [comment]
Ok resolved using the Error Handling provided by @reinink in the Inertia site. Just added a custom check if the class of the exception it's the same of requested, in this way:
```php
if (get_class($exception) == 'App\Exceptions\CannotCreateUser') {
    return back()->withErrors(['organizations' => true]);
}
```

**Comment by claudiodekker** [comment]
Hi, great that you solved it! 

Another way to do this is inside the exception handler. That way, you won't have to do this check everywhere, and won't need to do a try-catch and `get_class` check yourself. In addition, you get the benefit of still being able to catch the error first using something like what you're doing yourself, so you can do something different from the default in specific scenarios.

https://laravel.com/docs/8.x/errors#rendering-exceptions
