### ISSUE TITLE
Promise deprecation warning triggers error in some situations

### ISSUE THREAD

**Issue by klaasgeldof** [inertiajs/inertia#260]
A Proxy is used to show a deprecation warning and return the original value:

https://github.com/inertiajs/inertia/blob/7f68b3e113571a9e1de150eab16db668a480173b/packages/inertia/src/inertia.js#L192

When you do a function call on the returned object, this works fine. But if you access a property, for example:

```js
this.$inertia.visit('...').foo
```

then you get the following error:

```
TypeError: Cannot read property 'bind' of undefined
```

I constantly have this error in my new app, where I use the Element framework and have things like this:

```html
<el-button @click="$inertia.visit('...')">Click Here</el-button>
```

I don't know what that framework does on the `click` event. I guess it's checking the returned result for stuff and tries to access properties. And these accesses trigger the error above...

Searched around on the topic, and it should be resolved when you change that line to:

```js
return Reflect.get(...arguments)
```

**Comment by reinink** [comment]
Okay I think I have this fixed, if anyone wants to review/test my PR: https://github.com/inertiajs/inertia/pull/262
