### ISSUE TITLE
Making Progress bar optional

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#267]
Let's have something like 
`
showProgress:false
`

Use Case: I want to mark a notification as read, The user should not see a progress bar every time he clicks a notification.

[Issue 124](https://github.com/inertiajs/inertia/issues/124) could not provide a use case, so I did, cause I've been looking for a way to do this, the only other way I thought of was to make my own ajax requests, not even sure Inertia won't catch that.

But I'm open to alternative Ideas please. I just want my users to click a notification in my react app, and i can update it as read in the backend. Displaying a Progressbar and even a spinner in this instance is really ugly.

**Comment by claudiodekker** [comment]
Closing this issue in favour of the already-existing #124, as there is already a discussion ongoing there.
