### ISSUE TITLE
Change or remove Inertia.replace()

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#292]
I think we need to change or remove the `Inertia.replace()` method, because it's kind of confusing:

1. This method signature is different than the other methods, in that it doesn't have a second argument for `data`.
2. This method arbitrarily sets `preserveState: true`.
3. The amount of times you need to set `replace: true` is actually very rare, since Inertia automatically does this for visits made to the same URL.

It's honestly better to just use one of the other methods:

```js
//  Before
Inertia.replace('/users', { data: { search: 'John' } })

// After
Inertia.get('/users', { search: 'John' })

// And if you need state preserved:
Inertia.get('/users', { search: 'John' }, { preserveState: true })
```

I think this is much more clear. 👍 

The options:

1. Just remove it, and recommend using another method like `Inertia.get()`.
2. Update the method signature to `Inertia.replace(url, data, options)` and remove setting `preserveState: true`.

Since it's a breaking change either way, my vote is to just remove it. We can start with a deprecation warning.

**Comment by Lowriider** [comment]
Hi, so will you remove it or update it ? 2years later replace still working for me but got issues with get -> replace and preserveState doesn't work for me on Laravel 8
