### ISSUE TITLE
Mistake in documentation - laravel middleware

### ISSUE THREAD

**Issue by rst630** [inertiajs/inertia#298]
https://inertiajs.com/forms#server-side-validation

```
class HandleInertiaRequests extends Middleware
{
    public function share(Request $request)
    {
        return array_merge(parent::share($request), [
            'errors' => fn () => $request->session()->get('errors')
                ? $request->session()->get('errors')->getBag('default')->getMessages()
                : (object) [];
            },
        ]);
    }
}
```

![image](https://user-images.githubusercontent.com/644549/97459185-15563400-196e-11eb-9133-6b7970a3258e.png)

Also as of documentation I always get 302 from laravel validator

**Comment by reinink** [comment]
Good catch, this has been fixed: https://github.com/inertiajs/inertiajs.com/commit/b3f3b1f6983a18dd6caaa6b2fe9a167b36d28a61

> Also as of documentation I always get 302 from laravel validator

This is normal behaviour, as explained on that [same page](https://inertiajs.com/forms#server-side-validation). Laravel automatically redirects (302) back to the same page that you're on, passing through the validation errors in the session.

**Comment by rst630** [comment]
What I need to do if my form in modal and it's xhr request and I want if was errors - show it in same modal w/o redirect?

**Comment by reinink** [comment]
Then just use a regular xhr/fetch request/response, instead of using an Inertia request/response. I actually just [tweeted about this](https://twitter.com/reinink/status/1321440632683040768) earlier today.
