### ISSUE TITLE
Detect cancelled Events

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#302]
Lemme just throw the whole thing here.
```
		Inertia.post(
            route("contact.message"),
            { ...data, _error_bag: "contact" },
            {
                preserveScroll: true,
                onBefore: () => this.confirmAction,
                onStart: () => this.load(true),
                onFinish: props =>
                    this.load(false) && console.log("props", props),
                onSuccess: page => {
                    const errors = page.props.errors.contact;
                    errors && setErrors(errors);
                },
                onCancel: () => alert("You cancelled the Request")
            }
        );
```

my `onBefore: () => this.confirmAction,` returns false, to cancel the request.

How do I detect that the request was cancelled. because the 
`onCancel: () => alert("You cancelled the Request")` did nothing.
Thanks @reinink

**Comment by reinink** [comment]
The `onCancel()` event and callback are only called for visits that have actually started. If you prevent the visit by returning `false` from the `onBefore()` method, the visit never starts. You'll notice that the `onStart()` callback is also not called when you do this.

This is the desired behaviour. 👍

**Comment by anubra266** [comment]
Okay. Thanks That means the `alert("You cancelled the Request")` has to be sent in the confirmAction method

**Comment by reinink** [comment]
Yes, that's correct.

**Comment by anubra266** [comment]
Thanks a lot. I've asked too much questions today. Feel like I'm disturbing. Sorry for that.

**Comment by reinink** [comment]
All good, thanks for your consideration. 👍

Also, these kind of questions are often better asked on [our Discord channel](https://discord.gg/gwgxN8Y).

**Comment by anubra266** [comment]
Wow! didn't know about the channel. Thanks

**Comment by claudiodekker** [comment]
One thing I'd also like to add to @reinink's recommendation, is that the Discord is also by far the better place for questions. The primary reason is that there's lots of people from the Inertia community helping each other out pretty much 24/7.

Another reason is that by having a separate place for questions, it allows us (the maintainers) to have a better overview of actual bug reports, issues or feature requests that are coming in, and to be right on top of it when something important gets reported. 👍

**Comment by anubra266** [comment]
@claudiodekker Thanks, I understand, already joined the Channel
