### ISSUE TITLE
useRememberedState does not work - React

### ISSUE THREAD

**Issue by anubra266** [inertiajs/inertia#308]
I don't think it caches unless I'm doing it wrong.
```
const [data, setData] = useRememberedState({ data: '' });
<input value={data.data} onChange={e=>setData(d => ({ ...d, data: e.target.value }))} />
```
after renavigation. the state is always reset.
Thanks @reinink

**Comment by claudiodekker** [comment]
Hi,

The `useRememberedState` hook works/is exactly the same as the `preserveState` feature that we discussed earlier over here, so I believe that should answer your question: https://github.com/inertiajs/inertia/issues/301

Hope this helps!

**Comment by reinink** [comment]
@anubra266 Be aware that this only works for HISTORY navigation, not new navigation.

Meaning you fill in a form (or whatever), and this data is saved to the history state, and then when you navigate away, but then hit back in the history, the data is repopulated.

**Comment by anubra266** [comment]
Oh @reinink I understand now.

**Comment by reinink** [comment]
Okay excellent. I thought you maybe were trying to use it in the same way you were trying to use the "preserve state" feature...as a way to keep state in local memory. That's not what this is for. It's for keeping state in your history. 👍

**Comment by claudiodekker** [comment]
Apologies, I misunderstood the question, but yes, @reinink's correction just about covers it. 😅

**Comment by anubra266** [comment]
Thanks @reinink and @claudiodekker
