### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by xoxoj** [inertiajs/inertia#31]
<inertia-link class="flex items-center group py-3" :href="route('contacts')">

**Comment by xoxoj** [comment]
`<inertia-link class="flex items-center group py-3" :href="route('contacts')">`

**Comment by MichaelDeBoey** [comment]
@xoxoj Thanks for taking your time to report a possible bug.

Can you please provide us with a reproduction repo so we have a little more context?

**Comment by reinink** [comment]
Closing this in favour of https://github.com/inertiajs/inertia-vue/issues/32
