### ISSUE TITLE
Conditional disable "Progress indicators" per manual visit request 

### ISSUE THREAD

**Issue by boxybird** [inertiajs/inertia#310]
In a few of my recent projects I've needed to create a way to poll for data on the backend (setInterval() every 15 secs), and so far `Inertia.reload({ only: ['some_data'] })` has been working great!

However, one UX issue I've run across is every time the `Inertia.reload(...)` fires, the progress bar shows and feels a bit odd.

I'm aware this is intended behavior and could be avoided using a standard XHR/axios request, but in the spirit of Inertia, I'm trying to avoid creating as many REST API endpoints as I can.

What does everyone think of having an option to run a "silent" low priority XHR request, i.e. `progressIndicator: false`?

Hypothetical:
```php
Inertia::share([
    'notification_count' => Inertia::lazy(function () {
        return auth()->user()->notifications()->count();
    }),
]);
```
```js
setup() {
    const page = usePage()
    const notificationsCount = ref(0)

    watch(page.props, () => {
      notificationsCount.value = page.props.value.notification_count
    })

    onMounted(() => {
      setInterval(() => {
        Inertia.reload({ 
             only: ['notification_count'],
             progressIndicator: false <- Maybe something like this
        })
      }, 15000)
    })
}
```

**Comment by boxybird** [comment]
Not sure if the best solution, but this works:

```js
import { Inertia } from '@inertiajs/inertia';
import NProgress from 'nprogress'

Inertia.on('start', ({ detail: { visit } }) => {
  if (!visit.hasOwnProperty('progressIndicator') || visit.progressIndicator) {
    NProgress.start()
  }
})
```
```js
Inertia.reload({ 
    only: ['notification_count'],
    progressIndicator: false <- Maybe something like this
})
```

**Comment by anubra266** [comment]
This solution won't work in inertia 0.6.1.

**Comment by reinink** [comment]
For what it's worth, I would strongly recommend not making Inertia visits within `setInterval()` (polling). Only ONE Inertia visit can happen at a time. If you make a visit while another visit is in progress, the first one is cancelled.

Using regular xhr/fetch requests in these situations is the proper approach.

Inertia visits are for just that...making page visits, not as a way of loading additional data.

**Comment by boxybird** [comment]
> For what it's worth, I would strongly recommend not making Inertia visits within `setInterval()` (polling). Only ONE Inertia visit can happen at a time. If you make a visit while another visit is in progress, the first one is cancelled.
> 
> Using regular xhr/fetch requests in these situations is the proper approach.
> 
> Inertia visits are for just that...making page visits, not as a way of loading additional data.

I second this. It was my poor attempt at a solution.

**Comment by timothymarois** [comment]
@reinink Is there a way to disable the progress indicator on a per request basis? Because I'm finding more use-cases where this is valuable.

**Comment by reinink** [comment]
@timothymarois This is possible in v2 (currently in beta) via the `showProgress` visit option: https://v2.inertiajs.com/manual-visits

More info on v2 here: https://v2.inertiajs.com/upgrade-guide
