### ISSUE TITLE
Manually refreshing form data on successful submit

### ISSUE THREAD

**Issue by shealan** [inertiajs/inertia#314]
I'm using Inertia via the Laravel adapter with the following on a form page:

```
this.form.patch(route('record.update'), {
  preserveState: true
 })
```

When submitting a form this ensures that on a 422 error the invalid field values are preserved. This gives the user an opportunity to correct and resubmit.

However, I only want to preserve this state when a form is invalid. When a form is successfully submitted I want to reload the data as I am doing some subtle transformation on the backend.

Is there a way to `preserveState: false` on successful submits only?

**Comment by vortechron** [comment]
just redirect the user back to that page on the controller

```
$request->validate([
... your validateion ...
]);

... your controller action ...

return back();

```

if it doesn't meet your use case or doesn't work, try overriding onFail method of this.form

```
mounted() {
   this.form.onFail = () => { .... your custom action, reload page with preserveState false or whatsoever,,, }
}
```

i didnt try this, only brainstorming here

**Comment by shealan** [comment]
@vortechron thanks for the thoughts. I already have a redirect back.

I anded up using this solution and it worked nicely, but I wonder if there's a more simple way...?

```
  data() {
    return {
      form: this.$inertia.form(this.record, {
        bag: 'recordUpdate'
      })
    }
  },
  watch: {
    record: function (recordNew, recordOld) {
      this.form.setInitialValues(recordNew)
    }
  },
  methods: {
    submit() {
      this.form.put(route('actions.record.update'), {
        preserveState: true
      })
    }
  }
```

**Comment by reinink** [comment]
So, I'm not totally sure I'm following the use-case here. Normally you don't have to manually refresh the form after success, since that's the most up-to-date version...there is no need to refresh.

That said, there is sometimes clean up work you need to do on success (no validation errors). For example, maybe you want to reset a password field. In these situations you can simply check against your errors object to determine this:

```js
onSuccess: () => {
  if (Object.keys(this.errors).length === 0) {
    this.form.password = null
  }
},
```

Does that solve your issue?

**Comment by sebastiandedeyne** [comment]
`preserveState` accepts a callback for these kind of situations where you want to decide whether to preserve or not based on the response.

```js
this.form.patch(route('record.update'), {
  preserveState: page => page.props.errors.length > 0
})
```

This should solve your issue, feel free to ping back if you have any more questions!

**Comment by davidblanco-m** [comment]
> `preserveState` accepts a callback for these kind of situations where you want to decide whether to preserve or not based on the response.
> 
> ```js
> this.form.patch(route('record.update'), {
>   preserveState: page => page.props.errors.length > 0
> })
> ```
> 
> This should solve your issue, feel free to ping back if you have any more questions!

Thank you very much! In my case `page.props.errors` was returned as an Object instead of an Array, so this did the trick for me:
```
this.form.patch(route('record.update'), {
     preserveState: page => Object.keys(page.props.errors).length > 0,
})
```
