### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mwangaben** [inertiajs/inertia#318]
Please add typescript support as now i get weird errors like 

  `TS2339: Property '$inertia' does not exist on type 'ComponentPublicInstance<Readonly<{ errors?: any; }>, { form: TheForm; }, {}, {}, { createUser(): void; }, Record<string, any>, Readonly<{ errors?: any; }>, {}, false, ComponentOptionsBase<...>>'.`

On Vuejs app code like below 

` methods: {
            createUser() {
                this.$inertia.post('/users', this.form)
                // .then((data) => {}).catch(response => { })
            }
        }`

**Comment by sebastiandedeyne** [comment]
We'll gladly accept PRs that add TypeScript support to the Vue adapters :)

**Comment by reinink** [comment]
We plan to eventually add TypeScript support to Inertia. However, until then, this is managed by the community via PRs. Feel free to submit a PR to add this. 👍
