### ISSUE TITLE
Cannot resolve dependency during NPM install (Inertia & Inertia React)

### ISSUE THREAD

**Issue by fourstacks** [inertiajs/inertia#319]
Hi, I am running into the same issue seen in #299.  I read through the solution suggested by @claudiodekker but I'm not entirely sure that I understand the underlying problem or how the solution can work when using an automated build step on a server.

Here's a stripped back test case.

Create a directory and add the following package.json file:

```
{
  "name": "test-inertia",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@inertiajs/inertia": "^0.6.0",
    "@inertiajs/inertia-react": "^0.4.1",
    "@inertiajs/progress": "^0.2.2"
  }
}
```

Run `npm install`.

NPM will spit out the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-inertia@1.0.0
npm ERR! Found: @inertiajs/inertia@0.6.1
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   @inertiajs/inertia@"^0.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @inertiajs/inertia@"^0.5.0" from @inertiajs/inertia-react@0.4.1
npm ERR! node_modules/@inertiajs/inertia-react
npm ERR!   @inertiajs/inertia-react@"^0.4.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/xxxxx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2020-11-09T11_50_02_972Z-debug.log
```

The solution here is probably to ensure that the peer dependency in inertia-react is set to `"^0.6.0"`

https://github.com/inertiajs/inertia/blob/588ff6c4089dd8e9ad24b4b8d31513306506edf3/packages/inertia-react/package.json#L40

However I'm unsure whether this would be a breaking change?

NPM version: 7.0.3
Node version: 15.0.1

**Comment by awebartisan** [comment]
In `npm v7`

> The new peer dependency algorithm ensures that a validly matching peer dependency is found at or above the peer-dependent’s location in the node_modules tree.

So, `@inertiajs/inertia` peer dependency needs to be bumped up to `0.6.0` for sub-packages like `inertia-react`.

**Comment by StefanYohansson** [comment]
de facto this occurs to inertia-vue too. From now, following the getting started documentation https://inertiajs.com/client-side-setup leads to this errors.

**Comment by sebastiandedeyne** [comment]
All adapter peer dependencies have been update to the latest version!

**Comment by reinink** [comment]
Thanks for fixing this @sebastiandedeyne!

In hindsight, I should have made the peer dependency `^0.5.0|^0.0.0`. However, I like this solution...it keeps folks on the latest version of Inertia, which is good. 👍

**Comment by fourstacks** [comment]
Thanks @sebastiandedeyne, appreciate the fix!
