### ISSUE TITLE
[TypeScript React] Incorrect type for usePage hook?

### ISSUE THREAD

**Issue by stephensamra** [inertiajs/inertia#321]
Printing the object returned from `usePage` shows the structure:
```json
{
  "component": "...",
  "props": {},
  "url": "/",
  "version": "...",
  "scrollRegions": [],
  "rememberedState": {}
}
```
However, when trying to access any property on this object, TypeScript fails to compile:
```ts
const page = usePage()
const props = page.props
// ==> Property 'props' does not exist on type 'PageProps'.
```
The type definition for `usePage` in `inertia-react/index.d.ts` is:
```ts
export function usePage<PageProps extends Inertia.PageProps = Inertia.PageProps>(): PageProps
```
Changing the type definition to...
```ts
export function usePage<Page extends Inertia.Page = Inertia.Page>(): Page
```
... seems to fix the error and VS Code autocompletion shows the correct types:

![image](https://user-images.githubusercontent.com/8583469/98881711-90e1d600-2482-11eb-90db-7bf5b545235b.png)

I could submit a PR with this change if you think it should be this way? I'm no TypeScript expert which is why I'm asking/checking if this is how it's meant to be.

Also, the `Page` type seems to be missing `scrollRegions` and `rememberedState` so I could include those in the PR, too.

Thanks for reading.

**Comment by sebastiandedeyne** [comment]
Hi @stephensamra!

Looks like the React typings are out of date with the most recent changes in Inertia.

Your suggested changes look good, could you send them over in a PR and tag me in it? Then I'll review & merge them asap.

Thanks!
