### ISSUE TITLE
onSuccess event is called even if i get 422 error

### ISSUE THREAD

**Issue by ZekiJohn** [inertiajs/inertia#325]
here is my code

    const createNewPage = (e, page_name) => {
        setSavingPage(true)
        e.preventDefault()

        Inertia.post(route('pages.store'), {name:  page_name}, {
            onSuccess: () => {
                // this runs even if i get 422 response 
            }
        })
    }

**Comment by reinink** [comment]
Yes, this is expected behaviour, since a `422` response is never sent. Please see here for a full explanation: https://github.com/inertiajs/inertia-laravel/issues/184
