### ISSUE TITLE
InertiaLink (React) and server rendered page (with small React component)

### ISSUE THREAD

**Issue by jaydiablo** [inertiajs/inertia#327]
We have a situation in an app that's being slowly migrated to React (and we're testing using Inertia for anything that has had the full page migrated to React already) where I tried to use `InertiaLink` to link out to an Inertia handled page from a React component that is used in the server rendered page (otherwise not React or Inertia).  Everything renders ok, but when clicking on the `InertiaLink` powered link an error is thrown:

>Uncaught (in promise) TypeError: this.resolveComponent is not a function

I see Inertia make an XHR request for the destination with the `X-Inertia=true` header, which responds ok, but in this case, since the entire page wasn't rendered with React (or Inertia) I think it's trying to build a page component into a React/Inertia context that doesn't exist (again, this is a server rendered page that just has a small re-usable React component inserted into the DOM at a specific location, nothing is wrapped by the `InertiaApp` component in this situation).

This same component is used on other pages that **are** React rendered where it works fine (hence the reason that we'd like to continue to use `InertiaLink` here).

Is it possible for `InertiaLink` to detect whether or not it's in an Inertia context and use the Inertia XHR request if it is, but use a standard HTTP request if it's not?

For now we can just remove the `InertiaLink` component and replace it with a normal `a` link, but then we lose the Inertia magic on those navigations that are fully Inertia.

Happy to provide other details where I can. I might be able to put together a small demo if the situation isn't clear from the description.

Thanks!

**Comment by sebastiandedeyne** [comment]
Hey @jaydiablo!

This sounds like a very niche problem. I'm not really keen to add checks to solve this just yet, and I believe it can already be solved in userland.

> Is it possible for InertiaLink to detect whether or not it's in an Inertia context and use the Inertia XHR request if it is, but use a standard HTTP request if it's not?

I suggest you create your own `InertiaLink` wrapper that does that check. Untested, but this should do the trick:

```js
// resources/js/components/InertiaLink.js

import { Inertia } from '@inertiajs/inertia'
import { InertiaLink as BaseInertiaLink } from '@inertiajs/inertia-react'

export default function InertiaLink({ href, className, children, ...props }) {
  // This is an implementation detail of Inertia, but a valid way to check if 
  // it's ready for use on the current page
  if (! Inertia.resolveComponent) {
    return <a href={href} className={className}>{children}</a>
  }

  return (
    <InertiaLink href={href} className={className} {...props}>
      {children}
    </InertiaLink>
  )
}
```

Does this solve your issue?

**Comment by jaydiablo** [comment]
@sebastiandedeyne thanks for the reply, I agree that this is probably an unusual edge case, but perhaps useful for people that are in our situation (migrating an existing server side application to React + Inertia.js).

Your code above does work, I just had to make a small modification:

```javascript
// resources/js/components/InertiaLink.js

import { Inertia } from '@inertiajs/inertia'
import { InertiaLink as BaseInertiaLink } from '@inertiajs/inertia-react'

export default function InertiaLink({ href, className, children, ...props }) {
  // This is an implementation detail of Inertia, but a valid way to check if 
  // it's ready for use on the current page
  if (! Inertia.resolveComponent) {
    return <a href={href} className={className}>{children}</a>
  }

  return (
    <BaseInertiaLink href={href} className={className} {...props}>
      {children}
    </BaseInertiaLink>
  )
}
```

(changed the component rendered to `BaseInertiaLink` from `InertiaLink` so it uses the alias defined on the import.)  

I'm also using Typescript, so had to ignore the `Inertia.resolveComponent` line since that's not exposed in the types and make a few other tweaks to make Typescript happy elsewhere. Ideally this should be temporary though. I'll keep an eye out in case something like this were to make it into a release so I can remove the override.

Thanks again.
