### ISSUE TITLE
Access this.$inertia inside Composition API vue 3

### ISSUE THREAD

**Issue by carpad88** [inertiajs/inertia#329]
Hi people,

I'm new using inertia, so I get up an app with `Laravel-Inertia-Vue3`. 

I've been playing around with the Composition API but I don't know how to access `this.$inertia` inside the set up method. 

The code is:

```
<script>
import {reactive} from "vue";

export default {
    setup() {
        const data = reactive({
            form: {
                first_name: null,
                last_name: null,
                email: null,
            },
        });

        const submit = () => {
            this.$inertia.post('/form', data.form)
        }

        return {
            data,
            submit
        }
    }
}
</script>
```

But when calling the submit method I got `Uncaught TypeError: _this is undefined`.

**Comment by reinink** [comment]
When using the Vue 3 composition API, `this` is `undefined` within the `setup()` method. Meaning you cannot access `this.$inertia`. In these situations, you need to simply import Inertia instead.

```js
import { Inertia } from '@inertiajs/inertia'

Inertia.post('/form', data.form)
```

**Comment by carpad88** [comment]
@reinink thanks a lot, now is working as expected.

Is there any difference in using `Inertia.post('/form', data.form)` over `axios.post('/form', data.form)` with the Composition API?

If I use `this.$inertia` on the Options API and for example I make `dd(request()->all()` on the server side,  I got a modal with the result on the client side (see image).

<img width="1792" alt="Screen Shot 2020-11-16 at 14 10 36" src="https://user-images.githubusercontent.com/13703238/99303003-d18c7700-2815-11eb-8875-1cb88ffeecff.png">

But when I use `Inertia.post('/form', data.form)`, there isn't modal I have to check out the response on devtools

**Comment by arukompas** [comment]
@carpad88 - hey! 

`Inertia.post('/form', data.form)` expects a special InertiaResponse from the server and if it doesn't get one, it shows the received contents in a modal. This can be helpful when developing/debugging and tells you that you did NOT return a proper InertiaResponse, like so:
```php
public function index()
{
    return Inertia::render('Accounts/Index', [
        'accounts' => request()->user()->accounts,
    ]);
}
```

calling `dd(...)` in a controller does NOT return an InertiaResponse, but rather a regular Laravel Response.

meanwhile with `axios.post('/form', data.form)` you are responsible for handling the response yourself and Inertia doesn't interfere in any way.
