### ISSUE TITLE
Webpack is trying to resolve 

### ISSUE THREAD

**Issue by rick20** [inertiajs/inertia#332]
I'm creating a package as well as the main app.
The component pages in the package can be customised from the main app.

I initiate my app like this:

```js

const el = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(el.dataset.page),
      resolveComponent: name => {
        try {
          return require(`./Pages/${name}`).default
        } catch (error) {
          try {
            name = name.replace('@packit::', '')
            return require(`@packit/Pages/${name}`).default
          } catch (error) {
            return require(`@packit/Pages/Auth/Login`).default
          }
        }
      }
    }
  }),
}).$mount(el)
```

However when i run npm run dev it gives me warning

```
 warning  in ./resources/js/app.js

Module not found: Error: Can't resolve './Pages' in '/packit/resources/js'
```

I wrapped the require() with try catch but still no changes.

The odd thing is that it works fine in my macos catalina, but it fails in 2 servers.

I did `rm -rf node_modules/ && npm cache clear --force && rm -f package-lock.json && npm install && npm run dev` but still no changes as well.

Is this the correct way to make the customisation works?
Does the webpack supposed to be resolving the require() on npm run dev?
Thank you

npm: 6.13.4
node: 12.15.0

**Comment by sebastiandedeyne** [comment]
What does your file structure look like?

And what exactly do you mean with "I'm creating a package as well as the main app", a JavaScript package or a PHP package? Do you have any more snippets that clarify this?

Note that `try/catch` only works for runtime errors. `require()` is a special Webpack feature which is evaluated at build time, so `try/catch` isn't able to help.

**Comment by sebastiandedeyne** [comment]
Regarding this:

> The odd thing is that it works fine in my macos catalina, but it fails in 2 servers.

This often happens because macOS is case-insensitive. Are you sure there are no casing issues? Is the directory named `pages` or `Pages`? A mismatch there could be causing this error.

**Comment by rick20** [comment]
Hi @sebastiandedeyne thank you for your enlightenment...I can confirm it works now!
All this time, it was just because of one wrong first-letter case in one of the folder name :( 

> And what exactly do you mean with "I'm creating a package as well as the main app", a JavaScript package or a PHP package? Do you have any more snippets that clarify this?

What I mean is, it's more like ```laravel/laravel``` as the main app and the ```laravel/framework``` as a package but with this package provides both the PHP and Vue components for basic functionalities.

But the main app has the ability to customise/extend/override what the package has....including the vue component.
That's why in my ```resolveComponent()``` (in main app), I did a lookup first on the main app assets, and fallback to the package assets.
There will be more main apps that will use the package, but the customisation on main app wont be that much.

I dont separate the php and vue package, at least for now, since we dont have enough manpower to maintain both packages in separate repo. I know this is a bad practice, but putting it all together in 1 repo will give us easier workflow to run for now.

However I'm just curious for a better way to make the ```resolveComponent()``` to resolve from other js packages too. Do you have any idea on this?

Thank you :)

**Comment by sebastiandedeyne** [comment]
With that explanation, I think the general idea of the original snippet looks good!

You might be able to clean up the `try/catch` shenanigans with Webpack's `require.context` API, since you can do proper checks if a module exists or not.

https://webpack.js.org/guides/dependency-management/#requirecontext

This is untested, and probably needs some additional tweaks to work.

```js
function resolveComponent(name) {
  const app = require.context('./Pages');
  const packit = require.context('@packit/Pages');

  if (app.keys().includes(name)) {
    return app(name);
  }

  if (packit.keys().includes(name)) {
    return packit(name);
  }

  // …
}
```
