### ISSUE TITLE
Inertia link wont go to next component

### ISSUE THREAD

**Issue by devlloedy** [inertiajs/inertia#345]
Hello i am wondering how can i go to my next component. Here is my code it doesn't work. I am using vuex and axios thanks

![image](https://user-images.githubusercontent.com/75713279/101592273-ef21ba80-3a28-11eb-9afc-e331dc4435ef.png)

**Comment by sebastiandedeyne** [comment]
I think `@click.prevent` is going to prevent the `button` event from bubbling up to the `inertia-link` component, so the visit handler doesn't get fired.

What does `createPatientProfile` do? Based on this small snippet, I think you want something like this:

```vue
<template>
  <button class="btn-indigo" type="button" @click="createPatientProfile(formPatient)">
    Submit
  </button>
</template>
<script>
export default {
  // …

  methods: {
    createPatientProfile(data) {
      this.$inertia.post('/patients', data, { preserveState: true })
    }
  }
}
</script>
```

The `/patients` `POST` endpoint then needs to return a redirect to `/partients/card-info`.

Does that help? If it doesn't, please provide as much context as possible of what you're trying to achieve (routes, controllers, full components, etc.)

**Comment by devlloedy** [comment]
@sebastiandedeyne thank you! This is what I'm exactly looking for.
