### ISSUE TITLE
InertiaJs + Ionic response issue

### ISSUE THREAD

**Issue by Codcore** [inertiajs/inertia#348]
I am trying Inertia.js (Rails on backend) to get working with Ionic app. It actually works, but when I click Inertia link I got error message that response from server is not valid Inertia response - ***"All Inertia requests must receive a valid Inertia response, however a plain JSON response was received."***, however all Headers and response are look good and same app works as web app with Inertia. I can't figure out how why does Inertia consider that response not valid.

Here is error:
[![enter image description here][1]][1]

Response and request headers:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/XYPJm.png
  [2]: https://i.stack.imgur.com/t79U2.png

**Comment by reinink** [comment]
So, that modal is only shown if the response comes back WITHOUT `X-Inertia: true`. Are you 100% sure your headers are being set as you expect?

**Comment by reinink** [comment]
Closing this due to lack of response. Feel free to update it, and we can reopen. 👍
