### ISSUE TITLE
Can you rerender parts of a persistent layout?

### ISSUE THREAD

**Issue by amiranagram** [inertiajs/inertia#349]
First of all, I love the persistent layout feature and I don't wanna remove it.

The scenario: I have unread notifications in shared data and a notification dropdown in a persistent layout. When I click on any link inside the notification dropdown I send and additional `?read_notification=notification_id`. On the back-end side, I have a middleware that checks for the existence of read_notification param in URL query string and tries to find that notification and mark it as read. 

After the successful response the unread notifications are updated in shared data, but is there a way I could rerender that part of the layout as well? It stays the same until unless I go to a page with a different layout and than go back or I hit refresh.

**Comment by hotmeteor** [comment]
One possible solution would be to add a global event listener like:
```js
import { createApp, ref } from '@inertiajs/inertia'
import { Inertia } from '@inertiajs/inertia'

const app = createApp(/*...*/);

app.config.globalProperties.notification_count = ref(0)

Inertia.on('success', (event) => {
    this.notification_count = event.detail.page.props.notification_count
})
```
And then in your `Layout.vue` file you just make sure you're referencing the count as a computed value or something.

It does seem like it should just update though.
