### ISSUE TITLE
ask for help: May I keey url static when make a inertia get reqeust ?

### ISSUE THREAD

**Issue by smartymoon** [inertiajs/inertia#350]
sometime, I don't want url changed when makeing a inertia request. such as get a pagination list on my phone.

**Comment by reinink** [comment]
If you'd like to keep the exact same URL but still make a server request for more data, I'd recommend just making a regular fetch/xhr request to get and update this data.

Alternatively, you could use a header to set the pagination page number, and still use Inertia, but that's definitely not a very conventional way to go.

Personally, I like when the URL changes when paging through a paginated list, as it allows me to go forward/back. You can see examples of that in Ping CRM, our demo app: https://inertiajs.com/demo-application

**Comment by smartymoon** [comment]
thank you
