### ISSUE TITLE
@inertiajs/inertia typings are outdated

### ISSUE THREAD

**Issue by snaptopixel** [inertiajs/inertia#353]
We use our own frontend with Inertia (web-components/StencilJS) and I recently noticed the typings are not in sync, specifically `Inertia.init` doesn't have types for `transformProps` and our app breaks
```
Uncaught (in promise) TypeError: n.transformProps is not a function
```

**Comment by snaptopixel** [comment]
Wait, I thought the whole lib was typescript? Did you guys go vanilla js? Madness.

**Comment by snaptopixel** [comment]
@sebastiandedeyne can you shed any light on this? What's the process for updating the types?

**Comment by snaptopixel** [comment]
@reinink @sebastiandedeyne I'm working on a TS fork now fwiw

**Comment by reinink** [comment]
Hey, just so you know @snaptopixel, one of the items on my todo list is to convert Inertia.js to Typescript. This is something I've wanted to do myself, as I need to learn it in the process. Meaning, if you fork and convert it, don't be alarmed if I don't merge that in. It's really something I want to do myself. That said, I'm sure it would be a helpful reference. I hope that makes sense.

Right now all the typings are managed by the community. Meaning, if they are out of date, the best thing to do is submit a PR to update them. Once we officially convert to Typescript, that problem will go away! 👍

**Comment by snaptopixel** [comment]
Thanks @reinink, I'm just about done so feel free to use as a reference or merge as-is once it comes out ;)
