### ISSUE TITLE
Error when making a request with JSON return

### ISSUE THREAD

**Issue by carlosalbertocruz** [inertiajs/inertia#369]
I'm trying to make a request to receive JSON data using axes and with this. $ Inertia.visit itself and I get this message in a popup:

All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.

**Comment by reinink** [comment]
Hello @carlosalbertocruz,

`Inertia.visit()` is intended for making Inertia visits, not plain JSON requests. If you'd like to make a standard XHR request, simply use XHR directly, or via a library like axios, or even fetch.

The docs have a note about this: https://inertiajs.com/forms#classic-xhr-submits
