### ISSUE TITLE
Add additional partial reload options

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#377]
Right now, to use partial reloads, you have the `only` option. By setting this, you *only* get the props you explicitly requested. 

```js
Inertia.visit('/whatever', {}, {
  // get all the default props (users and companies) and the optional categories prop
  only: ['users', 'companies', 'categories']',
})
```

However, especially with optional lazy props, it would be helpful to have a way of saying "I want all the default props, plus this optional lazy prop". In that case, a `with` option might be better:

```js
Inertia.visit('/whatever', {}, {
  // get all the default props and the optional categories prop
  with: ['categories']',
})
```

And sometimes, it might be nice to have an `except` option to get all the default props, except one specific one.

```js
Inertia.visit('/whatever', {}, {
  // get all the default props except for one
  except: ['companies']',
})
```

**Comment by sebastiandedeyne** [comment]
`with` is a reserved word in JavaScript, any other ideas?

Laravel sometimes uses `append` for these kind of things.

**Comment by reinink** [comment]
> `with` is a reserved word in JavaScript, any other ideas?

Does that matter? It would only be used as a property in the options object.

**Comment by sebastiandedeyne** [comment]
Whoops, you're right, guess my editor was warning me for nothing.

**Comment by ibrunotome** [comment]
> And sometimes, it might be nice to have an `except` option to get all the default props, except one specific one.
> 
> ```js
> Inertia.visit('/whatever', {}, {
>   // get all the default props except for one
>   except: ['companies']',
> })
> ```

I was opening an issue to discuss about a possible `except: ['translations']` but it seems to be on the plans 😄

**Comment by CeansBzh** [comment]
Hi, it doesn't seem that this functionnality has been implemented. It would be really useful in some cases.

Could this issue be reopened ?
