### ISSUE TITLE
Docs: Inertia.delete callback examples are outdated

### ISSUE THREAD

**Issue by j-codes-4** [inertiajs/inertia#378]
### Versions:

- `@inertiajs/inertia` version: 0.8.0
- `@inertiajs/inertia-vue` version: 0.5.0

### Describe the problem:

The callbacks are not being called when using an example from the docs Manual Visits page

### Steps to reproduce:

The following doesn't work on the latest version, it will send the delete request to the server, but no callbacks will be fired

Inertia.delete(`/users/${user.id}`, {
  onBefore: () => confirm('Are you sure you want to delete this user?'),
})

Changing it to the following will allow all callbacks to be fired.  The example above is missing the 2nd parameter.

Inertia.delete(`/users/${user.id}`, {}, {
  onBefore: () => confirm('Are you sure you want to delete this user?'),
})

I know this version was just released recently and the docs may not have caught up yet, but I ran into to this problem and thought I should share to hopefully help anyone who has the same issue.

Great job on inertia, thanks for making it

**Comment by claudiodekker** [comment]
Hi @j-codes-4,

You're absolutely right, the problem is that we haven't updated this part of the docs yet. 

The delete signature now accepts data as its second attribute, making its signature identical to all the other request methods. Passing in an empty object `{}` should be sufficient to solve your problem 👍

Hope this helps!

**Comment by reinink** [comment]
Yeah, changing the `Inertia.delete()` method signature was a mistake, and we're going to revert this change. We hadn't even included this in the release notes.

Already changed:
https://github.com/inertiajs/inertia/commit/0970f5fbf11dc300ea0341a5c82e5f857583a49b
https://github.com/inertiajs/inertia/commit/b73850628cf53b9f0741508459e81c82086aaf0f

We'll be releasing a bug fix shortly.
