### ISSUE TITLE
Security Vulnerability in Axios 0.20.x

### ISSUE THREAD

**Issue by jaydiablo** [inertiajs/inertia#379]
### Versions:

- `@inertiajs/inertia` version: 0.8.0
- `@inertiajs/inertia-react` version: 0.5.0

### Describe the problem:

Snyk is reporting that Inertia is installing a version of Axios that has a known security vulnerability: https://snyk.io/test/npm/@inertiajs/inertia/0.8.0

I have `axios` `0.21.1` specified in my deps, but that version isn't compatible with the one defined in Intertia's package.json. Output of `yarn why axios`:

```
=> Found "axios@0.21.1"
info Has been hoisted to "axios"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "504KB"
info Disk size with unique dependencies: "548KB"
info Disk size with transitive dependencies: "548KB"
info Number of shared dependencies: 1
=> Found "@inertiajs/inertia#axios@0.20.0"
info This module exists because "@inertiajs#inertia" depends on it.
info Disk size without dependencies: "500KB"
info Disk size with unique dependencies: "544KB"
info Disk size with transitive dependencies: "544KB"
info Number of shared dependencies: 1
```

I believe this just requires adding `^0.21.0` here: https://github.com/inertiajs/inertia/blob/master/packages/inertia/package.json#L31 but I'm haven't looked at what else changed from 0.20 to 0.21.

**Comment by jaydiablo** [comment]
#195 was re-opened due to the release of Axios 0.21.0, relaxing Axios dependency (again) would address both issues I believe.

**Comment by reinink** [comment]
Updated: https://github.com/inertiajs/inertia/commit/b7f1761374b1d66c60db7a523a7adc8889514889

Released: https://github.com/inertiajs/inertia/releases/tag/v0.8.1

**Comment by reinink** [comment]
Thanks for the reminder on this @jaydiablo!
