### ISSUE TITLE
Wrong laravel mix rewrite url path when place project in subfolder

### ISSUE THREAD

**Issue by hafizSiddiq7675** [inertiajs/inertia#381]
### Versions:

- `@inertiajs/inertia` version: 0.1.7
- `@inertiajs/inertia-react` version: 0.1.4

I have deployed laravel react application on the server, inside a folder namely patients/ so the complete url for the app is domain.com/patients 

app.js and app.css files are not found, I am facing a 404 error, because it is trying to serve files from domain.com/ instead of domain.com/patients/app.css and domain.com/patients/app.js if i change mix to asset or place mix inside asset then, all the other assets like 0.js, 0.css are not found, following is the my webpack.mix.js

`const cssImport = require('postcss-import');
const cssNesting = require('postcss-nesting');
const mix = require('laravel-mix');
const path = require('path');
const purgecss = require('@fullhuman/postcss-purgecss');
const tailwindcss = require('tailwindcss');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
  .react('resources/js/app.js', 'public/js')
  .postCss('resources/css/app.css', 'public/css/app.css')
  .options({
    postCss: [
      cssImport(),
      cssNesting(),
      tailwindcss('tailwind.config.js'),
      ...(mix.inProduction()
        ? [
            purgecss({
              content: [
                './resources/views/**/*.blade.php',
                './resources/js/**/*.js'
              ],
              defaultExtractor: content =>
                content.match(/[\w-/:.]+(?<!:)/g) || [],
              whitelistPatternsChildren: [/nprogress/]
            })
          ]
        : [])
    ]
  })
  .webpackConfig({
    output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
    resolve: {
      alias: {
        '@': path.resolve('resources/js')
      }
    }
  })
  .version()
  .sourceMaps();
`
I have also tried adding `mix.setResourceRoot('/laravel/public/');` at the end

**Comment by RobertBoes** [comment]
This seems more like something that would be caused by Laravel Mix, since Inertia doesn't serve any assets. This might solve your issue: JeffreyWay/laravel-mix#1026

**Comment by reinink** [comment]
Yeah, this isn't an Inertia issue.
