### ISSUE TITLE
On Finish Event details are null

### ISSUE THREAD

**Issue by MuhammadFaizanShakir** [inertiajs/inertia#385]
### Versions:

- `@inertiajs/inertia` version: 0.3.6
- `@inertiajs/inertia-vue` version: 0.2.4

### Describe the problem:

I am trying to add **Ng progress** on finish event but event details are always null. That why **InertiaProgress** was also not auto hiding when after success full visit. it always throws an error that says 

**`Uncaught TypeError: can't access property "visit", event.detail is null`**

### Steps to reproduce:
here is my app.js file 
**import NProgress from 'nprogress'
import { Inertia } from '@inertiajs/inertia'
import { InertiaApp } from '@inertiajs/inertia-vue';
import { InertiaForm } from 'laravel-jetstream';
let timeout = null

Inertia.on('start', () => {
    timeout = setTimeout(() => NProgress.start(), 250)
})

Inertia.on('progress', (event) => {
    if (NProgress.isStarted() && event.detail.progress.percentage) {
        NProgress.set((event.detail.progress.percentage / 100) * 0.9)
    }
})

Inertia.on('finish', (event) => {
    console.log(event);
    clearTimeout(timeout)
    if (!NProgress.isStarted()) {
        return
    } else if (event.detail.visit.completed) {
        NProgress.done()
    } else if (event.detail.visit.interrupted) {
        NProgress.set(0)
    } else if (event.detail.visit.cancelled) {
        NProgress.done()
        NProgress.remove()
    }
})**

**Comment by reinink** [comment]
This is because you're using Jetstream, which is on an older version of Inertia, which doesn't have the updated events. The finish event was fixed in Inertia [version 0.6.0](https://github.com/inertiajs/inertia/releases/tag/v0.6.0), so you'll need to be on that version. Fair warning, that can be hard, since it requires upgrading all of Jetstream as well.
