### ISSUE TITLE
Consider renaming the "useRememberedState" to "useRememberState"

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#387]
Right now the Vue adapters use the `remember` property, and the Svelte adapter uses a `remember` store. However, the React adapter uses a `useRememberedState` hook. I think it would be more consistent to call this hook `useRememberState`.

Ping @sebastiandedeyne for input.

**Comment by sebastiandedeyne** [comment]
Don't really have an objective argument against it, but `useRememberState` sounds odd to me.

How about `useRemember`? More consistent, more succinct.

**Comment by reinink** [comment]
Love it, of course `useRemember`. 👍 

I'll make this happen, but I'll keep `useRememberedState` for now, and throw a deprecation warning.
