### ISSUE TITLE
Lazily evaluation of preserveState using form helper hasErrors

### ISSUE THREAD

**Issue by ajnsn** [inertiajs/inertia#389]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:

At least for me the by @reinink  [described](https://twitter.com/reinink/status/1345386092875411456?s=21) lazy evluation of `preserveState` using form helper's `hasErrors` does not work as expected. This might be because `setPage` [is called before the form helper is recording any errors](https://github.com/inertiajs/inertia/blob/17e6c711d91d7ab33bd3557b032a8ddcac6b124b/packages/inertia/src/inertia.js#L252).

`hasErrors` works correctly in the `onError` callback.

### Steps to reproduce:

```js
data() {
    return {
        form: this.$inertia.form({
            name: null,
        }),
    };
},
methods: {
    submit() {
        this.form.patch(this.$route('profile.update'), {
            preserveState: page => {
                console.log({
                    errorProp: Object.keys(page.props.errors).length > 0,
                    hasErrros: this.form.hasErrors,
                });
            },
        });
    },
},
```

Outputs:
```js
{errorProp: true, hasErrros: false}
```

**Comment by reinink** [comment]
Interesting, @claudiodekker, haven't you done this (in CS)? 🤔

**Comment by claudiodekker** [comment]
@reinink Haha, I did, but only after you suggested the change, but it indeed apparently doesn't work as expected 😅  Here's what we were doing:

```js
{
  preserveScroll: () => this.form.hasErrors,
  preserveState: () => this.form.hasErrors,
}
```
