### ISSUE TITLE
preserveScroll not working on form helper.

### ISSUE THREAD

**Issue by santlalgodara** [inertiajs/inertia#392]
![image](https://user-images.githubusercontent.com/17198268/103502176-699df880-4e76-11eb-966b-f803b3ace579.png)

### Versions:

- `@inertiajs/inertia` version: #.#.#
- `@inertiajs/inertia-vue` version: #.#.#

### Describe the problem:
preserve scroll position not staying same. when form data returning from laravel after submitting scroll move to the top.

**Comment by claudiodekker** [comment]
Hi,

The form helper does not take a second argument (e.g. options) as part of the initialization step. 
Instead, pass in the options when you make the actual request later on `this.form.post('/foo', { preserveScroll: true })`
