### ISSUE TITLE
Started having problems with Redirect::back()

### ISSUE THREAD

**Issue by ThinkDevStudios** [inertiajs/inertia#416]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-react` version: 0.5.1

### Describe the problem:

Started having problems with Redirect:::back() after upgrading to the latest version. getting 404 errors mostly issues with XHR when using Redirect::back() or even Redirect::route(). This only happens when redirecting back from a post or put a response.

### Steps to reproduce:

Using the demo PingCRM-React. I upgraded the inertia js and inertia react version. Mostly following the instructions from the site. Had to Npm audit fix force due to Axios vulnerability.

**Comment by reinink** [comment]
This happens when the you don't have the Inertia middleware setup properly. Are you using Rails or Laravel? Ensure that you have the middleware setup properly. 👍

**Comment by ThinkDevStudios** [comment]
It's working now. I was using the demo app to react. the share data was placed on the app providers. that's why even though I have created the middleware. I did not put it on the kernel. but everything is working now. Thank you!

**Comment by reinink** [comment]
Excellent 👍
