### ISSUE TITLE
Issue using 'remember' since Inertia Form update

### ISSUE THREAD

**Issue by aryehraber** [inertiajs/inertia#417]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:

Upgraded our app to Jetstream V2 this morning, and as a consequence to the latest versions of Inertia and the Vue 2 adapter, and started seeing the following error:

```
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'serialize' of null"
```

### Steps to reproduce:

The below example should allow you to easily recreate the issue:

```
<script>
export default {
  data: () => ({
    foo: null,
  }),

  remember: ['foo']
}
</script>
```

---

I've been able to resolve the issue locally and will be submitting a PR shortly!

**Comment by reinink** [comment]
Hey thanks for reporting this, this has been fixed in #575!
