### ISSUE TITLE
Refactor to only named exports

### ISSUE THREAD

**Issue by MichaelDeBoey** [inertiajs/inertia#42]
My suggestion is to refactor both core and adapters to only have named exports.

I came across [this article](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html), when I started looking what's most used in the community.
When I looked into the React community I came across well know libraries which were 50-50 divided in the use of only named exports or having a default export too.

Only named:
- [`react-beautiful-dnd`](https://github.com/atlassian/react-beautiful-dnd/blob/master/src/index.js)
- [`react-dates`](https://github.com/airbnb/react-dates/blob/master/src/index.js)
- [`react-router`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/index.js)
- [`@reach/router`](https://github.com/reach/router/blob/master/src/index.js)
- [`@reach/tabs`](https://github.com/reach/reach-ui/blob/master/packages/tabs/src/index.js)
- [`react-spinners`](https://github.com/davidhu2000/react-spinners/blob/master/src/index.js)
- [`react-virtualized`](https://github.com/bvaughn/react-virtualized/blob/master/source/index.js)
- [`stimulus`](https://github.com/stimulusjs/stimulus/blob/master/packages/%40stimulus/core/src/index.ts)
- [`recharts`](https://github.com/recharts/recharts/blob/master/src/index.js)

Default export too:
- [`react`](https://github.com/facebook/react/blob/master/packages/react/index.js) itself
- [`turbolinks`](https://github.com/turbolinks/turbolinks/blob/master/src/index.ts)
- [`downshift`](https://github.com/downshift-js/downshift/blob/master/src/index.js)
- [`react-select`](https://github.com/JedWatson/react-select/blob/master/src/index.js)

But when looking a bit closer, It stood out to me that the libraries that expose nestable components, only have named exports.

Since `InertiaLink` is something that needs te be nested in `Inertia[Adapter]` (just like `Link` is nested in a `Router` f.i.), my suggestion is to update all current packages to only export named exports.

This too has the advantage that it will maybe (don't know for sure) be easier to refactor the typings in a more modern way without the use of modules.

Like I said before: I only looked into the React community to see what's commonly used, but I think that if we do it for one of the packages, we should do it for all of them to be consistent.

**Comment by MichaelDeBoey** [comment]
Ping @reinink @sebastiandedeyne

**Comment by MichaelDeBoey** [comment]
Ping @reinink @sebastiandedeyne

**Comment by sebastiandedeyne** [comment]
Since it's 50/50 overall, I don't see any value in investing in this change now, since it doesn't provide any meaningful benefits today.

**Comment by reinink** [comment]
Yeah, I'd second that. I'm okay with our current approach. I appreciate your research into this though @MichaelDeBoey!

**Comment by reinink** [comment]
It's worth noting that we did, in the end, choose named exports, as part of the [first release](https://github.com/inertiajs/inertia/releases/tag/v0.1.0). 😅
