### ISSUE TITLE
Shared data not working on Jetstream 2

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia#421]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:
After upgrading Laravel Jetsream to v2, I updated @inertiajs/inertia to v0.8.2 and @inertiajs/inertia-vue to v0.5.4

Now when I login into the app it throw this errors:
```js
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating '_vm.$page.user.profile_photo_url')"

found in

---> <AppLayout> at resources/js/Layouts/AppLayout.vue
       <Show> at resources/js/Pages/Domains/Show.vue
         <Inertia>
           <Root>
```

```js
TypeError: undefined is not an object (evaluating '_vm.$page.user.profile_photo_url')
```

**Comment by claudiodekker** [comment]
Hi,

This is happening [because of a breaking change introduced in inertia-vue@0.3.0](https://github.com/inertiajs/inertia/releases/tag/inertia-vue%40v0.3.0), and to fix this specific issue all you'd have to do is change your references when using the $page object. In your example, this would be the fix:
```diff
- $page.user.profile_photo_url
+ $page.props.user.profile_photo_url
```

Since it's unlikely that this is the only thing that's broken since, our recommendation is to work your way backwards through the [releases page](https://github.com/inertiajs/inertia/releases) on the repository, applying all mentioned (breaking) changes that are relevant. In your situation, this means it's safe to ignore all `@inertiajs/inertia-vue3`, `@inertiajs/inertia-react` etc. package releases.

Hope this helps!

**Comment by lucaros97** [comment]
Ok seems working!

But there is something else not working anymore.
The form.error() method used by default in Jestream now throw an error related to Inertia.
For example in the Profile page I have a form where I can update the profile information and there's the input-error component called like this:
`<jet-input-error :message="form.error('photo')" class="mt-2" />`

However this throw an error as the same:
```js
[Vue warn]: Error in render: "TypeError: Cannot read property 'updateProfileInformation' of undefined"

found in

---> <JetFormSection> at resources/js/Jetstream/FormSection.vue
       <UpdateProfileInformationForm> at resources/js/Pages/Profile/UpdateProfileInformationForm.vue
         <AppLayout> at resources/js/Layouts/AppLayout.vue
           <Show> at resources/js/Pages/Profile/Show.vue
             <Inertia>
               <Root>
```

```js
TypeError: Cannot read property 'updateProfileInformation' of undefined
    at InertiaForm.hasErrors (app.js:13748)
    at InertiaForm.error (app.js:13753)
    at fn (app.js:63822)
    at normalized (app.js:73248)
    at Proxy.renderSlot (app.js:73344)
    at Proxy.render (app.js:55182)
    at VueComponent.Vue._render (app.js:74202)
    at VueComponent.updateComponent (app.js:74718)
    at Watcher.get (app.js:75129)
    at new Watcher (app.js:75118)
```


Seems not working also with the [validation](https://inertiajs.com/validation) provided in the inertia documentation

**Comment by claudiodekker** [comment]
Yes, this too is correct. The entire `$inertia.form` helper that shipped with Jetstream v1 ([laravel-jetstream](https://github.com/laravel/jetstream-js) NPM package) has been removed in Jetstream v2 in favour of the form helper that Inertia now ships with out of the box: https://inertiajs.com/forms#form-helper

There's not a lot of changes related to it, but in short calls such as `form.error('photo')` have been changed to `form.errors.photo`, and `form.hasErrors()` has been changed to `form.hasErrors`. 

Apart from that, most things should work the same, but it's best to take a look at the docs, or at the [Jetstream V2 repo](https://github.com/laravel/jetstream/tree/2.x/stubs/inertia/resources/js) to see the differences between your installation and the new Jetstream install

**Comment by lucaros97** [comment]
Missed that too. Anyway I ended up replacing all the Jestream core files with the new ones coming in v2.
Thank you @claudiodekker for the real help!

**Comment by BartMommens** [comment]
The quickest appraoch updating Jetstream 1x to Jetstream 2x was just doing a clean install of Jetstream 2 and moving my PHP code and custom views over from 1x to the fresh install, what a nightmare this has been ... 

@lucaros97  i also tried your approach but here and there some things seem to be slipping up.
