### ISSUE TITLE
Automatically cancel in-progress visits when navigating history

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#426]
Right now if you have an active Inertia visit, and you go forward/back in history, that visit will not be cancelled. This can lead to weird states. Since history visits are really the same as Inertia visits, in that they are synchronous, it makes sense to just cancel any in-progress visits within the `popstate` handler.

It's worth noting that you cannot cancel `popstate` events, so there is no way to prevent the user from navigating history. This is different than a classic (non-SPA) app, where you can cancel page visits using `onbeforeunload`.

```js
window.onbeforeunload = function() {
  return "Are you sure you want to navigate away?";
}
```

**Comment by claudiodekker** [comment]
Similar: #655
