### ISSUE TITLE
Route helpernot accpet multi params

### ISSUE THREAD

**Issue by IgorDePaula** [inertiajs/inertia#427]
### Versions:

- `@inertiajs/inertia` version: "^0.3.0"
- `@inertiajs/inertia-vue` version: ^0.2.0"

### Describe the problem:
I'm use inerta with laravel jetstream, I created a route wit /abc/{A}/def/{B}. I can't set params A and B. Only one parameter.
I not got use route('abcdef', [A, B]) or route('abcdef, {A:A, B:B})

**Comment by claudiodekker** [comment]
Hi,

Inertia does not ship/maintain a `route` helper, so this unfortunately isn't something we can really help with. 
That said, I believe you are referring to the Ziggy route helper that Jetstream ships with, so perhaps you could try and see if their documentation answers your question, or alternatively open an issue over on their repository?: https://github.com/tighten/ziggy#usage

Good luck!

**Comment by IgorDePaula** [comment]
Sorry
