### ISSUE TITLE
File upload only post?

### ISSUE THREAD

**Issue by IgorDePaula** [inertiajs/inertia#430]
Versions:

    @inertiajs/inertia version: "^0.3.0"
    @inertiajs/inertia-vue version: ^0.2.0"

### Describe the problem:
I tryed send upload but with PUT http verb I not got, only POST http verb.

### Steps to reproduce:
Try send upload file with put http verb on post http verb instead.

**Comment by claudiodekker** [comment]
Hi,

This is a known issue with HTML forms, and unfortunately isn't something we can solve for _everyone_ out of the box, as multiple back-end frameworks and languages might implement a solution to this problem differently. 

Luckily, however, [most frameworks do implement a somewhat 'standard' solution to this](https://laravel.com/docs/8.x/routing#form-method-spoofing). So, assuming you have something like this now:
```js
this.$inertia.put('/endpoint', {
    file: new File(..) // Your file
});
```

What you'll want to do, is change your request to `POST` instead, and add a `_method` field that contains the _actual_ method that you want to use. This value will then be used on the back-end as the actual incoming HTTP request method:
```js
this.$inertia.post('/endpoint', {
    _method: 'put',
    file: new File(..) // Your file
});
```

Hope this helps!

**Comment by IgorDePaula** [comment]
Sorry, I remember now, but not help me. =/
