### ISSUE TITLE
Error in query string serialization with arrays containing objects

### ISSUE THREAD

**Issue by marvinrabe** [inertiajs/inertia#431]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4
- `@inertiajs/inertia-vue3` version: not tested
- `@inertiajs/inertia-react` version: not tested
- `@inertiajs/inertia-svelte` version: not tested

### Describe the problem:

Arrays with objects are not properly serialized in query string.

```js
this.$inertia.get('/url', { filter: [{ path: 'foo', value: 'a' }, { path: 'foo', value: 'b' }] });
```

Results in:

```
/url?filter%5B0%5D%5Bpath%5D=foo&filter%5B1%5D%5Bvalue%5D=a&filter%5B2%5D%5Bpath%5D=foo&filter%5B3%5D%5Bvalue%5D=b
```

Which is interpreted by Laravel as:

<img width="505" alt="Bildschirmfoto 2021-01-14 um 13 30 34" src="https://user-images.githubusercontent.com/515860/104591664-4db40700-566d-11eb-84f1-9ffbec049f1a.png">

Which is clearly not the result one would expect. It creates a new object per key.

### Steps to reproduce:

Call

```js
this.$inertia.get('/url', { filter: [{ path: 'foo', value: 'a' }, { path: 'foo', value: 'b' }] });
```

Expected Query string:

```
filter%5B0%5D%5Bpath%5D=foo&filter%5B0%5D%5Bvalue%5D=a&filter%5B1%5D%5Bpath%5D=foo&filter%5B1%5D%5Bvalue%5D=b
```

Actual Query string:

```
filter%5B0%5D%5Bpath%5D=foo&filter%5B1%5D%5Bvalue%5D=a&filter%5B2%5D%5Bpath%5D=foo&filter%5B3%5D%5Bvalue%5D=b
```

**Comment by marvinrabe** [comment]
I reverted the version to:

    "@inertiajs/inertia": "^0.6.3",
    "@inertiajs/inertia-vue": "^0.4.3",

In this version everything works as expected.

I think something from 0.7 causes this error.

**Comment by marvinrabe** [comment]
This whole merging thing behaves weirdly in other places as well. For example:

You are on `/page?items[]=1&items[]=2` and you have some form of choosing "items". When you do

```js
this.$inertia.reload({
  data: { items: [] }
})
```

It does not reset the list of items, because it deepmerges the old items into the data structure.

And this:

```js
this.$inertia.reload({
  data: { items: [3] }
})
```

Results in this:  `/page?items[]=1&items[]=2&items[]=3` 

There is currently no way to reset arrays except by doing this:

```js
this.$inertia.get(window.location.pathname,  { items: [] })
```

Maybe some form of option like `mergeSearchParams: true` would be useful to have more control over this behaviour.

**Comment by RyonMB** [comment]
I have still the same issue at 
"@inertiajs/inertia": "^0.11.0",
 "@inertiajs/inertia-vue3": "^0.6.0",

Vue 3: ` [{ hoi: "hoi", doei: "doei" }]`

laravel reads it like this `[
{
hoi: "hoi"
},
{
doei: "doei"
}
]`

**Comment by NessterGit** [comment]
For Googlers that will end up here like I did, there is an option since v0.11.0 (jan 2022) to specify the query string array format:

```
<Link href="/foo" :data="{ a: ['b', 'c'] }" queryStringArrayFormat="brackets">Example</Link>
<!-- Generated href: /foo?a[]=b&a[]=c -->

<Link href="/foo" :data="{ a: ['b', 'c'] }" queryStringArrayFormat="indices">Example</Link>
<!-- Generated href: /foo?a[0]=b&a[1]=c -->
```
Ref: https://github.com/inertiajs/inertia/pull/994

Manual visits:
```
Inertia.get(route('foo'), {a: ['b', 'c']}, {
    queryStringArrayFormat: "indices",
    onSuccess: (page) => {
        ...
    }
});
```
