### ISSUE TITLE
Event callbacks not working with Jetstream

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia#436]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:
I'm trying to use event callbacks in a Jetstream application using the new Inertia.js form helper.
The problem is that no methods seems to be fired.
Also trying to put a confirmation using the onBefore event didn't work:
```js
onBefore: () => confirm('Are you sure you want to delete this user?'),
```

### Steps to reproduce:
This is my method in the Vue component:
```js
this.form.post(route("user.update"), this.form, {
    onSuccess: () => this.closeModal(),
});
```

and then in my Laravel controller I just return redirect back like this after calling some jobs:
```php
return redirect()->back();
```

**Comment by ajnsn** [comment]
@lucaros97 

You are providing `this.form` in the form helpers options. The signature of the underlying method is

```js
post(url, options) 
```
```js
this.form.post(route("user.update"), {
    onSuccess: () => this.closeModal(),
});
```

**Comment by lucaros97** [comment]
Oh what a miss. I feel like an idiot 😅

Thank you!
