### ISSUE TITLE
Access Laravel array validation messages from Inertia

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia#437]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:
I'm trying to access to all the messages passed from an array validation in Laravel.

### Steps to reproduce:
In the controller I defined this validation method:
```php
request()->validate([
    'parameters.*.value' => 'required'
]);
```

This is what Laravel pass to Inertia props:
```js
props: {
  errors: {
    "parameters.0.value": "The field is required",
    "parameters.1.value": "The field is required"
}
```

I'm using the new Inertia form validation helper so I have something like this in the Vue component:
`<jet-input-error :message="form.errors.*" class="mt-2" />`

But I can't access to the specific error in the array, because the <jet-input-error> it's inside a foreach in a form

**Comment by ajnsn** [comment]
@lucaros97 Afaik there is no native support for this. You could implement your own method, e.g.

```js
getErrors(field) {
    const fields = Object.keys(this.form.errors).filter(key => key === field || key.startsWith(`${field}.`));

    return fields.reduce((carry, key) => {
        this.form.errors[key].forEach(message => {
            carry.push(message);
        });

        return carry;
    }, []);
},
```


```js
getErrors('parameters')
```

Should return:
```js
["The parameters.0.value field is required.", "The parameters.1.value field is required."]
```

**Comment by claudiodekker** [comment]
Yeah, so, what @ajnsn is recommending above is pretty much what I would do as well, as this indeed currently isn't supported natively. 

Another thing you could do, is override/create a custom implementation of your [server-side error sharing mechanism](https://github.com/inertiajs/inertia-laravel/blob/master/src/Middleware.php#L44-L51) in your own Inertia middleware,  and/or [create a custom implementation of your client-side `resolveErrors` callback](https://github.com/inertiajs/inertia/blob/master/packages/inertia/src/inertia.js#L11) (which [works similar to the standard-documented `resolveComponent` callback](https://inertiajs.com/client-side-setup#initialize-app))

**Comment by alisanie** [comment]
Hello
Here is the solution.
I have an array called "faq" .I used this array to make dynamic input and put it in v-for, so I can see my input data and validation error:

```
 <div class="grid grid-cols-4 gap-4" v-for="(faq,index) in form.faqs" :key="index">
                                    <div class="mt-5">
                                        <label for="address" class="block text-sm font-medium text-gray-700">
                                            question
                                        </label>
                                        <input type="text" v-model="faq.question"
                                               class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"/>

                                        <small class="text-red-600" v-if="$page.props.errors[`faqs.${index}.question`]"
                                               v-text="$page.props.errors[`faqs.${index}.question`]"></small>
                                    </div>
</div>
```

as you can see I just simply used below code to show validation error dynamically:

```
<small class="text-red-600" v-if="$page.props.errors[`faqs.${index}.question`]"
                                               v-text="$page.props.errors[`faqs.${index}.question`]"></small>
```
