### ISSUE TITLE
(failed)net::ERR_EMPTY_RESPONSE on photo upload with more than 10KB filesize

### ISSUE THREAD

**Issue by embabista** [inertiajs/inertia#442]
### Versions:

- `@inertiajs/inertia` version: ^0.3.0
- `@inertiajs/inertia-vue` version: ^0.2.0

### Describe the problem:

I've been searching for solution on my current issue using Laravel Jetstream InertiaJS and VueJS.
The InertiaJS I'm using which is compatible with the current Laravel Jetstream is version ^0.3
the issue I face is whenever I upload a photo on the Laravel Jetstream Profile Page is, I can upload some photos specifically less than 10KB photos, but once the file size exceeds 10KB the execution of the code doesn't even reach the Laravel Side. it just submits the update request but will not return anything. I've done some troubleshooting and I found out that the `this.$inertia.form`  `this.form.post` is where the execution freezes. I've written a DD code on the user-profile-information.update and if the file size is small it displays the dd code but if the file size is bigger than 10KB. example 120KB then the request timeout and will return (failed)net::ERR_EMPTY_RESPONSE on the browser console

```
data() {
            return {
                form: this.$inertia.form({
                    '_method': 'PUT',
                    name: this.user.name,
                    email: this.user.email,
                    photo: null,
                }, {
                    bag: 'updateProfileInformation',
                    resetOnSuccess: false,
                }),
                photoPreview: null,
            }
        },
```

        methods: {
            updateProfileInformation() {
                if (this.$refs.photo) {
                    this.form.photo = this.$refs.photo.files[0]
                }

                this.form.post(route('user-profile-information.update'), {
                    preserveScroll: true,
                    onError: errors => {console.log(errors)},
                });

            },`

### Steps to reproduce:

Environment Setup
composer.json
` "require": {
        "php": "^7.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "inertiajs/inertia-laravel": "^0.2.4",
        "laravel/framework": "^8.0",
        "laravel/jetstream": "^1.6",
        "laravel/passport": "^10.0",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.0",
        "tightenco/ziggy": "^0.9.4"
    },`
package.json
`"devDependencies": {
        "@inertiajs/inertia": "^0.3.0",
        "@inertiajs/inertia-vue": "^0.2.0",
        "autoprefixer": "^9.8.6",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-jetstream": "^1.2.0",
        "laravel-mix": "^5.0.9",
        "lodash": "^4.17.20",
        "moment": "^2.26.0",
        "portal-vue": "^2.1.7",
        "postcss": "^7.0.35",
        "postcss-import": "^12.0.1",
        "resolve-url-loader": "^3.1.2",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },`

Using WSL2 - Windows 10
Valet Linux

on the <laravel-jetstream-app>/user/profile
upload an image for the profile picture with filesize of less than 10kb
then upload an image for the profile picture with filesize of more than 10kb

**Comment by claudiodekker** [comment]
Hi,

So, that `net::ERR_EMPTY_RESPONSE` indicates that the request (sending the file) happened just fine, but that an empty response came back. Usually, this is something that occurs when (as you already discovered) it doesn't get processed properly. 

Because Inertia doesn't have any logic that could potentially cause a file-size limit, my bet (as well as prior experience with similar issues) is that it's your local web server (Apache, Nginx) or even PHP itself is configured to not accept and drop requests that are larger than a given size. My recommendation would be to look into that.

Good luck!
