### ISSUE TITLE
Back button reserve wrong state

### ISSUE THREAD

**Issue by khalid-o** [inertiajs/inertia#443]
### Back-end
- `laravel/framework` version: 8.12
- `inertiajs/inertia-laravel` version: 0.3.5

### Front-end
- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:

I have a problem, with navigation by a browser back button, it reserve a wrong state of my app, I don't know is this normal or not, but in somehow it's seems wrong.

### Steps to reproduce:

1. Open resource view page.
![deleted](https://user-images.githubusercontent.com/13126152/104811112-f5fad480-5801-11eb-952b-bc6e3ee2b296.png)

2. Delete this resource, then redirected me to list.
3. Press browser back button.
4. Same previous -deleted- resource page (state doesn't refreshed).
![deleted](https://user-images.githubusercontent.com/13126152/104811112-f5fad480-5801-11eb-952b-bc6e3ee2b296.png)

5. Refresh page -resource not found-.
![notfound](https://user-images.githubusercontent.com/13126152/104811136-23e01900-5802-11eb-9e94-26bdbb54e534.PNG)

**Comment by claudiodekker** [comment]
Hi,

So, Inertia is designed to mimic default browser behaviour, which is to show the _previous_ state when navigating history. We even have the "remember" functionality to help you cache local component state to history state, to ensure that form data (or whatever) is properly cached when navigating history.

What this means, is that at least right now, there is no way to show *fresh state* when pressing back, which in turns means that the behaviour that you're experiencing is indeed correct.

If you feel like this isn't supposed to be the case, and you _do_ want to refresh the page state when clicking the back button, I recommend [adding a feature request under the "ideas" section of our Discussions tab](https://github.com/inertiajs/inertia/discussions/categories/ideas).

Hope this helps!

**Comment by khalid-o** [comment]
Thank you, actually in some cases this will not work properly, and cause some security issues as I think.
