### ISSUE TITLE
inertia.delete not returning callback

### ISSUE THREAD

**Issue by muarachmann** [inertiajs/inertia#444]
### Versions:

- `@inertiajs/inertia` version: ^0.8.2
- `@inertiajs/inertia-vue` version: ^0.4.2

### Describe the problem:

Calling `this.$inertia.delete(url, options)` doesn't seem to execute its callbacks function like `onSuccess` , `onFinish`, `onError`, none of these works. Using post works, but as for deletes no callbacks are being made

### Steps to reproduce:
```
this.$inertia.delete(this.url, this.form, {
                onStart: () => {
                    console.log('Start deleting')
                },
                onSuccess: () => {
                    console.log("no success is called");
                },
                onFinish: () => {
                    console.log("no Finish is called");
                },
                onError: () => {
                    console.log("no Error is called");
                },
            });
```
Method works fine but no callbacks after it returns from the server. 

####  Additional context

Using Laravel for back-end code
```
    public function destroy($id)
    {
        $employee = Employee::find($id)
         if ($employee) {
            $employee->delete();
            return Redirect::back()->with('success', 'Employee deleted');
         }
        return Redirect::back()->with('error', 'No such employee');
    }
```

**Comment by ajnsn** [comment]
@muarachmann The signature of the `delete` method is

```js
this.$inertia.delete(url, options)
```

See [documentation](https://inertiajs.com/manual-visits#method). Can you try the callbacks by removing `this.form` from your call?

**Comment by muarachmann** [comment]
> @muarachmann The signature of the `delete` method is
> 
> ```js
> this.$inertia.delete(url, options)
> ```
> 
> See [documentation](https://inertiajs.com/manual-visits). Can you try the callbacks by removing `this.form` from your call?

Oh my bad, thanks very much.
