### ISSUE TITLE
Upgrade help : Bumping inertia-svelte from 0.3.1 to 0.6.0 causes blank screen

### ISSUE THREAD

**Issue by TheRealThor** [inertiajs/inertia#446]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-svelte` version: 0.6.0

### Describe the problem:

I cloned a fresh pingcrm-svelte package to local, installed it as described and it worked. Then I bumped the version of both packages mentioned above (npm install @inertiajs/inertiajs@latest ). Only the login page was shown as expected. Error handling worked as well. After login  any other page was blank. html code and js code was there but the js seemed like  it just didn't start up. No error message was shown in console. 

I saw the release notes of inertiajs 0.8.0  of the  breaking changes. I couldn't determine if those are the reason. Can anybody point in the right direction how to upgrade or has a code sample of App.js working using `@inertiajs/inertia-svelte` version: 0.6.0 ?

**Comment by TheRealThor** [comment]
I figured out what caused the blank screen. I just had to go even further back into the release notes to see other breaking changes. There was a breaking change in inertiajs that the props of each page filled with data from the larval background are no longer accessed with just $page but with $page.props. Now upgrade to 0.8.2 worked.

**Comment by reinink** [comment]
Excellent, thanks for reporting back on this. 👍
