### ISSUE TITLE
validation handling with axios and inertiajs

### ISSUE THREAD

**Issue by 90umut** [inertiajs/inertia#470]
### Versions:

- `@inertiajs/inertia` version: 0.3.0
- `@inertiajs/inertia-vue` version: 0.2.0

### Describe the problem:

  I don't understand how I can manage validation in my vue. If the validation fail, it returns a 422 error with axios. It works with inertia in according to the docs but I don't want to change vue, I just want to return a plain response so I use axios. How can I handle validation errors like Inertia but with axios request ? 

### Steps to reproduce:

 The axios request : 
```
submit() {
            // this.$inertia.post("/order",{form: this.form})
            axios.post("/order",{form: this.form})
                .then(res => console.log(res))

        }
```
  The method that verify request : 
```
public function create(Request $request)
    {
        $form = $request->input("form");
        
        $validate = $request->validate([
            'form.mail' => "required|email",
            'form.name' => "required|string",
            'form.postcode' => 'required|numeric',
            'form.postadress' => 'required|string',
            'form.city' => 'required|string',
        ]);


        Order::create([
            'book_id' => $form["book"]["id"],
            'name' => $form["name"],
            'mail' => $form["mail"],
            'postcode' => $form["postcode"],
            'adress' => $form["postadress"],
            'city' => $form["city"],
        ]);

        return true;
        
    }
```

**Comment by ruvaifa-masood** [comment]
You can try this approach:

`<template>
  <span class="form-error" v-if="form.errors['FIELD_NAME']">
    {{ form.errors['FIELD_NAME'][0] }}
  </span>  
</template>

<script>
export default {
  data() {
    return {
      form: {
        fields: {
          // YOUR FORM'S FIELDS
        },
        errors: []
      }
    }
  },
  methods: {
    order() {
      this.form.errors = []

      axios.post('/order').then(response => {
        //  Handling the response (Show a success message etc)
      }).catch(error => {
        //  Handling the response (Show an error notification etc)
        if (error.response) { // You can also check the status i.e 422
          this.form.errors = error.response.data.errors
        }
      })
    }
  }
}
</script>`

**Comment by ruvaifa-masood** [comment]
You can try this approach:

```javascript
<template>
  <span class="form-error" v-if="form.errors['FIELD_NAME']">
    {{ form.errors['FIELD_NAME'][0] }}
  </span>  
</template>

<script>
export default {
  data() {
    return {
      form: {
        fields: {
          // YOUR FORM'S FIELDS
        },
        errors: []
      }
    }
  },
  methods: {
    order() {
      this.form.errors = []

      axios.post('/order').then(response => {
        //  Handling the response (Show a success message etc)
      }).catch(error => {
        //  Handling the response (Show an error notification etc)
        if (error.response) { // You can also check the status i.e 422
          this.form.errors = error.response.data.errors
        }
      })
    }
  }
}
</script>
```

**Comment by ruvaifa-masood** [comment]
You can try this approach:

```javascript
<template>
  <span class="form-error" v-if="form.errors['name']">
    {{ form.errors['name'][0] }}
  </span>  
</template>

<script>
export default {
  data() {
    return {
      form: {
        fields: {
          name: ''
          // Other fields
        },
        errors: []
      }
    }
  },
  methods: {
    order() {
      this.form.errors = []

      axios.post('/order', this.form.fields).then(response => {
        //  Handling the response (Show a success message etc)
      }).catch(error => {
        //  Handling the response (Show an error notification etc)
        if (error.response) { // You can also check the status i.e 422
          this.form.errors = error.response.data.errors
        }
      })
    }
  }
}
</script>
```

```php
public function create(Request $request)
{    
    $payload = $request->validate([
        'name' => ['required'] // You can add more rules to it
        // Other fields
    ]);

    Order::create($payload);

    // Other operations/tasks
}
```

**Comment by claudiodekker** [comment]
Yeah, like @ruvaifa-masood already demonstrated above, 400/500 responses (and perhaps others too) will cause the Axios `promise` to fail, meaning it'll never hit the `.then` part, but will instead hit any defined `.catch` blocks. Here's some more information that might be useful:

- https://javascript.info/promise-chaining
- https://github.com/axios/axios#handling-errors
