### ISSUE TITLE
Scrollbar jumps on reload

### ISSUE THREAD

**Issue by bebetoalves** [inertiajs/inertia#475]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue` version: 0.5.5
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

Hello! I've searched and found nothing like this, so I don't know if it's really a bug or if it's a bad setup.

So what's going on? When I reload the page, with the scroll bar in the middle of the page, the bar goes back to the beginning and then jumps to where it was.

Demonstration: [Streamable](https://streamable.com/yqhguy)

### Steps to reproduce:

Place the cursor in the middle or end of the page and reload it.

### What have I tried so far?

As I am working with Vue, I used Vite to load my template and everything worked perfectly.

**Comment by reinink** [comment]
Sorry, but it's really hard to figure out what's going wrong here without any code.

I have a bit of a suspicion that this is related to BrowserSync, and isn't an Inertia.js issue.

I'd recommend trying to see if you can reproduce this in a production build, without BrowserSync. If the issue persists, please report back with some code to reproduce. 👍
