### ISSUE TITLE
Redirect broken if new page's shared data is missing objects from previous page

### ISSUE THREAD

**Issue by taylorotwell** [inertiajs/inertia#476]
For example, imagine a dashboard that displays a piece of shared data from the user:

```
{$page.props.auth.user.name}
```

On a logout action from this dashboard, we call `Auth::logout()` and redirect to `/`. The request `/` executes but the shared `user` prop is now `null`. Because of this, Svelte seems to have problems and never redirects to the new page. Nothing happens at all. 

If you change your usage of the `user` prop to use optional chaining, everything will work again:

```
{$page.props.auth.user?.name}
```

This does not seem to be necessary with other drivers. It seems like the new shared data is loaded into the `$page.props` before the component is swapped out after the redirect response. Then the template seems to break and no component swap happens in response to the redirect.

**Comment by jordankaerim** [comment]
I noticed that too and I do the same thing in my code you do. I am not sure how the other adapters behave but it does make sense because if you would first render the new components and then inject the new props then the props wouldn't be available on the next render.

**Comment by reinink** [comment]
This has been fixed in `@inertiajs/inertia-svelte@0.6.1`. 👍
