### ISSUE TITLE
Inertia visit events do not resolve asynchronously

### ISSUE THREAD

**Issue by ervinnnc** [inertiajs/inertia#480]
I have an issue where I'm using await/async to wait for a Promise to be returned. However, it seems that the event handlers are not awaiting for async, so thus the event just returns without being able to be cancelled.

`this.$inertia.on('before', async event => {
    return await this.$refs.message.show();
});`

For example, the code above doesn't respect the Promise and does not wait for the Promise to be resolved. 

Synchronous methods like `confirm()` will work (given that event was NOT async):-

`this.$inertia.on('before', event => {
    return confirm("Are you sure?");
});`

However, allowing the event callbacks to await for async would be nice to allow for custom components (for example, a custom message box component such as the one I'm using).

**Comment by reinink** [comment]
Hmm, I'm not really following what you're trying to do, but `Inertia.on()` is really just a proxy for native browser event handler registration, with the exception that it automatically returns a function used to remove the event listener. Meaning, you can just use `document.addEventListener` here instead:

```js
document.addEventListener('inertia:start', (event) => {
  console.log(`Starting a visit to ${event.detail.visit.url}`)
})
```

Here is some discussion on how to use promises in browser event handlers: https://stackoverflow.com/questions/50623279/js-event-handler-async-function

Hope that helps. 👍
