### ISSUE TITLE
onError callback is not triggered called

### ISSUE THREAD

**Issue by zablik** [inertiajs/inertia#484]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

Hello everyone!

`.catch()` callback is deprecated, but when I use `onError` callback it simply does not call it.

### Steps to reproduce:

Response is
`GET https://localhost 403 (Forbidden)`
There is only `--- catch ---` in my console dev tools
```
$inertia.visit("/", {
    onError: errors => {
        console.log('--- onError callback ---');
    }
})
    .catch(e => {
        console.log('--- catch ---');
    });
```

**Comment by ajnsn** [comment]
@zablik The `onError` callback naming is imHo somehow misleading as it's only triggering when validation errors are present. [According to the documentation](https://inertiajs.com/manual-visits#event-callbacks) the `exception` event is the right choice for replacing `catch`:

```js
Inertia.on('exception', (event) => {
  event.preventDefault()
  // Handle the error yourself
})
```

**Comment by zablik** [comment]
@ajnsn Thanks for your reply!

I tried `Inertia.on('exception'...`, but it is a global handler, am I right?

**Comment by ajnsn** [comment]
@zablik Yes, the event is only available globally. If you want to do this per visit, you can stick to the `catch`. See the code behind the scenes [over here](https://github.com/inertiajs/inertia/blob/8a137c5e43277897ee2074bce094bed5413550ae/packages/inertia/src/inertia.js#L285-L288). If there's no global `exception` event which does a `event.preventDefault()`, it should throw return a `Promise.reject`.

**Comment by zablik** [comment]
@ajnsn Thanks, now it's clear! =)

**Comment by Bleachfuel** [comment]
When i came across this, it was very annoying for me. .catch(e) doesnt work anymore and onError only does validationErrors,   but no errors like network errors. Then i have to use the global callback. Very annoying should be changed back or have two different error callbacks
