### ISSUE TITLE
How do we reset nested data in the form helper?

### ISSUE THREAD

**Issue by betaSavvy** [inertiajs/inertia#485]
```vuejs
data() {
  return {
    form: this.$inertia.form({
      owner: '',
      car: {
        model: '',
      },
      bike: {
        model: '',
      },
    })
  }
}
```

Trying to reset with this but it is not working.
`this.form.reset('car.model', 'bike.model')`

**Comment by ajnsn** [comment]
@betaSavvy Afaik that is currently not possible. The form helper [does not support nested values nor dot notation](https://github.com/inertiajs/inertia/blob/8a137c5e43277897ee2074bce094bed5413550ae/packages/inertia-vue/src/form.js#L37). You can clear the parent attribute though.

**Comment by betaSavvy** [comment]
@ajnsn 
> @betaSavvy Afaik that is currently not possible. The form helper [does not support nested values nor dot notation](https://github.com/inertiajs/inertia/blob/8a137c5e43277897ee2074bce094bed5413550ae/packages/inertia-vue/src/form.js#L37). **You can clear the parent attribute though.**

Do you mean `this.form.reset('car')`?

**Comment by claudiodekker** [comment]
> Do you mean `this.form.reset('car')`?

@betaSavvy Yep, that's correct, you can currently only reset the root-level attribute. 

This makes me curious, though.. Is it even possible to use nested fields like this (e.g. `car[model][version]`)? 
And do we currently already correctly serialize fields this way? (we might?)
If that's the case, then this would be [a great idea to add & track here](https://github.com/inertiajs/inertia/discussions/new?category=ideas) 👍
