### ISSUE TITLE
Submitting form helper with files sends no data to Laravel backend.

### ISSUE THREAD

**Issue by markvesterskov** [inertiajs/inertia#495]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.5

### Describe the problem:

I have a Laravel Jetstream-backed admin interface using Inertia. I'm using the form helper to submit data to the backend. When i do not have any files in my form, it submits just fine, and everything can be stored correctly. As soon as i pick a file, it breaks the data being sent to the backend, so i get an empty request in Laravel.

`this.form.patch(
                    route('$streams.update', {stream: 436),
                    {
                        preserveScroll: true
                    }
                )`

https://user-images.githubusercontent.com/7515900/107811095-f12c3080-6d6d-11eb-8ee0-d8ea27e7a6b2.mov

### Steps to reproduce:

Submit a form with a file - observe issue. I'd love trying out whatever to triage the issue, but I've hit a wall here, and I'm starting to doubt whether I have hit a bug, or messed up myself.

**Comment by claudiodekker** [comment]
Hi,

Most likely this has to do with [a long-standing 'bug' in PHP](https://bugs.php.net/bug.php?id=55815), which doesn't properly accept multipart forms (forms with binary data such as uploads) under `PUT`/`PATCH`/`DELETE` methods. Luckily, however, [most frameworks do implement a somewhat 'standard' solution to this](https://laravel.com/docs/8.x/routing#form-method-spoofing). 

Assuming you have something like this now:
```js
this.form = this.$inertia.form({
  upload: <your file>
});

// ...
this.form.patch( route('$streams.update', {stream: 436), { preserveScroll: true } )
```

What you'll want to do, is change your request method to `POST` instead, and add a `_method` field that contains the _actual_ method that you want to use. This value will then be used on the back-end as the actual incoming HTTP request method:
```js
this.form = this.$inertia.form({
  _method: 'patch',
  upload: <your file>
})

// ...
this.form.post( route('$streams.update', {stream: 436), { preserveScroll: true } )
```

Hope this helps!

**Comment by markvesterskov** [comment]
@claudiodekker You were absolutely right - it was the lovely "FormData only works on POST requests in PHP" caveat that got me. Thank you so much for the fast and comprehensive response, I really appreciate it!
