### ISSUE TITLE
Improve history navigation on iOS

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#5]
Right now going forward/back in history on iOS is a mess. I'm not honestly sure if there is anything that can be done to fix this. Probably would mean reintroducing caching to Inertia.

![2019-04-08 12 15 35](https://user-images.githubusercontent.com/882133/55739954-1e805880-59f8-11e9-8001-f11f66e03943.gif)

**Comment by Juhlinus** [comment]
This also seems to apply when you, for example, go to Organizations > Page 1 and then thereafter go to Page 6. If you press the back button on the browser then the URL will change to Page 1, but the view does not reload. If you try to reproduce this on Android (Firefox) then you will go back to the Dashboard(initial page).

**Comment by reinink** [comment]
This has been fixed.

@Juhlinus I think your issue is related to #3, which I still plan to fix.
