### ISSUE TITLE
Support file uploads

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#50]
We're trying to do file uploads with Inertia. That means the `Content-Type` header needs to be set. Currently using this beautiful snippet 😬 

```js
axios.interceptors.request.use(config => {
    if (config.data instanceof FormData) {
        config.headers['Content-Type'] = 'multipart/form-data';
    }

    return config;
});
```

Is there any better way to modify headers for specific visits?

**Comment by rakk7** [comment]
Its seems that it's not possible to customize the headers for now, there is a [PR ](https://github.com/inertiajs/inertia/pull/46#issue-284072756)for this.

but you can do this https://github.com/inertiajs/inertia-vue/issues/48#issuecomment-497979954

**Comment by sebastiandedeyne** [comment]
Turns our Axios is smart enough to take care of this in the background. Since this isn't a problem anymore I'm closing this for now.
