### ISSUE TITLE
Use Inertia for 'none' Inertia Page Loads

### ISSUE THREAD

**Issue by thoresuenert** [inertiajs/inertia#51]
We have two use cases where we need to use `axios` directly, because we load data async from api endpoints. We want to avoid using axios directly and use inertia for it.

**1. File Uploads**
We a list of files which will be uploaded asynchronously and attached to the form data as array of ids after successful upload.

**2. Select fields**
We have a lot of users in the database which we want to pick from a select field.

When we use `inertia.post` without setting the inertia header, the response data will be shown in the modal view. When we add the inertia header in the response the data will be applied to the `setPage` function.

**The Solution**
We include`header['x-inertia']` in the response for those `async` non page endpoints,
which will solve the modal view problem.
We need a check if the payload data is an inertia page payload and return the data object if not.

https://github.com/inertiajs/inertia/blob/a515eaee3ba716c7773b994fb9850a613cb4f1a7/src/inertia.js#L86-L90

Possible solution:
```js
then(page => {
      if (page.version /* && page.component .. whatever is needed for the detection*/) {
        this.setPage(page, visitId, replace, preserveScroll, preserveState)
      } else {
        return page
      }
})
```

This change gives us the possibilty to access the returned data in then:
```js
this.$inertia.post(..., formData).then((data) => {
//... do something with the data here.
})
```

**final question**
Is this change worst it?
Should we intergrate this behaviour to avoid the direct use of `axios`?

Slidely differnt solution to https://github.com/inertiajs/inertia/pull/44/

**Comment by reinink** [comment]
So, for file uploads, `Inertia.post()` and `Inertia.put()` should already work. You'll just have to use `FormData`. See here: #50

As for other requests, I don't really see anything wrong with just using axios directly in those situations. I do that in my own apps, for exactly your situation (a select dropdown).

Hope that helps!
