### ISSUE TITLE
'errorBag' does not exist in type 'VisitOptions'

### ISSUE THREAD

**Issue by vadimsg** [inertiajs/inertia#510]
### Versions:

- `@inertiajs/inertia` version: 0.8.4

### Describe the problem:

When using errorBag option typescript gives 'errorBag' does not exist in type 'VisitOptions'.

**Comment by reinink** [comment]
This needs to be added to the [types definition file](https://github.com/inertiajs/inertia/blob/master/packages/inertia/index.d.ts). We're accepting PRs for type changes, but we don't maintain them ourselves at this time.
