### ISSUE TITLE
Form helpers not showing any errors upon failed request validation

### ISSUE THREAD

**Issue by aerrata** [inertiajs/inertia#511]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

I am validating a simple form using the validate function, but the form helper does not return any error regarding the failed validations.

But strangely when I use the shared data feature, it does show me the validation errors.

### Steps to reproduce:

IndexController.php:

```php
public function store(Request $request)
{
    $request->validate([
        'content' => ['required', 'max:10']
    ]);

    return redirect()->back();
}
```

HandleInertiaRequests.php (I try to use form helpers, this is just for testing purposes)

```php
public function share(Request $request)
{
    return [
        ...
        'errors' => function () use ($request) {
            return $this->resolveValidationErrors($request);
        },
        ...
    ];
}
```

Index.vue:

```vue
<template>
  <form @submit.prevent="form.post(route('tweet.store'))">
    <input v-model="form.content">
    <div>{{ $page.props.errors }}</div> <!-- This works, it returns the error -->
    <div>{{ form.errors }}</div> <!-- But this doesn't, it's empty :( -->
  </form>
</template>

<script>
export default {
  data() {
    return {
      form: this.$inertia.form({
        content: '',
      }),
    }
  },
}
</script>
```

Am I missing something? Thanks!

**Comment by ajnsn** [comment]
> But strangely when I use the shared data feature, it does show me the validation errors.

@aerrata The form helper is only client side. It still needs the server side validation errors to be generated and shared within the `errors` prop. 

If you are using the Laravel adapter, this is done automatically within the default [middleware](https://github.com/inertiajs/inertia-laravel/blob/master/src/Middleware.php#L47-L49). 

It is recommended to always include this default sharing when using your extended middleware. This is also included by default when calling `php artisan inertia:middleware`. 

```php
public function share(Request $request)
{
    return array_merge(parent::share($request), [
        //
    ]);
}
```
Notice the `array_merge` with the `parent::share`. Or, like you did, populate the `errors` prop and overwrite or do not merge the default (= parent).

**Comment by aerrata** [comment]
Okay I get it now,  I don't rerun `php artisan inertia:middleware` after I upgraded the laravel-inertia package, so that's why.

Thanks @ajnsn 👍🏻
