### ISSUE TITLE
Control Param serialization of get requests

### ISSUE THREAD

**Issue by thoresuenert** [inertiajs/inertia#52]
We rely on `json:api` filtering and we use the wonderful querybuilder from spaite https://github.com/spatie/laravel-query-builder.
It would be helpful to have an option for the `paramsSerializer` function to pass to `axios` globally so we dont need to think about it.

Problem:
When we use a `json:api` conform `get filter string` (for example: filter[name]=mpociot), we cannot use the data object as implemented.

We cannot use the get params introduced by @mpociot with https://github.com/inertiajs/inertia/pull/28 , because the standard serialization of axios conflicts with json:api.

instead of:
```js
 this.$inertia.get(url,form)
```
we have to use the `url` and encode with every request:

```js
this.$inertia.get(url + Qs.Stringify(form, {
            encode: false,
            addQueryPrefix: true,
            filter: (prefix, value) => (value === "" ? undefined : value)
          })
```
When we allow to make use of:
```js
//axios config (pass with each request)
paramsSerializer: function (params) {
    return Qs.stringify(params, {arrayFormat: 'brackets'})
},
```
we can use for my example:
```js
paramsSerializer: function (params) {
    return Qs.Stringify(this.data(), {
            encode: false,
            addQueryPrefix: true,
            filter: (prefix, value) => (value === "" ? undefined : value)
          });
},
```

and apply it globally before the adapter is set up:

```js
Inertia.paramsSerializer = function (params) { ... };
```

to make json:api conform request.

**final question**
Do we want to support this?
If yes i will provide a pr shortly.

**Comment by sebastiandedeyne** [comment]
Inertia uses axios under the hood, so for now you can just override axios' own paramsSerializer using an intercepter, and Inertia will pick it up too.

https://github.com/axios/axios#interceptors

**Comment by thoresuenert** [comment]
@sebastiandedeyne can you provide an example?

When i use the following code i am not able to intercept inertia requests:
```js  //app.js
import { InertiaApp } from "@inertiajs/inertia-vue";
Vue.use(IntertiApp);
import axios from "axios";
axios.interceptors.request.use(
    function(config) {
        // Do something before request is sent
        console.log(config);
        return config;
    },
    function(error) {
        // Do something with request error
        return Promise.reject(error);
    }
);
...

new Vue(....)
``` 
I dont understand what happen when i import multiple times, maybe that is the problem. Otherwise i cannot intercept because axios is not global

**Comment by Juhlinus** [comment]
@thoresuenert First off, you've misspelled `InertiaApp`.
`Vue.use(IntertiApp);`

That might be enough for your app to not work.

I got it working with the following in a fresh PingCRM clone:
```javascript
import { InertiaApp } from '@inertiajs/inertia-vue'
import PortalVue from 'portal-vue'
import Vue from 'vue'
import axios from 'axios'

Vue.config.productionTip = false
Vue.mixin({ methods: { route: window.route } })
Vue.use(InertiaApp)
Vue.use(PortalVue)

axios.interceptors.request.use(
    function(config) {
        // Do something before request is sent
        console.log(config);
        return config;
    },
    function(error) {
        // Do something with request error
        return Promise.reject(error);
    }
);

let app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)

```

**Comment by thoresuenert** [comment]
First thanks for the fastest answer ever received :D 

@Juhlinus can you confirm the following please:

When you update inertia to latest tags it breaks the interceptor?
```js
"@inertiajs/inertia": "^0.1.3",
"@inertiajs/inertia-vue": "^0.1.1",
```

with 0.1.0 its work like you said.

**Comment by thoresuenert** [comment]
Finally i found the problem:

Inertia updated `axios` to `v0.19`
In PingCRM `axios` is installed seperately as `v0.18.0` which results in `@inertia` in `v0.1.0`

When you install `inertia` with a version mismatch axios `0.18` and `0.19` npm will install an own module within the `node_modules/@inertia/node_modules/axios` folder.
After that the interceptor intercepts the wrong version of `axios`
