### ISSUE TITLE
useForm missing in type definition file

### ISSUE THREAD

**Issue by mxmtsk** [inertiajs/inertia#520]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-react` version: 0.5.4

### Describe the problem:

When using TypeScript, you get an error when trying to import `useForm` since it's not defined in the `index.d.ts` definition file yet.

> Module '"../../../../node_modules/@inertiajs/inertia-react"' has no exported member 'useForm'.ts(2305)

### Steps to reproduce:

Just import the `useForm` in a typescript project:

Module '"../../../../node_modules/@inertiajs/inertia-react"' has no exported member 'useForm'.ts(2305)

**Comment by reinink** [comment]
We're accepting PRs for type changes, but we don't maintain them ourselves at this time. Free to submit a PR to add this. 👍
