### ISSUE TITLE
Persistent layouts doesn't work in Vue 3

### ISSUE THREAD

**Issue by buismaarten** [inertiajs/inertia#527]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

Using persistent layouts gives the following error:
```
Error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.
```

### Steps to reproduce:

Switch from the layout component used in template to layout defined in component object.

**Comment by reinink** [comment]
Can you please share your code? In particular, can you share:

1. Your app.js file
2. Your page component file
3. Your layout file

I've been using persistent layouts without issue with the Vue 3 adapter, so I'm not convinced this is actually a bug.

**Comment by buismaarten** [comment]
Sure!

I've shared the files using a GitHub Gist: https://gist.github.com/buismaarten/469d45f23134436bd596134c0126a420

**Comment by reinink** [comment]
@buismaarten This appears to be the working code (it's not using persistent layouts). Can you share the code that doesn't work?

**Comment by reinink** [comment]
Wait, I see the issue here. You're using named slots. See #171.

If you need named slots, you'll need to use regular layouts, not persistent layouts. Feel free to join in the discussion in the existing issue.

Closing this, as it's a duplicate.

**Comment by buismaarten** [comment]
Sorry, in the Gist I shared I accidentally shared the regular layout approach because I reverted the change.

I see... thanks for clarifying!
