### ISSUE TITLE
mergeDataIntoQueryString is not considering nested array indexes

### ISSUE THREAD

**Issue by ahmedkandel** [inertiajs/inertia#532]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

When sending a nested array as parameters with `get` request then array indexes are neglected which will cause incorrect data structure when parameters are received server side. 

### Steps to reproduce:

Assume the following object to be sent as `get` parameters:
```JS
filters: {
    constraints: [
        {
            matchMode: 'startsWith',
            value: 'a',
        },
        {
            matchMode: 'endsWith',
            value: 'z',
        },
    ],
    
    ...
}
```

The resulting URL params:
```
filters[constraints][][matchMode]=startsWith&filters[constraints][][value]=a&filters[constraints][][matchMode]=endsWith&filters[constraints][][value]=z
```
The server will recieve `constraints` as:
```
array:4 [
  0 => array:1 [
    "matchMode" => "startsWith"
  ]
  1 => array:1 [
    "value" => "a"
  ]
  2 => array:1 [
    "matchMode" => "endsWith"
  ]
  3 => array:1 [
    "value" => "z"
  ]
]
```

While it should be:
```
filters[constraints][0][matchMode]=startsWith&filters[constraints][0][value]=a&filters[constraints][1][matchMode]=endsWith&filters[constraints][1][value]=z
```
To recieve `constraints` as:
```
array:2 [
  0 => array:2 [
    "value" => "a"
    "matchMode" => "startsWith"
  ]
  1 => array:2 [
    "value" => "z"
    "matchMode" => "endsWith"
  ]
]
```

After a little digging, I see that Inertia is using `qs` with [`arrayFormat: 'brackets'`](https://github.com/inertiajs/inertia/blob/896c53bb0e80bb6ba56e588a3afe665fa8aa0498/packages/inertia/src/url.js#L13), I think this needs to be [`arrayFormat: 'indices'`](https://github.com/ljharb/qs)

**Comment by claudiodekker** [comment]
Related: https://github.com/inertiajs/inertia/pull/338
