### ISSUE TITLE
Feature: Inertia form helper

### ISSUE THREAD

**Issue by ninjaparade** [inertiajs/inertia#539]
Currently with the Inertia form helper, you are able to create a reactive data representation of your data that you would use to send to the server.

an example in Vue 3 below.

```javascript

const form = Inertia.form({ 'name': null, 'brilliantIdea': true})

```

and then once you're ready to submit this form you call

```javascript 

form.post('/not-trash')

```

so what if we could, rather than having to define the method and path for the form, when we submit, actually add that to the form object itself?

```javascript

const form = Inertia.form({ 'name': null, 'brilliantIdea': true }, 'url': '/not-trash', 'method': 'post' })

```

and then you can just magically call 

```javascript 

form.submit()

form.submit({
  preserveScroll: true,
  onSuccess: () => form.reset('password'),
})

```

I know what you're saying right now reading this, what a fantastic idea. Trust me I agree with you.
![giphy (1)](https://user-images.githubusercontent.com/228899/110036513-fc7dd680-7cf1-11eb-9f58-de435f39efe7.gif)

I think this would be awesome and well received by the Inertia community. 

Thank you for your time, now a note from our creator. 

![image](https://user-images.githubusercontent.com/228899/110036589-19b2a500-7cf2-11eb-988f-93cf72561642.png)

_Originally posted by @ninjaparade in https://github.com/inertiajs/inertia/discussions/538_

**Comment by claudiodekker** [comment]
Closing this in favour of the #538 idea, as this is really not an bug/issue 😅

**Comment by ninjaparade** [comment]
@claudiodekker I made the idea cause it's a feature but @reinink wanted an issue. Thanks for taking my side and proving me right. 





Thanks,
Yaz

**Comment by claudiodekker** [comment]
Haha, all good!

@reinink does that mean you want this re-opened? 😆
