### ISSUE TITLE
Google search console

### ISSUE THREAD

**Issue by Resin01** [inertiajs/inertia#54]
Hi
Just testing our interia (react version) for a website, and it seems that google search console does not like the intertia.js file in the main intertia repo.
It throws an error when trying to parse inertia

The error
![image](https://user-images.githubusercontent.com/13980140/60798009-9fbec700-a170-11e9-9b71-007118186cde.png)

First line of stack trace
![image](https://user-images.githubusercontent.com/13980140/60797976-95043200-a170-11e9-9376-da2fc5534170.png)

The part it is complaining about.
![image](https://user-images.githubusercontent.com/13980140/60798178-ea404380-a170-11e9-9f85-dac74a196f5f.png)

Sadly I havent been able to fix a way to fix it myself (I have added @babel/polyfill but it still throws the error.

**Comment by Resin01** [comment]
Same issue on IE11
![image](https://user-images.githubusercontent.com/13980140/60799771-1a3d1600-a174-11e9-8102-8735b13c948e.png)

**Comment by sebastiandedeyne** [comment]
None of the scripts in neither `inertia` and `inertia-react` is being transpiled right now, so older browsers might have syntax issues if you don't transpile the contents of your `node_modules`.

For now, the only solution is to modify your build system's configuration to transpile `node_modules`. 

When we create an 0.1 release, we'll have a transpilation step in place before publishing the assets so this won't be an issue anymore.

**Comment by hivokas** [comment]
Is there any ETA of 0.1 release?

**Comment by heikokrebs** [comment]
@sebastiandedeyne any hints how to achieve this now or when the 0.1 will be released?
https://github.com/inertiajs/pingcrm/issues/28 seems to be aa smiliar error?

**Comment by sebastiandedeyne** [comment]
I haven't tried this out, but a snippet like this should work with Laravel Mix:

```js
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /node_modules\/(inertia)|(inertia-react)|(inertia-vue)\/.+\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: mix.config.babel()
                    }
                ]
            }
        ]
    }
});
```

If someone got this to work, please ping back to confirm!

**Comment by sebastiandedeyne** [comment]
v0.1.0 has been tagged today, if you upgrade this isn't a problem anymore!
