### ISSUE TITLE
InertiaLink Buttons route to Undefined.

### ISSUE THREAD

**Issue by Shiva-Shadowsong** [inertiajs/inertia#567]
### Versions:

        "@inertiajs/inertia": "^0.8.5",
        "@inertiajs/inertia-svelte": "^0.6.1",

### Describe the problem:

As per official documentation, such a button should work in Svelte:

```html
<button href="/logout" use:inertia="{{ method: 'post' }}" type="button">Logout</button>
```

I also have imported the following in the component:
```js
    import { inertia, InertiaLink } from '@inertiajs/inertia-svelte'
``` 

However, it returned a 404 page, and upon inspection of network, I notice it makes a request to `/undefined`

![Problem](https://i.imgur.com/maQE3XG.png)

### Steps to reproduce:

I pasted the HTML from official documentation which I provided above in order to test/tweak it, and reproduce it by using that button.

### Additional Info:
I was able to get it working by using the `<InertiaLink>` wrapper instead, but that made me run into another issue which I will post about.

If this original approach doesn't work, the documentation should probably be updated or the bug fixed.

**Comment by Shiva-Shadowsong** [comment]
It looks like it works if instead of 
```html
<button href="/logout" use:inertia="{{ method: 'post' }}" type="button">Logout</button>
```
you put a href key in the use:inertia object:

```html
<button use:inertia="{{ href: '/logout', method: 'post' }}" type="button">Logout</button>
```

I guess my problem is solved, but you should update it in the documentation example. 🍺
@pedroborges

**Comment by tom-on-the-internet** [comment]
Just ran into this exact issue. Thank you @Shiva-Shadowsong!
+1 to maybe having this in the documentation.

This code works because the `href` is in the directive. It did not work with the href as an attribute.
```
<button use:inertia={{ href: `/posts/${id}`, method: "delete" }} type="button">Delete</button
```

Love Inertia. Thank you for it.
