### ISSUE TITLE
Crazy cookie problem since moving from Laravel Mix to Vite

### ISSUE THREAD

**Issue by shealan** [inertiajs/inertia#576]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-vue` version: 0.5.4

### Describe the problem:

This one is a real head scratcher. Since moving from Laravel Mix to Vite my application appears to be adding a giant cookie to my requests. It's actually too large which is causing all of my Inertia requests to fail.

![cookie](https://user-images.githubusercontent.com/74932/112554691-dfcd4e00-8e1a-11eb-886d-885f362a056b.png)

With the exception of moving to Vite I have made no changes to my application, and it continues to work normally when running locally. I checked and the cookie isn't added locally. When I build and push to production (via Vapor) I get the "cookie too large" error.

I'm not really sure how to go about debugging this problem as I am not sure exactly what part of the stack is adding this. Can you think of any part of Inertia that might be responsible when paired with Vite?

### Steps to reproduce:

Remove Laravel Mix and add Vite

**Comment by reinink** [comment]
Have you tried asking about this in the Vite.js repo? At first glance this doesn't strike me as an Inertia issue.

@sebastiandedeyne Any thoughts here?

**Comment by sebastiandedeyne** [comment]
Vite only generates assets, so I don't think Vite is _directly_ causing the large cookie. Since that screenshot is from the Laravel request, it also can't be appended by Vite at that point.

This is from https://vapor.laravel.com:

<img width="597" alt="Screenshot 2021-04-02 at 09 25 30" src="https://user-images.githubusercontent.com/1561079/113392494-82467d80-9395-11eb-9e44-cdd6e55c066d.png">

They have a similar cookie with a wrangled name. I assume that cookie is generated by Vapor, but I can't find out what it's for. We'll need to find that out first!

**Comment by sebastiandedeyne** [comment]
After digging a bit deeper, it looks like the value in that cookie is something encryped by Laravel, so it's definitely set by Laravel/Vapor.

**Comment by reinink** [comment]
Going to close this, because I don't think this is an Inertia specific issue. If you do figure out that Inertia is causing this bug in some way, please report back. 👍

**Comment by shealan** [comment]
Thanks so much for looking into this guys. I really appreciate you taking the time. I'll submit a support request to the Vapor team to find out if they recognise what's happening. It's certainly one of the stranger issues I have experienced and a frustrating speedbump on what has been one of the more enjoyable projects I have built thanks to Inertia :)

**Comment by Victor-emil** [comment]
@shealan. Did you find a solution for this? I am experiencing the same problem using Laravel Inertia, Vite and Laravel Vapor.

**Comment by shealan** [comment]
@Victor-emil sorry I don't actually remember... I think I may have reverted to Mix. Now that Vite is officially part of the Laravel eco-system I think it is more likely a bug would be spotted with this stack -- especially if you are using the official packages and the latest version of Laravel.
