### ISSUE TITLE
Initial values of useForm are not set when navigating

### ISSUE THREAD

**Issue by Bloemendaal** [inertiajs/inertia#581]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-react` version: 0.5.4

### Describe the problem:

The initial values of `useForm`, given as the first parameter, are not set when the user navigates back and forth using the browser.

### Steps to reproduce:

Create a form using the `useForm` function with initial values and a component that relies on these values.
```ts
interface FormData {
    test: number[];
}

interface FormData1 {
    test1: string;
}

const Component: React.FunctionComponent = () => {
    const { data, setData, post, processing } = useForm<FormData>({ test: [] });
    const { data: data1, setData: setData1, post: post1, processing: processing1 } = useForm<FormData1>({ test1: 'test' });
    
    return (
        <div style={{ color: data.test.length > 0 ? 'blue' : 'green' }} />
    );
};
```

When the user navigates back to this component, it'll throw an error:
```cmd
Uncaught TypeError: Cannot read property 'length' of undefined
```

This is because the property `test` of data not set anymore. You'd expect it to be set, similar to how it is set when the component mounts.

EDIT: It seems to happen only when there are multiple `useForm`s on the page.

**Comment by Bloemendaal** [comment]
It does seem to work with this particular example. I'll continue to investigate, but it does not seem to be a problem with Inertia.

**Comment by Bloemendaal** [comment]
Solved using the key attribute, seems that it is not listed in the typings.

**Comment by reinink** [comment]
Yeah, exactly, that's the way to solve this. [See here](https://inertiajs.com/remembering-state#multiple-components) for more information on pages with multiple forms.
