### ISSUE TITLE
Form helper throws error if prop data contains array

### ISSUE THREAD

**Issue by bradgenereux** [inertiajs/inertia#582]
### Versions:

- `@inertiajs/inertia` version: 0.8.6
- `@inertiajs/inertia-vue3` version: 0.3.6

### Describe the problem:
The form helper throws an error if prop data contains an array. Related to #552.

```DOMException: Failed to execute 'replaceState' on 'History': [object Object] could not be cloned.```

### Steps to reproduce:

```php
public function create()
{
  return Inertia::render('Products/Create', [
    'product' => [
      'name' => '',
      'items' => [],
    ],
  ]);
}
```

```js
export default {
  props: {
    product: Object,
  },
  data() {
    return {
      form: this.$inertia.form(this.product),
    }
  },
}
```

**Comment by dillingham** [comment]
related https://github.com/inertiajs/inertia/issues/578
