### ISSUE TITLE
Incorrect Type Definitions for `usePage`

### ISSUE THREAD

**Issue by jjorissen52** [inertiajs/inertia#589]
I believe this is a bug, but I cannot be totally sure. So if it is, here's the report, and if not, please advise! Thank you for the amazing library.

### Versions:

- `@inertiajs/inertia` version: 0.8.6
- `@inertiajs/inertia-react` version: 0.5.5

### Describe the problem:
After upgrading to latest, we are seeing a new issue with the types associated with usePage:
![image](https://user-images.githubusercontent.com/12461302/113009104-45804980-913d-11eb-8e8e-0f80c2982189.png)

We have a `TemplateProps` type definition that we use:
```ts
export type InertiaProps = {
  props: {
    errors?: Record<string, string[]>,
    flash: Record<string, unknown> | {
      success: boolean,
      error: boolean,
    },
    csrf_token: string,
    auth: Auth,
  }
}

export type TemplateProps = InertiaProps & {
  version: string | number,
  url: string,
  component: string,
}
```

and various components that use it like so:
```ts
const { props: { auth } } = usePage() as TemplateProps;
```
With the new version, TS now complains: 

> TS2352: Conversion of type 'Page<PageProps>' to type 'TemplateProps' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

After some playing around, this seems to be the structure that pleases TS:
```ts
const { props: { props: auth } } = usePage() as Page<TemplateProps>;
```

but of course, this is incorrect, JS wise. As a temporary solution, we have started using:

```ts
const { props: { auth } } = usePage() as unknown as TemplateProps;
```

**Comment by reinink** [comment]
We don't manage the type definition files (these are community driven), so we've asked for PRs around this, not issues.

That said, I wouldn't bother submitting a PR it, as we're in the process of formally offering TS support. 👍
