### ISSUE TITLE
inertia form doesn't work anymore in extended component

### ISSUE THREAD

**Issue by makroxyz** [inertiajs/inertia#594]
### Versions:

- `@inertiajs/inertia` version: 0.8.6
- `@inertiajs/inertia-vue` version: 0.5.6

### Describe the problem:

IT WORKS IN 0.8.5

- BaseComponent with inertia form in data()
- NewComponent extends BaseComponent

form in NewComponent doesn't contain any data

### Steps to reproduce:

BaseComponent:
```
data() {
        return {
            form: this.$inertia.form({
              a:1,
              b:2,
              c:3
            })
        }
    },
```

NewComponent:
```
extends: BaseComponent,

created() {
    console.log(this.form) // <- doesn't contain a, b, c 
}
```

**Comment by makroxyz** [comment]
Sorry there was a typo error in my example...
Anyway I hope could you have a look at this issue.

**Comment by reinink** [comment]
So I just tested this, and it works fine for me. Can you please provide a demo app that reproduces this?

**Comment by makroxyz** [comment]
Upgraded to latest version this morning and it's working again now.
