### ISSUE TITLE
Form helper not assigning $page.props.errors to form.errors

### ISSUE THREAD

**Issue by dpflucas** [inertiajs/inertia#596]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-vue` version: 0.5.6

### Describe the problem:

 With version 0.5.5 of `@inertiajs/inertia-vue`, the form helper automatically assigns the value of the `$page.props.errors` to `form.errors`. After upgrading, it seems this is no longer happening.

### Steps to reproduce:

I'm using Rails as the backend server, and I'm using `inertia_share` to make errors available in the `$page.props.errors`:

```ruby
inertia_share errors: -> {
  session.delete(:errors) || {}
}
```

Then, in Vue I have:

```javascript
data() {
  return {
    form: this.$inertia.form({
      user: {
        email: null,
        password: null,
        terms_and_privacy: false
      }
    })
  }
},
```

and then on the template:

```vue
<form @submit.prevent="form.post($routes.user_registration())" novalidate="true">
  <InputGroup
    v-model="form.user.email"
    :errors="form.errors.email"
    type="email"
  />
  ...
</form>
```

however `form.errors` is now always empty. Note that I confirmed that `$page.props.errors` has the errors as expected, the issue is them not being binded to the `form` object.

**Comment by reinink** [comment]
Yeah, you need to be on [inertia-0.8.6](https://inertiajs.com/releases/inertia-0.8.6) for this to work. You would have received peer dependency warnings when you updated this. Simply update Inertia, and you'll be fine.

Also, FYI, we're making some more changes to the form helpers, to revert some of the changes in the latest release. See here for more info: #597

**Comment by dpflucas** [comment]
That makes sense, thanks for the explanation and for the heads up about the upcoming changes.

Already tried and confirmed it works fine with https://inertiajs.com/releases/inertia-0.8.6 👍

**Comment by reinink** [comment]
@dpflucas Excellent! 🙌
