### ISSUE TITLE
Existing/unchanged props should not be cloned during partial reloads

### ISSUE THREAD

**Issue by snaptopixel** [inertiajs/inertia#598]
### Versions:

- `@inertiajs/inertia` version: 0.8.6

### Describe the problem:

I've been debugging some infinite render/watch loops which started when we updated Inertia to the latest version.

I've boiled it down to the following scenario

- Page loads initially 👌 
- Stuff happens in the ui 👆 
- `Inertia.reload({only: 'foo'})` ♻️ 
- `visit` resolves and `this.page.props` is merged with the updated props 👌 
- `setPage` clones **all** props 🙅 
- All non-primitive props trigger updates in the component since they receive new values 🙅 
- Bad things happen 😭 

I believe the correct behavior is that _only_ the `only` props should be cloned and passed to `transformProps` and the rest should be merged as-is (by reference) since they have already been cloned and transformed previously. This will avoid any unnecessary and unpredictable updates from occurring.

**Comment by reinink** [comment]
Thanks for submitting this. This has been "fixed" by us removing `transformProps()` from Inertia. See #693 for more information. 👍
