### ISSUE TITLE
Partial page reloads

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#60]
Different sections of a page sometimes have different data requirements. For example a datatable with a set of dropdown filters: when you switch pages in the datatables, the dropdown data will also be refetched on the server. This isn't necessarily bad, but this can slow down your app with large datasets. 

Ideally, there would be a way to tell Inertia which data you _want_ changed, so it would only fetch and update subset of the page's data.

On the server, data would need to optionally be marked as potentially "lazy". In PHP/Laravel, the data could be wrapped in a callback:

```php
class UsersController extends Controller
{
    public function index()
    {
        return Inertia::render('Users/Index', [
            'users' => Users::paginate(),
            'countries' => function () {
                return Country::all();
            }
        ]);
    }
}
```

*(Sidenote: this only affects subsequent loads on the same page, the first visit will always fetch all of the page's necessary data)*

On the client, you'd need to be able to specify which data you want to reload. In Vue:

```js
this.$inertia.reload({ only: ['users'] });
```

This would send a request with an `X-Inertia-Only` header containing the `users` key, so Inertia can strip out the rest of the data on the server. The `Country::all()` database query would be completely skipped because it never gets evaluated.

When the request comes back, the new props will be merged with the old ones.

---

Kind of related to inertiajs/inertia-laravel#37

Thanks @reinink and @adamwathan for the feedback on this earlier 💪

**Comment by sebastiandedeyne** [comment]
Another use case is when you're handling modal state with Inertia. When you open a modal, the server needs to pass recalculate and pass down all data for whatever's in the view _behind_ the modal too. 

Partial reloads would allow you to ignore that data and just receive whatever's necessary for the modal itself.

**Comment by reinink** [comment]
Yes @sebastiandedeyne, I love it. I love the "partial reloads" name to this feature as well. Says exactly what it is.

I think we always need to be careful when adding features like this to not accidentally start turning Inertia.js into a typical SPA framework. I really want Inertia.js to be the server-side powered SPA. However, the closer we can walk the line, and gain the benefits of both approaches, without compromising what Inertia is, the better.

**Comment by iwasherefirst2** [comment]
Assume I have 1000 users for that endoint and I want to only update a single user, lets say userſ[49]. Can I do that with partial reloads as well?
