### ISSUE TITLE
useForm rememberKey is always 'string'

### ISSUE THREAD

**Issue by kmikey** [inertiajs/inertia#603]
### Versions:

- `@inertiajs/inertia` version: 0.8.6
- `@inertiajs/inertia-vue3` version: 0.3.10

### Describe the problem:

In the useForm function rememberKey constant is set to 'string'

### Steps to reproduce:
https://github.com/inertiajs/inertia/blob/b56e813f209927acce72791afdf4f2978d806f3a/packages/inertia-vue3/src/useForm.js#L6

should be:
```javascript
const rememberKey = typeof args[0] === 'string' ? args[0] : null
```

**Comment by reinink** [comment]
Shoot! 🤦‍♂️

Thanks for reporting.

This has been fixed: bef83aa8a131a01d34897ac3de4dbd5835f6ec2f
