### ISSUE TITLE
v-model for file input type

### ISSUE THREAD

**Issue by RomkaLTU** [inertiajs/inertia#605]
### Versions:

- `@inertiajs/inertia` version: ^0.8.6
- `@inertiajs/inertia-vue3` version: ^0.3.10

### Describe the problem:

How does v-model should work in an example if we can't use it with file input type?
VueJS will throw the error "v-model cannot be used on file inputs since they are read-only."
This should be updated in documentation. We need to use @change for file input.

**Comment by bedus-creation** [comment]
I exactly come through to it. Can you elaborate @RomkaLTU the solution ? 

```shell
VueCompilerError: v-model cannot be used on file inputs since they are read-only. Use a v-on:change listener instead.
```

**Comment by dillingham** [comment]
@bedus-creation 
```html
<input type="file" @input="form.avatar = $event.target.files[0])" />
```

**Comment by reinink** [comment]
This isn't really something Inertia needs to document, as this is known Vue behaviour, and isn't specific to Inertia.

**Comment by RomkaLTU** [comment]
Well, I disagree, there is a mistake in the documentation and that should be corrected imho. It's not about full implementation but you can't do v-model on file input type.

**Comment by reinink** [comment]
Oh I'm sorry, where is this wrong in the docs?

Feel free to create an issue in the [documentation repo](https://github.com/inertiajs/inertiajs.com), or even better, submit a PR to fix this. 👍

**Comment by reinink** [comment]
Ahh, found it: https://inertiajs.com/file-uploads

**Comment by reinink** [comment]
Updated: https://github.com/inertiajs/inertiajs.com/commit/73f6e1a16e502405c4c5d93db4eee73da47e29d0

In the future, please post documentation related issues in that repo. 👍
