### ISSUE TITLE
inertia-link tag creating odd spacing issue

### ISSUE THREAD

**Issue by liam-ot** [inertiajs/inertia#618]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-vue` version: 0.5.5

### Describe the problem:

I have a SPA built with vue2, laravel, and tailwindcss 2.x, on top of inertia. 

When applying an `inertia-link` tag to a reusable template, it completely alters the template's display

### Steps to reproduce:

```
            <!-- Item card container -->
            <div class="flex flex-col">
                <div class="p-4 my-6 flex flex-row overflow-x-scroll">
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                    <inertia-link :href="route('shop.productPage')"> <ProductCard :product="product" class="w-1/6"/> </inertia-link>
                </div>
            </div>
            <!-- End Item card container -->
```

with link applied cards render like:
![image](https://user-images.githubusercontent.com/48032728/114120322-42622780-98ba-11eb-8f1d-9682ebe618ab.png)

when inspecting the page and hovering over the element with the inertia-link, it shows the typical box around the `ProductCard` but with it a very large amount or right-margin between it and the next photo

this margin is not in my code

and without render like this:
![image](https://user-images.githubusercontent.com/48032728/114120511-a127a100-98ba-11eb-93d3-810fb54cf53d.png)

if there is more info needed please inform me, the code producing the second photo, the desired style, is identical to the one above but without the `inertia-link` tag

**Comment by liam-ot** [comment]
UPDATE:

oddly enough adding the inertia tag to the `ProductCard` vue component fixed it

from:
```
<template>
    <!-- Root div -->
    <div class="px-3">
        ...some code...
    </div>
    <!-- End Root div -->
</template>

<script>
export default {
    props: ['product'],
}
</script>
```

to:
```
<template>
    <!-- Root div -->
    <div class="px-3">
        <inertia-link :href="product.link">
            ...some code...
        </inertia-link>
    </div>
    <!-- End Root div -->
</template>

<script>
export default {
    props: ['product'],
}
</script>
```

still not sure what the issue was the other way but figure it should probably be noted

thanks for working on inertia, you guys are great!

**Comment by RSpeekenbrink** [comment]
By default `<inertia-link>` will render an anchor (`<a>`) tag. It seems like wrapping your div in de anchor tag changed your design.

**Comment by claudiodekker** [comment]
Hey 👋,

Yeah, Inertia doesn't set any element sizes or styles whatsoever, which means that any changes that might exist are definitely either in your CSS or browser-applied default styles. Because of this, as well as that this issue's been open forever, I'm going to close this issue for now.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!
