### ISSUE TITLE
Question: How to browser back correctly

### ISSUE THREAD

**Issue by michaelklopf** [inertiajs/inertia#64]
Hi everyone,

we currently have a Laravel application coupled with inertia. I was browsing the issues here and I'm not sure how to handle browser back correctly.

Scenario:

- visit a detail view in the application (page A)
- inertia-link to another page B where a form is filled in
- submit the form with `this.$inertia.post`
- in the controller do stuff, create a flash message and `redirect()->route` to page A again

- the flash message appears, everything is ok
- go to another page C to watch some information
- browser back to page A

- now, we see the flash message **again**

Why is that so? Probably because the browser back loads the cached data when page A was initially loaded which includes the flash message.

But what to do, so that the flash message is not appearing again?

Another scenario:

- a multi-step form process
- visit form A, fill in the data
- go from form A to B with a forward button
- the data is posted to the backend, saved and we redirect to form B

- we are in form B now
- go back to form A with the back button
- the form on A is empty, like our initial visit to the page

- go back to form A with a back button (inertia-link)
- the form is filled in, as done by the user

What would be the best way to show a fresh state of form A when the user presses browser back?

I'm not really sure what is expected behaviour here. When pressing browser back, do we want to see the page as it was initially loaded, or in the state the user left it in?

Would be nice if anyone could notch me in the right direction. Thank you in advance 🙏🏻

**Comment by reinink** [comment]
Hey thanks for your interest in Inertia!

So, Inertia is designed to mimic default browser behaviour, which is to show the _previous_ state when navigating history. We even have the "remember" functionality to help you cache local component state to history state, to ensure that form data (or whatever) is properly cached when navigating history.

Meaning, there is no way, at least right now, to show *fresh state* when pressing back. However, you could totally use the remember functionality to restore the form data (that was saved) when hitting back. Be sure to check that out!

**Comment by mariusberget92** [comment]
As this is a few years old I would like to ask if this is still the state of InertiaJS. I am facing the same problem as OP had in the first scenario. I display a toast flash message with SWAL, then when I go back and forward to that page again I will see the same flash message.

**Comment by zcuric** [comment]
> As this is a few years old I would like to ask if this is still the state of InertiaJS. I am facing the same problem as OP had in the first scenario. I display a toast flash message with SWAL, then when I go back and forward to that page again I will see the same flash message.

Yes, this is still the case.

**Comment by anchan42** [comment]
I found this after a long search and many battles with AI 🤣
https://www.vincentschmalbach.com/preventing-flash-messages-from-reappearing-on-browser-back-navigation-in-laravel-vue-inertia-apps/
