### ISSUE TITLE
VisitOptions missing onBefore TS definition?

### ISSUE THREAD

**Issue by devpake** [inertiajs/inertia#649]
https://github.com/inertiajs/inertia/blob/653ccdda512bdc73ce0491103f9ade0b803cdbb0/packages/inertia/index.d.ts#L27

`onBefore` does not seem to be defined within `VisitOptions` in the definition file but it is referenced in the docs [https://inertiajs.com/manual-visits](https://inertiajs.com/manual-visits).  Should it be added or is `onBefore` being deprecated?

**Comment by reinink** [comment]
Inertia core has now been updated to TypeScript, so this is no longer an issue. 👍
