### ISSUE TITLE
Reloading with data duplicate query parameters

### ISSUE THREAD

**Issue by dsazup** [inertiajs/inertia#65]
If I am on a `/users?page=1` page, and I click on a button that does 

```
Inertia.reload({
  data: {
    page: 1,
 }
```

I now see `/users?page=1&page=1`, and it keeps duplicating when I click again. Is this expected behaviour or is this a bug?

**Comment by Juhlinus** [comment]
Hello @dsazup ! 

It's the expected behavior. The replace method just fetches the current url and adds your parameters to it, so if you just pass the same argument data over and over, then the same data will be added to the URL. 

This might be something that we'd want to check for upon calling the method as to not generate the result you're experiencing.

Maybe something along these lines:
```javascript
  replace(url, options = {}) {
    return this.visit(url.split('?')[0], { preserveState: true, ...options, replace: true })
  },
```

**Comment by dsazup** [comment]
Ok, makes sense. It would be really nice if Inertia handled this, but I suppose this might be out of scope for this project. I'll leave it up to you guys to decide what you want to do with this issue 👍

**Comment by RSpeekenbrink** [comment]
Maybe its an idea to replace 'window.location.href' in:

https://github.com/inertiajs/inertia/blob/472c1d3daa455b67df68aa71b6e2a656724d9652/src/inertia.js#L160-L162

With something like:

```
window.location.origin
```

and some kind of parser to parse the current url parameters to the data object in the options function parameter? And the parser will prefer option data over current url parameters so you can 'replace' them?

Just some brainstorming :) it would be nice indeed to fix this in Inertia.

**Comment by anthony-lopez-dev** [comment]
@dsazup @Juhlinus @reinink 

It's just an idea, but don't you think it can be possible to put parameters as an object in shared data (`this.$page.parameters`) and use "[Vue Reactivity](https://vuejs.org/v2/guide/reactivity.html)" to watch when that object is modified. When the event is triggered, you rebuild url based on parameters object updated and use`Inertia.visit`.
May I have your opinion ? =)

I have a project where users can choice between showing 8 or 16 posts with a `<select>`. So I think it can be good to use that pattern and set params when my select change: `onChange : setParameters('per_page', $value)`

**Comment by hotmeteor** [comment]
Any solutions on this one?

**Comment by hotmeteor** [comment]
Alright, here's how I made it work (I'm using Ziggy as well):
```js
this.$inertia.replace(route(route().current(), route().params), {
    method: 'get',
    data: this.filters,
    replace: false,
    preserveState: true,
    preserveScroll: true,
    only: ['logs'],
})
```

**Comment by markkingDS** [comment]
This is how I was able to get it to work. Little different from what @hotmeteor used:

this.$inertia.replace(route(route().current(), {}), {
            method: 'get',
            data: {
                'sortBy': this.sort.by,
                'sortDirection': this.sort.direction,
                'searchTerms': this.terms,
                'page': this.page
            },
            preserveState: true,
            preserveScroll: true,
            only: ['data', 'searchTerms', 'sort']
        });

**Comment by rico** [comment]
I guess I still see this problem with `vue@3.2.34` and `inertia-vue3@0.6.0`. Anybody else or just me?

**Comment by MtDalPizzol** [comment]
Also facing this with `inertia-vue3@0.6.0`. `Inertia.get` with `window.location` didn't worked out for me.

**Comment by MtDalPizzol** [comment]
Sorry for commenting on a closed issue, but I'm not sure if what I'm facing is a bug or expected behavior:

When calling `Inertia.reload({ data })`, the parameters are replaced correctly, and not duplicated.
**However**, if some parameter is an array, **that array gets merged**.

To ilustrate:

```javascript
{
   search: 'term 1',
   date: ['2022-12-19', '2022-12-20']
}

// /?search=term%201&date[]=2022-12-19&date[]=2022-12-20

Inertia.reload({
   data: {
      search: 'term 2',
      date: ['2022-12-24', '2022-12-25']
   }
})

// Produces /?search=term%202&date[]=2022-12-19&date[]=2022-12-20&date[]=2022-12-24&date[]=2022-12-25
// Should be /?search=term%202&date[]=2022-12-24&date[]=2022-12-25
```

**Comment by danielsballes** [comment]
@MtDalPizzol 
Did you find any solve to the issue, I'm facing the same problem.

**Comment by philippbuerger** [comment]
I fixed it by using `router.get` instead of `router.reload`. As I understand the `router.reload()` is just a shorthand for `router.get(currentUrl)` but for some reason it fixed this issue for me.

**Comment by danielsballes** [comment]
@philippbuerger 
> I fixed it by using `router.get()` instead of `router.reload(currentUrl)`. As I understand the `router.reload()` is just a shorthand for `router.get(currentUrl)` but for some reason it fixed this issue for me.

Yeah, It's the same I did, idk why but seems like reload have a messy behavior

**Comment by aqordeon** [comment]
@philippbuerger 
> I fixed it by using `router.get(currentUrl)` instead of `router.reload()`. As I understand the `router.reload()` is just a shorthand for `router.get(currentUrl)` but for some reason it fixed this issue for me.

Although the Inertia docs says that `router.reload()` is a shorthand for `router.get(currentUrl)` but both of them have different behaviour. `router.get(currentUrl)` will rerun the code inside <script> in Vue 3 Composition API (idk Options API haven't tried), while `router.reload()` is not rerun the <script>

Stack: "vue": "^3.2.31", "@inertiajs/vue3": "^1.0.0"

**Comment by eddi00** [comment]
Same
