### ISSUE TITLE
form.onChange with useForm.setData triggers 'save password' modal when typing password

### ISSUE THREAD

**Issue by kioltk** [inertiajs/inertia#650]
### Versions:

- `@inertiajs/inertia` version: 0.8.5
- `@inertiajs/inertia-react` version: 0.5.4

### Describe the problem:

When using `setData` from `useForm` inside `onChange` event from `form`, when typing password after second character, it triggers browser to popup 'Do you want to save the password'. Appears on safari and some versions of chrome

### Steps to reproduce:

The component:
```
const { data, setData, errors, post, processing } = useForm();

<form onChange={(e) => { setData(e.target.name, e.target.value ?? e.target.value); }} />
   <input name="email" type="password" />
   <input name="password" type="password"/>
</form>
```
Start typing password, after 2 characters you will see 'save password' modal, but no `onSubmit` was triggered

You can also see the reproduction uploaded on heroku [here](https://ping-crm-useform-bug-example.herokuapp.com/login) and the example code on GitHub [here](https://github.com/kioltk/pingcrm-react/blob/form-onchange-example/resources/js/Pages/Auth/Login.js)

**Comment by kioltk** [comment]
Just updated `inertia` to `0.8.7` and `inertia-react` to `0.5.12` and it works perfectly.

**Comment by reinink** [comment]
@kioltk Good to hear! 👍
