### ISSUE TITLE
Errors produced when new JS bundle out of sync with history data

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#655]
Right now if you deploy an update to your Inertia app, which causes the JS assets to update in production, and then you go back in history, you can end up with JS errors, because the props saved in history state are out of sync with the new JS bundle.

There are theoretically two ways to fix this:

1. When the JS versions are out of date, refetch the data from the server when navigating history state. This sucks, since it's going to be new data, not the data shown when the page originally loaded, but it will at least work. We could potentially just force a full page reload when this happens, instead of trying to do this via an Inertia visit to get the fresh data from the server.
2. Try to find a way to preserve the previous JS bundle, and use that instead when navigating history. Honestly, this doesn't even sound possible. 😅

Point is, we need to keep the JS bundle and data (props) in sync somehow.

**Comment by claudiodekker** [comment]
Similar: #426
