### ISSUE TITLE
form.processing is not reset to false on request error

### ISSUE THREAD

**Issue by lucasromanojf** [inertiajs/inertia#657]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue3` version: 0.3.14

### Describe the problem:

After submitting a form, the "processing" property is not reset to false if the form.post call fails (example, 500 error).

### Steps to reproduce:

1) Submit a form using form.post
2) In the backend, throw an exception
3) The form's processing property keeps as true

**Comment by inlogicstudio** [comment]
> ### Versions:
> 
> ### Describe the problem:
> After submitting a form, the "processing" property is not reset to false if the form.post call fails (example, 500 error).

Check this link 
https://inertiajs.com/error-handling
https://inertiajs.com/forms

Also in a typical laravel application if you post a form and you encounter 500 error from the server   what is the behavior ? 

Think of inertia like that  the link above will help

**Comment by lucasromanojf** [comment]
> > After submitting a form, the "processing" property is not reset to false if the form.post call fails (example, 500 error).
> 
> Check this link
> https://inertiajs.com/error-handling
> https://inertiajs.com/forms
> 
> Also in a typical laravel application if you post a form and you encounter 500 error from the server what is the behavior ?
> 
> Think of inertia like that the link above will help

It was working before, it stopped working in some version. Also, if a form submit throws error, the form is not submitting anymore, so the logical behavior is that  submitting should be back to false again.

**Comment by reinink** [comment]
This has been fixed! 👍 

See #682.

Thanks for bringing this to our attention.
