### ISSUE TITLE
Inertia emitted events

### ISSUE THREAD

**Issue by theblindfrog** [inertiajs/inertia#66]
More of a question, than an issue per se... 

A couple of previous apps I've worked on have used turbolinks and vue - pretty much as @reinink described in his [article about backend apps with client rendering](https://reinink.ca/articles/server-side-apps-with-client-side-rendering)

What's useful about using turbolinks in this approach, is that it [emits a heap of events](https://github.com/turbolinks/turbolinks/blob/17ffb3ad2a7cf1987edacab65ea7339351193ce7/src/controller.ts#L236-L262), that your application can hook in to - for example - fire off analytics tracking, etc.

I think there might be merit for inertia.js to emit some of its own events for other parts of applications to latch on to.

For example, you could listen for events like `click`, `visit`, `hardvisit`, `restore`, under an `inertia` namespace:

```javascript
document.addEventListener('inertia:visit', (event) => {
    // do something, for example: 
    dataLayer.push({
      'url': event.data.path, // e.g. `/user/1/update`
      'event': event.data.trigger // e.g `updateProfile`
    });
});
```
If this is something that folks would find useful, I might be able to hack on a PR to add such a feature. 

Any thoughts?

**Comment by Juhlinus** [comment]
@theblindfrog This seems like cool feature indeed!

We should wait for feedback from @reinink and @sebastiandedeyne on this, but I don't see any reason why this wouldn't be good feature for the framework. 😄

**Comment by sebastiandedeyne** [comment]
I like this idea, maybe we could even use it internally to deal with the loading indicator (it would also provide a way for users to implement custom loading indicators)

**Comment by theblindfrog** [comment]
@sebastiandedeyne That's an _even better_ use-case for something like this. 

After more thought, what I'm trying to do could be achieved in the 'layout' layer of my app (or most apps, fwiw) - firing off a new pageview to analytics as new frontend component(s) are created.

Depending on what @reinink's view is, the original thrust of this issue might not be relevant; even if the 'loading indicator' use-case may warrant another look.

**Comment by reinink** [comment]
So, events are certainly on my radar. However, I can't decide if they offer any real benefit over simply providing additional configuration options, either at the adapter level, or even with Inertia core.

**Comment by theblindfrog** [comment]
Fair point @reinink. Perhaps they're the 'easy' way to offer some of this functionality; in contrast to more elegant implementations.

I'll close this issue. Thanks!

**Comment by ellefsen** [comment]
Did any of this make it into v.1? I'm having some difficulties figuring out how to fire my analytics events. Any existing strategies you guys know of that would work with Inertia?

**Comment by theblindfrog** [comment]
AFAIK emitted events have not made it into inertia.. but I solved this by adding my analytics/tracking code to the 'Layout' view (vue, jsx, etc) of inertia.

So for vue, you could do something like

```vue

<template>
// your layout
</template>

<script>

export default {

  props: {
    url: String,
  },

  mounted() {

    // Google Analytics via GTM
    dataLayer.push({
        'event': 'pageView',
        'virtualUrl': this.$inertia.page.url;,
    });

  }
}
</script>

```

Hope that helps @ellefsen

**Comment by ellefsen** [comment]
Thanks. That does work for now. I figured it wouldn't because Vue wouldn't re-render the layout component on each page request, but it does so for now that's how I'll roll.

Thanks @theblindfrog !

**Comment by theblindfrog** [comment]
Ha! I had those same thoughts initially too.
PingCRM used to (now uses a plugin) update the document title in a similar way. 
https://github.com/inertiajs/pingcrm/blob/424aeff32218983c01f0f7617887b224e7c93117/resources/js/Shared/Layout.vue#L74-L81

**Comment by ledermann** [comment]
Recently I noticed that [transformProps](https://inertiajs.com/transforming-props) can be used as event hook. It is executed on every response received by Inertia.

Example usage here:
https://github.com/ledermann/pingcrm/blob/638bdd82a0a64a7462555215ebfff71c3472a827/app/javascript/packs/application.js#L51-L63

**Comment by theblindfrog** [comment]
Nice find @ledermann!

**Comment by reinink** [comment]
Reopening, as this is something we still need to deal with. 👍

**Comment by pedroborges** [comment]
I haven't needed events with Inertia myself but I see it could be very useful. What about extending the `Inertia` object with [mitt](https://github.com/developit/mitt)? The API for subscribing to Inertia events would look like:

```js
Inertia.on('click', event => /* ... */)
Inertia.on('visit', url => /* ... */)
```

**Comment by marvinrabe** [comment]
For example Turbolinks uses the default DOM event listeners.

> Turbolinks emits events that allow you to track the navigation lifecycle and respond to page loading. Except where noted, Turbolinks fires events on the document object.

Maybe this can be used in Inertia aswell. So dispatching events are as simple as:

```js
    const event = new Event('inertia:visit')
    document.dispatchEvent(event)
```

Everyone can listen to events like this:

```js
    document.addEventListener('inertia:visit', () => alert('visit'))
```

This is a solution that relies heavily on the DOM though.

Another solution might be using an event emitter like component/emitter.

**Comment by itguy614** [comment]
Adding my interest to this.  We have been using some very 'hacky' solutions to update a complex navigation structure.  Hooking into an event in the navigation component to listen for an inertia page load would be much more elegant.

**Comment by iamniels** [comment]
Adding my interest as well. Need it to update navigation as well and to log every click to a database.

**Comment by Stian-Scholtz** [comment]
> I haven't needed events with Inertia myself but I see it could be very useful. What about extending the `Inertia` object with [mitt](https://github.com/developit/mitt)? The API for subscribing to Inertia events would look like:
> 
> ```js
> Inertia.on('click', event => /* ... */)
> Inertia.on('visit', url => /* ... */)
> ```

This would be very usefull. One case I would like to use it is when I want to display a custom loading indicator. I.e. when inertia emits a loading event I can display my loader accordingly.

**Comment by reinink** [comment]
@Stian-Scholtz Coming soon: #208 😉

**Comment by reinink** [comment]
The new event system (#208) has been merged in. I hope to tag a release tomorrow, and I also plan to add documentation to the website explaining how to use it. 🙌
