### ISSUE TITLE
Laravel Echo and InertiaJS dont mix

### ISSUE THREAD

**Issue by peterson-umoke** [inertiajs/inertia#665]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5
- `inertiajs/inertia-laravel` version: 0.3.5

### Describe the problem:
By default, setting up Laravel echo is a breeze,  but for some reason, using Laravel echo, Laravel websockets and Inertiajs doesn't seem to return the right json response.

i keep getting this error from the broadcasting/auth endpoint: 
`{type: "AuthError", error: "JSON returned from auth endpoint was invalid, yet status code was 200. Data was: ", status: 200}` 

### Steps to reproduce:
1. Create a clean fresh laravel project
2. run `composer require laravel/breeze --dev`
3. Run `php artisan breeze:install --dev`
4. run `npm install --save-dev laravel-echo pusher-js`
5. Uncomment the laravel echo configuration in your bootstrap.js file and replace it with the code 
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    forceTLS: true,
    disableStats: true,
});
```
6. Run `composer require beyondcode/laravel-websockets`
7. run `php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="migrations"`
8. run `php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="config"`
9. run `php artisan migrate`
10. Head over to config/broadcasting.php, and replace the pusher configuration with the following code
```
'driver' => 'pusher',
'key' => env('PUSHER_APP_KEY'),
'secret' => env('PUSHER_APP_SECRET'),
'app_id' => env('PUSHER_APP_ID'),
'options' => [
    'cluster' => env('PUSHER_APP_CLUSTER'),
    'host' => '127.0.0.1',
    'port' => 6001,
    'scheme' => 'http',
    'useTLS' => false,
],
```
11. head over to config/websockets.php and replace apps array cofig with 
```
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
```
 12.headover to resources/js/Pages/Welcome.vue and just insert this code right after the props objects
 ```
mounted() {
        Echo.join(`chat`)
            .here((users) => {
                console.log(users.id);
            })
            .joining((user) => {
                console.log(user);
            })
            .leaving((user) => {
                console.log(user);
            })
            .error((error) => {
                console.error(error);
            });
    }
```
13. Lastly head over to config/app.php and uncomment broadcast service provider from line 174

**Comment by peterbabic** [comment]
@peterson-umoke Why did you close this? Did you find it working in the end?
