### ISSUE TITLE
v-if not toggled upon client -> server -> client

### ISSUE THREAD

**Issue by heychazza** [inertiajs/inertia#678]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

I've got a form that a user enters their game server address, and upon clicking the Check button - a request is sent back to the server to check this game server. After, the response is sent back to the client. The issue I currently face is that 'connected' is then set to true, however the `v-if="connected"` is never toggled.

### Steps to reproduce:

https://pastebin.com/Wk8PpR3c
https://pastebin.com/96npCCLs

**Comment by inlogicstudio** [comment]
@heychazza  move the post request to a controller instead of doing it in the route 

And in your component make use of a function to submit that form so that you will be able to make use of the form methods like preserve state 
Try this let's see

**Comment by heychazza** [comment]
> @heychazza move the post request to a controller instead of doing it in the route
> 
> And in your component make use of a function to submit that form so that you will be able to make use of the form methods like preserve state
> Try this let's see

I kept it in the route just temporary, or does moving to a controller make a difference with the issue I have?

I do use preserve state in the form `form.post('/add', { preserveState: true })`

**Comment by reinink** [comment]
I'm honestly not sure what's wrong here. It's very hard to read the code on PasteBin. In the future, please just post the code here on GitHub. Also, for what it's worth, `preserveState` is automatically set to `true` when doing a `post` request, so you don't need to manually set this.

I'd recommend inspecting the response that comes back from the server, to verify that `connected` is ACTUALLY being set to `true`. You might want to even just output in your template somewhere to see that's updating.

I'd also recommend updating to the latest versions of both Inertia, the Inertia Vue 3 adapter, and Vue 3 itself.

If all that fails, please provide a SIMPLE demo app that reproduces this issue, and I can have another look.

Good luck. 👍
