### ISSUE TITLE
PreserveScroll option is ignored by form helper

### ISSUE THREAD

**Issue by marcomessa** [inertiajs/inertia#679]
### Versions:

- `@inertiajs/inertia` version: 0.8.4
- `@inertiajs/inertia-vue3` version: 0.3.5

### Describe the problem:

Preserve Scroll option is ignored with form helper.

### Steps to reproduce:
Just try a post visit using the form helper: the scroll is always resetted.

```js
setup(props) {
    const form = useForm({
      title: null,
      content: null,
      score: 1,
    })

    const addReview = () => {
      form.submit('post', route('review.create', {course: props.course.slug}, {
        data: form,
        preserveScroll: true
      }))
    }

    const setScore = (value) => {
      form.score = value
    }

    return {form, addReview, setScore}
  },
```

If I use Inertia.post() it works flawlessly
```js
const addReview = () => {
      Inertia.post(route('review.create', {course: props.course.slug}), form, {
        preserveScroll: true
      })
    }
```

Hope this helps!!

**Comment by reinink** [comment]
Hmm, this is wrong. You've added options to the `route()` method:

```js
const addReview = () => {
  form.submit('post', route('review.create', {course: props.course.slug}, {
    data: form,
    preserveScroll: true
  }))
}
```

Try this instead:

```js
const addReview = () => {
  form.submit('post', route('review.create', { course: props.course.slug }), {
    preserveScroll: true
  })
}
```

Or even better, this:

```js
const addReview = () => {
  form.post(route('review.create', { course: props.course.slug }), {
    preserveScroll: true
  })
}
```

Also, keep in mind that you don't need to pass the data manually (`data: form`), as the form helper handles this for you.

**Comment by marcomessa** [comment]
@reinink you are totally right! I wrote really in a hurry and didn't notice I was passing options to the route method! I apologize for the false alarm!

p.s. ty for the data tip!
