### ISSUE TITLE
Module not found: Error: Can't resolve '@/Shared/Layout'

### ISSUE THREAD

**Issue by stoneC0der** [inertiajs/inertia#687]
### Versions:

- `@inertiajs/inertia` version: ^0.8.7
- `@inertiajs/inertia-vue` version: ^0.5.12

### Describe the problem:

I am trying to import the Shared/Layout.vue in Pages/Home.vue, the docs said to import it using:

```import Layout from "@/Shared/Layout";```

but I get this error:

Module not found: Error: Can't resolve '@/Shared/Layout'

But it works with

```import Layout from "../Shared/Layout";```

I follow the step from the docs without skyping any, I use Laravel-Mix 6 and I configured babel for dynamic import.

### Steps to reproduce:

The steps I use are the same as the ones on the docs.

**Comment by freakzlike** [comment]
Check your webpack config it should contain something like:
```js
// ...
resolve: {
  alias: {
     '@': path.resolve('resources/js') // or other path to your files
  }
}
// ...
```

If you are using Typescript, then import vue components with file ending ".vue" `import Layout from "../Shared/Layout.vue";`

**Comment by stoneC0der** [comment]
Thank you very much!
