### ISSUE TITLE
Children components?

### ISSUE THREAD

**Issue by n7olkachev** [inertiajs/inertia#70]
First of all, nice idea as always @reinink!
What do you think about going deeper and allowing to return children components from backend?

**Comment by georgehanson** [comment]
For things like this it would be best for the component itself to handle this. It would make a `GET` request to the backend to retrieve whatever data it needed to update.

**Comment by sebastiandedeyne** [comment]
It's not documented yet, but we recently added support for partial reloads to help reduce the amount of extra endpoints you need to build for this: https://github.com/inertiajs/inertia/pull/61

@n7olkachev could you provide an example of what you mean with child components?

**Comment by sebastiandedeyne** [comment]
Going to close this for now. Feel free to open a new issue with a more detailed description!
