### ISSUE TITLE
Error prop is only showing one error for each key

### ISSUE THREAD

**Issue by hcancelik** [inertiajs/inertia#703]
### Versions:

Package.json
- `@inertiajs/inertia` version: 0.9.0
- `@inertiajs/inertia-vue3` version: 0.4.1

Composer.json
- `inertiajs/inertia-laravel` version: 0.4.2

### Describe the problem:

Not sure if this is intended behavior or I am missing something else but when there are multiple errors for the same key, the error prop is only showing a single error for that key.

### Steps to reproduce:

Assume this is the validation rule in Laravel.

```php
$request->validate([
    "title" => ["min:25", "endsWith:test"],
]);
```

When the title fails on both validation rules the `errors` prop only shows one error even though the `errorBag` has both errors.

errors prop
```js
  errors: {
    title: "Title must be at least 25 characters"
  }
```

attrs errorBags
```js
errorBags: {
  default: {
    title: [
      "Title must be at least 25 characters",
      "Title must end with one of the following: test",
  }
}
```

**Comment by emargareten** [comment]
@hcancelik this is the intended functionality, you can override `resolveValidationErrors()` in your Inertia middleware how the errors should be returned.

**Comment by hcancelik** [comment]
@emargareten Thanks for the reply and pointing me to the right direction. Much appreciated.

**Comment by reinink** [comment]
Yup, exactly as @emargareten has said. You can read more about this here: https://inertiajs.com/releases/inertia-laravel-0.2.9-2020-09-05

To get an array of errors, do something like this instead:

```php
'errors' => function () {
    return Session::get('errors')
        ? Session::get('errors')->getBag('default')->getMessages()
        : (object) [];
},
```
