### ISSUE TITLE
Having a problem with firefox browser back button and preserving scroll position

### ISSUE THREAD

**Issue by themebon** [inertiajs/inertia#706]
### Versions:

- `@inertiajs/inertia` version: 0.4.2
- `@inertiajs/inertia-vue3` version: 0.4.0

I was testing inertia.js and vue3.js and come upon a strange behavior when using Firefox. Firefox does not preserve the scroll position when click on <inertia-link></inertia-link> (scroll position should on top when I am in new page) and also going back (pressing the browser back button), but Google Chrome does.

Is this a Vue or maybe Inertia problem? Any explanation is welcome.

Firefox is: 89.0 (64-bit) Tried also with Brave & Google Chrome and those preserve scroll when going page back. (Chromium-based)

**Comment by reinink** [comment]
You are on a VERY old version of `@inertiajs/inertia`, which is not compatible with `@inertiajs/inertia-vue3@0.4.0`. I'm honestly surprised the app works at all.

I'd recommend updating to the latest version of both. I suspect that will fix your issues.
