### ISSUE TITLE
"Overflow: hidden" set on <body> element

### ISSUE THREAD

**Issue by Propaganistas** [inertiajs/inertia#708]
### Versions:

- `@inertiajs/inertia` version: 0.9.1
- `@inertiajs/inertia-vue` version: 0.6.2

### Describe the problem:

The `<body>` element receives `overflow: hidden;` styling without any reason.
This wasn't the case before upgrading.

### Steps to reproduce:

Upgrade `inertia` from 0.8.* to 0.9.*
and `inertia-vue` from 0.5.* to 0.6.*

**Comment by sinnbeck** [comment]
Any chance that it is when a modal is opened?

https://github.com/inertiajs/inertia/blob/e8495240aed73a7b5e6428a9551af19c1951b3ca/packages/inertia/src/modal.ts#L32

**Comment by Propaganistas** [comment]
I found that line as well, but I don't make use of the modal feature..

**Comment by reinink** [comment]
Hmm, I suspect this is the result of another library. Other than the Inertia modal (which only gets shown when a non-Inertia response is received), we don't set any styles at all with Inertia. I've also checked my own demo apps on Vue 2 and the latest versions of Inertia, and they too are not getting `overflow: hidden` on the body.

I'm going to close this, but feel free to provide a small demo app that reproduces this, and I'd be happy to look into it again. 👍
