### ISSUE TITLE
Return page object after Inertia.visit

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#71]
In PingCRM there's a part where the `$page` property is checked to determine what to do next after a visit.

https://github.com/inertiajs/pingcrm/blob/4b8849ac43aa0519e770068ce7a6d88774a2bba0/resources/js/Pages/Users/Edit.vue#L83-L90

This works in Vue, but is not possible in React because of the way state in React works. (at least not in a straightforward way)

How about we return the new `$page` object in the promise instead, so it works everywhere?

The PingCRM code would become:

```js
this.$inertia.post(this.route('users.update', this.user.id), data)
  .then(page => {
    this.sending = false
    if (Object.keys(page.errors).length === 0) {
      this.form.photo = null
      this.form.password = null
    }
})
```

**Comment by reinink** [comment]
@sebastiandedeyne Is this still an issue in React, or have you found a sensible workaround here?

I ask because we've deprecated the visit promises in favour of the new event callbacks. However, if this problem still exists, we could potentially return the page object to the `onSuccess()` callback.

**Comment by sebastiandedeyne** [comment]
This is still an issue. I think the `onSuccess` callback is a good solution to this.

Maybe the new event system could provide a workaround, but I think that'd be a weird place to do that.

**Comment by reinink** [comment]
Yeah, okay cool. I think we can make this happen.

Next question then, should the `onSuccess()` callback get the whole page object (url, version, props), or just the props?

Option 1 (entire page object)

```js
return onSuccess(this.page)
```

Option 2 (props only)

```js
return onSuccess(this.page.props)
```

Option 3 (treat props as the page, but include the url)

```js
return onSuccess({
  page: this.page.props,
  url: this.page.url,
})
```

So, this is tricky, because right now in the Vue.js adapter, `$page` is actually just the props. We made this decision to avoid having to do `$page.props` every time. However, there are times where having access to the URL would be nice (`$page.url`), so I've considered adding a `$url` property as well.

Either way...do we need to be consistent here?

**Comment by reinink** [comment]
To be honest, I kind of hate that we ever scoped `page.props` to `$page` in Vue.js. Yes, it's a nice convenience, but in reality I think it confuses what the "page" object is in Inertia.js. I kind of feel like we should move toward not doing this, and MAYBE even consider making this a change in the Vue.js adapter.

**Comment by reinink** [comment]
Okay, `onSuccess()` now receives the `page` object.

Considering this issue resolves. 🙌

**Comment by steven-lury** [comment]
@reinink  `onSuccess` or other eventListener doesn't work in my project but when I use `then` it works. Do you have any idea

**Comment by claudiodekker** [comment]
@steven-lury Probably you're using an outdated version of Inertia, as the `onSuccess` and other event listeners were introduced in `@inertiajs/inertia` version `0.3.0`: https://github.com/inertiajs/inertia/releases/tag/v0.3.0

Could you try updating both the `@inertiajs/inertia` package in your application, as well as your stack-specific (react, vue, svelte) JS adapters? I believe that should solve your issue.

**Comment by grantholle** [comment]
I haven't found the reasoning on deprecating promises. Could someone elaborate for me?
