### ISSUE TITLE
Vue component is compiled and rendered twice.

### ISSUE THREAD

**Issue by digitalam025** [inertiajs/inertia#716]
### Versions:

- `@inertiajs/inertia` version: 0.9.1
- `@inertiajs/inertia-vue3` version: 0.4.2
- `Laravel` version: 8.x

### Describe the problem:

Both `app.js` and my component `Index.vue`  are being compiled.

Hence, `Index.vue` is being mounted twice. I suspect it's 
```resolve: (name) => import('./Pages/${name}')``` (as shown in `Client-side Setup` in the [docs](https://inertiajs.com/client-side-setup) and below:

```
createInertiaApp({
    resolve: (name) => import(`./Pages/${name}`),
    setup({ el, app, props, plugin }) {
        createApp({ render: () => h(app, props) })
            .use(plugin)
            .mount(el)
    },
})
```

When I use `resolveComponent:` as below,
```
createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(`./Pages/${name}`).default,
        }),
})
```
the components are mounted as usual.

### Steps to reproduce:

- Install Laravel Breeze with Inertia per the [docs](https://laravel.com/docs/8.x/starter-kits#breeze-and-inertia)
- Update  `@inertiajs/inertia`  and  `@inertiajs/inertia-vue3`  to versions stated above.
- Follow `Client-Side Setup` from Inertia Docs (link above)
- Create new component in `resources/js/Pages`.
- Add `mounted()` function and `console.log('Hello world!')`
- Switch from `createInertiaApp` block to `createApp` block to notice the changes.

### What to expect:

`Hello world!` to be logged only once in console.

**Comment by jaulz** [comment]
Same case with `vue2`. I think the component is rendered initially when the component is mounted and then again when `Inertia` is initialized (via `swapComponent`).

**Comment by reinink** [comment]
Yes, this is expected behaviour, given the way that we now initialize Inertia. Does this matter? My understanding is that client-side apps should be designed in such a way that they can re-render at any time. And, practically speaking, from my experience, they often do.

**Comment by jaulz** [comment]
Client-side apps should definitely be designed that they can re-render at any time but then you will keep an instance of the component (at least for stateful components). At the moment the component itself is instantiated twice and any logic in `mounted` is executed twice:
![image](https://user-images.githubusercontent.com/5358638/120811423-40c87f00-c54c-11eb-832d-b4f3522b9d0e.png)

![image](https://user-images.githubusercontent.com/5358638/120811453-4625c980-c54c-11eb-8439-9e46a5e267da.png)

If you retrieve some data from an API or have some other expensive logic you would trigger it twice consequently.

**Comment by digitalam025** [comment]
Yup, I do agree that these apps should be able to re-render at any time. My only concern with this is just the performance issues that this might unnecessarily cause. (No hard facts on this, maybe someone could help to prove it wrong/right)

But come to think about it, I don't think it matters. It's just a minute difference 👍🏻 Thanks!

**Comment by reinink** [comment]
@jaulz Great point. I think I've got this fixed. See #724.
