### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by ellefsen** [inertiajs/inertia#72]
I've been struggling to have Inertia and Inertia-vue working with IE11.

Is there an official browser support chart for Inertia?

The first issue I ran into was 'Promise is undefined', and once I managed to transpile it I'm just seeing a blank page with no errors.

Any ideas? Shouldn't this repo be transpiled before it's published to npm?

**Comment by gregupton** [comment]
Check this out: 

https://stackoverflow.com/questions/56446904/transpiling-es6-for-ie11-with-babel

**Comment by ellefsen** [comment]
Thanks! That worked.

It did add ~100kb to my js file though so it would have been a lot cheaper to set `useBuiltIns: 'usage'` when compiling babel. Or at least know which polyfills are needed.

**Comment by 7ammer** [comment]
@ellefsen, I've not used inertia.js yet but https://polyfill.io/v3/ might be of interest.
