### ISSUE TITLE
 Browser back button navigation does not trigger event "before" 

### ISSUE THREAD

**Issue by Archheretic** [inertiajs/inertia#721]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-react` version: 0.5.12

### Describe the problem:

When user is using back button navigation in browser the "before" event is not triggered.
The "navigate" event is triggered, but since this is not a cancelable event we can not use this to trigger a window.confirm to prevent loss of unsaved data. 

In a traditional none SPA the event "beforeunload" is triggered before all browser navigation including "back button" navigation. Therefore the  expected behavior would be that the Inertia "before" event is also triggered before this kind of navigate event. 

This can be pasted into browser console in a not SPA to test default browser behavior:
`
window.addEventListener('beforeunload', function (e) {
  // Cancel the event
  e.preventDefault(); // If you prevent default behavior in Mozilla Firefox prompt will always be shown
  // Chrome requires returnValue to be set
  e.returnValue = '';
});
`

### Steps to reproduce:
1. Insert this into a react component 
`
	useEffect(() => {
		const removeEventListener = Inertia.on('before', event => {
			if (
				!window.confirm(
					'You got unsaved changes, are you sure you want to navigate?'
				)
			) {
				event.preventDefault();
			}
		});
		return () => {
			removeEventListener();
		};
	}, []);
`
2. Mount the react component.
3. Click browser back button.

**Comment by reinink** [comment]
So it's not possible to prevent history navigation (`popstate` events -  [see here](https://stackoverflow.com/questions/32432296/is-it-possible-to-e-preventdefault-in-window-onpopstate)), otherwise we probably would support this.

I completely agree though, this would be nice to do. But, this is a limitation of the browsers, and not something we can control.
