### ISSUE TITLE
Can't find `InertiaHead` when using TypeScript

### ISSUE THREAD

**Issue by Lloydinator** [inertiajs/inertia#722]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-react` version: 0.5.12

### Describe the problem:

I'm using TypeScript. When trying to use InertiaHead in the way described by the docs, I get the error "Module '"@inertiajs/inertia-react"' has no exported member 'InertiaHead'." When I try `import InertiaHead from '@inertiajs/inertia-react'`, I get  `JSX element type 'InertiaHead' does not have any construct or call signatures.`. Should I make a _*.d.ts_ file and declare it? What should I put in it?

### Steps to reproduce:

My _tsconfig.json_ file looks like this:

```
{
  "include": [
    "./resources/js/**/*.ts",
    "./resources/js/**/*.tsx", 
    "admitr.d.ts"
  ],
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    "target": "es5",                               
    "module": "esnext",                         
    "lib": ["es6", "es7", "dom"],                                  
    "jsx": "react",                              

    /* Strict Type-Checking Options */
    "strict": true,                                 

    /* Module Resolution Options */
    "moduleResolution": "node",                 
    "baseUrl": ".",                             
    "esModuleInterop": true,                        

    /* Advanced Options */
    "skipLibCheck": true,                          
    "forceConsistentCasingInFileNames": true        
  }
}

```

**Comment by reinink** [comment]
You need to be on [@inertiajs/inertia@0.9.0](https://inertiajs.com/releases/inertia-0.9.0-2021-05-25) and [@inertiajs/inertia-react@0.6.0](https://inertiajs.com/releases/inertia-react-0.6.0-2021-05-25) to use the new head features. 👍

**Comment by BertvanHoekelen** [comment]
@reinink I think it's because it's not exported in index.d.ts.

**Comment by reinink** [comment]
@BertvanHoekelen That's true, it's not. We don't maintain the TypeScript file in the adapters...that's community driven. Feel free to submit a PR. 👍 

(Eventually we hope to convert the adapters to TypeScript, just like Inertia core.)
