### ISSUE TITLE
Vue3 example on Client-side setup pages leads to unwanted code splitting

### ISSUE THREAD

**Issue by veerman72** [inertiajs/inertia#727]
### Describe the problem:
The example uses the `import` command instead of `require` in the `resolve` callback. This leads to the code splitting as explained under the section **code splitting** whilst this example should lead to one file.

`resolve: (name) => import(`./Pages/${name}`),` 

### Steps to reproduce:
https://inertiajs.com/client-side-setup

**Comment by reinink** [comment]
Hey thanks so much for catching this. This has been fixed, and it's deploying to production right now. 👍
