### ISSUE TITLE
Canvas elements break Inertia.js navigation in 0.9.2

### ISSUE THREAD

**Issue by marvinrabe** [inertiajs/inertia#730]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue` version: 0.6.2

### Describe the problem:

Visiting Pages with Chart.js have this error:

```
Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': CanvasRenderingContext2D object could not be cloned.
    at e.n.replaceState
    at e.n.saveScrollPositions 
    at e.n.resetScrollPositions 
```

This breaks navigation completely. I can not navigate to other pages after visiting pages with Chart.js graphs.

I have not enabled preserve-scroll anywhere.

This problem did not exist in 

    "@inertiajs/inertia": "^0.8.2",
    "@inertiajs/inertia-vue": "^0.5.4"

### Steps to reproduce:

1. Visit page with Chart.js or similar canvas element.

**Comment by reinink** [comment]
I am using Chart.js in an Inertia and Vue 2 project, and I have not run into this issue.

Can you please provide a minimum app that reproduces this issue?

**Comment by marvinrabe** [comment]
I think this relates somehow to `vue-chartjs`. I am removing `vue-chartjs` now and everything works as expected.

**Comment by grantholle** [comment]
I also encountered this. The problem is that it's related to `$page.props` and object references. For example, this throws the error, as `vue-chartjs` must be modifying `chartData`

```js
data () {
    const data = this.$page.props.statusCounts

    return {
      chartData: data,
    }
  }
```

But if I clone the prop, it works fine:

```js
import cloneDeep from 'lodash/cloneDeep'

//

// Clone the prop instead of using it directly
const data = cloneDeep(this.$page.props.statusCounts)
```
