### ISSUE TITLE
Typescript error when using some options inside form.post(url, options)

### ISSUE THREAD

**Issue by Bjornar97** [inertiajs/inertia#735]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.5

### Describe the problem:
We are using method specific function on the formhelper in Composition API, for example "form.post(url, options)". We want to use some options, such as onSuccess and preserveScroll. If we include those, we get an error from Typescript saying we are missing the following properties from type 'Visit': method, data, replace, preserveState and 4 more. It looks like all the options are required in the Typescript Visit type. Should they not be optional?

### Steps to reproduce:
1. Use the setup function in a component
2. Create a form using `const form = useForm(data)`
3. Try to submit the form:
      ```javascript
      form.post(url, {
          onSuccess: () => {
            emit("success");
          },
          preserveScroll: true,
      })
      ```
4. Typescript will show an error: 
      ```
      TS2345: Argument of type '{ onSuccess: (page: Page) => void; preserveScroll: true; }' 
        is not assignable to parameter of type 'VisitOptions'.
      
      Type '{ onSuccess: (page: Page) => void; preserveScroll: true; }' is missing the following properties from type 'Visit': 
        method, data, replace, preserveState, and 4 more.
      ```

**Comment by reinink** [comment]
The TypeScript files in the adapters are community driven. We hope to eventually convert them to TypeScript (as we did with Inertia core), but until then, if there are issues, please submit a PR to correct any issues. 👍

**Comment by Bjornar97** [comment]
@reinink I poked around a bit and it seems like the type used for options is referencing the VisitOptions type from core.

**Comment by Bjornar97** [comment]
We found a workaround:
```typescript
    import { VisitOptions } from "@inertiajs/inertia";

      form.patch(url, {
        onSuccess: (page) => {
          emit("success");
          setMode("view");
        },
        preserveScroll: true,
      } as VisitOptions);
```
page parameter needs to be supplied in the onSuccess and we write as VisitOptions after the options object

I am pretty new to Typescript, so I dont feel comfortable edititing the types in the repo.

**Comment by reinink** [comment]
> I am pretty new to Typescript, so I dont feel comfortable edititing the types in the repo.

Exactly how I feel 😅
