### ISSUE TITLE
Property data-page does not update after visiting links or redirect back after form post

### ISSUE THREAD

**Issue by DrooLTU** [inertiajs/inertia#736]
Jetstream with inertia and vue

Hello, I am chasing a solution for a very strange issue or bug.

I have a page to CRUD a model. Issue is I get this error every time I do $inertia.post: "Uncaught (in promise) TypeError: null has no properties". I was googling the hell out of this issue but nothing helps.

However I noticed something while troubleshooting:
1. If I do a 'delete' on one item prior to posting - everything works as expected and after $inertia.post it load data correctly.
2. I noticed that the 'data-page' property of `<div id="app">` DOES NOT update with new data when I visit other page links or redirect back after CUD form action. Is it supposed to be so?

What can be causing this issue?

Template code where this is happening, let me know if more needed:

`<template>

    <app-layout v-bind:form="form" v-bind:items="items">

        <template #header>

            <h2 class="font-semibold text-xl text-gray-800 leading-tight">

                Inventorius

            </h2>

        </template>

        <div class="py-12">

            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-4 py-4">

                    <button @click="openModal()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3">Sukurti naują</button>

                    <div class="grid grid-cols-1 md:grid-cols-3">
                        <span v-for="row in items" :key="row.id">
                            <item-card  @edit="edit" @deleteRow="deleteRow" v-bind:item="row"></item-card>
                        </span>
                    </div>

                </div>

            </div>

        </div>

        <item-form @images="handleImages" v-model:isOpen="isOpen" v-model:editMode="editMode" v-model:form="form" v-model:checkedAttributesB="checkedAttributesB"></item-form>

    </app-layout>

</template>

<script>
    
    import AppLayout from '@/Layouts/AppLayout'
    import ItemForm from "./CUItemForm"
    import ItemCard from "./ItemCard"
    
    export default {

        components: {

            AppLayout,
            ItemForm,
            ItemCard,

        },

        props: ['items'],

        data() {

            return {

                isOpen: false,

                editMode: false,

                checkedAttributesB: [],

                form: {

                    name: null,

                    description: null,

                    images:[],

                    attribute: false,

                    parents: [],

                    children: [],

                },

            }

        },

        watch: {

            checkedAttributesB: function(){
                console.log(this.checkedAttributesB);
                this.form.children = this.checkedAttributesB;
            },
            
        },

        methods: {

            handleImages(files){

                this.form.images = Object.assign({}, files);
                
            },

            openModal: function () {

                this.isOpen = true;

            },

            edit: function (data) {

                this.form = Object.assign({}, data);

                if(data.attributes.length){

                    this.form.children = data.attributes;

                }
                

                this.editMode = true;

                this.openModal();

            },

            deleteRow: function (data) {

                if (!confirm('Ar tikrai norite ištrinti?')) return;

                data._method = 'DELETE';

                this.$inertia.post('/items/' + data.id, data)

            }

        }

    }

</script>`

**Comment by reinink** [comment]
Can you please add versions (as per the issue template) and clean up the code you posted.

```
- `@inertiajs/inertia` version: #.#.#
- `@inertiajs/inertia-vue` version: #.#.#
```

**Comment by reinink** [comment]
Closing this for now due to lack of reply. Please feel free to share your versions and clean up the code samples, and we have have another look. Please also include your server-side code if you do. 👍
