### ISSUE TITLE
@vue/compat: Cannot read property 'shapeFlag' of null 

### ISSUE THREAD

**Issue by jaulz** [inertiajs/inertia#743]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue` version: 0.6.2

### Describe the problem:

The application dumps with the newest @vue/compat package. It seems like this piece of code is causing issues:
https://github.com/inertiajs/inertia/blob/1580d2ba887c4f50b57e8dc0fa0707da3e123b2b/packages/inertia-vue/src/form.js#L181-L190

Can we somehow rewrite this? What is it supposed to do?

### Steps to reproduce:

Use new `@vue/compat` package and use `$inertia.form()` to generate a form.

See: https://github.com/vuejs/vue-next/issues/3936

**Comment by reinink** [comment]
@jaulz Sorry, but I simply don't think we have the capacity at this time to also support the `@vue/compat` package. You are, of course, welcome to tackle this problem, and submit a PR to fix it.

A little background on this particular piece of code. We're using a bit of a hack in the Vue 2 form helper to create a watcher, which involves creating an additional Vue instance. I suspect that's the issue. If you can find a different way to create a watcher within the form helper, that would probably fix it, but I don't know that Vue 2 provides a way to watch something outside of a component ([like Vue 3 does](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue3/src/useForm.js#L181-L186)).

Sorry I cannot be more helpful. 😕

**Comment by jaulz** [comment]
No worries, I simply switched to the vue3 version and it works perfectly well 😊 

Thanks anyway!

**Comment by reinink** [comment]
Hah, awesome. 👍
