### ISSUE TITLE
[0.4.6][Vue 3] Upgrading broke the form helper

### ISSUE THREAD

**Issue by johanvanhelden** [inertiajs/inertia#745]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.6

### Describe the problem:

Since the update to 0.4.6 (from 0.4.5) the form helper is no longer working properly. The post itself is working fine, errors are coming back from the back-end, but the page seems to be refreshed or something.

Downgrading back to 0.4.5 solves the issue.

### Steps to reproduce:

After submitting a form using *(I still need to switch to the composition API, but the option API should be fully backward compatible):
```
    data() {
        return {
            form: this.$inertia.form({
                email: null,
            }),
        };
    },
    methods: {
        submit() {
            this.form.post(route('password.email'), {
                onFinish: () => {
                    this.form.reset('email');
                },
            });
        },
    },
```

Using 100% the same code and the same form input where I only downgraded to the vue3 0.4.5 adapter is working fine.

Might be related to https://github.com/inertiajs/inertia/issues/744 but I am not using Jetstream and I am not getting an error in the console.

**Comment by reinink** [comment]
Fixed (8ee916703b408db1ff0d4dc318a79a12af566bb4) and released as `0.4.7`.

**Comment by johanvanhelden** [comment]
Can confirm it's working again, thanks!

**Comment by reinink** [comment]
Awesome, thanks for following up @jacksontong! 👍
