### ISSUE TITLE
React.memo don't prevent all components tree re-render when visit a page

### ISSUE THREAD

**Issue by robert2206** [inertiajs/inertia#746]
It's possible to prevent page components tree re-renderization when visit a page?

**Comment by reinink** [comment]
Pinging @sebastiandedeyne, as I'm not really sure what this question means.

For what it's worth, when making visits, you can use the `preserveState` option when making visits to the same page component to prevent a full page re-render. See here: https://inertiajs.com/manual-visits#component-state

**Comment by sebastiandedeyne** [comment]
Hey @robert2206!

Could you share a snippet of what your code looks like? Specifically, where are you adding `React.memo` in your component tree?

**Comment by reinink** [comment]
Closing this due to lack of response. Feel free to provide the information requested, and we can reopen. 👍
