### ISSUE TITLE
Broken link on inertia website (Forms Page)

### ISSUE THREAD

**Issue by Sohib** [inertiajs/inertia#749]
Hello 

I didn't find the inertia website repository to open the issue there.  I've found a broken link at inertia [Forms page](https://inertiajs.com/forms) at the following part.
 > While it's possible to make classic form submissions with Inertia, it's not recommended, as they cause full page reloads. Instead, it's better to intercept form submissions and then make the [request](https://inertiajs.com/requests) using Inertia.

**https://inertiajs.com/requests** is not available.

**Comment by reinink** [comment]
Hey thanks, this has been fixed. 👍 

73135619a208ec3aa145d662d7af57a55a8d0ab5
