### ISSUE TITLE
[TS] VisitOptions definition forces us to use all options

### ISSUE THREAD

**Issue by obennaci** [inertiajs/inertia#751]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:
Using the form helper and trying to pass a visit option such as `onSuccess` triggers TS errors, it expects all of VisitOptions to be passed or none at all.

eg:
```js
form.post('some-url', {
  onSuccess: () => {/*... */}
})

// Argument of type '{ onSuccess: (page: Page) => void; }' is not assignable to parameter of type 'VisitOptions'.
// Type '{ onSuccess: (page: Page) => void; }' is missing the following properties from type 'Visit': method, data, replace, preserveScroll, and 5 more.
```

**Comment by johanvanhelden** [comment]
@claudiodekker I just stumbled upon the same issue. Might I ask when a release is planned?

**Comment by Jacobtims** [comment]
I have the same problem in the V1 version?
