### ISSUE TITLE
Add beforeVisit option to Inertia.visit and InertiaLink

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#76]
I don't have an exact API for this yet, but here's the idea…

It'd be nice to be able to do something before a visit (and potentially cancel the visit). 

Something that comes up a lot is displaying a confirm modal before deleting something. We could render a modal in the `beforeVisit` call, and only do the visit after the user has confirmed.

```html
<InertiaLink :href="`/posts/${post.id}`" method="DELETE" beforeVisit="confirm">
  Delete post
</InertiaLink>
```

This could get rid of unnecessary boilerplate in applications. I thought of this after a discussion with @michaeldyrynda on Discord.

<img width="508" alt="Screenshot 2019-09-26 at 11 11 06" src="https://user-images.githubusercontent.com/1561079/65675428-79614700-e04e-11e9-96a4-ec8dfc72c859.png">
<img width="520" alt="Screenshot 2019-09-26 at 11 10 57" src="https://user-images.githubusercontent.com/1561079/65675434-7bc3a100-e04e-11e9-9c68-fa75f9cb2e8e.png">

**Comment by hawezo** [comment]
Not sure if this is part of this scope, but it would also be great to be able to cancel *any* visit when on a specific page. 

My use case for this was to display a confirmation modal when leaving a page with a form, and I had to do a lot of tweaking to achieve this. 

I don't know how to properly do that, though, but [this is something that Vue Router has](https://router.vuejs.org/guide/advanced/navigation-guards.html).

**Comment by reinink** [comment]
Would it make sense to update all the Inertia link components to include the new event callbacks? That said, currently the event callbacks do NOT support cancelling events, so that still wouldn't help here. Of course, we could update them to support cancelling by doing a `return false`.

That would give you this ability:

```vue
<InertiaLink :href="`/posts/${post.id}`" method="DELETE" :onStart="() => confirm('Are you sure you delete this post?')">
  Delete post
</InertiaLink>
```

//cc @claudiodekker

**Comment by claudiodekker** [comment]
Yeah, I'm in favor of that idea 👍

**Comment by innocenzi** [comment]
This would be nice, indeed. 👍

**Comment by reinink** [comment]
The `onStart()` callback can now cancel visits by returning `false` (see #233). That sets the path forward for adding this behaviour to the Inertia links. 👍

**Comment by reinink** [comment]
This is now possible in the link components in the React and Vue.js adapters (just need to release). There is also a WIP PR for Svelte. Going to close this, since it's basically done. 👍

**Comment by thewebartisan7** [comment]
@reinink this seem not working with Link component. The onStart() is called but even returning false it's not preventing visit:

```
<Link :href="route('users.destroy', user)" method="delete" as="button" type="button" :onStart="() => confirm('Are you sure?')">Delete</Link>
```
