### ISSUE TITLE
Partial reloading does not seem work

### ISSUE THREAD

**Issue by reinvanimschoot** [inertiajs/inertia#767]
### Versions:

- `@inertiajs/inertia` version: 0.8.2
- `@inertiajs/inertia-react` version: 0.5.0

### Describe the problem:

When I'm using 
```
Inertia.reload({only: ['users']})
```
the reloaded props entirely unchanged. In other words, the `users` prop is not updated.

It is only when using
```
Inertia.reload()
```
that the props are in fact updated and the `users` prop reflects the updates.

### Steps to reproduce:

I'm not doing anything exotic really, I am performing a post request and I would like to update the props passed from my Rails server, hence the `Inertia.reload`.

```
  function submitExercise() {
    Inertia.post(
      routes.questionAnswersPath,
      { answer: { value: { checkedAnswers } } },
      { only: ['answered_by_user'] },
    );
  }
```

**Comment by reinink** [comment]
Can you please post your request *headers*, as well as the response *body* you're getting when making this request?

**Comment by reinvanimschoot** [comment]
The request headers are:
![Screenshot 2021-06-23 at 13 58 25](https://user-images.githubusercontent.com/35171567/123092885-40c0ee00-d42b-11eb-9d36-45205e44aaec.png)

The response body is
```
{"component":"classroom/Show", "props":{}, "url":"/b/3F00/klas", "version":null}
```

So it seems no props are passed along.

To contrast, this is the response body when I do not use any partial reloading:

```
{"component":"classroom/Show","props":{"auth":{"user":{"id":2,"email":"student@school.com","role":"student"}},
"questionable":{"nodeKey":"203a1327-0295-4a55-b22a-f30405a6e06d","nodeType":"exercise__multiple_choice",
...
,"answeredByUser":true,
"routes":{"questionAnswersPath":"/questions/273/answers"}},
"url":"/b/3F00/klas","version":null}

**Comment by reinink** [comment]
Hmm, you're asking for only `answered_by_user` back from the server, but I don't see that in your props when not using partial reloads. Are you sure `answered_by_user` is a valid top-level prop for that endpoint?

**Comment by reinink** [comment]
It appears to be `answeredByUser`, not `answered_by_user`.

**Comment by reinvanimschoot** [comment]
Woops, yes, I'm sorry. It's `answeredByUser` but the problem remains. I tried it with different other props such as `routes` but whenever I specify any prop in the `only` field, no props are returned.

**Comment by reinink** [comment]
And, just to be certain, the page you're submitting to uses the same page component, yes? As per the docs:

> Partial reloads only work for visits made to the same page component.

**Comment by reinvanimschoot** [comment]
It is indeed. But I think I've found the culprit. It's something we do to streamline our props. So I think we can close the issue. Thanks for helping me work through this!

**Comment by reinvanimschoot** [comment]
For reference, we are trying to format our props before passing them to inertia

```
  def render_inertia(template, props)
    render inertia: template, props: camelize(props)
  end

  def camelize(props)
    props.deep_transform_values!(&:as_json)

    props.deep_transform_keys { |key| key.to_s.camelize(:lower) }
  end
```
but this seems to interfere with partial reloading.

**Comment by reinvanimschoot** [comment]
And to conclude the puzzle, the keys were no longer Symbols, that was the issue in the end :)

**Comment by reinink** [comment]
Glad you got it figured out. 👍
