### ISSUE TITLE
Implement a middleware pipeline

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#77]
A middleware pipeline could potentially clean things up internally and make the package a lot more extendible.

A few usage examples:

- Pretty much everything in `visit` could be moved to a middleware, making `inertia.js` a lot lighter
- Refactor `transformProp` to a middleware
- Allows users to hijack the request/response cycle (as requested in #73)
- Could be used to implement loading indicators (#9)
- Could be used to hijack the request for previsits (#45)

**Comment by reinink** [comment]
While a neat idea, I don't see a strong need for this right now, especially considering much of this has been solved already using the new event system.
