### ISSUE TITLE
Subdomain not changing when navigating using inertia-link

### ISSUE THREAD

**Issue by luiyongsheng** [inertiajs/inertia#771]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:

Let's say you have Laravel named routes like:
```PHP
'dashboard.home' => 'dashboard.example.com/home',
...
'account.settings' => 'account.example.com/acc/settings',
```

When you are in `dashboard.home` page, clicking the `<inertia-link>` that has `href` linking to `account.settings` will bring you to the page.

However, the address bar is showing `https://dashboard.example.com/acc/settings`, this will cause a 404 error when user refresh the page as the correct URL should be `https://account.example.com/acc/settings`.

**Comment by claudiodekker** [comment]
Hi,

As of today, this is indeed not possible, as Inertia internally uses relative URL's only (see the XHR response).

Even if we could support full URL's so that cross-subdomain redirects become possible, I'm wondering whether this wouldn't cause browsers to complain about CORS issues? In either case, we'll have to investigate this a bit more.

**Comment by RobertBoes** [comment]
@claudiodekker this is not possible because Inertia uses the history API, pushState is subject to the same origin policy


https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
> The new URL must be of the same origin as the current URL; otherwise, `pushState()` will throw an exception

So, with Inertia it's only possible to navigate to another domain by making a full page visit, either using `window.location` or with a regular anchor tag

**Comment by claudiodekker** [comment]
Thanks @RobertBoes!

@luiyongsheng Given that this isn't possible / cannot be possible, I'm going to close this issue. On top of what @RobertBoes already mentioned, you may use `Inertia::location` for this: https://inertiajs.com/redirects#external-redirects

Hope this helps!

**Comment by victorlap** [comment]
Maybe this should happen automatically? If inertia sees a url with a differenet origin, it should force a reload, as otherwise you would end up on not existing pages. You cannot always do this server side, for example when not all routes in the navigation are on the same origin.

**Comment by lucasdcrk** [comment]
Did anyone found a way to make Inertia do a full page visit whenever hitting a page on a different domain?

**Comment by swapnil-technoward** [comment]
Did anyone found a way to make Inertia do a full page visit whenever hitting a page on a different domain?

i am sending route from the inertia middleware even receiving the response from  the backend but still the url is not changing also not rendering the component.

const functionLogin = async (route) => {
    Inertia.visit(route, {
        method: 'get',
        headers: {
            'X-Inertia': true,
            'X-Requested-With': 'XMLHttpRequest',
            'Accept': 'application/json',                // Ensures JSON response
        },
        preserveScroll: true,                             // Preserve scroll if needed
        preserveState: true,                              // Preserve component state
        onSuccess: (page) => {
            console.log('Inertia Page Response:', page);  // Log Inertia data on success
        },
        onError: (errors) => {
            console.error('Inertia Error:', errors);      // Log any Inertia-specific errors
        },
    });
};
const navigateToLogin = () => functionLogin(loginRoute.value);

only getting the below error in the console.

"@inertiajs_inertia.js?v=8a4a3ba7:1565 Uncaught (in promise) TypeError: this.resolveComponent is not a function
    at n2.setPage"
