### ISSUE TITLE
Inertia.reload() not loading more than 1 component

### ISSUE THREAD

**Issue by jatinthapar1910** [inertiajs/inertia#777]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:

Using `Inertia.reload()` for 2 components is not loading more than one component. Ex. Lets I have 2 tables on a screen one by monthly and one by weekly as following:

Controller
```
public function index(Request $request)
    {
        return Inertia::render('Dashboard/Index', [
            'datatableConfig'  => config('datatable_configs.dashboard'),
            'datatable'        => Inertia::lazy(function () use ($request) {
                return $this->datatable('month');
            }),
            'weeklyDashboard'        => Inertia::lazy(function () use ($request) {
                return $this->datatable('week');
            }),
        ]);
    }
``` 

Index.vue
```
<template>
    <PrimeTable lazyLoadLink="datatable" :datatableConfig="props.datatableConfig"></PrimeTable>

    <PrimeTable
        lazyLoadLink="weeklyDashboard"
        :datatableConfig="props.datatableConfig"
        @table-data="onDataLoad"
    ></PrimeTable>
</template>
```
Then it is only loading second component, the first ignored. 
Ideally it should load both the components since these are lazy load.

**Comment by reinink** [comment]
So Inertia doesn't control which components get rendered when a page reloads. It simply controls what props come back from the server, and are then subsequently passed to your page component. Meaning, if you do a partial reload, only the props you specify will update in your page component. How they are used within your page component is up to you.

If you want to do a partial reload for multiple props, you can do that:

```js
Inertia.reload({ only: ['foo', 'bar'] })
```

Hope that helps.

**Comment by jatinthapar1910** [comment]
Sounds good and this really helps.
Thanks for responding 👍

**Comment by reinink** [comment]
Happy to help. And, for what it's worth, there is a more in-depth explanation of partial reloads here: https://inertiajs.com/partial-reloads

**Comment by jatinthapar1910** [comment]
Sounds good. 

It would be great if we can isolate partial reload for different components. Ex. one page - `Index.vue` may have 2 Datatables -`DatatableComponent` with lazy load - say **"Weekly"** Datatable and **Monthly** Datatable on a page and for fetching the records we can use Inertia.reload({only: 'datatable'}) in `DatatableComponent`.

Though this can achieved with axios or fetch but if we do it with Inertia then its GREAT!
