### ISSUE TITLE
Add the ability to mutate pageProps

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia#78]
Sometimes I wish there was a way to mutate the page props. 

For example: you have a list of posts that have a publish button that uses Axios. After clicking publish, the post's status needs to be updated.

The current way of doing thigs:

1. Inertia sends a `posts` object in the response
2. You need to copy the `posts` object to local component state, which may be mutated
3. Whenever an `Inertia.visit` happens with `preserveState`, you need to manually override your local component state with the fresh `posts` data

This is really annoying to maintain, and would be simpler if we could just mutate the prop in Inertia.

This is a potentially dangerous feature, so I'm not sure about it yet. Would like some external input.

**Comment by reinink** [comment]
So, in your example, why wouldn't you just do an `Inertia.put()` to update the post status, and then redirect back to the post index? What's the benefit of doing this an an Axios request?

**Comment by sebastiandedeyne** [comment]
This probably doesn't matter in the posts example, however, if you're dealing with data that changes often, there's a chance that your list has completely changed by the time you do the `put` request.

If you're on page 2 of a list, modify an item, and receive a new set of data for page 2, there's a chance that the item you modified isn't part of the list anymore, which would be super confusing for the user.

We do this in Flare, since errors can come in pretty fast is an application is on fire. We use Axios call to resolving or snoozing errors to ensure the context doesn't completely change after a request.

**Comment by reinink** [comment]
Ahh yes, real interesting. That makes sense.

Something that needs to be considered here is that if we change the props somehow, we'll also need update the cached history state data as well.

I also wonder if, with a feature like this, you quickly get into modifying the URLs and history state as well. I feel like this is a dangerous road to go down, but will be very tempting.

**Comment by reinink** [comment]
So, I'm seeing some interesting use cases for a feature like this, where you can modify the root level props (page object), which then reactively updates the page component props.

One really neat use case for this is infinite scrolling. Imagine you have a tweets page, that shows the 15 most recent tweets. Then, when you scroll and load additional tweets, you could use something like `Inertia.updateProps()` to push these additional tweets into the `page` object. Something like this:

```js
loadMoreTweets() {
  fetch(`/tweets?page=${nextPage}`)
    .then(response => response.json())
    .then(tweets => Inertia.updateProps(props => {
      props.tweets.concat(tweets)
      return props
    }))
}
```

A different approach would be to allow per visit prop transformations:

```js
loadMoreTweets() {
  let currentTweets = this.tweets
  Inertia.get(`/tweets?page=${nextPage}`, {
    transformProps(props => {
      props.tweets = currentTweets.concat(props.tweets)
      return props
    })
  })
}
```

I like this approach as well, for two reasons. One, you can still make these requests with Inertia, and second, [transforming props](https://inertiajs.com/transforming-props) is already a thing in Inertia. However, I suspect the `Inertia.updateProps` feature would support a wider range of use-cases.

**Comment by sebastiandedeyne** [comment]
In React-land there's a library called [SWR](https://swr.vercel.app) that helps you deal with fetching/caching/invalidating data. SWR has a very interesting [`mutate` function](https://swr.vercel.app/docs/mutation).

`mutate` allows you to modify data before sending a request. So you can optimistically update the UI before the request is fulfilled.

```js
// update the local data immediately, but disable the revalidation
mutate('/api/user', { ...data, name: newName }, false)

// send a request to the API to update the source
await requestUpdateUsername(newName)

// trigger a revalidation (refetch) to make sure our local data is correct
mutate('/api/user')
```

I think there are some interesting ideas in there we could use as inspiration, including the name.

```js
function updateUser(user) {
    Inertia.mutate(props => ({ ...props, user }));

    Inertia.post('/users/123', { user });
}
