### ISSUE TITLE
The DELETE method is not supported for this route

### ISSUE THREAD

**Issue by stoneC0der** [inertiajs/inertia#798]
### Discussed in https://github.com/inertiajs/inertia/discussions/797

<div type='discussions-op-text'>

<sup>Originally posted by **stoneC0der** July 10, 2021</sup>
"inertiajs/inertia-laravel": "^0.4.1",
"@inertiajs/inertia": "^0.8.7",

Hi, I am having hard time using inertia put/patch and delete method, when submitting the form, the action is successfully performed like, updating the record.
The issue rise when trying to redirect to the users.index route.

this the code i am using:
DOES NOT WORK
```js updateProject () {
      this.processing = true;
      this.$inertia.patch(`/projects/${this.project.id}`, this.form).then(() => {
        this.processing = false;
      });
    },
```

- as I understand, this might be the issue

"*Note, when redirecting after a PUT, PATCH or DELETE request you must use a 303 response code, otherwise the subsequent request will not be treated as a GET request. A 303 redirect is the same as a 302 except that the follow-up request is explicitly changed to a GET request.*"

- If you're using one of our official server-side adapters, redirects will automatically be converted."

- But I am using the official server-side adapter, I tried setting the redirect code to 303 nothing, I even watch a video and the guy is also using the same code and no further configuration and it works as it should.

- For now the solution is to use `post` and set the intended method in the method option, but I would like to know why it not working with `this.$inertia.patch`

WORK: when I put the `_method: patch` in the form object
this the code i am using:
```js updateProject () {
      this.processing = true;
      this.$inertia.post(`/projects/${this.project.id}`, this.form).then(() => {
        this.processing = false;
      });
    },
```</div>

**Comment by stoneC0der** [comment]
Never did bother to look at the doc for updates

**Comment by niklasnoldin** [comment]
Hey @stoneC0der, can you explain what exactly the problem was here? I only ran into this issue after updating the inertia packages to the latest versions.

**Comment by niklasnoldin** [comment]
Nevermind, I needed to install the inertia middleware in Laravel. Clearly documented [here](https://inertiajs.com/releases/inertia-laravel-0.3.0-2020-10-14). Read the docs, fellow kids.
