### ISSUE TITLE
Form Heler Processing not working

### ISSUE THREAD

**Issue by jatinthapar1910** [inertiajs/inertia#799]
### Versions:

- `@inertiajs/inertia` version: 0.9.2
- `@inertiajs/inertia-vue3` version: 0.4.7

### Describe the problem:

I am trying to submit a form with Inertia form helper but it does not reset the processing to true. 

### Steps to reproduce:

Using the following code for Vue3 with `import { useForm } from '@inertiajs/inertia-vue3';` is not setting the processing to true.
```
const form = useForm({
  name: null
});

function createTenant() {
  Inertia.post('/tenant', form);
}
```
Please lemme know if you need further details.

**Comment by jatinthapar1910** [comment]
There is an additional issue with Form Helper using `"vue": "^3.1.2",`
Submitting the form using 

```
const form = useForm({
    name: 'Testing',
    type: 'Testing',
    avatar: null
});
Inertia.post('link', form);
```
submits the complete raw object 
```
{
	"name": "Testing",
	"type": "Testing",
	"isDirty": true,
	"errors": {},
	"hasErrors": false,
	"processing": false,
	"progress": null,
	"wasSuccessful": false,
	"recentlySuccessful": false,
	"__rememberable": true
}
```

**Comment by jatinthapar1910** [comment]
The code used here is not correct. 

```
const form = useForm({
    name: 'Testing',
    type: 'Testing',
    avatar: null
});
form.post('link');
```
This solves the issue.

**Comment by reinink** [comment]
Glad you got it figured out. 👍
