### ISSUE TITLE
@inertiajs/inertia-vue3"' has no exported member 'Head'

### ISSUE THREAD

**Issue by dacoto97** [inertiajs/inertia#807]
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue3` version: 0.5.1

### Describe the problem:

Javascript error: @inertiajs/inertia-vue3"' has no exported member 'Head'

### Steps to reproduce:

When updating to the latest version, which as explained @reinink in another PR #765  the components for vue are no longer automatically exported, it seems that the Head for vue3 is not being exported. Relates to: #755

<img width="709" alt="CleanShot 2021-07-14 at 15 53 39@2x" src="https://user-images.githubusercontent.com/16915053/125634148-c604bfa7-d02c-4543-8559-dcc60c6f115d.png">

**Comment by reinink** [comment]
Hmm, it's definitely exported, see here:

https://github.com/inertiajs/inertia/blob/a966727c27171c8e0ca729b8551e4e19e92aa369/packages/inertia-vue3/src/index.js#L4

But the TypeScript definition file has not been updated. Is that maybe the issue?

Note, we personally don't maintain the adapter TypeScript definition files. Feel free to submit a PR to have this added. 👍

**Comment by dacoto97** [comment]
You are right, the problem is the definition of Typescript. I'm going to do a PR to add this definition.

**Comment by reinink** [comment]
Thanks! 👍 

FYI, the release notes have been published: https://inertiajs.com/releases/inertia-vue3-0.5.0-2021-07-13
