### ISSUE TITLE
Django Support

### ISSUE THREAD

**Issue by Immortalin** [inertiajs/inertia#82]

**Comment by Juhlinus** [comment]
Hello @Immortalin !

This is definitely something that would be great to have, but, most of the people working on Inertia don't have enough experience with Django to write an adapter for it.

You are very much welcome to write one yourself and share it with us.

**Comment by timonweb** [comment]
@Juhlinus check this repo out: https://github.com/jsbeckr/inertia-django

**Comment by reinink** [comment]
We'd love to have an official Django adapter some day, but non exist right now, sorry.
