### ISSUE TITLE
[Vue warn]: Failed to resolve component: inertia-link after upgrade to 0.10.x

### ISSUE THREAD

**Issue by FrankFlow** [inertiajs/inertia#827]
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue3` version: 0.5.1

 
After upgrade to 0.10.0 I've got this warning: 
`[Vue warn]: Failed to resolve component: inertia-link`

in each page

**Comment by simioluwatomi** [comment]
I had to import the inertia link component manually like so to have the error go away

```import { createInertiaApp, InertiaLink } from '@inertiajs/inertia-vue'```

**Comment by reinink** [comment]
This is expected behaviour, and is explained in the release notes: https://inertiajs.com/releases/inertia-vue3-0.5.0-2021-07-13
