### ISSUE TITLE
Link does not exist in @inertiajs/inertia-vue, it should be InertiaLink

### ISSUE THREAD

**Issue by StuartCreed** [inertiajs/inertia#838]
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue` version: 0.7.1

### Describe the problem:

Link does not exist in @inertiajs/inertia-vue, it should be InertiaLink

### Steps to reproduce:

On https://inertiajs.com/links for Vue2 it states to use a Link do the following:
  ```
  import { Link } from '@inertiajs/inertia-vue'
    <Link href="/">Home</Link>
  ```
  It should be:
  `import { InertiaLink } from '@inertiajs/inertia-vue'`
  Then in my case I have used it globally with `Vue.component('inertia-link', InertiaLink)`

![image](https://user-images.githubusercontent.com/45539606/127672611-3d4a8f13-ecef-4482-8364-aafe6ede673c.png)

**Comment by ajnsn** [comment]
```js
Vue.component('InertiaLink', Link);
```

or

```js
Vue.component('inertia-link', Link);
```

both should work. 👍

**Comment by NickSdot** [comment]
@StuartCreed this should be fixed with https://github.com/inertiajs/inertia/pull/819

**Comment by reinink** [comment]
And this was released yesterday as well. 👍
