### ISSUE TITLE
Inertia Form `isDirty` attribute not there

### ISSUE THREAD

**Issue by liam-ot** [inertiajs/inertia#848]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue` version: 0.5.12

### Describe the problem:
I am using the inertia form helper:
```
data() {
        return {
            form: this.$inertia.form({
                formData: this.object.fillerData,
                anImage: null,
            })
        }
    }
```

the form is populated with already existing data from a prop passed to the page because this page is where you update the db records

it also has a file upload section in the form but initially that is just loaded in as a null value 

in the vue dev tools the form comes up with the following attributes:
```
...
errors:Object (empty)
get:ƒ get(e, r)
hasErrors:false
patch:ƒ patch(e, r)
post:ƒ post(e, r)
...
```
as you can see the form has no `isDirty` property which is what i would like to use to ensure a change to the form data has occurred before allowing the user to submit the new data to the controller method which will handle it, like so:
```
<SubmitFormButton v-if="form.isDirty" @click="send" :loading='form.processing' type='submit'>Update {{prop.propName}}</SubmitFormButton>
```

to reproduce try making a form with pre-filled data from a prop and a null value form section and then see if the form has the `isDirty` property

**Comment by reinink** [comment]
The `isDirty` helper was added in [inertia-vue@0.6.0](https://inertiajs.com/releases/inertia-vue-0.6.0-2021-05-25).

You'll need to update before you can use this. 👍

**Comment by liam-ot** [comment]
@reinink thanks, i have upgraded to 0.7.2 but now none of my pages load due to
```
 Error in created hook: "TypeError: i.createHeadManager is not a function"
```

i assume this has to do with [this](https://inertiajs.com/releases/inertia-vue-0.6.0-2021-05-25) and maybe [this](https://inertiajs.com/releases/inertia-vue-0.7.0-2021-07-13)

some guidance to resolving this error would be helpful, thanks for creating Inertia this is a **great** framework

**Comment by reinink** [comment]
You'll need to upgrade `@inertiajs/inertia` as well, and then follow the release notes to correct any breaking changes. 👍

**Comment by liam-ot** [comment]
yes sorry i missed that, upgrading to the lastest `inertia-vue` and `inertia`, however now there is this issue
```
Unknown custom element: <inertia-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by RobertBoes** [comment]
> yes sorry i missed that, upgrading to the lastest `inertia-vue` and `inertia`, however now there is this issue
> 
> ```
> Unknown custom element: <inertia-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> ```

The link component isn't registered globally anymore, see the release notes https://inertiajs.com/releases/inertia-vue-0.7.0-2021-07-13
So you'll have to import it in each component, or register it globally yourself

**Comment by liam-ot** [comment]
In case you guys didn't know, there is no other project which gives as good support as Inertia, at least that I know of

@RobertBoes @reinink Thank you so very much
