### ISSUE TITLE
Preserve #id_of_element in route after redirection

### ISSUE THREAD

**Issue by smbdelse** [inertiajs/inertia#85]
**Problem:**
When inertia-link href attribute contains #some_id it is not preserved.

**Example:**
After click inertia-link with href="homepage#contact" it send us to //example.com/homepage, dropping "#contact" from url.

**Expected behavior:**
To keep #id in url and scroll to it's position after redirect

**Comment by smbdelse** [comment]
For now I am marking proper behavior by getting hash before redirection, transform it to standard GET parameter, send a request with it and attach it to $page object with response, so I can scroll to desired location then. But I think that it should be somehow handled by Inertia itself.

**Comment by reinink** [comment]
Yeah, totally, this is something I need to figure out still. 👍

**Comment by hivokas** [comment]
My proposal is to send `X-Inertia-Hash` header alongside with other headers.
And append the value of this header at the end of `url` which is sent to the front end on each Inertia response.

**Comment by hivokas** [comment]
My another proposal would be to get the hash of the target URL before visiting it. 
And execute `location.href = hash` after the axios request.

**Comment by hivokas** [comment]
@reinink your thoughts?

**Comment by anatoliyarkhipov** [comment]
@hivokas 

> My another proposal would be to get the hash of the target URL before visiting it.
> And execute location.href = hash after the axios request.

It's not so simple: if you manipulate the hash bypassing Inertia (i.e. through `location.href = "#hash"` like in your proposal, or by click on a `<a href="#hash" />`), and then navigate somewhere through `Inertia.visit` (or `InertiaLink`, which uses `Inertia.visit` under the hood), the Back button will not work properly - it will change URL in the address bar back to `#hash`, but will not get you back to the page from which you `visit`ed the current one.

**Comment by reinink** [comment]
This has been fixed in #257, which just got merged in, and will be released soon. 🙌

**Comment by ldanielduarte** [comment]
Hello guys,

I'm sorry to write this here because it is not an issue or a bug report, just some support request - but it seems that the topic fits very well in the subject and I am sure that @reinink will be able to help me 😄 

When redirecting from the controller:
```
class EntityController extends Controller
{
    public function store(Request $request): RedirectResponse
    {
        ....
        return redirect()->route('entities.list')->withFragment('manage');
    }
}
```

How can I keep the hash in the URL?

For instance, in this case, return to the page `https://domain.com/entities#manage`

I am suspecting that Inertia is doing some magic behind in this case, because I am not being able to keep the hash in the URL and from what it is written in Laravel docs, it seems that it should be possible.

**Comment by Baspa** [comment]
@ldanielduarte I asked in the Inertia Discord channel about this And @RobertBoes gave me the following answer:

> I don't think that'll ever work, because the request is made using XHR. So the browser will deal with the redirect.
> 
> Quickly tried it in PingCRM, the response is a 302 with the following header: Location: http://pingcrm.test/contacts#something so the correct redirect URL is set. However, the followup request is made by the browser which is just GET http://pingcrm.test/contacts. So the browser will discard the fragment, afaik this isn't something Inertia can do anything about. Even the underlying library has no impact (Axios), because the browser itself will do the redirect, not Axios.
>
> XHR requests are always made without a fragment, as seen here: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL any URL fragment present in the URL will be stripped away.
>
> Can't find the RFC that that has all this explained right now, but iirc it's just how these requests work. For example, if you do Inertia::get('/dashboard#something') then Inertia will strip the fragment from the URL, make the request and after the request is completed it will add the fragment back to the URL using the History API, because the fragment is not sent along with the XHR request.
