### ISSUE TITLE
django user authentication and authorization

### ISSUE THREAD

**Issue by asimshahzad78** [inertiajs/inertia#86]
Hi Everyone,
I need suggestion on the following issue, actually I start developing a small erp in django. I’m quite confuse about how to handle user authentication and authorization. My project architecture is 

	ERP (Main Project)
o	HR (App)
o	Finance (App)
o	Payroll (App)
o	Sale (App)
How to implement login system in above architecture?

Thanks

**Comment by reinink** [comment]
Hello @asimshahzad78, I don't really know anything about Django myself, or how to setup auth in that framework, but I don't really think this is an Inertia related issue either way.
