### ISSUE TITLE
Layout: null ignored on default layout.

### ISSUE THREAD

**Issue by Tim-Frensch** [inertiajs/inertia#867]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2

### Describe the problem:

When setting up a default layout the layout: null is ignored as setting.

### Steps to reproduce:

Setup a default layout and try to exclude a page from it by using the layout: null setting.

**Comment by reinink** [comment]
Without any code, this is hard to help with. However, I'm guessing you're using the example code from the docs for this:

```js
import Layout from './Layout'

createInertiaApp({
  resolve: name => {
    const page = require(`./Pages/${name}`).default
    page.layout = page.layout || Layout
    return page
  },
  // ...
})
```

Instead of doing that, try this instead:

```js
createInertiaApp({
  resolve: name => {
    const page = require(`./Pages/${name}`).default
    if (page.layout === undefined) {
      page.layout = Layout
    }
    return page
  },
  // ...
})
```

This will support setting the layout to `null`, which will disable the default layout. 👍

**Comment by Tim-Frensch** [comment]
> Without any code, this is hard to help with. However, I'm guessing you're using the example code from the docs for this:
> 
> ```js
> import Layout from './Layout'
> 
> createInertiaApp({
>   resolve: name => {
>     const page = require(`./Pages/${name}`).default
>     page.layout = page.layout || Layout
>     return page
>   },
>   // ...
> })
> ```
> 
> Instead of doing that, try this instead:
> 
> ```js
> createInertiaApp({
>   resolve: name => {
>     const page = require(`./Pages/${name}`).default
>     if (page.layout === undefined) {
>       page.layout = Layout
>     }
>     return page
>   },
>   // ...
> })
> ```
> 
> This will support setting the layout to `null`, which will disable the default layout. 👍

I used the examples from the docs indeed. Your solution fixes it. Thanks a lot!

**Comment by reinink** [comment]
Happy to help! 💪

**Comment by HazJ** [comment]
The example in the docs works fine for me, however, it doesn't work when using [code splitting](https://inertiajs.com/client-side-setup#code-splitting). Any ideas on how this can be achieved in combination? @reinink 
```
    resolve: name => {
        const page = import(`./Pages/${name}`)
        page.layout = page.layout || Layout

        return page
    },
```

**Comment by Vercoutere** [comment]
@HazJ Dynamic imports return a promise.

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports

You can set the default layout once the import has resolved.

`resolve: name => {
    return import(`./Pages/${name}.vue`)
    .then(page => {
        page.default.layout = page.default.layout || App;
        return page;
    });
},`
