### ISSUE TITLE
Is anyone using inertia in production?

### ISSUE THREAD

**Issue by Nothing-Works** [inertiajs/inertia#88]
I think this may be useful? If someone could make this issue as a pinned issue that would be great!

**Comment by theblindfrog** [comment]
I'm very close to deploying something to production - mobile-first sales application, deployed on Vapor.
Makes the whole app super fast and perfect for 3/4G connections

**Comment by sebastiandedeyne** [comment]
http://flareapp.io is built with Inertia :)

**Comment by m1guelpf** [comment]
Both [Blogcast](https://blogcast.host) and [Sitesauce](https://sitesauce.app) are build with Inertia :)

**Comment by georgehanson** [comment]
I've built a number of production projects using Inertia.

**Comment by Nothing-Works** [comment]
@georgehanson do you mind to share some of them?

**Comment by rodrigopedra** [comment]
https://avaliadora.com.br
It is a contact quality assessment SaaS, Brazil-based. Home page is plain Laravel but the app uses Inertia heavily. Launched in August, already have four tenants with an average of 100 active daily users. If you want to take a look send me a DM in twitter with your email address and I can create a login in the demo tenant. UI only in Portuguese. My twitter handle is the same as in github.

Previously I worked on another project for a client, which is a real state development company where I first used Inertia, project is not on production yet. In this project the client asked to have a hardcoded delay between two screens so the users can notice the page was changing. As both screens were very were similar and Inertia made the app so fast they didn't notice the navigation between them.

**Comment by reinink** [comment]
Yes, I have Inertia.js projects in production. 😎

Closing this for now, since I want to keep the issues focused on Inertia issues/feature requests. 👍

**Comment by atymic** [comment]
I built a thing :)

https://builtwithinertia.com/

@sebastiandedeyne @m1guelpf 
I've added Flare, Sitesauce & Blogcast to the site. Feel free to send me a DM on twitter if you'd like me to update anything on your listing 🎉

**Comment by reinink** [comment]
Awesome @atymic! If you tweet about it I'll be sure to retweet. 👍

**Comment by atymic** [comment]
Here's the launch tweet:

https://twitter.com/BWinertia/status/1193051895541035011

Thanks 😎

**Comment by reinink** [comment]
@atymic RETWEETED 💪
