### ISSUE TITLE
Mix building stopped at (10 %)

### ISSUE THREAD

**Issue by mousa74hassan** [inertiajs/inertia#881]
Hello guys,
I made some pages with laravel and inertia js and it was working without any problem. After i finished 5 pages and ran "npm run watch" it stopped without any error messages . I followed this commands and not working.

**_rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install_**

Problem:
* Mix ███                                       █ building (10%) 0/2 entries 131/166 dependencies 15/93 modules 62 active
 node_modules\vue2-google-maps\dist\components\placeInputImpl.js

dependencies:
 "@inertiajs/inertia": "^0.10.1",
        "@inertiajs/inertia-vue": "^0.7.2",
        "vue": "^2.6.14",
       
Laravel 8

Can anyone help ?!

**Comment by mousa74hassan** [comment]
I found the solution, the problem was in a wrong tag . when i removed it the project working . Thanks

**Comment by reinink** [comment]
Glad you got it figured out. 👍
