### ISSUE TITLE
Persistent Layouts don't render with Inertia/Svelte

### ISSUE THREAD

**Issue by burlesona** [inertiajs/inertia#898]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-svelte` version: 0.7.4

### Describe the problem:

Following the example from the documentation at https://inertiajs.com/pages I set up my Svelte component to use a persistent layout.

```home.svelte
<style>
  h1 { font-size: var(--size-12); }
</style>

<h1>{greeting}</h1>
<p>I'm an example home page.</p>

<script>
  import { inertia, Link } from '@inertiajs/inertia-svelte';
  import DefaultLayout from '@/layouts/default.svelte';

  export const layout = DefaultLayout;
  export let greeting;
</script>
```
The default layout looks like this:

```default.svelte
<nav>Insert Navigation here</nav>
<main>
  <slot></slot>
</main>
```

The layout does not render.

However if I change this to a "non-persistent layout" it works exactly as expected.

```home.svelte
<DefaultLayout>
  <h1>{greeting}</h1>
  <p>I'm an example home page.</p>
</DefaultLayout>

<script>
  import { inertia, Link } from '@inertiajs/inertia-svelte';
  import DefaultLayout from '@/layouts/default.svelte';

  // export const layout = DefaultLayout;
  export let greeting;
</script>
```

I'm not getting any errors, but I do see the following _warnings_ in the console:
<img width="620" alt="Screen Shot 2021-09-12 at 11 34 42 AM" src="https://user-images.githubusercontent.com/312268/132995515-975b423d-0e8f-41a1-9bc7-bd1c7e5587f2.png">

Specifically the message `<Home> received an unexpected slot "default".` seems related, but note that this warning appears whether with both versions (persistent and non-persistent), and googling it turns up [this issue](https://github.com/sveltejs/svelte/issues/4546) which indicates this may not be a real error.

Also since the code works exactly correctly using the "non-persistent" version, I'm inclined to think that something in the inertia plumbing isn't hooked up right.

For reference, I also tried doing this by setting it up as a default layout in the main function:

```main.js
import '@/styles/application.css'
import { createInertiaApp } from '@inertiajs/inertia-svelte'
import DefaultLayout from '@/layouts/default.svelte';

createInertiaApp({
  resolve: name => {
    const page = import(`./pages/${name}.svelte`);
    page.layout = page.layout || DefaultLayout;
    return page;
  },
  setup({ el, App, props }) {
    new App({ target: el, props })
  },
})
```

This had no effect, the result was exactly the same as using `export layout` from the home page component.

### Steps to reproduce:

Described in detail above.

**Comment by pedroborges** [comment]
The code related to persisted layout should go in Svelte's context module script block, not the main script block.

```svelte
<style>
  h1 { font-size: var(--size-12); }
</style>

<h1>{greeting}</h1>
<p>I'm an example home page.</p>

<script context="module">
  import DefaultLayout from '@/layouts/default.svelte';
  export const layout = DefaultLayout;
</script>

<script>
  import { inertia, Link } from '@inertiajs/inertia-svelte';

  export let greeting;
</script>
```

**Comment by burlesona** [comment]
Hi @pedroborges, thanks for the help, that fixed it. Sorry for what turned out to be a mistake reading the docs.

For future reference in case anyone else lands here by googling, setting the default layout in my main function didn't work because I'm bundling with Vite, and thus using `import()` instead of `require()`. Import is async, so I needed to add async/await to get it to work.

**Comment by aliwesome** [comment]
@burlesona Thank you for this, I try to add async/await and I faced another issue that said `TypeError: Cannot add property layout, object is not extensible` I do not know exactly what should I do here.

**Comment by andregoldstein** [comment]
@burlesona Thanks for this, I seem to be able to get the layout picked up by default using async/await import syntax but my slot is always empty, would you be able to share your entry point by any chance? Thanks!

**Comment by andregoldstein** [comment]
Helped a lot by this article https://dev.to/buhrmi/setting-up-a-new-rails-7-app-with-vite-inertia-and-svelte-c9e

**Comment by WalterWoshid** [comment]
> should go in Svelte's context module script block, not the main script block

Oh my, reading is hard, even for me. Somehow I completely overlooked that...

Thanks for the help!
