### ISSUE TITLE
Allow custom loading indicators

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia#9]
Currently Inertia uses [nprogress](http://ricostacruz.com/nprogress/) for its loading indicator. However, it would be nice to support other libraries. We'd simply have to expose this as a configuration option somehow.

For example:

```js
new Vue({
  render: h => h(Inertia, {
    props: {
      component: app.dataset.component,
      props: JSON.parse(app.dataset.props),      
      resolveComponent: (component) => { ... },
      beforeVisit: () => { /* start loading indicator */ },
      afterVisit: () => { /* stop loading indicator */ },
    },
  }),
}).$mount(app)
```

**Comment by reinink** [comment]
I actually think a better approach is to allow Inertia level customization directly via Inertia, and not through the adapters.

```js
Inertia.beforeVisit(() => {}),
Inertia.afterVisit(() => {}),
Inertia.startProgress(() => {}),
Inertia.incrementProgress(() => {}),
Inertia.stopProgress(() => {}),
```

**Comment by MichaelDeBoey** [comment]
I do think we should also support this in some way or another via the adapters, since those are really a component mapping over the Inertia API

**Comment by reinink** [comment]
I'm not sure I agree. There is nothing wrong with using Inertia directly (ie. `Inertia.visit()`), and we're really just talking about configuration here. To make every adapter responsible for this just means more work at the adapter level.

**Comment by MichaelDeBoey** [comment]
Just seems a bit weird to have the following code then:

```js
import InertiaVue, { Inertia } from 'inertia-vue'
import Vue from 'vue'

Inertia.beforeVisit(() => {})
Inertia.afterVisit(() => {})
Inertia.startProgress(() => {})
Inertia.incrementProgress(() => {})
Inertia.stopProgress(() => {})

Vue.use(InertiaVue)

const app = document.getElementById('app')

new Vue({
  render: h => h(InertiaVue, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)

```

**Comment by dbpolito** [comment]
This is something i would love to see, in my case i customised the CSS as a workaround but i would love to use something built-in i already have on my project.

Any ideas on how to solve this? I would love to contribute on this one.

Are we going with something simpler as https://github.com/inertiajs/inertia/issues/9#issuecomment-493676180 or https://github.com/inertiajs/inertia/issues/77?

**Comment by snaptopixel** [comment]
I've built a similar solution to Inertia that handles this via css. Whenever a request is in flight the page gets an `is-loading` css class. Then it's up to the user to figure out how/what they want to show while things are loading.

In my case I have a `shimmer` class that can be added to any element that looks like:

```css
.is-loading .shimmer {
  /* fancy animated gradient bg here */
}
```

**Comment by billmn** [comment]
This could very very useful: https://github.com/inertiajs/inertia/issues/9#issuecomment-493676180

**Comment by itsthejoker** [comment]
Alternatively, can I just show a gif as a loading indicator?

**Comment by RahulDey12** [comment]
> I actually think a better approach is to allow Inertia level customization directly via Inertia, and not through the adapters.
> 
> ```js
> Inertia.beforeVisit(() => {}),
> Inertia.afterVisit(() => {}),
> Inertia.startProgress(() => {}),
> Inertia.incrementProgress(() => {}),
> Inertia.stopProgress(() => {}),
> ```

Can I use it on a particular page

**Comment by reactor123** [comment]
> Currently Inertia uses [nprogress](http://ricostacruz.com/nprogress/) for its loading indicator. However, it would be nice to support other libraries. We'd simply have to expose this as a configuration option somehow.
> 
> For example:
> 
> ```js
> new Vue({
>   render: h => h(Inertia, {
>     props: {
>       component: app.dataset.component,
>       props: JSON.parse(app.dataset.props),      
>       resolveComponent: (component) => { ... },
>       beforeVisit: () => { /* start loading indicator */ },
>       afterVisit: () => { /* stop loading indicator */ },
>     },
>   }),
> }).$mount(app)
> ```

i have tried this solution but is not working

**Comment by Juhlinus** [comment]
> > Currently Inertia uses [nprogress](http://ricostacruz.com/nprogress/) for its loading indicator. However, it would be nice to support other libraries. We'd simply have to expose this as a configuration option somehow.
> > For example:
> > ```js
> > new Vue({
> >   render: h => h(Inertia, {
> >     props: {
> >       component: app.dataset.component,
> >       props: JSON.parse(app.dataset.props),      
> >       resolveComponent: (component) => { ... },
> >       beforeVisit: () => { /* start loading indicator */ },
> >       afterVisit: () => { /* stop loading indicator */ },
> >     },
> >   }),
> > }).$mount(app)
> > ```
> 
> i have tried this solution but is not working

Hi @reactor123 !

This is a proposed change and not yet implemented, unfortunately.

**Comment by billmn** [comment]
The ability to set a custom progress indicator is on roadmap. 

Take a look to this tweet of Jonathan: https://twitter.com/reinink/status/1290666276730408965?s=21

**Comment by reinink** [comment]
Custom loading indicators are now possible thanks to the new event system (#208). I hope to tag a release tomorrow, and I also plan to add documentation to the website explaining how to use the event system to add your own custom loading indicators. 🙌

**Comment by ycs77** [comment]
@reinink The [Loading indicator](https://inertiajs.com/client-side-setup#loading-indicator) section need added the progress description.

**Comment by reinink** [comment]
@ycs77 Yup, totally. It's on my TODO list. 👍

**Comment by NabeelYousafPasha** [comment]
Thanks a lot for spinners/indicators @reinink 
Respect from Pakistan
