### ISSUE TITLE
How Inertia.js renders?

### ISSUE THREAD

**Issue by gajosadrian** [inertiajs/inertia#90]
We all know Inertia.js is using _tightenco/ziggy_ and other stuff. The HTML response together with the Laravel Named Routes inside JavaScript is a bit big data.
So I want to ask, because when I were debuging Inertia.js in Chrome console I have seen that when webbrowser is fetching new Inertia.js SPA page enviroment, it gets full HTML and JS, with that response. But then while navigating between routes I see that Inertia.js is getting only Json reponse for a  new rendered component. Is that real response from server? or does the Inertia.js always renders whole HTML and returns only Json? The Inertia::render() returns HTML, but it also returns Json?
Does the Inertia.js renders whole HTML and returns only Json or does the Inertia.js renders only Json and returns only Json?
So how to make ajax/axios request to Inertia.js to get Json response?

**Comment by reinink** [comment]
@gajosadrian Hey there! I'd highly recommend reading this page of the docs: https://inertiajs.com/how-it-works. It explains in detail how Inertia.js works under the hood.

As for making standard ajax requests that return JSON, we recommend just using Axios directly in those situations. You can't use `Inertia.visit()` for pages that don't return a proper Inertia response.

Also, for what it's worth, Inertia doesn't use the "tightenco/ziggy" library, although our [Ping CRM](https://github.com/inertiajs/pingcrm) demo app does.
