### ISSUE TITLE
Svelte file upload example does not work as published

### ISSUE THREAD

**Issue by WilHall** [inertiajs/inertia#906]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-svelte` version: 0.7.4

### Describe the problem:

When running the [Svelte file upload example](https://inertiajs.com/file-uploads#file-upload-example) provided on [inertiajs.com](https://inertiajs.com/), the request payload is not converted to `FormData` and the file is not included in the request:
```json
{name: "Testing", avatar: "C:\fakepath\foop.png"}
```

I would expect the example to result in a multipart request containing the file. Comparing the Svelte example to the other examples, all the others set `form.avatar` to the value of `event.target.files` leading me to believe that either the Svelte example is incorrect, or `inertia-svelte` is supposed to work differently.

### Steps to reproduce:

1. In a new Svelte app using `@inertiajs/inertia@0.10.1` and `@inertiajs/inertia-svelte@0.7.4` set up an example page with just the content from the [Svelte upload file example](https://inertiajs.com/file-uploads#file-upload-example):

<details>
<summary>Svelte upload file example (as published)</summary>

```svelte
<script>
import { useForm } from '@inertiajs/inertia-svelte'

let form = useForm({
  name: null,
  avatar: null,
})

function submit() {
  $form.post('/users')
}
</script>

<form on:submit|preventDefault={submit}>
  <input type="text" bind:value={$form.name} />
  <input type="file" bind:value={$form.avatar} />
  {#if $form.progress}
    <progress value={$form.progress.percentage} max="100">
      {$form.progress.percentage}%
    </progress>
  {/if}
  <button type="submit">Submit</button>
</form>
```

</details>

2. Set the name field, select a file in the form, and click the submit button
3. Inspect the request from the browser dev tools. You should see a non-multipart request body such as `{name: "Testing", avatar: "C:\fakepath\foop.png"}`

I was able to adjust the example to get it working, drawing inspiration from the examples in the other languages. Instead of using `bind:value` on the file input, I instead `bind:files` onto the file input and then using a reactive statement to update the form when `files` changes.

<details>
<summary>Svelte upload file example (modified)</summary>

```svelte
<script>
  import { useForm } from '@inertiajs/inertia-svelte'

  let form = useForm({
    name: null,
    avatar: null,
  })

  function submit() {
    $form.post('/users')
  }

  let files = null
  $: $form.avatar = files ? files[0] : null
</script>

<form on:submit|preventDefault={submit}>
  <input type="text" bind:value={$form.name} />
  <input type="file" bind:files />
  {#if $form.progress}
    <progress value={$form.progress.percentage} max="100">
      {$form.progress.percentage}%
    </progress>
  {/if}
  <button type="submit">Submit</button>
</form>
```

</details>

Is this the correct approach for Svelte, in which case the example is incorrect? Or should the example be working as published?

**Comment by pedroborges** [comment]
@WilHall thanks for reporting this issue with the docs. It will be fixed soon.

While your solution works, there's a shorter alternative:

```svelte
<input type="file" on:input={event => $form.avatar = event.target.files[0]} />
```
