### ISSUE TITLE
Clicking InertiaLink pop-up shows [object Object]

### ISSUE THREAD

**Issue by Rodeveer** [inertiajs/inertia#93]
Well as the title describes; When clicking on a InertiaLink a pop-up shows [object Object] locally. While in live it does the same thing on my computer, but on a different PC (cloned setup) it doesn't. 

Is there any knowledge on how this is possible? If I check the console I definitely see the right xhr response.

Oh, maybe nice to know. I'm working with a combination of Intertia Laravel and Inertja React

Thanks in advance!

**Comment by reinink** [comment]
Hey there! You'll see `[object Object]` in the modal when your server returns a non-Inertia JSON response. I suspect this might be some type of error handling that's returning JSON. If you are seeing a real Inertia.js JSON response payload ([see here](https://inertiajs.com/how-it-works) for an example of an Inertia response), then you might want to double check to see if your headers are being set properly. All Inertia.js responses must have an `X-Inertia` header set to `true`. Without that, it will treat the response as an HTML response.

Hope that helps! I'm closing this issue, but feel free to post more details here if the problem persists.
