### ISSUE TITLE
Form Helper form.reset() not clearing form inputs with onFinish callback - <script setup> Vue3

### ISSUE THREAD

**Issue by mmillis1** [inertiajs/inertia#933]
### Versions:

- `@inertiajs/inertia` version: "0.10.1"
- `@inertiajs/inertia-vue3` version: "0.5.2"

### Describe the problem:

Using Vue 3.2 new composition API script setup, the `form.reset()` does not clear the form's input with the `onFinish` callback. If you call `form.reset()` within `onSuccess`, the form clears the input as expected.

If the `form.post()` fails, the `form.reset()` within `onFinish` will clear the input as expected. So the `form.reset()` only doesn't clear the inputs when the form successfully posts.

### Steps to reproduce:
I tried my best to create a code sandbox to duplicate the issue but had trouble setting things up.

Here is an example: 

```
<template>
  <form @submit.prevent="submit" class="mt-4">
    <input type="text" v-model="form.regcode"/>

    <button type="submit">Confirm</button>
  </form>
</template>

<script setup>
import { useForm } from '@inertiajs/inertia-vue3'

const form = useForm({
    regcode: '',
})

const submit = function () {
    form.post('/api/endpoint-goes-here', {
        onFinish: () => {
            // this won't clear form input
            form.reset()
        },
        onSuccess: () => {
            // this will clear form input
            // form.reset()
        }
    })
}
</script>
```

EDIT: I also just tried this not using script setup and just using the options API and `form.reset()` is still not working

```
<script>
export default {
    data() {
        return {
            form: this.$inertia.form({
                regcode: '',
            })
        }
    },

    methods: {
        submit() {
            this.form.post('/api/route'), {
                onFinish: () => this.form.reset(),
            })
        }
    }
}
</script>
```

Please let me know if I'm doing anything incorrectly. Thank you for your time!

**Comment by ajnsn** [comment]
The reason is that Inertia currently [sets the defaults to the updated form data](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue3/src/useForm.js#L110-L111) after calling the `onSuccess` callback. The `onFinish` callback is called afterwards and already has your updated form data as defaults.

It looks to me that this is a desired behaviour as successful form submits should update the forms default data.

**Comment by gradedcatfood** [comment]
Thank you for posting that source code example to me. Still kinda seems like strange behavior, esp how `onError` does not act the same.

I assume the way I'm doing things is the correct way to clear the form then? Just call `form.reset()` on `onSuccess`?
