### ISSUE TITLE
Error: Cannot find module './Welcome' with InertiaJS and React from Laravel Blade

### ISSUE THREAD

**Issue by elijahcruz12** [inertiajs/inertia#937]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 0.7.1

### Describe the problem:

I installed inertiaJS and React onto a brand new Laravel Installation using Laravel Breeze. After I installed, I ran `npm i` and `npx mix` of course to run mix. When I went onto the site, the issue I had is that when I head to the site, I get `Cannot find module './Welcome'` on the home page, and then at `/login`, I got this:
````
Login(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
````

### Steps to reproduce:

I installed Laravel using `laravel new <myprojectname>`

Then I installed breeze using `composer require laravel/breeze`

Then I ran `php artisan breeze:install react` to install the React version

Then I `npm i` and `npm mix`

Then I loaded the site.

I am using Ubuntu 20.04 and Nginx as well to load the site, as well as Node 16 and PHP 8.0. Thanks!

**Comment by taylorotwell** [comment]
Unable to recreate this.

**Comment by claudiodekker** [comment]
Thanks @taylorotwell!

@elijahcruz12 I'll be closing this issue now, as it cannot be reproduced. If you feel like it is still relevant, feel free to re-open this issue with more details. Ideally, in the form of a public github repository where the issue can be consistently reproduced.

Thanks!

**Comment by elijahcruz12** [comment]
Thanks guys, I'll see why I had this issue. Love both your guy's work so much! ☺️
