### ISSUE TITLE
How To Use Get Request and Handle Response

### ISSUE THREAD

**Issue by paulotra** [inertiajs/inertia#94]
I have a code here to get the request just to check if the coupon is valid.

```
Inertia.visit(`/product/${this.data.slug}/coupons/${this.coupon}`).then(data => {
    console.log(data)
})
```

I'm not getting the data or response, how should that look like for the controller and on my vue component?

**Comment by georgehanson** [comment]
Using `Inertia.visit` isn't designed to change the page you are currently viewing, not to retrieve data from a back-end system. Instead you should use `axios` to make the request to your backend.

**Comment by reinink** [comment]
Yup, as @georgehanson noted, the whole idea behind Inertia is that you don't manually handle the Inertia responses. Rather, each response returns a full page payload, and Inertia knows how to display that. You can read more about how Inertia works [here](https://inertiajs.com/how-it-works).

If you're trying to create an endpoint to check if a coupon is valid, I'd recommend just creating this as a non-Inertia endpoint, and then using Axios to make a plain ajax request to that endpoint. Then you'll be able to get the response in the `then()` handler.

**Comment by JoaoHamerski** [comment]
@reinink Is it ok to use Ajax to fetch data from backend? As you say, "the whole idea", it make it looks like it's wrong to do such thing.

I mean that because sometimes we don't want to fetch all data at once and send to the frontend, sometimes we have some data to display only when a user opens a modal, so I want to fetch the data and just so display it, maybe the user will never open the modal so why would I send that data in every request?

**Comment by vlad0209** [comment]
Here's an example of how you can modify your code to use Axios:
```
axios.get(`/product/${this.data.slug}/coupons/${this.coupon}`)
  .then(response => {
    console.log(response.data);
    // Handle the response data here
  })
  .catch(error => {
    console.error(error);
    // Handle any errors here
  });
```
By using Axios, you can make a GET request to the desired endpoint and handle the response data within the then block. Remember to handle any potential errors by utilizing the catch block as well.
