### ISSUE TITLE
[FeatureRequest] Visit but with "back direction"

### ISSUE THREAD

**Issue by enzonotario** [inertiajs/inertia#95]
Let's say we have these pages:

- /users
    - /users/{id}

When I'm in `/users/{id}` I have a back button that just does `window.history.back()`. But if the user opens that route in a new tab, there is no history, so `window.history.back()` doesn't work.

What I do is define what would be the previous page, so I have somehing like

```
<layout title="User..." :go-back="route('user.index')">
...
</layout>
```

The method that handles the back button is like:
```
back() {
      if (window.history.length && window.history.length > 1) {
        return window.history.back();
      }

      if (this.goBack) {
        return this.$inertia.visit(this.goBack);
      }

      return this.$inertia.visit('/');
    },
```

So, when there isn't any history, it just visit the route defined by the `goBack` prop. The problem here is that the direction is "forward", not "backward". I mean, I think it should be something similar to the [ionic4 router](https://ionicframework.com/docs/api/router#methods) that has a `routerDirection` so I could do something like `this.$inertia.visit(this.goBack, {direction: 'back'})`. This way, Inertia will visit that route but popping the history state, not pushing a new one.

What do you think?

**Comment by georgehanson** [comment]
Having no history when opening a page within a new tab is kind of a standard thing, I'm not sure about changing the default browser behaviour in this case.

Plus there are other issues, for example if there is more than one way to access that internal page, when the user presses the back button they could end up on a page they wouldn't be expecting.

**Comment by reinink** [comment]
When opening a link in a new tab, the history state is totally reset, so there is no way to do this properly. As @georgehanson noted, this is standard browser behaviour.

**Comment by enzonotario** [comment]
Yes, sorry, maybe it's my english, but I'm not talking about to change the behaviour of the history, but to change the behaviour of `$inertia.visit` that, instead of add a new route in the history, it just pop a route (but after all it does the visit).
But I can't even explain it well because my limited english, lol

Thanks anyway, it's an amazing project!

**Comment by reinink** [comment]
Sorry @enzonotario, I wish I knew what you were talking about. 😂 

You can do a "replaceState" instead of "pushState", which is done using the `replace` option. See [here](https://inertiajs.com/requests#history-state). I suspect that's not what you mean though.

**Comment by enzonotario** [comment]
Mmm yes, that solves more or less the issue so far!, thanks so much!

What I want to do is what Ionic4 does with his router, that has a [push method](https://ionicframework.com/docs/api/router):

push
--
Navigate to the specified URL.
push(url: string, **direction?: RouterDirection**) => Promise<boolean>

But I didn't see it in the "vue world", even with `vue-router`...
