### ISSUE TITLE
How to use facebook and twitter meta tags with Inertia Head

### ISSUE THREAD

**Issue by Professor93M** [inertiajs/inertia#952]
- `@inertiajs/inertia` version: "^0.8.4"
- `@inertiajs/inertia-vue3` version: "^0.3.5"

how can I use Facebook and Twitter MetaTags like og:description, twitter:description, og:image and twitter:image, etc...

with Inertiajs **Head** 

as I did it I made **vue component** like that

```
<template>
    <head>
      <title>{{ title }}</title>
      <meta name="description" :content="description">

        <!-- Facebook Meta Tags -->
        <meta property="og:image" :content="img">

        <!-- Twitter Meta Tags -->
        <meta name="twitter:image" :content="img">
    </head>
</template>

<script>
export default {
    props:['title', 'description', 'img']
}
</script>

```

**Comment by Professor93M** [comment]
I updated the InertiaJs version to the latest and everything is fine but the meta tags are not working

**Comment by ajnsn** [comment]
Are you using "View source" to inspect that "its working? As long as you are not using Server Side Rendering (SSR). You need to inspect your page via the Dev tools because Inertia injects the head elements on runtime.

Here comes a Vue 3 sample code that works for me:

```js
<template>
    <div>
        <Head>
            <title>{{ title }}</title>
            <meta name="description" :content="description" />

            <!-- Facebook Meta Tags -->
            <meta property="og:image" :content="img" />

            <!-- Twitter Meta Tags -->
            <meta name="twitter:image" :content="img" />
        </Head>
    </div>
</template>

<script>
import { Head } from '@inertiajs/inertia-vue3';

export default {
    components: {
        Head,
    },
    data() {
        return {
            title: 'Inertia.js - The Modern Monolith',
            description:
                'Inertia.js lets you quickly build modern single-page React, Vue and Svelte apps using classic server-side routing and controllers.',
            img: 'https://inertiajs.com/img/jonathan.png',
        };
    },
};
</script>
```
Outputs:

**Comment by Professor93M** [comment]
Yes, I did that but it doesn't work with me.

But I put all meta tags for OG and Twitter on the app.blade and pass the data from the backend using Laravel and it's worked.

**Comment by hailwood** [comment]
To clarify here, the `<Head>` element works perfectly but the scapers used by the social media sites *do not run Javascript* when looking for the meta tags.

What this means is that you cannot dynamically set the og meta data. You **must** do it on a serverside render (which is what your workaround accomplishes). Inertia SSR would also accomplish this.

**Comment by claudiodekker** [comment]
Thanks for answering this one @hailwood 👍

**Comment by zealot128** [comment]
I also noticed, that (because i don't use SSR yet) the Social media previews for the site is blank, because many Crawlers don't execute Javascript, so a solution to add static meta tags on the server side is a must.

For other people like me, finding this post, here is a solution that works by setting the meta tags on the server side framework (Rails in my case), both passing those to Inertia via PageProps and then InertiaHead, and setting them by the server side layout.

Important: That you add a attribute "inertia" to all relevant  og-Meta-Tags and Title tags. Then Inertia can remove them and replace them with the Head meta tags. Otherwise you will end up with duplicate head tags.


Rails controller shared meta data via InertiaRails.share:

```ruby
def show
  InertiaRails.share(meta_tags: {
        title: post.title,
        ogType: 'article',
        ogDescription: post.teaser.presence || Setting.slogan,
        ogImage: view_context.vite_asset_path("images/favicon.png"),
      }.compact)
```


Rails layout:

- also accesses those meta tags, so it is consistent with the Javascript

```erb
 <title inertia><%= InertiaRails.shared_plain_data&.dig(:meta_tags, :title) || Setting.site_title %></title>
 <meta inertia name="description" content="<%= InertiaRails.shared_plain_data.dig(:meta_tags, :ogDescription) || Setting.slogan %>" />
 <meta inertia property="og:image" content="<%= InertiaRails.shared_plain_data.dig(:meta_tags, :ogImage) || image_url("favicon/apple-touch-icon.png") %>" />
 <meta inertia property="og:title" content="<%= InertiaRails.shared_plain_data.dig(:meta_tags, :ogDescription) || Setting.slogan %>" />
 <meta inertia property="og:type" content="website" />
```

Inertia Layout/Head takes over:

```vue
<template>
  <Head :title="pageProps.meta_tags.title">
    <meta name="description" :content="pageProps.meta_tags.ogDescription" head-key="description" />
    <meta property="og:image" :content="pageProps.meta_tags.ogImage || defaultImage" head-key='og:image' />
    <meta property="og:title" :content="pageProps.meta_tags.ogTitle"  head-key='og:title'/>
    <meta property="og:type" :content="pageProps.meta_tags.ogType" head-key='og:type' />
  </Head>
  <div>
...
<script setup>
import { Head, usePage } from "@inertiajs/inertia-vue3"
const { props: pageProps } = usePage()


```

**Comment by bknoles** [comment]
The docs and [this comment](https://github.com/inertiajs/inertia/issues/792#issuecomment-879366600) indicate that we should use _either_ the Inertia Head component, _or_ server rendered meta tags, but not both.

Is there a reason for that?

In a Rails app I'm currently working on, I wired up something similar to what @zealot128 wrote out in the comment above. It seems to work great! I'm dynamically adding the meta tags on each route via shared Inertia props. The same tag data are then consumed both by the Rails layout (on first page load) and by an Inertia layout (once the Inertia app loads and takes over rendering). Essentially, the tags are "synced" between server/inertia and are correctly shown even when javascript is disabled.

This solves my biggest pet peeve working with React: getting good link previews on social for individual pages. Doing that without SSR or pre-rendering is a huge win for me.

I'm wondering if:

1. There are some gotchas to this approach that I haven't run into yet
2. If not, would it be interesting to get first class support for this in Inertia? It doesn't require a whole lot of code on the Rails side, but we might be able to create a pattern and clean it up for generalized use.
