### ISSUE TITLE
Dynamic import/require in resolveComponent/resolve function using modules?

### ISSUE THREAD

**Issue by maxonfjvipon** [inertiajs/inertia#957]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-react` version: 0.7.1

### Describe the problem:

Hello everyone. I use InertiaJS with Laravel. Also I use [nWidart/laravel-modules](https://github.com/nWidart/laravel-modules). I want to render JS files from my modules dynamically. They are in Modules/Module-name/Resources/assets/js.
This is my controller
```
    public function showLoginForm(): Response
    {
        return Inertia::render('AdminPanel::Login');
    }
```

My webpack.mix
```
mix.js('resources/js/app.js', 'public/js')
    .react()
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig({
        output: {chunkFilename: 'js/[name].js?id=[chunkhash]'},
        resolve: {
            alias: {
                '@': path.resolve(__dirname, 'resources/js'),
                '~': path.resolve(__dirname, 'Modules'),
            }
        },
    })

mix.version()
```

This is my app.js
```
const app = document.getElementById('app');

render(
    <InertiaApp
        initialPage={JSON.parse(app.dataset.page)}
        resolveComponent={async name => {
            let parts = name.split('::')
            if(parts.length > 1) {
                return import(`~/${parts[0]}/Resources/assets/js/Pages/${parts[1]}`).then(module => module.default)
            }else {
                return import('./src/Pages/' + name).then(module => module.default)
            }
        }}
    />,
    app
);
```
In this case I go many webpack errors like:
```
ERROR in ./node_modules/enhanced-resolve/lib/MainFieldPlugin.js 8:13-28
Module not found: Error: Can't resolve 'path' in '/Volumes/Storage/Shared/pump-manager/node_modules/enhanced-resolve/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

```
I also tried with `CreateInertiaApp` and `required` functions - the same result

But if I use static path to module files like: `~/AdminPanel/Resources/assets/js/${parts[0]}` then there are no errors and everything works fine. But that means I should describe all my modules and static paths to their js files in app.js. I would want to escape this.

I also checked [this issue](https://github.com/nWidart/laravel-modules/issues/1162) and [this one](https://github.com/inertiajs/inertia-laravel/issues/92) but unsuccessfully... Someone has the same errors, someone has it works fine

Thanks

**Comment by rafalkrawiec** [comment]
@maxonfjvipon Not 100% sure but it might be related to the webpack's dynamic imports being limited to specific directory only, meaning that you will be able to only bundle files in a single directory you provide in your dynamic expression.

I had the same problem with my project where I've tried to generate separate chunks for every page to avoid loading whole app in single JS file as it is treated as performance issue. I wasn't able to do that with standard dynamic import because I have my pages separated into multiple directories. I ended up using `require.context` (you can find the docs here: https://webpack.js.org/api/module-methods/#requirecontext).

Here is how I've configured my entrypoint file:

```ts
const app  = document.getElementById("app") as HTMLElement;
const init = JSON.parse(app.dataset.page as string);
const context = require.context("resources/js/Pages", true, /\.tsx$/, "lazy");

const resolver = (name: string) => context("resources/js/Pages/" + name + ".tsx").then((module: any) => {
  const page = module.default;

  // ... some default layouts staff here

  return page;
});

ReactDOM.render(<InertiaApp initialPage={init} resolveComponent={resolver} initialComponent={LoadingScreen}/>, app);
```
As you can see I declare files context which scans for all *.tsx files recursively inside my `resources/js/Pages` directory. Then instead of `import()` I use `context()` as a function which will resolve required module. As you might notice I use absolute paths in my project, but the approach with `~` should work as well.

I think it's worth to try it that way.
Hope that helps.

**Comment by maxonfjvipon** [comment]
> @maxonfjvipon Not 100% sure but it might be related to the webpack's dynamic imports being limited to specific directory only, meaning that you will be able to only bundle files in a single directory you provide in your dynamic expression.
> 
> I had the same problem with my project where I've tried to generate separate chunks for every page to avoid loading whole app in single JS file as it is treated as performance issue. I wasn't able to do that with standard dynamic import because I have my pages separated into multiple directories. I ended up using `require.context` (you can find the docs here: https://webpack.js.org/api/module-methods/#requirecontext).
> 
> Here is how I've configured my entrypoint file:
> 
> ```ts
> const app  = document.getElementById("app") as HTMLElement;
> const init = JSON.parse(app.dataset.page as string);
> const context = require.context("resources/js/Pages", true, /\.tsx$/, "lazy");
> 
> const resolver = (name: string) => context("resources/js/Pages/" + name + ".tsx").then((module: any) => {
>   const page = module.default;
> 
>   // ... some default layouts staff here
> 
>   return page;
> });
> 
> ReactDOM.render(<InertiaApp initialPage={init} resolveComponent={resolver} initialComponent={LoadingScreen}/>, app);
> ```
> 
> As you can see I declare files context which scans for all *.tsx files recursively inside my `resources/js/Pages` directory. Then instead of `import()` I use `context()` as a function which will resolve required module. As you might notice I use absolute paths in my project, but the approach with `~` should work as well.
> 
> I think it's worth to try it that way. Hope that helps.

Thanks for your answer.
So I tried this way, but it seems I did something wrong. 
There is how I did it:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/37025995/141836187-7f6d2bd8-1bea-449b-8f25-ff474a2bbd6a.png">

Now I don't have any errors, just I warning. 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/37025995/141836416-f70465e7-553d-4f53-afa4-cb5b829d57bc.png">
Also I have many loaded files:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/37025995/141836372-1d88269c-078d-4637-bb46-91cae02163a2.png">
But when I try to go to page that is located in module, I get this:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/37025995/141836567-45786514-a8e0-455f-964e-7e9f239fa953.png">
Also there is no any path to js files in ```map``` variable in app.js (if we check it via browser)

I also tried to move ```context``` variable out of ```resolver``` function, but then there are errors as before.

**Comment by interviadmin** [comment]
@maxonfjvipon It probably doesn't work because you're trying to use `require.context` in a "dynamic" context (by calling it inside resolver and also using a variable in directory path), where it should be used "statically" (you should prepare everything to load at the build time). Maybe try defining your context before the resolver like that:

```js
const context = require.context('../../Modules', true, /\.js$/, 'lazy');
```

If you have other JS files in your modules which you don't want to include there a third argument of that `context` function is a standard RegExp so you might use something like `/Pages\/(.+)\.js$/` to improve the filtering and catch only your pages.

That big list of files you get now when webpack builds, are actually your chunks, so every page will be generated as separate output, and will only be loaded when it's needed.

**Comment by rafalkrawiec** [comment]
@maxonfjvipon Just in case, make sure to console.log context and check generated map with files paths. In my case I always get absolute paths in map, no matter if I use an absolute or relative path in `require.context`. This might be because I'm using absolute paths in my whole projects. My generated map looks like this:

```js
var map = {
	"./Article/Index.tsx": [
		"./resources/js/Pages/Web/Article/Index.tsx",
		"resources_js_Pages_Web_Article_Index_tsx"
	],
	"./Article/Show.tsx": [
		"./resources/js/Pages/Web/Article/Show.tsx",
		"resources_js_Pages_Web_Article_Show_tsx"
	],
	"./Blog/Index.tsx": [
		"./resources/js/Pages/Web/Blog/Index.tsx",
		"resources_js_Pages_Web_Blog_Index_tsx"
	],
	"./Blog/Show.tsx": [
		"./resources/js/Pages/Web/Blog/Show.tsx",
		"resources_js_Pages_Web_Blog_Show_tsx"
	],
	"./Contact/Index.tsx": [
		"./resources/js/Pages/Web/Contact/Index.tsx",
		"resources_js_Pages_Web_Contact_Index_tsx"
	],
	"./Error.tsx": [
		"./resources/js/Pages/Web/Error.tsx",
		"resources_js_Pages_Web_Error_tsx"
	],
	"./Homepage/Index.tsx": [
		"./resources/js/Pages/Web/Homepage/Index.tsx",
		"resources_js_Pages_Web_Homepage_Index_tsx"
	],
	"resources/js/Pages/Web/Article/Index.tsx": [
		"./resources/js/Pages/Web/Article/Index.tsx",
		"resources_js_Pages_Web_Article_Index_tsx"
	],
	"resources/js/Pages/Web/Article/Show.tsx": [
		"./resources/js/Pages/Web/Article/Show.tsx",
		"resources_js_Pages_Web_Article_Show_tsx"
	],
	"resources/js/Pages/Web/Blog/Index.tsx": [
		"./resources/js/Pages/Web/Blog/Index.tsx",
		"resources_js_Pages_Web_Blog_Index_tsx"
	],
	"resources/js/Pages/Web/Blog/Show.tsx": [
		"./resources/js/Pages/Web/Blog/Show.tsx",
		"resources_js_Pages_Web_Blog_Show_tsx"
	],
	"resources/js/Pages/Web/Contact/Index.tsx": [
		"./resources/js/Pages/Web/Contact/Index.tsx",
		"resources_js_Pages_Web_Contact_Index_tsx"
	],
	"resources/js/Pages/Web/Error.tsx": [
		"./resources/js/Pages/Web/Error.tsx",
		"resources_js_Pages_Web_Error_tsx"
	],
	"resources/js/Pages/Web/Homepage/Index.tsx": [
		"./resources/js/Pages/Web/Homepage/Index.tsx",
		"resources_js_Pages_Web_Homepage_Index_tsx"
	]
};
```

What you actually provide later, using `context(...).then(...)` is a key from the map above. So in my case, when I return `Web/Homepage/Index` in response as a component name, I use `context('resources/js/Pages/' + name + '.tsx').then(...)` to load proper chunk.

Hope it helps.

**Comment by maxonfjvipon** [comment]
@interviadmin @rafalkrawiec 
There is a progress. Builds without errors and warnings
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/37025995/141860178-75368542-7b01-4ae4-a7c1-9e280a83e723.png">
Also now I have chunks that were located from modules:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/37025995/141860451-9b7c0b53-72e9-40e3-8b7a-d9e3c75e6447.png">
But still something wrong:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/37025995/141860643-c89cb3f1-5620-44a1-baa3-6b3a988d2d9c.png">
I think it should be it
<img width="487" alt="image" src="https://user-images.githubusercontent.com/37025995/141860801-610cb735-6a21-4d7e-b437-5206ea3fbcf4.png">
In controller it looks like:
<img width="484" alt="Screen Shot 2021-11-16 at 1 09 58 AM" src="https://user-images.githubusercontent.com/37025995/141860969-8da28347-77c6-4465-80e6-28f437cdc404.png">

**Comment by rafalkrawiec** [comment]
@maxonfjvipon Seems like your if statement is wrong, as it never gets to that context() call. I think there should be `parts.length > 1` as split method will return array.

**Comment by maxonfjvipon** [comment]
@rafalkrawiec @interviadmin 
I bow before you. It finally works. Thank you so much.
Now it looks like this:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/37025995/141862421-6765b16c-1dd6-4481-90a9-23f61ab92367.png">

I did not realize before that first argument in ```require.context()``` function and path ```context``` are not the same! @rafalkrawiec - you were right about the map. 
So we're done here. Thanks again. <3

**Comment by maxonfjvipon** [comment]
Just in case, if somebody does not want to load chunk for every page file.
You may do:
Module structure:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/37025995/143779431-31e06deb-b634-43a0-9743-80b657ee8f19.png">
app.js in your module
<img width="433" alt="image" src="https://user-images.githubusercontent.com/37025995/143779453-9e8da190-9f58-4d23-b83e-22feffd8bfc6.png">
Every page file should be exported as default: 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/37025995/143779470-3475782a-8623-4f6a-bd1f-e4ac969b9fff.png">
main app.js (in resources/js/)
<img width="806" alt="image" src="https://user-images.githubusercontent.com/37025995/143779507-17cebcef-587b-422d-b74e-a221a093817a.png">

**Comment by parth391** [comment]
this don't seem to work in 0.11.0 version

    const context = require.context('../../Modules', true, /Pages\/(.+)\.js$/, 'lazy');

    createInertiaApp({
        title: (title) => `${title} - ${appName}`,
        resolve: (name) => {
            let parts = name.split('::');
            if (parts.length > 1) {
                return context(`./Modules/${parts[0]}/Resources/assets/js/Pages/${parts[1]}.js`).then(module => module.default);
            } else {
                return require(`./Pages/${name}`);
            }
        },
        setup({ el, App, props }) {
            return render(<App {...props} />, el);
        },
    });
