### ISSUE TITLE
Unable to access $page when using script setup

### ISSUE THREAD

**Issue by betaSavvy** [inertiajs/inertia#966]
### Versions:

- `@inertiajs/inertia` version: 0.10.0
- `@inertiajs/inertia-vue3` version: 0.5.1

### Describe the problem:
Was trying to use the `<script setup>` composition api, but unable to access $page object.

Currently managed to get it by importing `getCurrentInstance` from `vue`, then access it by `getCurrentInstance.appContext.app.config.globalProperties.$page`

Is this the correct way or am i missing something?

**Comment by ajnsn** [comment]
`usePage` example should also work with `script setup`?:
https://github.com/inertiajs/inertia/discussions/781#discussioncomment-956629

**Comment by betaSavvy** [comment]
@ajnsn Thanks! I should have checked the discussion section instead of asking it here.
