### ISSUE TITLE
Dynamic properties in form

### ISSUE THREAD

**Issue by bajki** [inertiajs/inertia#968]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2

### Describe the problem:

Is there any way to add property to form if it's not defined  on start?
Like this it won't post custom field.
Thanks

### Steps to reproduce:
```
data() {
        return {
            sending: false,
            form: this.$inertia.form({
                name: "",
      })
};
},
methods: {
        submit() {
            this.sending = true;

            this.form.post(this.route("test"), {
                preserveScroll: true,
                onSuccess: () => (this.sending = false),
                onError: () => (this.sending = false)
            });
        }
}
mounted(){
  this.form.custom = "example".
}
```

**Comment by ajnsn** [comment]
Hey @bajki 
the Form Helper only includes the attributes you set when initaliazing it. What you could do is to build up the form in the mounted hook, e.g: 

```js
export default {
    data() {
        return {
            form: {},
        };
    },
    mounted() {
        this.form = this.$inertia.form({
            name: '',
            custom: 'example',
        });
    },
};
```

**Comment by bajki** [comment]
So there is no way to reinitaliazing after you set it.
 
The idea is that i don't know if  i will use custom field or don't beacuse i dynamically import components.

This way works, it will send custom field but i created all with helper.
```
<template>
  <input v-model="form.custom" />
</template>
<script>
export default {
  data() {
    return {
      form: {},
    };
  },

  methods: {
    submit() {
      this.$inertia.post(this.route("test"), this.form);
    },
  },
};
</script>

```

**Comment by ajnsn** [comment]
You can either build the whole form object in your submit()-method or use the transform-callback, Example [here](https://github.com/inertiajs/inertia/discussions/382#discussioncomment-338461).

**Comment by claudiodekker** [comment]
Thanks for answering this one @ajnsn 👍

**Comment by juanparati** [comment]
There are many ways of add dynamic properties with the "form" helper.

### - Creating a dynamic property (First alternative solution)
You should create a root property which value is an empty object.

Example:
```
this.form = useForm({root: {}});
```

Then you need to provide the "root" as reference:

```
<input type="text" v-model="form.root.mydynamicprop" />
```

The disadvantage is that you will need to use the main/root property as reference. If you are using Laravel and you want to keep the request validation without unfold the main/root node you can transform the request before to send.


### - Populate the properties from a Laravel model (Second alternative solution)

In case that you are using Laravel together with InertiaJS you can use the following Trait in your model:

```PHP
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Schema;

/**
 * Trait that provides all attributes dynamically for a new model.
 */
trait NeedAllAttributes
{
    public static function newModelWithAllAttributes() : static
    {
        /* @var $model \Illuminate\Database\Eloquent\Model */
        $model = new static;

        $columns = Schema::connection($model->getConnection()->getName())
            ->getColumnListing($model->getTable());

        $columns = array_merge(
            Arr::collapse(Arr::map($columns, fn($r) => [$r => null])),
            collect($model->attributes ?? [])
                ->map(fn ($r) => $r === '{}' ? (object) [] : ($r === '[]' ? [] : $r))
                ->toArray()
        );

        return $model->fill($columns);
    }
}
```

When you want to pass an empty model to Inertia, the static method "newModelWithAllAttributes" will return an empty model with all the columns that are found in the associated table schema . The method will also fill the model with the default values provided by the attributes property of the model.

Example:

```PHP
/**
 * Show site entity.
 *
 * @return \Inertia\Response
 */
 public function showEntity(Request $request, int $id = null)
 {
     $site = $id ? Site::findOrFail($id) : Site::newModelWithAllAttributes();

     return Inertia::render('Settings/Sites/SiteEntity', [
         'models' => [
             'entry' => $site,
         ],
     ]);
 } 
```
