### ISSUE TITLE
vue-meta not working in every page

### ISSUE THREAD

**Issue by jajamoks** [inertiajs/inertia#97]
Hi the vue-meta plugin is not working in every page it's only work on 
app.js
--------------------
metaInfo: {
    title: 'Cornerstone',
    titleTemplate: '%s'  
  },
------------------------

but in pages like Product.vue
--------------------
  metaInfo: { title: 'Products' },
-----------------------
It won't work, please suggest alternative.

**Comment by reinink** [comment]
I haven't run into this myself, and there isn't enough code here to figure out what's wrong. I'd suggesting bringing this issue to the vue-meta plugin, since I don't think it's Inertia.js related.

**Comment by jbardnz** [comment]
I know this issue is closed but I thought I should mention I have the same issue, if I have a default title set then the title in my page components does not show. If I remove the default title then the meta title on my pages works correctly.

**Comment by reinink** [comment]
Weird, I use a default title, and it does work. 🤷‍♂️

https://github.com/inertiajs/pingcrm/blob/35169709b54a521541e1ee201373b967528fed6e/resources/js/app.js#L15-L17

**Comment by khalilvaai** [comment]
@reinink please update pingcrm demo app from vue2 to vue3....
