### ISSUE TITLE
Link component breaks mailto/tel links by stripping off characters

### ISSUE THREAD

**Issue by ronaldtveen** [inertiajs/inertia#974]
### Versions:

- `@inertiajs/inertia` version: 0.10.1
- `@inertiajs/inertia-vue` version: 0.7.2

### Describe the problem:

When creating a link with a `tel:` or `mailto:` link it breaks default functionality. It strips off the prefixes _and_ the first character.

### Steps to reproduce with `mailto:` links:

1. Create a link `<Link href="mailto:mail@domain.test">mail@domain.test</Link>`
2. Check the output: `<a href="ail@domain.test">mail@domain.test</a>`
3. Expected output: `<a href="mailto:mail@domain.test">mail@domain.test</a>`

Same goes for `tel:`:
1. Create a link `<Link href="tel:+31123456789">+31 123 456 789</Link>` 
2. Check the output: `<a href="31123456789">+31 123 456 789</a>`
3. Expected output: `<a href="tel:+31123456789">+31 123 456 789</a>`

**Comment by druc** [comment]
Hey @ronaldtveen,

Unless you need to make an inertia request (call some controller action from your Laravel application), there is no need to use the `Link` component, you can just use a regular anchor tag `<a href="tel:+31123456789">+31 123 456 789</a>`

**Comment by ronaldtveen** [comment]
That makes sense, will do that from now on. 

Thanks @druc (PS love your YouTube content)

**Comment by claudiodekker** [comment]
Thanks for answering this one, @druc 👍

**Comment by omidgfx** [comment]
Is there any way to do this programmatically ?
like `nextjs router.push('tel:xxxx');`
