### ISSUE TITLE
Shared data performance concern

### ISSUE THREAD

**Issue by jajamoks** [inertiajs/inertia#98]
Hi, is the shared data(Inertia::share()) is currently the best option for accessing the log-in user? since it was plugged in the app service provider the data  was loaded in every single page and it's affecting performance of the app.

**Comment by georgehanson** [comment]
If it is affecting the performance, I would imagine it is more the queries that are being run when you are sharing the data; which can probably be optimised.

However, without providing any code of what you are currently having issues with it is difficult for us to debug and give you advice. Could you please share your service provider where you are using `Inertia::share`? Thanks

**Comment by reinink** [comment]
So, the thing to remember with Inertia.js is that it works just like a classic server-side framework. With a stock Laravel/Rails/Django setup, every time a new page visit is made, the page template data is reloaded from the server and populated in the HTML (along with the page itself). We've been building websites like this for decades. Using `Inertia::share()` to populate template data on every request is no different.

Now of course in both situations you could make poor database queries, or other performance mistakes that could impact your page load speeds. However, the fact that you're using Inertia.js doesn't introduce any new performance hits that we were not previously totally okay with. 👍
