### ISSUE TITLE
TS2305: Module '"@inertiajs/inertia-react"' has no exported member 'createInertiaApp'

### ISSUE THREAD

**Issue by olivertembo** [inertiajs/inertia#980]
### Versions:

- `@inertiajs/inertia` version: "^0.9.0",
- `@inertiajs/inertia-react` version: "^0.6.0"

### Describe the problem:

It's an error where the inertia-react/index doesn't have a default member
### Steps to reproduce:

Install Laravel with React Breeze
Use Typescript for React.

**Comment by claudiodekker** [comment]
Duplicate of #823 - Already fixed in version 0.7.1
