### ISSUE TITLE
Routing error if mailing someone

### ISSUE THREAD

**Issue by Loown** [inertiajs/inertia#985]
### Versions:

- `@inertiajs/inertia` version: ^0.10.0
- `@inertiajs/inertia-vue3` version: ^0.5.1

### Describe the problem:

I'm using it with Laravel, if I want to send a mail using Mail façade, I get a strange routing error.

`Uncaught ReferenceError: Ziggy is not defined`
`Uncaught (in promise) ReferenceError: route is not defined`

### Steps to reproduce:

1. Create a controller that renders a view.
2. Mail someone.

**Comment by ajnsn** [comment]
@Loown You probably have an issue with Ziggy. Please open an issue [at the Ziggy repo.](https://github.com/tighten/ziggy). A quick solution could be to use a static string for the route, e.g. `/users`

```js
Inertia.post('/users', {
  name: 'John Doe',
  email: 'john.doe@example.com',
})
```

**Comment by Loown** [comment]
I have transfered issue in Ziggy repo, thanks for tryin to help

**Comment by claudiodekker** [comment]
Thanks @ajnsn!
