### ISSUE TITLE
Redirecting to a subdomain after post request

### ISSUE THREAD

**Issue by drfraker** [inertiajs/inertia#99]
I'm writing an app using a multi-tenant architecture. When a new customer signs up they are in the central part of the app. When they submit the registration form, we process payment, set up their tenancy and new database, add the admin user to their users table, log in the admin user and redirect to their dashboard page on their subdomain. When I do this using regular laravel views it works. However, when I'm trying it with inertia I get a cors error in the console. Is there some way I'm not seeing in the docs that explains how to do this?

Workflow overview: 
1. visit example.com/register and enter details & cc info
2. click register button which fires a post request to the store method
3. store method sets up tenancy and new database, logs user in, redirects to acme.example.com/app
like so: `return redirect()->to('acme.example.com/app');`
4. With inertia views this is not working due to cors problems and/or logged in user in the session not persisting. When I add the spatie/laravel-cors package it still does not work. If I add cors headers in bootstrap/app.php I can make the cors problem go away, but then the user is redirected back to acme.example.com/login because the session is not persisted.

This is the cors error I see: `Access to XMLHttpRequest at 'http://foo.example.test/app/login' (redirected from 'http://example.test/register') from origin 'http://example.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by sicsol** [comment]
@drfraker have you set your SESSION_DOMAIN to something like `.example.com` so your sessions will persist across domains?

Also what did you add in the `bootstrap.js` file to remove the cors errors?

**Comment by drfraker** [comment]
@sicsol  Hey Thanks for the response. I added  this to the bootstrap/app.php file, just as a way to debug the issue.
```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: *');
```

Where would one set the SESSION_DOMAIN value? I've never heard of that before.

**Comment by sicsol** [comment]
@drfraker it's in the `config/session.php` file line 156. You can hard code it there otherwise you can also add it to your `.env` file as a key and value. Just make sure you add the `.` before the domain name.

**Comment by reinink** [comment]
@drfraker Did you get this figured out? This is an annoying problem that really has to do more with the fact that you're making xhr requests than Inertia.js requests. Have you considered simply making these particular signup requests using a full page visit?

**Comment by drfraker** [comment]
@reinink Thanks for replying, that (full page visit) is what we ended up going with.

**Comment by Larsklopstra** [comment]
I face this issue when dealing with a payment processor (mollie-cashier) - is it possible to redirect the user to the payment page if the form doesn't fail? A full page visit isn't pretty if the form fails for example... 🤔

**Comment by reinink** [comment]
Another option here is to return a 409 response with the `X-Inertia-Location` header set. Here is an example of this: https://github.com/inertiajs/inertia-laravel/issues/57#issuecomment-570581851

**Comment by reinink** [comment]
Redirecting to external sites server-side, from within an Inertia request, is now possible using the new Inertia "location" method:

```php
// Laravel
return Inertia::location('https://www.google.com');
```

And this is coming to the Ruby adapter shortly (https://github.com/inertiajs/inertia-rails/pull/48).

```ruby
inertia_location('http://google.com')
```

More in the docs [here](https://inertiajs.com/redirects#external-redirects) and on Twitter [here](https://twitter.com/reinink/status/1312019228598382592).

**Comment by kevnk** [comment]
We have a site that switches subdomains a lot... so we wrapped the `<inertia-link>` component to check:

```html
<template>
  <inertia-link :href="this.href" @click="visitLink">
    <slot/>
  </inertia-link>
</template>

<script>
  export default {
    name: 'SubdomainLink',

    props: ['href'],

    computed: {
      currentSubdomain() {
        return window.location.host.split('.')[1] ? window.location.host.split('.')[0] : null;
      },
      linkedSubdomain() {
        let linkedSubdomain = this.href.split('.')[1] ? this.href.split('.')[0] : null;
        return linkedSubdomain.replace('https://', '');
      }
    },

    methods: {
      visitLink() {
        if (this.currentSubdomain !== this.linkedSubdomain) {
          // Invalid subdomain link, force entire page visit/hard refresh
          window.location.href = this.href;
        }
      }
    }
  };
</script>
```

**Comment by MooseSaeed** [comment]
> We have a site that switches subdomains a lot... so we wrapped the `<inertia-link>` component to check:
> 
> ```
> <template>
>   <inertia-link :href="this.href" @click="visitLink">
>     <slot/>
>   </inertia-link>
> </template>
> 
> <script>
>   export default {
>     name: 'SubdomainLink',
> 
>     props: ['href'],
> 
>     computed: {
>       currentSubdomain() {
>         return window.location.host.split('.')[1] ? window.location.host.split('.')[0] : null;
>       },
>       linkedSubdomain() {
>         let linkedSubdomain = this.href.split('.')[1] ? this.href.split('.')[0] : null;
>         return linkedSubdomain.replace('https://', '');
>       }
>     },
> 
>     methods: {
>       visitLink() {
>         if (this.currentSubdomain !== this.linkedSubdomain) {
>           // Invalid subdomain link, force entire page visit/hard refresh
>           window.location.href = this.href;
>         }
>       }
>     }
>   };
> </script>
> ```

Can this help in this situation? https://laracasts.com/discuss/channels/laravel/redirects-not-working-no-access-control-allow-origin-header-laravel-inertiajs-and-vue
